### ISSUE TITLE
三星手机会报错

### ISSUE THREAD

**Issue by kenxiong0113** [getActivity/XXPermissions#10]
#2302 java.lang.RuntimeException
Parcel android.os.Parcel@e4e1aeb: Unmarshalling unknown type code 2131296891 at offset 696

com.lanbang.bosiqiKeeper.ui.activity.MainActivity.onCreate(MainActivity.java:261)

**Comment by 880634** [comment]
请加技术Q群78797078，Github沟通效果低

**Comment by 880634** [comment]
通过Parcelable协议传递数据出现错误，本框架没有用到关于Parcelable子类。故此，这口锅，我不背
