### ISSUE TITLE
使用木木模拟器请求MANAGE_EXTERNAL_STORAGE权限闪退

### ISSUE THREAD

**Issue by zhouzhuo810** [getActivity/XXPermissions#102]
## 问题描述

* 框架版本：12.6

* 问题描述：使用木木模拟器请求权限，配置了`android:requestLegacyExternalStorage="true"`,但是还是抛出异常：
```
Please register the android:requestLegacyExternalStorage=\"true\" " +
                            "attribute in the AndroidManifest.xml file
```

* 复现步骤：
请求
```
<uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE" />
```
权限，就会抛出异常，似乎是解析不到`requestLegacyExternalStorage `这个属性配置。

targetSDK 30

* 是否必现：是

* 手机信息：网易木木模拟器

## 请回答

* 是部分机型还是所有机型都会出现：部分

* 框架最新的版本是否存在这个问题：是

* 是否已经查阅框架文档还未能解决的：是/否（文档会提供最常见的问题解答，可以看看是否有自己想要的）

* issue 是否有人曾提过类似的问题：是/否（看看曾经有人提过类似的问题，先参考一下别人是怎么解决的）

* 是否可以通过 Demo 来复现该问题：是/否（排查一下是不是自己的项目代码写得有问题导致的）

* 使用原生 API 是否会出现该问题：是/否（排查一下是不是框架的代码写法存在问题导致的）

## 其他

* 提供报错堆栈（如果有报错的话必填）

<img width="1567" alt="image" src="https://user-images.githubusercontent.com/15272555/140246463-c86b3c88-9caa-4b85-96ca-de9060db8eb2.png">

* 提供截图或视频（根据需要提供，此项不强制）

<img width="690" alt="image" src="https://user-images.githubusercontent.com/15272555/140244838-bed85ef9-c6d7-44cb-ac79-bc98ed6b0ce3.png">

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by zhouzhuo810** [comment]
对了，我是Mac Book Pro上的木木模拟器出现的，Windows版本还没试过。

**Comment by zhouzhuo810** [comment]
![image](https://user-images.githubusercontent.com/15272555/140246256-c51b5bb8-af36-4be1-b7ba-e106b94f740e.png)

**Comment by getActivity** [comment]
小伙子，请回答我以下两个问题：
1. 真机机型是否出现这样的问题？
2. 是否可以通过 Github 提供的 Demo 来复现该问题？

**Comment by zhouzhuo810** [comment]
我就是担心真机出现这样的问题，不过真机暂时没遇到。Demo我可以弄一个

**Comment by getActivity** [comment]
小伙子，你直接下载 Github 上面提供的 Demo 即可，不需要自己写一个。

**Comment by zhouzhuo810** [comment]
奇怪，我新建项目，复制核心代码单独拿出来又不报错，在项目里就会报错。有点迷

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/140265750-c3e228f8-1a9b-4b73-85b8-099846ea505b.png)

**Comment by getActivity** [comment]
* 劳烦小伙子，下载源码，并在上面截图的地方加上这句代码测试，并把测试结果告知给我

```java
if ("manifest".equals(parser.getName())) {
    String packageName = parser.getAttributeValue(null, "package");
    Log.i("XXPermissions", "当前读取到的清单文件包名是：" + packageName);
}
```

**Comment by getActivity** [comment]
除了告诉我输出的包名，还要告诉我这个包名是否是你项目的包名

**Comment by zhouzhuo810** [comment]
我发现时项目里这个解析出来为0

<img width="869" alt="image" src="https://user-images.githubusercontent.com/15272555/140266825-15ac5ff6-7fef-484c-a7e0-f00938a5baaa.png">

然后这个对应的是Android System WebView的AndroidManifest文件。所以解析不出来那个属性

**Comment by zhouzhuo810** [comment]
你那个代码我加进来试了，因为Android System WebView的AndroidManifest文件没有package属性，所以没拿到。

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/140267729-c99e77ab-b9d5-4a06-9d6e-c82b3466ffbf.png)

**Comment by getActivity** [comment]
小伙子，上面截图有三个断点，你 debug 一下看看是怎么走的？断点 1、断点 2、断点 3 是怎么走的？

**Comment by zhouzhuo810** [comment]
走的第一个

**Comment by zhouzhuo810** [comment]
正如注释里说的，我的模拟器是6.0.1的，所以返回0也是情理之中

<img width="930" alt="image" src="https://user-images.githubusercontent.com/15272555/140268719-0811aedc-e658-418e-8784-ef0a11e9956c.png">

**Comment by getActivity** [comment]
[XXPermissions-12.8.aar.zip](https://github.com/getActivity/XXPermissions/files/7472774/XXPermissions-12.8.aar.zip)

**Comment by getActivity** [comment]
小伙子，你用这个包测试看看，我做了包名过滤了，非当前项目包名的清单文件会被过滤掉。

**Comment by Htryhard** [comment]
我真机遇到同样的问题，刚来找就看到你们在讨论

**Comment by getActivity** [comment]
@Htryhard 小伙子，你的机型是什么？Android 版本是多少？

**Comment by zhouzhuo810** [comment]
> 我真机遇到同样的问题，刚来找就看到你们在讨论

真的假的？啥手机？

**Comment by zhouzhuo810** [comment]
> XXPermissions-12.8.aar.zip

好的，我试试

**Comment by getActivity** [comment]
@zhouzhuo810 小伙子，莫慌，这个检测机制只在 debug 模式、只在 debug 模式、只在 debug 模式下会触发，线上包肯定都是 release 模式，所以肯定不会走一遍这样的逻辑。

**Comment by Htryhard** [comment]
安卓 7.1.1
快递扫码那种砖头工作机子
targetSdkVersion : 30
已经配置：android:requestLegacyExternalStorage="true"
适配了分区存储：
`<meta-data
            android:name="ScopedStorage"
            android:value="true" />`

只要申请 MANAGE_EXTERNAL_STORAGE 权限就报错
`java.lang.IllegalStateException: Please register the android:requestLegacyExternalStorage="true" attribute in the AndroidManifest.xml file`

> 在安卓 9.0上无此问题

**Comment by getActivity** [comment]
@Htryhard OK 的，小伙子，我在上面发了一个 12.8 版本的 aar 包，你也试试看还会不会出现

**Comment by zhouzhuo810** [comment]
> @zhouzhuo810 小伙子，莫慌，这个检测机制只在 debug 模式、只在 debug 模式、只在 debug 模式下会触发，线上包肯定都是 release 模式，所以肯定不会走一遍这样的逻辑。

嗯，这个我了解，我也是刚加进来，还没发布。

**Comment by Htryhard** [comment]
用了12.8 版本的 aar 包还是出现这个问题，清单文件里配置了`android:requestLegacyExternalStorage="true"`,貌似这里一直解析不出来： 
`boolean requestLegacyExternalStorage = parser.getAttributeBooleanValue("http://schemas.android.com/apk/res/android", "requestLegacyExternalStorage", false);`

**Comment by zhouzhuo810** [comment]
<img width="1521" alt="image" src="https://user-images.githubusercontent.com/15272555/140274153-d4cc44a5-a14f-4872-b181-c0fe2e95028f.png">
我也是，还是走到下面来了。

**Comment by zhouzhuo810** [comment]
<img width="810" alt="image" src="https://user-images.githubusercontent.com/15272555/140274469-fa48707f-969e-4846-bb82-9bea219409cb.png">
你这两个逻辑矛盾了

**Comment by zhouzhuo810** [comment]
@getActivity

**Comment by getActivity** [comment]
[XXPermissions-12.8.aar.zip](https://github.com/getActivity/XXPermissions/files/7473074/XXPermissions-12.8.aar.zip)

**Comment by getActivity** [comment]
@zhouzhuo810 @Htryhard 改了，小伙子，再试一下

**Comment by zhouzhuo810** [comment]
> @zhouzhuo810 @Htryhard 改了，小伙子，再试一下

好，我试试

**Comment by zhouzhuo810** [comment]
> @zhouzhuo810 @Htryhard 改了，小伙子，再试一下

不闪退了。应该没问题了

**Comment by zhouzhuo810** [comment]
@getActivity 那这个issue我来关闭还是你来关闭？

**Comment by getActivity** [comment]
@zhouzhuo810 你关闭吧

**Comment by getActivity** [comment]
@zhouzhuo810 小伙子，由于这个问题影响范围不严重，所以你先用这个 aar 包做开发，后续我再发布远程依赖。

**Comment by Htryhard** [comment]
OK了，棒！

**Comment by zhouzhuo810** [comment]
@getActivity 了解

**Comment by getActivity** [comment]
@zhouzhuo810 @Htryhard 小伙子们，远程依赖已经更新了，记得更新一下
