### ISSUE TITLE
是否有考虑onActivityResult回调的权限申请切换成Activity Results API

### ISSUE THREAD

**Issue by LGlxb** [getActivity/XXPermissions#103]
现在官方不再推荐onActivityResult而是建议Activity Results API,
ActivityResultContracts.XX,可以兼容requestMultiplePermissions?

**Comment by getActivity** [comment]
1. 转和不转有什么区别吗？有什么好处？
2. 官方有多大的可能性把 onActivityResult API 删掉？

**Comment by getActivity** [comment]
还有 ActivityResultContract是 Activity 1.2.0-alpha02 和 Fragment 1.3.0-alpha02 中新追加的新 API，如果转了，那么还停留在 Support 包的开发者应该怎么处理？

**Comment by LGlxb** [comment]
> 应该

是的 一昧的求新反而得不偿失 框架更加考虑的是易用性和稳定

**Comment by getActivity** [comment]
是的，小伙子，你的项目想怎么弄都可以，你只需要考虑你的需求和场景，但是框架则不同，需要考虑和兼容众多需求和场景。
