### ISSUE TITLE
检查权限是否符合规范问题

### ISSUE THREAD

**Issue by ZachXie** [getActivity/XXPermissions#104]
## 问题描述

        if (debugMode) {
            // 检查申请的存储权限是否符合规范
            PermissionChecker.checkStoragePermission(mContext, permissions);
            // 检查申请的定位权限是否符合规范
            PermissionChecker.checkLocationPermission(mContext, permissions);
            // 检查申请的权限和 targetSdk 版本是否能吻合
            PermissionChecker.checkTargetSdkVersion(mContext, permissions);
        }
//
        if (debugMode) {
            // 检测权限有没有在清单文件中注册
            PermissionChecker.checkManifestPermissions(mContext, permissions);
        }

为什么检测权限是否符合规范只在debug模式下检查？？

**Comment by getActivity** [comment]
小伙子，生米都煮成熟饭了，你还想怎么样？

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/140293987-1280eb2c-7f62-42ab-b54b-242ffdde3cc4.png)

**Comment by ZachXie** [comment]
呃，那适配api 30的应用在调试时就加MANAGE_EXTERNAL_STORAGE，上线google play就只能去掉

**Comment by getActivity** [comment]
小伙子，这是什么奇怪的逻辑？你先跟我说你要做什么？

**Comment by ZachXie** [comment]
![image](https://user-images.githubusercontent.com/62977233/140297425-138b8af7-2a28-47e1-8f95-69b100f610f8.png)

按照Google的说法是，非核心功能就不要在清单文件中用MANAGE_EXTERNAL_STORAGE，不然不给上架。
就是我们的app，目标版本是30，访问存储只是上传头像，不能加这个权限。

**Comment by getActivity** [comment]
小伙子，这种情况不应该用这种骚操作，你应该去适配分区存储的特性

**Comment by getActivity** [comment]
小伙子，你需要这个 [AndroidVersionAdapter](https://github.com/getActivity/AndroidVersionAdapter)

**Comment by ZachXie** [comment]
现在用Media Store API获取图片

**Comment by ZachXie** [comment]
> 小伙子，你需要这个 [AndroidVersionAdapter](https://github.com/getActivity/AndroidVersionAdapter)

感谢大佬

**Comment by getActivity** [comment]
OK 的，小伙子，那这个 issue 我先关了，后续有问题你再提新的 issue 给我。
