### ISSUE TITLE
PACKAGE_USAGE_STATS

### ISSUE THREAD

**Issue by swatkill** [getActivity/XXPermissions#105]
## 建议收集

* 你觉得框架有什么不足之处？（必答项，你可以描述框架有什么令你不满意的地方）
* PACKAGE_USAGE_STATS 我需要这个权限 谢谢

* 你觉得该怎么去完善会比较好？（非必答项，你可以提供一下自己的想法或者做法供作者参考）

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/141044203-ca16d4f3-0258-4621-a18b-7b3e2651a36b.png)

**Comment by getActivity** [comment]
[XXPermissions-13.0.aar.zip](https://github.com/getActivity/XXPermissions/files/7509581/XXPermissions-13.0.aar.zip)

**Comment by getActivity** [comment]
```java
XXPermissions.with(this)
        .permission(Permission.PACKAGE_USAGE_STATS)
        .request(new OnPermissionCallback() {

            @Override
            public void onGranted(List<String> permissions, boolean all) {
                toast("获取任务栈权限成功");
            }
        });
```

**Comment by getActivity** [comment]
小伙子，你试试看可以不？

**Comment by getActivity** [comment]
小伙子，结果咋样了？还有你如果长时间不回复的话，我会认为你的问题已经解决了，我就会主动关闭这个 issue 了。

**Comment by getActivity** [comment]
超过三天没有响应，关闭此 issue。
