### ISSUE TITLE
小米10青春版出现闪退问题

### ISSUE THREAD

**Issue by zhouzhuo810** [getActivity/XXPermissions#106]
## 问题描述

* 框架版本：12.8

* 问题描述：小米10青春版出现空指针闪退问题
* 
* 复现步骤：
应该是获取文件管理权限。

![image](https://user-images.githubusercontent.com/15272555/141076032-a7335945-1e8b-4bb7-ac7c-a534ac2f158f.png)

* 是否必现：是

* 手机信息：小米10青春版

## 请回答

* 是部分机型还是所有机型都会出现：部分（例如：某为，某 Android 版本会出现）

* 框架最新的版本是否存在这个问题：是（如果用的是旧版本的话，建议升级看问题是否还存在）

* 是否已经查阅框架文档还未能解决的：是/否（文档会提供最常见的问题解答，可以看看是否有自己想要的）

* issue 是否有人曾提过类似的问题：是/否（看看曾经有人提过类似的问题，先参考一下别人是怎么解决的）

* 是否可以通过 Demo 来复现该问题：否，没有这个手机，上架小米，小米MONKEY测试出来的。（排查一下是不是自己的项目代码写得有问题导致的）

* 使用原生 API 是否会出现该问题：是/否（排查一下是不是框架的代码写法存在问题导致的）

## 其他

* 提供报错堆栈（如果有报错的话必填）

Caused by:
5
java.lang.NullPointerException:Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
6
h1.g.onRequestPermissionsResult(PermissionFragment.java:14)
7
android.app.Activity.dispatchRequestPermissionsResultToFragment(Activity.java:8646)
8
android.app.Activity.dispatchActivityResult(Activity.java:8484)
9
android.app.ActivityThread.deliverResults(ActivityThread.java:5095)
10
android.app.ActivityThread.handleSendResult(ActivityThread.java:5143)
11
android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
12
android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
13
android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
14
android.app.ActivityThread$H.handleMessage(ActivityThread.java:2108)
15
android.os.Handler.dispatchMessage(Handler.java:106)
16
android.os.Looper.loop(Looper.java:236)
17
android.app.ActivityThread.main(ActivityThread.java:7879)
18
java.lang.reflect.Method.invoke(Native Method)
19
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
20
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

* 提供截图或视频（根据需要提供，此项不强制）

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by getActivity** [comment]
小伙子，是 grantedPermission 对象为空还是 allPermissions 对象为空？

**Comment by getActivity** [comment]
还有小伙子，能否提供一下复现步骤？

**Comment by zhouzhuo810** [comment]
复现不来，就是不知道怎么复现，我也没有那个机型，云测平台也没有这个机型，应用市场审核不通过就是这个原因，我看bugly收集信息就是上面那些。

**Comment by zhouzhuo810** [comment]
具体不知道哪个，反正就是List.size()

**Comment by getActivity** [comment]
小伙子，那是否能提供一份没有混淆过的堆栈，PermissionFragment 调用 List.size 是比较多的，根据你的描述我没办法确定是哪句代码引发的。

**Comment by getActivity** [comment]
[XXPermissions-13.0.aar.zip](https://github.com/getActivity/XXPermissions/files/7512485/XXPermissions-13.0.aar.zip)

**Comment by getActivity** [comment]
小伙子，问题修复了，你用这个包试一下看看还会不会出现这个问题。

**Comment by getActivity** [comment]
小伙子，结果咋样了？还有你如果长时间不回复的话，我会认为你的问题已经解决了，我就会主动关闭这个 issue 了。

**Comment by zhouzhuo810** [comment]
啊，我自己下载源码加了一些非空判断，Monkey测试通过了，还没试你这个，因为要上架应用市场才能测试，不好测了，我把我改动的地方贴出来，做个参考吧，我先关闭这个issue了。
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/15272555/141646457-61b7545b-c43c-4354-845e-fb92b9fba836.png">
