### ISSUE TITLE
关于授权回调

### ISSUE THREAD

**Issue by jzllovecat** [getActivity/XXPermissions#107]
## 建议收集

* 你觉得框架有什么不足之处？（必答项，你可以描述框架有什么令你不满意的地方）
 个人觉得部分授权先调onDenied()再调onGranted()逻辑上稍微有些绕，这俩方法都要处理部分授权的情况
* 你觉得该怎么去完善会比较好？（非必答项，你可以提供一下自己的想法或者做法供作者参考）
  何不多写个 部分授权（），3种情况分别走对应的方法清晰明了，见名知意

**Comment by getActivity** [comment]
小伙子，这个建议无法采纳，首先你这个逻辑绕不是一个致命的问题，但是我要是一改，对后续升级框架的人将会是一个致命的问题，因为他们会大量给我反馈没有收到回调的问题，还有你说的逻辑绕的问题，这是一个伪命题，首先我在框架主页也有进行说明了，onGranted 方法有一个 all 参数，可用于判断权限是否全部授予了，第二个，无论是全部拒绝或者部分拒绝，方法里面的处理逻辑几乎都是一模一样的，都是通知用户去授权，如果我拆成两个方法来区分，那么写回调的人要写两遍同样的处理逻辑，这个问题又应该怎么解决呢？

**Comment by AdminQQZ** [comment]
拒绝权限里面判断到你关键权限就操作你的逻辑啊，否则都正常进入

**Comment by getActivity** [comment]
小伙子，你看看这边还有其他问题不，没有的话我就关闭 issue 了。

**Comment by jzllovecat** [comment]
1如果一改，对后续升级框架的人将会是一个致命的问题，我觉得不会啊，首先回调接口加一个方法让他必须重写，否则编译不通过
2 写回调的人要写两遍同样的处理逻辑   自己写一个权限拒绝后处理的方法，然后全部拒绝或者部分拒绝都走这个逻辑，如果是非现在必须要的权限就正常走下一步了

其实改不改都不影响使用，我只是有些逻辑强迫症，关了吧
