### ISSUE TITLE
被拒绝的权限可不可以返回中文名称

### ISSUE THREAD

**Issue by bingdu0** [getActivity/XXPermissions#108]
比如说 我的权限被拒绝了，想提示一下，哪些权限被拒绝了不能使用。或者说 勾选拒绝后不在询问，这时候想弹个框提示一下需要到设置页面开启哪些权限。我想拿到中文名称。来弹这个toast 或者框

**Comment by getActivity** [comment]
[PermissionInterceptor.java](https://github.com/getActivity/XXPermissions/blob/master/app/src/main/java/com/hjq/permissions/demo/PermissionInterceptor.java)
