### ISSUE TITLE
androix onActivityResult Deprecated

### ISSUE THREAD

**Issue by guominfang** [getActivity/XXPermissions#109]
onActivityResult，在高版本的androidx支持库中杯标记为 Deprecated了，

推荐使用 registerForActivityResult(ActivityResultContract, ActivityResultCallback)

这个是否考虑适配呢

**Comment by guominfang** [comment]
我想提的是建议，怎么变成了BUG呢

**Comment by getActivity** [comment]
https://github.com/getActivity/XXPermissions/issues/103
