### ISSUE TITLE
判断权限放着LunchActivity  onResum()下会导致MainAcitity无限重启，具体原因不详

### ISSUE THREAD

**Issue by xuxh6** [getActivity/XXPermissions#11]
if(XXPermissions.isHasPermission(this,Permission.Group.STORAGE)) {
            redirectToMain();//跳转mainActivity方法
        }

我申请权限代码正常是放在oncreate里面，用户拒绝权限后，会调用跳转到XXPermissions.gotoPermissionSettings(LunchActivity.this);
当用户设置完成返回到LunchActivity页面时 ，，，如果检查权限放在onResum()下，进入MainActivity后，MainActivity就会反复重启。。。具体原因不清楚
最后我这边的解决方案是 把判断语句放在onRestart()下面，就不会出现问题

**Comment by getActivity** [comment]
首先纠正几个英文单词的写法
LunchActivity   --->  LaunchActivity
onResum   ----> onResume

从别的Activity跳转过来理应回调Activity的onRestart方法，而不是在onResume中写代码
