### ISSUE TITLE
请问在Android11上申请MANAGE_EXTERNAL_STORAGE该权限

### ISSUE THREAD

**Issue by flying910402** [getActivity/XXPermissions#110]
你好，在Android11新增了MANAGE_EXTERNAL_STORAGE该权限，一开始我用原始代码申请了该权限，用于文件的存储，但是在谷歌市场更新被拒绝，理由为：所有文件访问权限不能使用，需要用mediastore api来替代；如果用您的框架的话，在Android11上申请存储权限是否可以解决该问题 ？

**Comment by getActivity** [comment]
小伙子，你在想啥呢？框架只不过对原生 API 做的封装，你无论用自己写的代码来申请还是框架的代码来申请，结果都是一样的。

**Comment by getActivity** [comment]
小伙子，你看看这边还有其他问题不，没有的话我就关闭 issue 了。

**Comment by getActivity** [comment]
超过三天没有响应，关闭此 issue。
