### ISSUE TITLE
你好，这个permission库会有在某些华为手机上无法申请管理所有文件权限的bug吗？
或者说曾经修复过吗？

### ISSUE THREAD

**Issue by 9292922** [getActivity/XXPermissions#111]
![Screenshot_2021-12-20-11-20-00-578_com.tencent.mm.jpg](https://user-images.githubusercontent.com/25112746/146706981-8e01c27b-6da8-4ee1-be48-5a0532bc5986.jpg)

**Comment by 9292922** [comment]
这个是用户反馈的bug，之前是用郭霖的库

**Comment by getActivity** [comment]
小伙子，我还没有遇到过有人跟我反馈过这个问题，还有你这个是 PermissionX 框架的问题吧？你可以考虑尝试换成 XXPermissions，如果有问题我会第一时间处理。

**Comment by 9292922** [comment]
对的，就是permissionx的问题，我反馈给郭霖了，他说还找不到类似的手机测试，所以我就打算你的库可以的话，我直接换过去方便点

**Comment by 9292922** [comment]
> 小伙子，我还没有遇到过有人跟我反馈过这个问题，还有你这个是 PermissionX 框架的问题吧？你可以考虑尝试换成 XXPermissions，如果有问题我会第一时间处理。

对的，就是permissionx的问题，我反馈给郭霖了，他说还找不到类似的手机测试，所以我就打算你的库可以的话，我直接换过去方便点

**Comment by 9292922** [comment]
> 小伙子，我还没有遇到过有人跟我反馈过这个问题，还有你这个是 PermissionX 框架的问题吧？你可以考虑尝试换成 XXPermissions，如果有问题我会第一时间处理。

我直接把demo发给用户试下，迟点给你反馈

**Comment by getActivity** [comment]
OK 的，小伙子，问题及时反馈给我

**Comment by 9292922** [comment]
> OK 的，小伙子，问题及时反馈给我
中午好，经用户测试，是可以正常获取权限的，可以close了，感谢解答

**Comment by getActivity** [comment]
行的，小伙子，后续有啥问题记得及时反馈。
