### ISSUE TITLE
activity以外申请权限

### ISSUE THREAD

**Issue by super0423** [getActivity/XXPermissions#112]
全局任意context申请权限，拉起一个透明activity去申请权限

**Comment by getActivity** [comment]
不会考虑做这个功能，因为在 Android 10 在后台跳转 Activity 需要额外适配：https://developer.android.google.cn/about/versions/10/privacy/changes#background-activity-starts

**Comment by getActivity** [comment]
你如果有需要那么做，我这边建议你获取栈顶的 Activity 来作为权限申请的 Context 对象，没有必要拉起新的 Activity 来申请权限，但只能在应用处于前台的情况下才有用，而在后台拉起 Activity 的情况在 Android 10 后面的版本是无法实现的。
