### ISSUE TITLE
分区存储申请权限出问题 Please register the android:requestLegacyExternalStorage="true"

### ISSUE THREAD

**Issue by Jerry1015** [getActivity/XXPermissions#114]
compileSdkVersion: 30,                     //sdk编译版本
buildToolsVersion: "30.0.2",                     //sdk编译版本
 minSdkVersion    : 21,                         //sdk兼容最低的安装版本
targetSdkVersion : 30,                      //目标编译的版本

按照文档已经增加以下代码
    <application
        android:name=".basic.MainApplication"
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:supportsRtl="true"
        android:theme="@style/AppTheme"
        android:usesCleartextTraffic="true">

        
        <meta-data
            android:name="ScopedStorage"
            android:value="true" />

但是提示了：java.lang.IllegalStateException: Please register the android:requestLegacyExternalStorage="true" attribute in the AndroidManifest.xml file, otherwise it will cause incompatibility with the old version

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/116090151-23df9700-a6d6-11eb-9402-33dce20f00d6.png)
