### ISSUE TITLE
关于分区存储的问题

### ISSUE THREAD

**Issue by Jerry1015** [getActivity/XXPermissions#115]
目标版本 30 ，运行在Android12
我兼容了分区存储，也添加了以下声明
<meta-data
            android:name="ScopedStorage"
            android:value="true" />
但是我没有添加
<application android:requestLegacyExternalStorage="true">，因为默认是强制执行。
结果运行的时候提示 要添加 android:requestLegacyExternalStorage="true" 或者是降低版本，这个是为何呢？ 我添加了之后就可以了， 这是什么原理 感觉这样写很奇怪 轮哥解答一下[破涕为笑]

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/146858848-e4cf5c5c-0b7f-4bb6-8b48-1293dedbdbba.png)
