### ISSUE TITLE
框架存在重复代码

### ISSUE THREAD

**Issue by akuruan** [getActivity/XXPermissions#117]
![image](https://user-images.githubusercontent.com/95744251/149300316-7afbb294-b18f-4f86-a4dd-67056c209148.png)
如上图所示，想确认一下代码是否存在重复

**Comment by getActivity** [comment]
小伙子，这个问题确实存在，感谢提醒，问题已经纠正，但这个问题无伤大雅，会在下个版本发布更新。

**Comment by getActivity** [comment]
超过三天没有响应，关闭此 issue。
