### ISSUE TITLE
代码的注释和代码好像是冲突的

### ISSUE THREAD

**Issue by akuruan** [getActivity/XXPermissions#119]
如下图所示，注释中说 BODY_SENSROS 权限是从 Android 10 才剥离成独立权限，既然后 Android 10 才剥离，那为何要在 Android 10以下的版本加上这个权限呢？
![image](https://user-images.githubusercontent.com/95744251/149305583-29402db4-f254-4692-984e-610d448853ec.png)

**Comment by getActivity** [comment]
小伙子，这个问题确实存在，感谢提醒，问题已经纠正，但这个问题无伤大雅，会在下个版本发布更新。

**Comment by getActivity** [comment]
小伙子，首先这句代码我 Review 了很多遍，是没有问题的，还有注释中的 `这个权限` 是指 `ACTIVITY_RECOGNITION` 权限，而不是指 `BODY_SENSORS` 权限。

**Comment by getActivity** [comment]
超过三天没有响应，关闭此 issue。
