### ISSUE TITLE
锤子手机7.1.1系统权限判断出错

### ISSUE THREAD

**Issue by sumusheng** [getActivity/XXPermissions#12]
锤子手机  Android 7.1.1系统在判断权限的时候都默认有该权限，可是实际上APP是没有这个权限的，用的是锤子坚果2手机进行测试

**Comment by 880634** [comment]
ContextCompat.checkSelfPermission(Context context, String permission);

用这个 API 判断权限会吗？

**Comment by getActivity** [comment]
你好，我这边经过测试是没有这个问题的，如果你还有问题，建议你加QQ群78797078联系我进行解决

**Comment by sumusheng** [comment]
ContextCompat.checkSelfPermission(Context context, String permission);这个方法判断是没有问题的，之前都是用这个方法来判断然后申请权限，后面就改用了XXPermissions来做运行时权限，目前就锤子手机出现了权限判断出错的问题，打断点走下去就是判断有权限了，实际上权限是没有开启的

**Comment by getActivity** [comment]
就锤子手机出现了该问题，其他机型会不会呢？没有权限会判断成有权限，如果是授予了权限的话，你那边是获取到的结果是什么

我这边再次测试了，小米的机型是没有任何问题的，代码逻辑也十分严谨，还有麻烦告知一下打断点判断权限出错的代码行

**Comment by sumusheng** [comment]
就锤子手机有问题，测试了小米，华为，vivo，oppo和锤子，就锤子有问题，代码是直接走下去了，不管权限有没有开启，锤子手机都是返回hasPermission，而且isAll返回true，其他手机判断是正常的

**Comment by getActivity** [comment]
你用这个ContextCompat.checkSelfPermission(Context context, String permission)再判断一下会不会

**Comment by sumusheng** [comment]
好的，现在锤子手机不在我这边，下午拿手机测试看下
