### ISSUE TITLE
VIVO手机如果第一次申请权限拒绝 第二次进去仍然会提示权限申请的框

### ISSUE THREAD

**Issue by kokobebekoko** [getActivity/XXPermissions#121]
## 问题描述

* 框架版本：v13.2

* 问题描述：VIVO手机如果第一次申请权限拒绝 第二次进去仍然会提示权限申请的框

* 复现步骤：第一次申请权限拒绝 第二次进去仍然会提示权限申请的框

* 是否必现：是

* 手机信息：IQOO

## 请回答

* 是部分机型还是所有机型都会出现：VIVO手机是这样的 华为没有 

* 框架最新的版本是否存在这个问题：是
* 是否已经查阅框架文档还未能解决的：是

* issue 是否有人曾提过类似的问题：稍微搜了下 没看到

* 是否可以通过 Demo 来复现该问题：是

* 使用原生 API 是否会出现该问题：测试了下简书 没有遇到这个问题

## 其他

* 提供报错堆栈（如果有报错的话必填）

* 提供截图或视频（根据需要提供，此项不强制）

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by getActivity** [comment]
`VIVO手机如果第一次申请权限拒绝 第二次进去仍然会提示权限申请的框`，小伙子，针对你现在提出的问题，我有两点疑惑，

1. 你第一次申请权限拒绝的时候有没有勾选不再询问？
2. 第二次进去仍然会显示权限申请的框？这里的对话框是系统的还是应用的？

**Comment by kokobebekoko** [comment]
> `VIVO手机如果第一次申请权限拒绝 第二次进去仍然会提示权限申请的框`，小伙子，针对你现在提出的问题，我有两点疑惑，
> 
>     1. 你第一次申请权限拒绝的时候有没有勾选不再询问？
> 
>     2. 第二次进去仍然会显示权限申请的框？这里的对话框是系统的还是应用的？

1.这里面没有勾选框 只有仅使用时允许 仅本次允许和禁止 点击禁止

2.打开后对话框是系统的只不过第二次是禁止且不再询问

**Comment by getActivity** [comment]
小伙子，你说了有禁止和点击禁止两个选项，这两个分别有什么区别？

**Comment by getActivity** [comment]
还有麻烦你现在录个视频过来我看看。

**Comment by getActivity** [comment]
超过三天没有响应，关闭此 issue。
