### ISSUE TITLE
编译版本为30的app在31上蓝牙扫描权限的问题

### ISSUE THREAD

**Issue by showwiki** [getActivity/XXPermissions#123]
## 问题描述

- 框架版本：13.2 

- 问题描述：Vivo iQOO8 升级到最新的版本后android S （sdk 31），具体版本号为 PD2136G_A_6.15.14, 

  如果用target版本为android R（sdk 30）的app进行蓝牙扫描，会出现错误，但如果用系统原生的权限请求时可以请求成功

  因为蓝牙扫描设备的权限在 android S 之后 增加了android.permission.BLUETOOTH_SCAN    在vivo 的权限系统中 ，对应 
附近设备的 权限选项

  我的app 编译版本的30， 运行在 android S 的iQOO8  上后，当申请蓝牙扫描权限的时候，提示

  

  > “ The targetSdkVersion SDK must be 31 or more, if you do not want to upgrade targetSdkVersion, please apply with the old permissions”

  但实际上，此时我如果用系统原生的权限请求时可以请求成功的 ，不过这也可能是vivo的锅，你可能好奇我明明低版本，为啥要申请高版本才有的权限，因为我不申请，vivo就抛异常给我看，功能还不正常。所以我怀疑vivo 并未做好这方面的适配。

  `

  ```kotlin
  val permi = "android.permission.BLUETOOTH_SCAN"
  registerForActivityResult(ActivityResultContracts.RequestPermission()) { result ->
      Timber.d("权限请求后的状态 单权限 %s", result)
      
  }.launch(permi)
  ```

  `

  看了一下源码，是 PermissionChecker 263行进行了检测，直接抛出了异常，但同样我试了试郭霖的框架，如果在target版本为30的app上强行去申请这个android S上的权限，是可以ok的

- 复现步骤：XXX

- 是否必现：是

- 手机信息：Vivo iQOO8

## 请回答

- 是部分机型还是所有机型都会出现：Vivo iQOO8 会， 小米的android S权限中 附近设备的 权限选项根本没有。
- 框架最新的版本是否存在这个问题：是 （如果用的是旧版本的话，会提示android.permission.BLUETOOTH_SCAN 为非必要权限，不需要申请）
- 是否已经查阅框架文档还未能解决的：否
- issue 是否有人曾提过类似的问题：没看到
- 是否可以通过 Demo 来复现该问题：就是简单的权限申请
- 使用原生的权限 API 是否会出现该问题： 否 

## 其他

- 提供报错堆栈（如果有报错的话必填）
- 提供截图或视频（根据需要提供，此项不强制）
- 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/153536978-63a4318b-5966-4d78-ae88-52efaef0c0f4.png)

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/153537044-00d14e7e-c9d5-4deb-aecf-fec0ff573a50.png)

**Comment by getActivity** [comment]
现在有两种解决方案：
1. 升级 targetSdk 的方案：直接升级就可以动态申请 `BLUETOOTH_SCAN` 权限
2. 不升级 targetSdk 的方案：使用对应的旧权限，即在清单文件中注册 `BLUETOOTH_ADMIN` 权限即可，因为这个权限不是危险权限或者特殊权限，不需要动态申请。

**Comment by showwiki** [comment]
是的，方案1 的确可以，但完全的适配android 12 改动还是蛮大的，
方案2 我在上面问题描述中已经说过了，升级到 android 12 的vivo 是不行的，实际上 vivio 出现这个问题，我怀疑大概率是vivio 适配没做好，本来我targetSdk 30 的app 就不应该要我申请这个权限，但它就发生了。好在原生result api 可以去申请，遇到这个权限的时候先用原生去处理吧， 可能以后不久vivio 就适配好了。

**Comment by getActivity** [comment]
超过三天没有响应，自动关闭此 issue。

**Comment by succlz123** [comment]
oppo 同样有这个问题，方案2 不可行的，虽然没 target 到 31 ，但是却要了31 的权限，无语。

**Comment by getActivity** [comment]
@succlz123 小伙子，你排查一下看看，是不是只有 oppo 机型才有这个问题？还是所有 Android 12 机型都会？

**Comment by getActivity** [comment]
@succlz123 如果是 oppo 才有这个问题，那就是 oppo 厂商修改了这块代码，可能需要你这边反馈给 oppo 那边。

**Comment by succlz123** [comment]
关于这个 Android 12 蓝牙权限问题，简书 stackoverflow 上都有相关帖子，包括不限于 vivo oppo 三星。
Android 12 之前 蓝牙权限是在 Location 里面的，而 Android 12 后拆分出单独的 Bluetooth 动态权限。 
目前解决方式是 target sdk version 30 的 APK 跑在 Android 12 上也必须要加上蓝牙动态权限，不然必定 crash。

**Comment by getActivity** [comment]
@succlz123  小伙子，你测试了多少 Android 12 的机型？结果有多少机型有这个问题？Android 原生和小米手机有这个问题？

**Comment by liuhuan8986** [comment]
鸿蒙3.0 也是这样，我app targetSDK 26, 跑在android 12 以下没问题，跑在android 12 不行，13没试过

**Comment by getActivity** [comment]
@liuhuan8986 反馈给厂商吧，这个是厂商的问题。我这边没有办法做兼容，我要是不限制申请蓝牙权限的 targetSdk 版本，那么后续用户拒绝了，跳转到应用详情页面都没有《附近设备的权限》选项，这个也是一个 Bug。

**Comment by liuhuan8986** [comment]
> @liuhuan8986 反馈给厂商吧，这个是厂商的问题。我这边没有办法做兼容，我要是不限制申请蓝牙权限的 targetSdk 版本，那么后续用户拒绝了，跳转到应用详情页面都没有《附近设备的权限》选项，这个也是一个 Bug。

测试另一台一加的手机android 13的，也是一样，都是tagetSDK 26，但是却需要android 12的蓝牙权限。

**Comment by xiemy1214** [comment]
鸿蒙 4.0 也是出现同样的异常信息
请问问题解决了吗? 怎么解决的?
谢谢

**Comment by showwiki** [comment]
> 鸿蒙 4.0 也是出现同样的异常信息 请问问题解决了吗? 怎么解决的? 谢谢

这个是厂商还没适配好，就像我遇到过的小米 12 pro 上 上一个系统版本还不要这个权限，下一个版本就需要了，一般这种新版本上新有的权限，用安卓原生的框架区申请就好。

**Comment by getActivity** [comment]
@showwiki @liuhuan8986 小伙子，你这边先调用 `unchecked` 方法，这样就避免框架给你抛这个异常，我将会在下个版本优化这个问题。

**Comment by getActivity** [comment]
小伙子，这个问题已经被修正，更新到远程依赖 [18.63](https://github.com/getActivity/XXPermissions/releases/tag/18.63) 再试一下。

**Comment by JackCui001** [comment]
realme GT5 Pro（OPPO系），Android 14，XXPermission 18.63 仍然可以复现。
具体表现：targetSdk < 30，清单中申请 BLUETOOTH，BLUETOOTH_ADMIN，BLUETOOTH_CONNECT 权限
调用 bluetoothAdapter.enable() 时，抛出 java.lang.SecurityException: Need android.permission.BLUETOOTH_CONNECT permission for ......
![微信图片_20240705094743](https://github.com/getActivity/XXPermissions/assets/6670163/6af0e9ee-7107-4f0d-b527-96720af0dd55)

但用 XXPermission 申请 BLUETOOTH_CONNECT 权限时，仍然抛出异常 java.lang.IllegalStateException: Request android.permission.BLUETOOTH_CONNECT permission, The targetSdkVersion SDK must be 31 or more, if you do not want to upgrade targetSdkVersion, please apply with the old permission.
![微信图片_20240705094812](https://github.com/getActivity/XXPermissions/assets/6670163/0dac2108-54d4-469d-8745-d17e94a1e5fc)
