### ISSUE TITLE
ACTION_MANAGE_OVERLAY_PERMISSION请求之后用户返回并关闭界面不能回调

### ISSUE THREAD

**Issue by hnty545** [getActivity/XXPermissions#124]
## 问题描述

* 框架版本：最新的13.5
* 手机信息：小米10pro / Android 11
* appcompat：1.3.1，activity继承androidx.appcompat.app.AppCompatActivity
* compileSdkVersion: 30,
            buildToolsVersion: "30.0.3",
            minSdkVersion    : 21,
            targetSdkVersion : 29

* 问题描述：

我使用XXPermissions的request来实现申请权限功能，请求的是SYSTEM_ALERT_WINDOW权限。
追踪到库内部是requestSpecialPermission的
// 跳转到特殊权限授权页面
startActivityForResult(PermissionPageIntent.getSmartPermissionIntent(activity, PermissionUtils.asArrayList(permission)), getArguments().getInt(REQUEST_CODE));

PermissionPageIntent.getSmartPermissionIntent得到的Intent是
if (Permission.SYSTEM_ALERT_WINDOW.equals(permission)) {
    return getWindowPermissionIntent(context);
}

内部源码是
/**
     * 获取悬浮窗权限设置界面意图
     */
    static Intent getWindowPermissionIntent(Context context) {
        Intent intent = null;
        if (AndroidVersion.isAndroid6()) {
            intent = new Intent(Settings.ACTION_MANAGE_OVERLAY_PERMISSION);
            // 在 Android 11 加包名跳转也是没有效果的，官方文档链接：
            // https://developer.android.google.cn/reference/android/provider/Settings#ACTION_MANAGE_OVERLAY_PERMISSION
            intent.setData(getPackageNameUri(context));
        }
        if (intent == null || !PermissionUtils.areActivityIntent(context, intent)) {
            intent = getApplicationDetailsIntent(context);
        }
        return intent;
    }

现在手机弹出了“显示在其他应用的上层”的系统授权页面，如果此时用户什么都不做退出授权界面，activity中的onActivityResult没有回调。在此期间activity没有问题一直是发起startActivityforResult的那个，也没有被释放，而且也不是singleTask的。

我进一步断点测试，PermissionFragment中的onActivityResult回调了，然后在继续追到PermissionFragment的run中到了requestDangerousPermission方法中
if (!AndroidVersion.isAndroid10() || locationPermission == null || locationPermission.isEmpty()) {
            requestPermissions(allPermissions.toArray(new String[allPermissions.size() - 1]), getArguments().getInt(REQUEST_CODE));
            return;
}
执行requestPermissions但是手机没有任何反应，之后就结束了。

我预想中应该回调activity的onActivityResult，或者XXPermissions的request时传入的OnPermissionCallback能给我onDenied回调。

请给我些建议，谢谢！

**Comment by getActivity** [comment]
<img width="614" alt="image" src="https://user-images.githubusercontent.com/28616817/155297937-5edef9d1-e1fb-432f-9620-37bb3bed27f5.png">

**Comment by getActivity** [comment]
小伙子，请严格按照 issue 模板要求来提问。
