### ISSUE TITLE
请求SYSTEM_ALERT_WINDOW权限但不操作直接返回，Activity的onActivityResult不回调

### ISSUE THREAD

**Issue by hnty545** [getActivity/XXPermissions#125]
## 问题描述

* 框架版本：13.5

* 问题描述：手机弹出了“显示在其他应用的上层”的系统授权页面，如果此时用户什么都不做退出授权界面，activity中的onActivityResult没有回调。在此期间activity没有问题一直是发起startActivityforResult的那个，也没有被释放，而且也不是singleTask的。

* 复现步骤：
我使用XXPermissions的request来实现申请权限功能，请求的是SYSTEM_ALERT_WINDOW权限。
追踪到库内部是requestSpecialPermission的
// 跳转到特殊权限授权页面
startActivityForResult(PermissionPageIntent.getSmartPermissionIntent(activity, PermissionUtils.asArrayList(permission)), getArguments().getInt(REQUEST_CODE));

PermissionPageIntent.getSmartPermissionIntent得到的Intent是
if (Permission.SYSTEM_ALERT_WINDOW.equals(permission)) {
return getWindowPermissionIntent(context);
}

内部源码是
/**
* 获取悬浮窗权限设置界面意图
*/
static Intent getWindowPermissionIntent(Context context) {
Intent intent = null;
if (AndroidVersion.isAndroid6()) {
intent = new Intent(Settings.ACTION_MANAGE_OVERLAY_PERMISSION);
// 在 Android 11 加包名跳转也是没有效果的，官方文档链接：
// https://developer.android.google.cn/reference/android/provider/Settings#ACTION_MANAGE_OVERLAY_PERMISSION
intent.setData(getPackageNameUri(context));
}
if (intent == null || !PermissionUtils.areActivityIntent(context, intent)) {
intent = getApplicationDetailsIntent(context);
}
return intent;
}

现在手机弹出了“显示在其他应用的上层”的系统授权页面，如果此时用户什么都不做退出授权界面，activity中的onActivityResult没有回调。在此期间activity没有问题一直是发起startActivityforResult的那个，也没有被释放，而且也不是singleTask的。

我进一步断点测试，PermissionFragment中的onActivityResult回调了，然后在继续追到PermissionFragment的run中到了requestDangerousPermission方法中
if (!AndroidVersion.isAndroid10() || locationPermission == null || locationPermission.isEmpty()) {
requestPermissions(allPermissions.toArray(new String[allPermissions.size() - 1]), getArguments().getInt(REQUEST_CODE));
return;
}
执行requestPermissions但是手机没有任何反应，之后就结束了。

我预想中应该回调activity的onActivityResult，或者XXPermissions的request时传入的OnPermissionCallback能给我onDenied回调。

请给我些建议，谢谢！

* 是否必现：是

* 手机信息：小米10pro / Android 11

## 请回答

* 是部分机型还是所有机型都会出现：没有测试别的手机，但应该是程序问题

* 框架最新的版本是否存在这个问题：是

* 是否已经查阅框架文档还未能解决的：是

* issue 是否有人曾提过类似的问题：否

* 是否可以通过 Demo 来复现该问题：是/否（排查一下是不是自己的项目代码写得有问题导致的）

* 使用原生的权限 API 是否会出现该问题：是/否（排查一下是不是框架的代码存在问题导致的）

## 其他

* 提供报错堆栈（如果有报错的话必填）
* 无报错

* 提供截图或视频（根据需要提供，此项不强制）
* 无

* 提供解决方案（如果已经解决了的话，此项不强制）
* 请给些排查建议，谢谢！

**Comment by getActivity** [comment]
<img width="768" alt="image" src="https://user-images.githubusercontent.com/28616817/155299596-8bdb2cbe-f5ef-49c5-af86-034a9dfd39f6.png">

**Comment by hnty545** [comment]
你好，我补充一下
我下载了最新的demo运行，和我的代码一样的编译和运行环境，分别是
框架版本：13.5
手机信息：小米10pro / Android 11
编译信息：
compileSdkVersion: 30,
buildToolsVersion: "30.0.3",
minSdkVersion    : 21,
targetSdkVersion : 29,


问题描述：使用DEMO中的悬浮窗按钮，发现同样是PermissionFragment中的onActivityResult有回调，MainActivity中的onActivityResult没有回调
同时注意到新版框架你加入了PermissionInterceptor，这里能得到deniedPermissions的回调，这样可能是解决的办法。但是MainActivity中的onActivityResult没有回调这个问题还是有的。

**Comment by getActivity** [comment]
在不修改 Demo 的任何代码的前提下，Demo 自带的申请悬浮窗权限流程有问题不？

**Comment by hnty545** [comment]
我模仿你的PermissionFragment，我自己写了一个非常简单的TestFragment，在其中onResume中
Activity activity = getActivity();
Intent intent = intent = new Intent(Settings.ACTION_MANAGE_OVERLAY_PERMISSION);
intent.setData(Uri.parse("package:" + activity.getPackageName()));
startActivityForResult(intent, 1);
同样发现activity的不回调，fragment的回调了
我觉得要不是手机系统问题，要不是这个版本安卓SDK本来就是这样

**Comment by hnty545** [comment]
我检查了代码，之前反馈的没有反馈是我的问题，在callback里是能正常返回
activity的不回调，fragment的回调，这个问题看来是普遍的，不知道是MIUI的问题还是安卓SDK30的问题了
谢谢，这里结束了
