### ISSUE TITLE
miui13出现Manifest.permission.INTERNET为true却无法联网的情况

### ISSUE THREAD

**Issue by ppg408331701** [getActivity/XXPermissions#127]
小米11升级到miui13之后，如果apk不是通过小米官方应用商店下载的，在初次启动的时候都会弹出一个授权的对话框

![微信截图_20220325142333](https://user-images.githubusercontent.com/16531268/160066492-f239123d-e1ae-44e9-a43b-ca82c8c88c06.png)

此时如果不授权任何权限就点确定进入app，会出现app无法连接任何网络的情况
一开始我以为是Manifest.permission.INTERNET没有被授权，于是检测Manifest.permission.INTERNET这个权限然后提示用户去开启，
但是发现Manifest.permission.INTERNET是已经授权返回true的。但是此时依旧无法上网

请问这种情况能检测出来，然后提醒用户吗？

此时应用的信息情况
![IMG_20220325_143105](https://user-images.githubusercontent.com/16531268/160067074-53bd32e8-6615-4639-9922-f8c98e44b15e.jpg)
![IMG_20220325_143200](https://user-images.githubusercontent.com/16531268/160067080-70393d36-a0bd-49a0-9a2f-846fb549e1b0.jpg)

**Comment by getActivity** [comment]
小伙子，`Manifest.permission.INTERNET` 这个权限既不是危险权限，也不是特殊权限，框架只能判断和处理危险权限和特殊权限。

**Comment by ppg408331701** [comment]
那看起来毫无检测的办法啊。谢谢了
