### ISSUE TITLE
轮子哥，关于android12 蓝牙权限问题

### ISSUE THREAD

**Issue by amosxb** [getActivity/XXPermissions#128]
## 问题描述

* 框架版本：13.5

* 问题描述：android 12 只需要动态请求BLUETOOTH_SCAN权限就可以吗？

* 复现步骤：XXX

* 是否必现：填是/否

* 手机信息：例如某米 9 / Android 10

## 请回答

* 是部分机型还是所有机型都会出现：部分/全部（例如：某为，某 Android 版本会出现）

* 框架最新的版本是否存在这个问题：是/否（如果用的是旧版本的话，建议升级看问题是否还存在）

* 是否已经查阅框架文档还未能解决的：是/否（文档会提供最常见的问题解答，可以看看是否有自己想要的）

* issue 是否有人曾提过类似的问题：是/否（看看曾经有人提过类似的问题，先参考一下别人是怎么解决的）

* 是否可以通过 Demo 来复现该问题：是/否（排查一下是不是自己的项目代码写得有问题导致的）

* 使用原生的权限 API 是否会出现该问题：是/否（排查一下是不是框架的代码存在问题导致的）

## 其他

* 提供报错堆栈（如果有报错的话必填）

* 提供截图或视频（根据需要提供，此项不强制）

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by getActivity** [comment]
小伙子，我不知道你在说什么，你究竟是想干什么？

**Comment by amosxb** [comment]
> 小伙子，我不知道你在说什么，你究竟是想干什么？

轮子哥，是这样的，我在代码里面动态申请BLUETOOTH_SCAN蓝牙权限，会不会适配android12以下版本的手机？

**Comment by getActivity** [comment]
> 轮子哥，是这样的，我在代码里面动态申请BLUETOOTH_SCAN蓝牙权限，会不会适配android12以下版本的手机？

会的，框架会向下兼容，但是低版本上面如果你要用到蓝牙模块需要定位权限
