### ISSUE TITLE
还是把依赖全迁移到Androidx 吧！

### ISSUE THREAD

**Issue by NewDay126** [getActivity/XXPermissions#129]
## 建议收集

* issue 是否有人曾提过类似的问题？（必答项，一旦出现重复提问我将不会再次解答）

* 你觉得框架有什么不足之处？（必答项，你可以描述框架有什么令你不满意的地方）

* 你觉得该怎么去完善会比较好？（非必答项，你可以提供一下自己的想法或者做法供作者参考）

**Comment by getActivity** [comment]
如果转了，那么还停留在 Support 包的开发者应该怎么处理？

**Comment by keta1** [comment]
> 如果转了，那么还停留在 Support 包的开发者应该怎么处理？

https://developer.android.com/studio/command-line/jetifier?hl=zh-cn#reverse_mode

**Comment by getActivity** [comment]
那人家就是基于 Support 项目，并且想用最新版本呢？

**Comment by getActivity** [comment]
超过一个星期没有响应，自动关闭此 issue。

**Comment by getActivity** [comment]
框架已迁移到 AndroidX，详情请见 [Release v28.0](https://github.com/getActivity/XXPermissions/releases/tag/28.0)
