### ISSUE TITLE
文件读写权限，File(path).listFiles()拿到文件列表的是null

### ISSUE THREAD

**Issue by mtj956052456** [getActivity/XXPermissions#130]
## 问题描述

* 框架版本：13.5

* 问题描述：目标版本30，文件读写权限，已经申请了MANAGE_EXTERNAL_STORAGE权限，但是使用File(path).listFiles()拿到文件列表的是null

* 复现步骤：
*  路径：/storage/emulated/0/Android/data 
*  File(path).listFiles()获取文件列表

* 是否必现：是

* 手机信息：Android12 红米k50pro

## 请回答

* 是部分机型还是所有机型都会出现：目前已知的是 红米k50pro Android12版本，其它版本没有真机测试

* 框架最新的版本是否存在这个问题：是

* 是否已经查阅框架文档还未能解决的：是

* issue 是否有人曾提过类似的问题：否

* 是否可以通过 Demo 来复现该问题：否 

* 使用原生的权限 API 是否会出现该问题：没有测试过、、、

## 其他

* 提供报错堆栈 无

* 提供截图或视频（根据需要提供，此项不强制）

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by getActivity** [comment]
<img width="892" alt="image" src="https://user-images.githubusercontent.com/28616817/164010602-2f2216f6-bba0-4fbe-afb7-da4fe6f572d6.png">

**Comment by mtj956052456** [comment]
好的，我去做一下适配，另外有个问题问下，DocumentFile在遍历子文件的时间速度特别慢，并且我需要使用子文件里面的MP4
文件播放，但是它的路径不是常规**/**/路径，导致不能播放视频。有没有什么好的解决方法？

**Comment by getActivity** [comment]
小伙子，我目前只处理框架的 Bug 和建议
