### ISSUE TITLE
添加存储权限，应用闪退

### ISSUE THREAD

**Issue by zhuzhuxiang** [getActivity/XXPermissions#131]
## 问题描述

* 框架版本：10.5

* 问题描述：添加存储权限，会报错    If you have adapted the scope storage, please register the <meta-data android:name="ScopedStorage" android:value="true" /> attribute in the AndroidManifest.xml file. If there is no adaptation scope storage, please use MANAGE_EXTERNAL_STORAGE to apply for permission    
*    <uses-permission android:name="android.permission.MANAGE_EXTERNAL__STORAGE"/>和     android:requestLegacyExternalStorage="true" 都有

* 复现步骤：XXX

* 是否必现   是

* 手机信息：华为Android 10    Vivo7.0

## 请回答

* 是部分机型还是所有机型都会出现：部分/全部（例如：某为，某 Android 版本会出现）

* 框架最新的版本是否存在这个问题：是/否（如果用的是旧版本的话，建议升级看问题是否还存在）

* 是否已经查阅框架文档还未能解决的：是/否（文档会提供最常见的问题解答，可以看看是否有自己想要的）

* issue 是否有人曾提过类似的问题：是/否（看看曾经有人提过类似的问题，先参考一下别人是怎么解决的）

* 是否可以通过 Demo 来复现该问题：是/否（排查一下是不是自己的项目代码写得有问题导致的）

* 使用原生的权限 API 是否会出现该问题：是/否（排查一下是不是框架的代码存在问题导致的）

## 其他

* 提供报错堆栈（如果有报错的话必填）

* 提供截图或视频（根据需要提供，此项不强制）

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by zhuzhuxiang** [comment]
user permission 换成 MANAGE_EXTERNAL_STORAGE  也不行

**Comment by getActivity** [comment]
<img width="718" alt="image" src="https://user-images.githubusercontent.com/28616817/165203527-c31e530f-c0cd-4a95-a031-02537d4ca18f.png">

**Comment by SMAXLYB** [comment]
一样
