### ISSUE TITLE
Android S内存泄露问题

### ISSUE THREAD

**Issue by kanshenmekan** [getActivity/XXPermissions#133]
## 问题描述

* 框架版本：13.6

* 问题描述：compileSdkVersion 31 出现内存泄漏

* 复现步骤：我下载的demo，把compileSdkVersion 改成31，修改代码，拒绝权限销毁自己，跳到下一个activity
![abc](https://user-images.githubusercontent.com/26561615/167800680-9ee5b7a3-c9a0-443e-b755-9cb93671b46c.png)

点击申请权限后拒绝，就可以复现
* 是否必现：是

* 出现问题的手机信息：小米10Pro miui13.0.3

* 出现问题的安卓版本： android12

## 请回答

* 是部分机型还是所有机型都会出现：未测试，估计全都出现

* 框架最新的版本是否存在这个问题：是

* 是否已经查阅框架文档还未能解决的：是

* issue 是否有人曾提过类似的问题：否

* 是否可以通过 Demo 来复现该问题：是

* 使用原生的权限 API 是否会出现该问题：想咨询一下大佬 [https://www.jianshu.com/p/b0de542204f8](url)

## 其他
内存泄漏
![abb](https://user-images.githubusercontent.com/26561615/167801243-5d70e667-a2c6-4e30-b3b4-b828f6eca99a.jpg)
了

**Comment by kanshenmekan** [comment]
compileSdkVersion 32也一样，demo里面 MainActivity作为launch，android12以上作为launch的activity按返回键不会销毁，测试不出来，所以加了一个finish()

**Comment by getActivity** [comment]
小伙子，这个内存泄漏的问题是系统的代码导致的，而不是框架的代码导致的。

**Comment by getActivity** [comment]
另外我目前没有任何解决方案去解决它，毕竟是系统的代码，只能寄希望于谷歌在下个 Android 版本将它修复。

**Comment by getActivity** [comment]
[XXPermissions-13.8.aar.zip](https://github.com/getActivity/XXPermissions/files/8670307/XXPermissions-13.8.aar.zip)

**Comment by kanshenmekan** [comment]
好的，OK了
