### ISSUE TITLE
Could not find XXPermissions-12.8.aar (com.github.getActivity:XXPermissions:12.8).

### ISSUE THREAD

**Issue by DodoSpringLove** [getActivity/XXPermissions#134]
## 问题描述
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugAidl'.
> Could not resolve all files for configuration ':app:debugCompileClasspath'.
   > Could not find XXPermissions-12.8.aar (com.github.getActivity:XXPermissions:12.8).
     Searched in the following locations:
         https://jitpack.io/com/github/getActivity/XXPermissions/12.8/XXPermissions-12.8.aar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 656ms
1 actionable task: 1 executed

* 框架版本：12.8

* 问题描述：XXX
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugAidl'.
> Could not resolve all files for configuration ':app:debugCompileClasspath'.
   > Could not find XXPermissions-12.8.aar (com.github.getActivity:XXPermissions:12.8).
     Searched in the following locations:
         https://jitpack.io/com/github/getActivity/XXPermissions/12.8/XXPermissions-12.8.aar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 656ms
1 actionable task: 1 executed

* 复现步骤：XXX
any rebuild

* 是否必现：填是/否
yes

* 出现问题的手机信息：请填写出现问题的品牌和机型
android  simulator

* 出现问题的安卓版本：请填写出现问题的 Android 版本
android 7.1.2

## 请回答

* 是部分机型还是所有机型都会出现：部分/全部（例如：某为，某 Android 版本会出现）

* 框架最新的版本是否存在这个问题：是/否（如果用的是旧版本的话，建议升级看问题是否还存在）

* 是否已经查阅框架文档还未能解决的：是/否（文档会提供最常见的问题解答，可以看看是否有自己想要的）

* issue 是否有人曾提过类似的问题：是/否（看看曾经有人提过类似的问题，先参考一下别人是怎么解决的）

* 是否可以通过 Demo 来复现该问题：是/否（排查一下是不是自己的项目代码写得有问题导致的）

* 使用原生的权限 API 是否会出现该问题：是/否（排查一下是不是框架的代码存在问题导致的）

## 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）

* 提供截图或视频（根据需要提供，此项不强制）
![image](https://user-images.githubusercontent.com/26377272/169492188-5e46b6eb-ef77-4247-8a0b-ca88c2ca22f1.png)

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by getActivity** [comment]
小伙子，我到 jitpack 重新构建了一下，你再试试看行不行

**Comment by DodoSpringLove** [comment]
当时着急，升了新版本，回头试下，感谢大佬

**Comment by aohanhongzhi** [comment]
> 
我这里遇到同样问题，gradle6.5 jdk8 ,linux。貌似网络没问题
![image](https://user-images.githubusercontent.com/37319319/225230123-3df59c70-ff55-406f-ab09-2e54b58d2f1f.png)

下载也是正常的

 https://jitpack.io/com/github/getActivity/XXPermissions/13.5/XXPermissions-13.5.aar
![image](https://user-images.githubusercontent.com/37319319/225230436-6a4b8a5e-ca13-4f9a-890a-85aa426fb01f.png)
