### ISSUE TITLE
想问下有些游戏手机的读写权限要怎么获取？例如红魔、联想拯救者pro电竞

### ISSUE THREAD

**Issue by 13512780735** [getActivity/XXPermissions#135]
## 建议收集

* issue 是否有人曾提过类似的问题？（必答项，一旦出现重复提问我将不会再次解答）

* 你觉得框架有什么不足之处？（必答项，你可以描述框架有什么令你不满意的地方）

* 你觉得该怎么去完善会比较好？（非必答项，你可以提供一下自己的想法或者做法供作者参考）

**Comment by getActivity** [comment]
小伙子，这个跟普通手机获取读写权限有什么区别么？

**Comment by 13512780735** [comment]
这些都是专门的游戏手机，有些拿不到读写权限

**Comment by getActivity** [comment]
为什么拿不到存储权限？那其他应用不是也获取不到？

**Comment by getActivity** [comment]
小伙子，这个问题只能靠你自己处理了，我是没有办法给你处理的

1. 我没有游戏手机可以复现和测试这个问题
2. 如果游戏不按照谷歌的 API 来走，我也没有任何办法，只能是等他们自己人修复
3. 如果游戏手机厂商就是这么做，利益最大受损者肯定是他们，因为他们的用户肯定会流失

**Comment by getActivity** [comment]
如果一个手机不给读写权限，那么市面上至少一半的软件用不了，基本上可以断定这是个半残废的手机，这种情况下，只有两种可能性，第一个可能是厂商的程序员写的 Bug，只能等他们修复，第二个可能是厂商故意那么做，那这个也没有办法，对于这些机型我一般不会去做兼容，让它听天由命吧，我只能保证框架的代码写得没有问题，无法给你保证在所有的厂商上面运行都没有问题，这个不是我的职责，除非你自己做了兼容再反馈给我，我会经过慎重考虑后才会决定要不要加入到框架中。
