### ISSUE TITLE
部分设备跳转应用详情页面崩溃

### ISSUE THREAD

**Issue by chenhangyuan** [getActivity/XXPermissions#138]
## 问题描述

* 框架版本【必填】：13.2

* 问题描述【必填】：在TV，车机上可能不存在要跳转的页面（比如应用详情设置页面）就会导致崩溃

* 复现步骤【必填】：TV上跳转应用详情页

* 是否必现【必填】：部分设备必现

* 出现问题的手机信息【必填】：

* 出现问题的安卓版本【必填】：
![image](https://user-images.githubusercontent.com/31436638/176577406-94f1a89a-4fdd-4ad5-8c71-2ff262e7ee1d.png)

## 请回答

* 是部分机型还是所有机型都会出现【必答】：部分

* 框架最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 Demo 来复现该问题【必答】：是

* 使用原生的权限 API 是否会出现该问题【必答】：否

## 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）
![image](https://user-images.githubusercontent.com/31436638/176577805-711c3947-1d4a-4ccd-83a4-a81f7b82fc1d.png)

* 提供截图或视频（根据需要提供，此项不强制）

* 提供解决方案（如果已经解决了的话，此项不强制）
 startActivityForResult增加try catch防护

**Comment by getActivity** [comment]
小伙子，如果连应用详情 `ACTION_APPLICATION_DETAILS_SETTINGS` 都跳转不过去，这样就有点说不过去了吧？

**Comment by getActivity** [comment]
[XXPermissions-15.2.aar.zip](https://github.com/getActivity/XXPermissions/files/9033000/XXPermissions-15.2.aar.zip)

**Comment by getActivity** [comment]
<img width="878" alt="image" src="https://user-images.githubusercontent.com/28616817/177000404-bb91709e-8293-4c8d-8102-7c166c6a8933.png">

**Comment by getActivity** [comment]
小伙子，我修改了代码，如果没有某个应用程序详情的意图，就跳转到所有应用的管理列表，麻烦用这个包测试一下是否还有这样的问题？

**Comment by chenhangyuan** [comment]
轮子哥 ACTION_APPLICATION_DETAILS_SETTINGS跳不过去确实说不过去 我观察到线上数据基本都是TV的 手机都是正常的，所以可能是TV的开发不太老实，目前我这边也没有测试设备TV。但是看你修改的代码还是会有隐患，万一上述三个都不存在的话 应该还是会崩溃吧。像这类设备跳不跳意义不大了，加个try catch我觉得ok,毕竟tv上的应用的可玩性不像手机

**Comment by getActivity** [comment]
@chenhangyuan 小伙子，try catch 不是万能的，一遇到 Bug 就 try catch 肯定是有问题的，Bug 就很大概率会被掩盖过去，站在你的角度思考可能没有错，加了 try catch 确实崩溃率好看了，但是你有没有想过以下几个问题？

1. 这种是不是最好的方案？还是说你采取了最简单粗暴、省时省力的方式？
2. 我看过你提交的代码，你确定这种写法能保证权限回调能被正常调用？
3. 还有你知道权限申请的回调没有被正常调用的结果意味着什么么？

**Comment by getActivity** [comment]
超过三天没有响应，自动关闭此 issue。
