### ISSUE TITLE
无法动态读取获取设备识别码的权限

### ISSUE THREAD

**Issue by dora4** [getActivity/XXPermissions#139]
## 问题描述

* 框架版本【必填】：15.0

* 问题描述【必填】：    java.lang.IllegalArgumentException: The android.permission.READ_PRIVILEGED_PHONE_STATE is not a dangerous permission or special permission, please do not apply dynamically
        at com.hjq.permissions.PermissionChecker.checkPermissionArgument(PermissionChecker.java:106)
        at com.hjq.permissions.XXPermissions.request(XXPermissions.java:164)

* 复现步骤【必填】：调用动态申请android.permission.READ_PRIVILEGED_PHONE_STATE权限

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：三星

* 出现问题的安卓版本【必填】：Android 12

## 请回答

* 是部分机型还是所有机型都会出现【必答】：全部

* 框架最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：否

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 Demo 来复现该问题【必答】：是

* 使用原生的权限 API 是否会出现该问题【必答】：否

**Comment by dora4** [comment]
那这个权限怎么用，只有系统应用或系统白名单可以用吗？

**Comment by getActivity** [comment]
这个权限是系统的权限，应用的话是不能动态申请的，你可以尝试把这个权限在清单文件中注册，如果不行的话也没有其他办法。
