### ISSUE TITLE
特殊权限申请问题

### ISSUE THREAD

**Issue by LiuXingzhou** [getActivity/XXPermissions#141]
## 建议收集

* issue 是否有人曾提过类似的问题？
* 没有看到相似的。
* 
* 你觉得框架有什么不足之处？
* 特殊权限如：MANAGE_EXTERNAL_STORAGE，在Android版本<30的手机上申请权限时。
* 13.X版本：默认替换检测Permission.Group.STORAGE权限组的权限，此时检测该权限返回false。
* onGranted：空。
* onDenied：MANAGE_EXTERNAL_STORAGE、READ_EXTERNAL_STORAGE、WRITE_EXTERNAL_STORAGE。
* 15.0版本：Android版本<30，无该特殊权限，此时检测该权限默认返回true。
* 导致15版本与旧版本相同权限申请的结果出现差异。
* onGranted：MANAGE_EXTERNAL_STORAGE。
* onDenied：READ_EXTERNAL_STORAGE、WRITE_EXTERNAL_STORAGE。
* 
* 你觉得该怎么去完善会比较好？
* 像这种特殊权限申请的情况，会改回13.X的形式（MANAGE_EXTERNAL_STORAGE=Permission.Group.STORAGE）去检测吗？

**Comment by getActivity** [comment]
[XXPermissions-15.2.aar.zip](https://github.com/getActivity/XXPermissions/files/9061684/XXPermissions-15.2.aar.zip)

**Comment by getActivity** [comment]
小伙子，问题修复了，用这个包再试一下看看会不会？

**Comment by LiuXingzhou** [comment]
可以了，正常了这个权限申请，感谢！而且我看大佬已经在适配Android13了呀。
