### ISSUE TITLE
android 13 权限适配

### ISSUE THREAD

**Issue by Ymmmsick** [getActivity/XXPermissions#142]
## 建议收集
  android 13已经将通知权限纳入运行时可以动态申请，还有细化的媒体权限，不知道大佬是否有时间适配一下
* issue 是否有人曾提过类似的问题？【必答】（一旦出现重复提问我将不会再次解答）
  未找到有类似建议
* 你觉得框架有什么不足之处？【必答】（你可以描述框架有什么令你不满意的地方）
  无
* 你觉得该怎么去完善会比较好？【非必答】（你可以提供一下自己的想法或者做法供作者参考）
  https://developer.android.com/about/versions/13/changes/notification-permission?hl=zh-cn

**Comment by getActivity** [comment]
多谢提醒，框架目前已经在适配完成了，但是还没有发布出来，就等官方官宣了。
