### ISSUE TITLE
android 12 无法访问Android/data/里面文件

### ISSUE THREAD

**Issue by 1477466721** [getActivity/XXPermissions#144]
版本框架:15.0
问题描述及步骤: XXPermissions.with(this) .permission(Permission.MANAGE_EXTERNAL_STORAGE)，将开关打开后，返回当前Activity，再调用 
           Intnet  intent = new Intent(Intent.ACTION_GET_CONTENT);
                intent.setType("*/*");//无类型限制
                intent.addCategory(Intent.CATEGORY_OPENABLE);
                startActivityForResult(intent, 1);
              依次进入：文件管理/Android/data ，在data里面没有找到任何文件。
目前手里只有一台一加手机（android12），请求大佬指导一下

**Comment by getActivity** [comment]
<img width="1126" alt="image" src="https://user-images.githubusercontent.com/28616817/179520107-668dc605-1835-4a54-8c63-f40a17ccc646.png">

**Comment by COO1M** [comment]
授予了MANAGE_EXTERNAL_STORAGE权限也不可以访问其他应用的私有目录，不属于该框架问题。
