### ISSUE TITLE
XXPermissions.isGranted这个方法问题

### ISSUE THREAD

**Issue by candebbs** [getActivity/XXPermissions#145]
## 问题描述

* 框架版本【必填】：15.0

* 问题描述【必填】：使用XXPermissions.isGranted方法判断手机是否申请了MANAGE_EXTERNAL_STORAGE、READ_EXTERNAL_STORAGE、WRITE_EXTERNAL_STORAGE。

* 复现步骤【必填】：申请存储权限，然后在应用禁止存储权限，然后使用XXPermissions.isGranted方法判断手机是否申请了MANAGE_EXTERNAL_STORAGE、READ_EXTERNAL_STORAGE、WRITE_EXTERNAL_STORAGE，通过日志发现，`XXPermissions.isGranted(this, Permission.MANAGE_EXTERNAL_STORAGE)`输出为true，READ_EXTERNAL_STORAGE、WRITE_EXTERNAL_STORAGE输出为false，

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：android平板，使用亮钻主板自定义硬件产品

* 出现问题的安卓版本【必填】：7.1.2

## 请回答

* 是部分机型还是所有机型都会出现【必答】：在测试手机realme x2 pro，同样有此问题。 

* 框架最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 Demo 来复现该问题【必答】：是

* 使用原生的权限 API 是否会出现该问题【必答】：

## 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）
* 参考代码：
```
        boolean isGranted_MANAGE_EXTERNAL_STORAGE = XXPermissions.isGranted(this, Permission.MANAGE_EXTERNAL_STORAGE);
        LogUtil.e(LogUtil.MAIN, "MANAGE_EXTERNAL_STORAGE isGranted=" + isGranted_MANAGE_EXTERNAL_STORAGE);

        boolean isGranted_READ_EXTERNAL_STORAGE = XXPermissions.isGranted(this, Permission.READ_EXTERNAL_STORAGE);
        LogUtil.e(LogUtil.MAIN, "READ_EXTERNAL_STORAGE isGranted=" + isGranted_READ_EXTERNAL_STORAGE);

        boolean isGranted_WRITE_EXTERNAL_STORAGE  = XXPermissions.isGranted(this, Permission.WRITE_EXTERNAL_STORAGE );
        LogUtil.e(LogUtil.MAIN, "WRITE_EXTERNAL_STORAGE isGranted=" + isGranted_WRITE_EXTERNAL_STORAGE);

MANAGE_EXTERNAL_STORAGE isGranted=true
READ_EXTERNAL_STORAGE isGranted=false
WRITE_EXTERNAL_STORAGE isGranted=false
```

* 提供截图或视频（根据需要提供，此项不强制）

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by budaowengd** [comment]
21.2版本isGranted方法调用还是存在bug，XXPermissions.isGranted(getAct(), Permission.Group.STORAGE) 一直返回false，用原生的api调用就返回true，索尼 安卓13手机

**Comment by getActivity** [comment]
> 21.2版本isGranted方法调用还是存在bug，XXPermissions.isGranted(getAct(), Permission.Group.STORAGE) 一直返回false，用原生的api调用就返回true，索尼 安卓13手机

你另提一个 bug issue
