### ISSUE TITLE
目前没有OPSTR_PICTURE_IN_PICTURE的判断和申请

### ISSUE THREAD

**Issue by nesror** [getActivity/XXPermissions#148]
## 建议收集

* issue 是否有人曾提过类似的问题？
   无

* 你觉得框架有什么不足之处？
   目前没有OPSTR_PICTURE_IN_PICTURE的判断和申请

* 你觉得该怎么去完善会比较好？
    增加OPSTR_PICTURE_IN_PICTURE的判断和申请

**Comment by getActivity** [comment]
小伙子，你确定 OPSTR_PICTURE_IN_PICTURE 这个是危险权限或者特殊权限？

**Comment by getActivity** [comment]
我在[官方文档](https://developer.android.google.cn/reference/android/Manifest.permission?hl=zh_cn)中没有找到这个权限

**Comment by nesror** [comment]
> 我在[官方文档](https://developer.android.google.cn/reference/android/Manifest.permission?hl=zh_cn)中没有找到这个权限


这个是视频的画中画权限，官方没有这个权限的运行时申请，大部分机型会默认给。
但设置中或者画中画左下角可以手动关闭。
我现在是这样判断的
`if (Build.VERSION.SDK_INT < Build.VERSION_CODES.N) {
            toast("你的手机不支持画中画模式")
            return
        } else {
            val appOps = getSystemService(Context.APP_OPS_SERVICE) as AppOpsManager
            if (appOps.checkOpNoThrow(
                    AppOpsManager.OPSTR_PICTURE_IN_PICTURE,
                    android.os.Process.myUid(),
                    packageName
                ) != AppOpsManager.MODE_ALLOWED
            ) {
                toast("画中画权限被关闭，或者手机内存小于2G系统支持")
                return
            }
        }`

**Comment by getActivity** [comment]
@nesror 小伙子，假设它是一个权限，那么权限设置页怎么跳转进去呢？

**Comment by nesror** [comment]
> @nesror 小伙子，假设它是一个权限，那么权限设置页怎么跳转进去呢？

apps->special app access->picture-in-picture

**Comment by getActivity** [comment]
[XXPermissions-16.2.aar.zip](https://github.com/getActivity/XXPermissions/files/9424910/XXPermissions-16.2.aar.zip)

**Comment by getActivity** [comment]
@nesror 小伙子，这个建议已经被采纳，目前框架已经适配了画中画权限，你可以下载上面的 aar 包进行本地依赖，具体申请画中画的代码如下：

```java
XXPermissions.with(this)
        .permission(Permission.PICTURE_IN_PICTURE)
        .request(new OnPermissionCallback() {

            @Override
            public void onGranted(List<String> permissions, boolean all) {
                if (!all) {
                    return;
                }
                toast("获取画中画权限成功");
            }
        });
```
