### ISSUE TITLE
OPPO R9s 、申请几个权限，全部拒绝走的是onGrant, all=true

### ISSUE THREAD

**Issue by li-xiaojun** [getActivity/XXPermissions#149]
## 问题描述

* 框架版本【必填】：16.0
* 问题描述【必填】：申请了几个权限，全部拒绝，竟然走的是onGrant, all=true

* 复现步骤【必填】：必现，机型 OPPO R9s , Android 6.0.1;
* 代码如下：
```
XXPermissions.with(this)
            .permission(Permission.READ_SMS, Permission.ACCESS_COARSE_LOCATION, Permission.ACCESS_FINE_LOCATION,
                Permission.CAMERA, Permission.READ_PHONE_STATE, Permission.READ_CONTACTS,
            Permission.READ_EXTERNAL_STORAGE, Permission.WRITE_EXTERNAL_STORAGE)
            .request(object : OnPermissionCallback {
                override fun onGranted(permissions: MutableList<String>, all: Boolean) {
                    LogUtils.e("onGranted  all:${all}")
                }

                override fun onDenied(permissions: MutableList<String>, never: Boolean) {
                    LogUtils.e("onDenied  permissions:${permissions.size}")
                }
            })
```

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：OPPO R9s , Android 6.0.1;

* 出现问题的安卓版本【必填】：Android 6.0.1;

**Comment by getActivity** [comment]
<img width="921" alt="image" src="https://user-images.githubusercontent.com/28616817/186326867-808559b1-ad4d-4540-9545-1526f83ba85a.png">

<img width="943" alt="image" src="https://user-images.githubusercontent.com/28616817/186326916-4847afd8-59d0-4000-8ac8-522e7d347276.png">
