### ISSUE TITLE
小米等个性化定制系统imei权限

### ISSUE THREAD

**Issue by maiyong** [getActivity/XXPermissions#15]

**Comment by maiyong** [comment]
小米等个性化定制系统imei权限，虽然获取了READ_PHONE_STATE权限，但是对于小米这些个性化定制系统，还有获取imei权限，这些能否也一同兼容？

**Comment by getActivity** [comment]
这个不是权限的问题，而是系统给不给的问题，系统已经确切禁止，就算有权限也获取不到，这个不属于我的范畴之内
