### ISSUE TITLE
对权限对话框取消的情况处理有误

### ISSUE THREAD

**Issue by parcool** [getActivity/XXPermissions#151]
## 问题描述

* 框架版本【必填】：v16.0

* 问题描述【必填】：对权限对话框取消的情况处理有误

* 复现步骤【必填】：下载最新演示demo apk，安装后点击‘申请单个危险权限’按钮，在弹出权限对话框时，点击对话框外面空白区域或者点击返回键。此时弹出**授权提醒**的对话框内容错误。按照正常逻辑是应该无任何提示或者‘已取消授权’之类，但实际提示的却是‘请手动授权相机权限’？

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：android模拟器

* 出现问题的安卓版本【必填】：api30、api31、api32

## 请回答

* 是部分机型还是所有机型都会出现【必答】：部分。个人猜测所有类原生系统都会有这个问题。

* 框架最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 Demo 来复现该问题【必答】：是

* 使用原生的权限 API 是否会出现该问题【必答】：是

## 其他

我在其他权限请求框架均发现了此问题，也上官网查过，也看过android源码，未找到对应的处理办法。但在我看来：这确实是一个非常不完美的大问题。

**Comment by parcool** [comment]
只能关闭了。这是安卓的缺陷，无法解决，目前我就是没有任何办法才来这里试试的，现在只有去Google那边提bug了。另外，我发现你这项目首页Readme的介绍里有一个小问题：Kotlin示例用法onGrant回调里好像少了个感叹号。
```if (all) {//这里:if(!all){
                toast("获取部分权限成功，但部分权限未正常授予")
                return
            }```

**Comment by getActivity** [comment]
@parcool 收到，纠正了，下个版本更新上去，多谢小伙子的提醒

**Comment by qianjujun** [comment]
可以通过延时法去做，勾选了不再询问的选项 ，这个是没有交互的返回失败结果，基本在100ms内被响应，而取消弹窗或者弹窗消失的结果反馈是有交互的 ，基本大于500ms以上
