### ISSUE TITLE
XXPermissions.isGranted 返回有误

### ISSUE THREAD

**Issue by wammy-h** [getActivity/XXPermissions#152]
## 问题描述

* 框架版本【必填】：16.0

* 问题描述【必填】：XXPermissions.isGranted 返回为false  其实是有权限的 MANAGE_EXTERNAL_STORAGE

* 复现步骤【必填】：设置权限后根据此方法获取状态一直为false

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：xiaomi redmi K30 pro Zoom Edition

* 出现问题的安卓版本【必填】：android 12

## 请回答

* 是部分机型还是所有机型都会出现【必答】：部分

* 框架最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：是

* 是否可以通过 Demo 来复现该问题【必答】：是

* 使用原生的权限 API 是否会出现该问题【必答】：否

## 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）

* 提供截图或视频（根据需要提供，此项不强制）

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by getActivity** [comment]
@wammy-h  小伙子，你直接申请一下这个权限看看是否正常？

**Comment by wammy-h** [comment]
不好意思 是我搞错了  拍照和相册框架用的还是另外2个
