### ISSUE TITLE
Android11 适配分区存储最好可以单独申请 READ_EXTERNAL_STORAGE

### ISSUE THREAD

**Issue by OliverY** [getActivity/XXPermissions#156]
#### 建议收集

我再看下分区存储的适配

* issue 是否有人曾提过类似的问题？【必答】没有

* 框架文档是否有提及到此问题？【必答】：

* 你觉得框架有什么不足之处？【必答】。

* 你觉得该怎么去完善会比较好？【非必答】

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/190682800-52ea59b9-cee8-41d4-99b9-a85bdf6da960.png)

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，具体原因如下：

* 没有严格按照 issue 模板填写

请重新提一个 issue 并纠正以上问题
