### ISSUE TITLE
鸿蒙3.0 系统 权限申请异常

### ISSUE THREAD

**Issue by XiaoWensc** [getActivity/XXPermissions#157]
#### 问题描述

* 框架版本【必填】：16.2

* 问题描述【必填】：在鸿蒙3.0系统中request直接回调了失败onGranted

* 复现步骤【必填】：
* 首次申请权限正常，已授权调用以下代码可复现
* 
 ```
 XXPermissions.with(this).permission(Permission.ACCESS_COARSE_LOCATION)
            .permission(Permission.ACCESS_FINE_LOCATION)
            .permission(Permission.Group.BLUETOOTH)
            .request(object : OnPermissionCallback {
                override fun onGranted(permissions: MutableList<String>?, all: Boolean) {
                    LogUtils.e("onGranted", permissions, all)
                }
                override fun onDenied(permissions: MutableList<String>?, never: Boolean) {
                    LogUtils.d("onDenied", permissions, never)
                    super.onDenied(permissions, never)
                }
            })
```
#####

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：华为P 50 虚拟机 （鸿蒙3.0）

* 出现问题的安卓版本【必填】：鸿蒙3.0

* 问题信息的来源渠道【必填】：自己遇到的

#### 请回答

* 是部分机型还是所有机型都会出现【必答】：鸿蒙3.0必现

* 框架最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 Demo 来复现该问题【必答】：是 （demo的申请定位权限可以复现这个问题） 

* 使用原生的权限 API 是否会出现该问题【必答】：没有尝试

#### 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）

* 提供截图或视频（根据需要提供，此项不强制）

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by getActivity** [comment]
<img width="769" alt="image" src="https://user-images.githubusercontent.com/28616817/192126090-cb231d20-0f97-4cf0-97c8-41ceb395476f.png">

小伙子，你使用原生 API 请求看看会不会有同样的问题？

**Comment by XiaoWensc** [comment]
使用原生API请求正常

**Comment by getActivity** [comment]
<img width="895" alt="image" src="https://user-images.githubusercontent.com/28616817/192280149-daf62550-29f0-4394-8654-b4a13907c1f0.png">

**Comment by getActivity** [comment]
> 直接回调了失败onGranted

小伙子，你不感觉这句有问题？onGranted 是授权成功的方法，onDenied 是授权失败的方法，你到底想表达成功还是失败？

**Comment by getActivity** [comment]
> 使用原生API请求正常

小伙子，我记得鸿蒙只到 Android 10，而蓝牙权限是 Android 12 才有，你直接用系统原生的 API 申请 Permission.Group.BLUETOOTH 能通过？

**Comment by getActivity** [comment]
超过一个星期没有响应，自动关闭此 issue。
