### ISSUE TITLE
可以单独出来一个兼容AndroidX的包吗。

### ISSUE THREAD

**Issue by 1377093782** [getActivity/XXPermissions#158]
#### 问题描述

* 框架版本【必填】：16.2

* 问题描述【必填】：lib1 通过api的方式引入了咱们库  项目1引入了lib 然后build.gradle版本比较高

buildscript {
    ext.kotlin_version = "1.7.0"
    ext.compose_ui_version="1.2.0"
    dependencies {
        classpath 'com.android.tools.build:gradle:7.1.3'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.10'
        classpath 'com.google.dagger:hilt-android-gradle-plugin:2.43.2'

    }

}

plugins {
    id 'com.android.application' version '8.0.0-alpha01' apply false
    id 'com.android.library' version '8.0.0-alpha01' apply false
    id 'org.jetbrains.kotlin.android' version '1.7.0' apply false
//    id 'com.android.application' version '8.0.0' apply false
//    id 'com.android.library' version '8.0.0' apply false
//    id 'org.jetbrains.kotlin.android' version "${kotlin_version}" apply false
}

* 复现步骤【必填】：
* lib1 通过api的方式引入了咱们库  项目1引入了lib 然后build.gradle版本比较高 然后同步代码就出现了
* 
``
* 是否必现【必填】：是

* 出现问题的手机信息【必填】：红米note11 pro

* 出现问题的安卓版本【必填】：12

* 问题信息的来源渠道【必填】：自己遇到的

#### 请回答

* 是部分机型还是所有机型都会出现【必答】：和机型没有关系。主要是as版本。。

* 框架最新的版本是否存在这个问题【必答】：是（如果用的是旧版本的话，建议升级看问题是否还存在）

* 是否已经查阅框架文档还未能解决的【必答】：是（文档会提供最常见的问题解答，可以看看是否有自己想要的）

* issue 是否有人曾提过类似的问题【必答】：额 建议分包。一个版本支持androidX, 一个支持suppert （看看曾经有人提过类似的问题，先参考一下别人是怎么解决的）

* 是否可以通过 Demo 来复现该问题【必答】：是（排查一下是不是自己的项目代码写得有问题导致的）

* 使用原生的权限 API 是否会出现该问题【必答】：与此无关（排查一下是不是框架的代码存在问题导致的）

#### 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）
* Your project has set `android.useAndroidX=true`, but configuration `:app:anguoDebugRuntimeClasspath` still contains legacy support libraries, which may cause runtime issues.
This behavior will not be allowed in Android Gradle plugin 8.0.
Please use only AndroidX dependencies or set `android.enableJetifier=true` in the `gradle.properties` file to migrate your project to AndroidX (see https://developer.android.com/jetpack/androidx/migrate for more info).
The following legacy support libraries are detected:
:app:anguoDebugRuntimeClasspath -> com.anguomob:total:1.0.6.34 -> com.github.getActivity:XXPermissions:16.2 -> com.android.support:support-fragment:27.1.1
:app:anguoDebugRuntimeClasspath -> com.anguomob:total:1.0.6.34 -> com.github.getActivity:XXPermissions:16.2 -> com.android.support:support-fragment:27.1.1 -> com.android.support:support-compat:27.1.1
:app:anguoDebugRuntimeClasspath -> com.anguomob:total:1.0.6.34 -> com.rengwuxian.materialedittext:library:2.1.4 -> com.android.support:support-annotations:27.1.1
:app:anguoDebugRuntimeClasspath -> com.anguomob:total:1.0.6.34 -> com.github.getActivity:XXPermissions:16.2 -> com.android.support:support-fragment:27.1.1 -> com.android.support:support-compat:27.1.1 -> android.arch.lifecycle:runtime:1.1.0
:app:anguoDebugRuntimeClasspath -> com.anguomob:total:1.0.6.34 -> com.github.getActivity:XXPermissions:16.2 -> com.android.support:support-fragment:27.1.1 -> android.arch.lifecycle:livedata-core:1.1.0 -> android.arch.lifecycle:common:1.1.0
:app:anguoDebugRuntimeClasspath -> com.anguomob:total:1.0.6.34 -> com.github.getActivity:XXPermissions:16.2 -> com.android.support:support-fragment:27.1.1 -> android.arch.lifecycle:livedata-core:1.1.0 -> android.arch.core:common:1.1.0
:app:anguoDebugRuntimeClasspath -> com.anguomob:total:1.0.6.34 -> com.github.getActivity:XXPermissions:16.2 -> com.android.support:support-fragment:27.1.1 -> com.android.support:support-core-ui:27.1.1
:app:anguoDebugRuntimeClasspath -> com.anguomob:total:1.0.6.34 -> com.rengwuxian.materialedittext:library:2.1.4 -> com.android.support:appcompat-v7:27.1.1 -> com.android.support:support-core-utils:27.1.1
:app:anguoDebugRuntimeClasspath -> com.anguomob:total:1.0.6.34 -> com.github.getActivity:XXPermissions:16.2 -> com.android.support:support-fragment:27.1.1 -> android.arch.lifecycle:livedata-core:1.1.0
:app:anguoDebugRuntimeClasspath -> com.anguomob:total:1.0.6.34 -> com.github.getActivity:XXPermissions:16.2 -> com.android.support:support-fragment:27.1.1 -> android.arch.lifecycle:livedata-core:1.1.0 -> android.arch.core:runtime:1.1.0
:app:anguoDebugRuntimeClasspath -> com.anguomob:total:1.0.6.34 -> com.github.getActivity:XXPermissions:16.2 -> com.android.support:support-fragment:27.1.1 -> android.arch.lifecycle:viewmodel:1.1.0
:app:anguoDebugRuntimeClasspath -> com.anguomob:total:1.0.6.34 -> com.rengwuxian.materialedittext:library:2.1.4 -> com.android.support:appcompat-v7:27.1.1
:app:anguoDebugRuntimeClasspath -> com.anguomob:total:1.0.6.34 -> com.rengwuxian.materialedittext:library:2.1.4 -> com.android.support:appcompat-v7:27.1.1 -> com.android.support:support-vector-drawable:27.1.1
:app:anguoDebugRuntimeClasspath -> com.anguomob:total:1.0.6.34 -> com.rengwuxian.materialedittext:library:2.1.4 -> com.android.support:appcompat-v7:27.1.1 -> com.android.support:animated-vector-drawable:27.1.1

* 提供截图或视频（根据需要提供，此项不强制）

* 提供解决方案（如果已经解决了的话，此项不强制）
* 额 建议分包。一个版本支持androidX, 一个支持suppert

**Comment by getActivity** [comment]
<img width="899" alt="image" src="https://user-images.githubusercontent.com/28616817/192138027-d9a5abc8-462c-484c-b087-40683cfe6dd0.png">

小伙子，你有按照文档说的这样做么？

**Comment by 1377093782** [comment]
有的。这个是新建的项目 默认的是存在的
![image](https://user-images.githubusercontent.com/22475833/192138122-f87de9d5-39eb-4ce5-90c1-d6b098ad3c38.png)

**Comment by 1377093782** [comment]
This behavior will not be allowed in Android Gradle plugin 8.0.
这个行为在以后的高版本就不支持了。。
我的方案也很简单。。你打两个包 
一个支持androidX的 可以叫
    implementation 'com.github.getActivity:XXPermissions:16.2'
另外一个不适配的叫
    implementation 'com.github.getActivity:XXPermissionsSupport:16.2'

**Comment by getActivity** [comment]
<img width="1268" alt="image" src="https://user-images.githubusercontent.com/28616817/192138182-f5baaa11-4672-4118-9ac8-90fd3dd663b9.png">

你确定？你自己到这个文件中搜索一下关键字 `enableJetifier` 看看有没有

**Comment by 1377093782** [comment]
额。。。
我错了。。好的大佬 谢谢 现在新建默认不带这个了。。我再尝试一次哦

**Comment by getActivity** [comment]
> This behavior will not be allowed in Android Gradle plugin 8.0. 这个行为在以后的高版本就不支持了。。 我的方案也很简单。。你打两个包 一个支持androidX的 可以叫 implementation 'com.github.getActivity:XXPermissions:16.2' 另外一个不适配的叫 implementation 'com.github.getActivity:XXPermissionsSupport:16.2'

如果谷歌不做向后兼容，那我作为开发者自然更加没办法，如果是这样子，我建议你不要用这个版本以上的。

**Comment by 1377093782** [comment]
我的项目还有其他的错误，但是好像那个问题解决了。谢谢你哦。没事了

**Comment by JarvanMo** [comment]
https://github.com/getActivity/XXPermissions/pull/215

**Comment by getActivity** [comment]
框架已迁移到 AndroidX，详情请见 [Release v28.0](https://github.com/getActivity/XXPermissions/releases/tag/28.0)
