### ISSUE TITLE
红米3  miui9.6 android:5.1.1 

### ISSUE THREAD

**Issue by Jsondx** [getActivity/XXPermissions#16]
申请权限拒绝之后，回调hasPermission ，获取成功。

**Comment by getActivity** [comment]
有一种情况，如果在请求多种权限的情况下，这些权限不是被全部授予或者全部拒绝了，而是部分授权部分拒绝这种情况，框架会如何处理回调呢？

框架会先调用noPermission方法，再调用hasPermission方法。
