### ISSUE TITLE
xxpermissions:6.0 版本 在MIUI13.0.7手机上，申请权限时会一直重复弹窗申请，连续三次。

### ISSUE THREAD

**Issue by topscommandroid** [getActivity/XXPermissions#162]
#### 问题描述

* 框架版本【必填】：[XXX](xxpermissions:6.0)

* 问题描述【必填】：xxpermissions:6.0 版本 在MIUI13.0.7手机上，申请权限时会一直重复弹窗申请，连续三次。

* 复现步骤【必填】：第一次安装APP，申请权限，{Permission.CAMERA, Permission.READ_CALL_LOG, Permission.WRITE_EXTERNAL_STORAGE, Permission.READ_PHONE_STATE, Manifest.permission.WRITE_CALENDAR,
            Manifest.permission.READ_CALENDAR}，然后会连续弹窗三次获取这几组权限

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：小米10

* 出现问题的安卓版本【必填】：Android 12

* 问题信息的来源渠道【必填】：自己测试发现，升级MIUI13后发现

#### 请回答

* 是部分机型还是所有机型都会出现【必答】：部分   升级miui13后的机型

* 框架最新的版本是否存在这个问题【必答】：还未升级

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 Demo 来复现该问题【必答】：是

* 使用原生的权限 API 是否会出现该问题【必答】：未排查

#### 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）

* 提供截图或视频（根据需要提供，此项不强制）

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by getActivity** [comment]
<img width="924" alt="image" src="https://user-images.githubusercontent.com/28616817/197195969-d81a3d7b-e6d8-4bca-bb28-f86d8b7f456b.png">

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，具体原因如下：

* 没有严格按照 issue 模板填写

请重新提一个 issue 并纠正以上问题
