### ISSUE TITLE
判断权限问题

### ISSUE THREAD

**Issue by oooo7777777** [getActivity/XXPermissions#165]
#### 问题描述

* 框架版本【必填】：16.2

* 问题描述【必填】：老哥您好，我分别申请了
MANAGE_EXTERNAL_STORAGE  
READ_MEDIA_IMAGES  
READ_MEDIA_VIDEO 这三个权限。

然后后XXPermissions.isGranted(this, Manifest.permission.WRITE_EXTERNAL_STORAGE)去判断这个权限，为什么返回的是false

* 复现步骤【必填】：是

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：小米10，小米11

* 出现问题的安卓版本【必填】：12

* 问题信息的来源渠道【必填】：自己遇到的

#### 请回答

* 是部分机型还是所有机型都会出现【必答】：部分，android11以下的手机不会

* 框架最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 Demo 来复现该问题【必答】：是

* 使用原生的权限 API 是否会出现该问题【必答】：是

#### 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）

* 提供截图或视频（根据需要提供，此项不强制）

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by getActivity** [comment]
小伙子，你用这个包试试看还会不会出现？

**Comment by oooo7777777** [comment]
> 小伙子，你用这个包试试看还不会出现？

老哥 这个aar用不了 
Failed to transform XXPermissions-16.3.aar to match attributes {artifactType=android-compiled-dependencies-resources}.

**Comment by getActivity** [comment]
[permissions.zip](https://github.com/getActivity/XXPermissions/files/9981800/permissions.zip)

**Comment by oooo7777777** [comment]
好的 感谢大佬！

**Comment by getActivity** [comment]
@oooo7777777 小伙子，换上之后还有问题吗？

**Comment by oooo7777777** [comment]
申请MANAGE_EXTERNAL_STORAGE 
XXPermissions.isGranted(this, Manifest.permission.WRITE_EXTERNAL_STORAGE)返回的还是false

申请READ_MEDIA_IMAGES
申请READ_MEDIA_VIDEO 
XXPermissions.isGranted(this, Manifest.permission.WRITE_EXTERNAL_STORAGE)返回的还是true

好奇怪 MANAGE_EXTERNAL_STORAGE 这个权限这么高 为什么还是返回的tre

**Comment by getActivity** [comment]
小伙子，我来解答你的疑惑

* 申请 `MANAGE_EXTERNAL_STORAGE`，但是判断 `WRITE_EXTERNAL_STORAGE` 返回的还是 false

> 这么说吧，`MANAGE_EXTERNAL_STORAGE` 权限不等同于 `WRITE_EXTERNAL_STORAGE` 权限，`MANAGE_EXTERNAL_STORAGE` 和 `WRITE_EXTERNAL_STORAGE` 是两个完全不一样的权限，两码事，你不能认定他们是同一个，一定要区分开，你在 Android 11 上面申请 `MANAGE_EXTERNAL_STORAGE` 权限，然后拿 `WRITE_EXTERNAL_STORAGE` 肯定是有问题的，千万别把这两个不同的权限当做同一个，OK？

* 申请 `READ_MEDIA_IMAGES` 和 `READ_MEDIA_VIDEO`，但是判断 `WRITE_EXTERNAL_STORAGE` 返回的是 true

> 这个问题很简单，`READ_MEDIA_IMAGES` 和 `READ_MEDIA_VIDEO` 这两个权限是 Android 13 的新权限，你应该不是拿 Android 13 的设备去测试，而是拿 Android 12 及以下的版本去验证，Android 12 没有 `READ_MEDIA_IMAGES` 和 `READ_MEDIA_VIDEO` 这两个权限的概念的，框架会自动添加 `READ_EXTERNAL_STORAGE` 和 `WRITE_EXTERNAL_STORAGE` 去申请，所以结果就如你看到的，你最后拿 `WRITE_EXTERNAL_STORAGE` 去判断是返回 true 的。

**Comment by oooo7777777** [comment]
感谢大佬解疑
