### ISSUE TITLE
引入框架编译失败

### ISSUE THREAD

**Issue by eatbanana** [getActivity/XXPermissions#171]
#### 问题描述

* 请描述一下你的疑惑【必填】：gradle.properties中已经添加了android.useAndroidX=true  android.enableJetifier=true  其他配置也按照说明操作完成，但是android studio编译不过，提示：Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'   
Could not find com.github.getActivity:XXPermissions:16.2
并且没有使用jitpack,  使用的远程库https://maven.aliyun.com/repository/public/com/github/getActivity/XXPermissions/16.2/XXPermissions-16.2.pom
请问时什么情况？
#### 请回答

* issue 是否有人曾提过类似的问题？【必答】否

* 框架文档是否有提及到此问题？【必答】：否

**Comment by getActivity** [comment]
* 如果你的项目 Gradle 配置是在 `7.0` 以下，需要在 `build.gradle` 文件中加入

```groovy
allprojects {
    repositories {
        // JitPack 远程仓库：https://jitpack.io
        maven { url 'https://jitpack.io' }
    }
}
```

* 如果你的 Gradle 配置是 `7.0` 及以上，则需要在 `settings.gradle` 文件中加入

```groovy
dependencyResolutionManagement {
    repositories {
        // JitPack 远程仓库：https://jitpack.io
        maven { url 'https://jitpack.io' }
    }
}
```

**Comment by getActivity** [comment]
小伙子，你确定有按照文档的要求集成这个远程仓库的地址？

**Comment by eatbanana** [comment]
是的，一步也没有落下。
settings.gradle文件中加了
`dependencyResolutionManagement {
    repositories {
        // JitPack 远程仓库：https://jitpack.io
        maven { url 'https://jitpack.io' }
    }
}`
build.gradle文件中dependencies中加了
`implementation 'com.github.getActivity:XXPermissions:16.2'`
gradle.properties文件里也有
`android.enableJetifier=true`

**Comment by getActivity** [comment]
你直接把 jitpack 提到远程仓库配置的最前面看看

**Comment by getActivity** [comment]
超过一个星期没有响应，自动关闭此 issue。
