### ISSUE TITLE
 标记定位权限为 android:maxSdkVersion="30" 导致框架内部报错，

### ISSUE THREAD

**Issue by wyntonchin** [getActivity/XXPermissions#172]
#### 问题描述

* 框架版本【必填】：16.2

* 问题描述【必填】：Android 12 以上可以单独申请蓝牙权限，所以可以将定位权限进行标记只使用的 `android:maxSdkVersion="30"`
但是在Android11及以下手机申请定位时，框架检查直接报错了

`java.lang.IllegalArgumentException: The AndroidManifest.xml file <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" android:maxSdkVersion="30" /> does not meet the requirements, please delete the android:maxSdkVersion="30" attribute`

* 复现步骤【必填】：在一个 demo 中标记 Android 30 以上不再使用定位权限的程序，安装到Android 11 一下使用蓝牙时申请定位权限

```xml
<uses-permission
    android:name="android.permission.ACCESS_COARSE_LOCATION"
    android:maxSdkVersion="30" />
<uses-permission
    android:name="android.permission.ACCESS_FINE_LOCATION"
    android:maxSdkVersion="30" />
<uses-permission
    android:name="android.permission.BLUETOOTH_SCAN"
    android:usesPermissionFlags="neverForLocation"
    tools:targetApi="s" />
<uses-permission android:name="android.permission.BLUETOOTH_ADVERTISE" />
<uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
```

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：我的手机时小米9，实际上跟手机无关

* 出现问题的安卓版本【必填】：Android 11版本，

* 问题信息的来源渠道【必填】：自己开发时候验证

#### 请回答

* 是部分机型还是所有机型都会出现【必答】： Android 11及以下版本

* 框架最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 Demo 来复现该问题【必答】：是

* 使用原生的权限 API 是否会出现该问题【必答】：否

#### 其他

* 提供报错堆栈

```text
java.lang.IllegalArgumentException: The AndroidManifest.xml file <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" android:maxSdkVersion="30" /> does not meet the requirements, please delete the android:maxSdkVersion="30" attribute
    at com.hjq.permissions.PermissionChecker.checkManifestPermission(PermissionChecker.java:561)
    at com.hjq.permissions.PermissionChecker.checkManifestPermissions(PermissionChecker.java:526)
    at com.hjq.permissions.XXPermissions.request(XXPermissions.java:177)
```

* 提供截图或视频（根据需要提供，此项不强制）

* 提供解决方案
1、`android:maxSdkVersion="30"` 这个意思是，超过这个版本的手机，我就不用这个权限了，但是低于等于他的我还是要用的。，你需要判断的是 `manifestMaxSdkVersion`  和当前手机 Android 版本关系，而不要用 `Integer.MAX_VALUE`
针对于 `PermissionChecker.java:526`  的判断   `checkManifestPermission(manifestPermissions, permission, Integer.MAX_VALUE);` 最后一个参数不应该传入最大值 `Integer.MAX_VALUE`。
2、或者 可以适配一下 Android 12 的蓝牙权限，或者作者可以在未知后续 Android 有明确要求的情况下，针对 `android:maxSdkVersion="30"` 这种标记应该按照系统的方式去做

**Comment by getActivity** [comment]
<img width="608" alt="image" src="https://user-images.githubusercontent.com/28616817/204554761-a75c89e2-d7a9-4e86-805a-84d3fff613aa.png">

<img width="977" alt="image" src="https://user-images.githubusercontent.com/28616817/204554867-5cf1d325-48a6-4e6e-8f7c-ed20a398b075.png">

**Comment by getActivity** [comment]
小伙子，你确定没有改过框架的代码？从你提供的异常信息里面都没有显示是哪个权限？但是我在框架代码里面是写了的。

**Comment by wyntonchin** [comment]
我标记我的代码的定位权限最高 android:maxSdkVersion="30"  ， 也就是Android 11
也就是说 我在Android12上我就不需要定位权限了。
但是我在Android11的手机还是需要定位权限的，因为我要用蓝牙。

你说“Android 11会自动添加定位权限”，这个肯定不对，用蓝牙之前，Android11的定位权限必须要自己主动申请才行的。否则APP根本扫描不到蓝牙ble设备。

**Comment by wyntonchin** [comment]
当然 android:maxSdkVersion="30" 这句去掉就好了，但是因为很多商店对这类敏感权限要填表 说明审核，特别麻烦

**Comment by getActivity** [comment]
小伙子，看来你还是没有听懂我上面的意思，我直接了断地说，你这种写法是错误的，裤子放屁（多此一举），我上面也说过了，你压根不需要判断 Android 版本来决定是申请定位权限还是蓝牙权限，直接申请蓝牙权限即可，在 Android 11 及以下版本申请的时候框架会自动帮你添加定位权限进去，你只需要直接这样写即可：

```kotlin
XXPermissions.with(this)
    .permission(Permission.BLUETOOTH_SCAN)
    .permission(Permission.BLUETOOTH_CONNECT)
    .permission(Permission.BLUETOOTH_ADVERTISE)
    .request(object : OnPermissionCallback() {
        fun onGranted(permissions: List<String>, all: Boolean) {

        }
    })
```

**Comment by wyntonchin** [comment]
好吧，你居然这样设计的。
但还是建议不要这么限制开发者这样调用

**Comment by getActivity** [comment]
<img width="659" alt="image" src="https://user-images.githubusercontent.com/28616817/205330467-31ed9700-c355-404a-b318-10f9dfee2539.png">

<img width="683" alt="image" src="https://user-images.githubusercontent.com/28616817/205330295-1a59874c-8d00-4b96-b648-96e06015da2d.png">

**Comment by getActivity** [comment]
同样的问题，请不要让我回答 N 遍，这样会把我逼成一台复读机。

**Comment by Nobler** [comment]
为什么不允许定义呢，我看代码这里是直接和Integer.MAX_VALUE比较的，所以不是真的版本号有问题吧。

**Comment by Nobler** [comment]
我的场景是请求WRITE_EXTERNAL_STORAGE，按照官方文档应该是要声明maxSdkVersion的https://developer.android.com/training/data-storage/shared/media#access-other-apps-files。

**Comment by getActivity** [comment]
@Nobler 小伙子，关于这个问题可以加上 `unchecked` 这个方法，这样就能避免框架对清单文件进行检测。

**Comment by Nobler** [comment]
> @Nobler 小伙子，关于这个问题可以加上 `unchecked` 这个方法，这样就能避免框架对清单文件进行检测。

可以解释一下maxSdkVersion的check逻辑吗，抛异常这里我感觉是强制的，按理说应该是要判断版本才对的吧。

**Comment by getActivity** [comment]
<img width="784" alt="image" src="https://github.com/getActivity/XXPermissions/assets/28616817/5ef10991-65dd-4aba-bf82-963866d8b532">

小伙子，框架文档上面不是有说了么？

**Comment by getActivity** [comment]
另外针对 `WRITE_EXTERNAL_STORAGE` 权限也比较特殊，框架存在一定的优化空间，更准确做法应该是先判断 targetSdk 版本，如果小于等于 29，那么就检测是否设置了权限对应的 `android:maxSdkVersion` 属性，如果有的话则抛出异常，如果 targetSdk 版本大于 30，那么就检测对应的 `android:maxSdkVersion` 属性的值有没有小于 29，如果是的话则才抛出异常，如果不是的话则不需要抛出异常。

**Comment by getActivity** [comment]
不过还有一个问题是，如果这样做的话，可能会导致另外一个问题，那么在 Android 11、Android 12 上面会申请 `WRITE_EXTERNAL_STORAGE` 会系统直接拒绝，因为这个权限虽然在清单文件中注册了，但是 `maxSdkVersion` 只到了 Android 10，在 Android 10 以上的设备申请是不受认可的，约等于在 Android 10 上面就是在清单文件中没有注册过这个权限的效果，而 Android 13 的话，我这边做了特殊处理，直接返回 true 表示有权限，所以没有什么影响，如果要解决刚刚说的那个问题，应该要把这个规则修改一下，同时在 Android 11、Android 12、Android 13 同时返回 true 表示有权限，这样应该就没有问题了。

**Comment by getActivity** [comment]
@Nobler 小伙子，这块你觉得呢？

**Comment by Nobler** [comment]
是的，文档有看到，但是这里的异常检查的逻辑是跟Integer.MAX_VALUE进行比较的，所以SDK实际上是不希望设置maxSdkVersion，而无关具体值是否是对的（其他场景下是有判断具体值的，但是详细逻辑没有具体再研究了）。
确实像你说的这个权限现在用起来有些理解成本，文档上也花了很大篇幅来解释，但其实很多人是不看文档的。

我觉得一个优化的角度，或者说是整个SDK的设计理念，可以尽量匹配官方策略。
像我最开始会以官方的角度去理解这个SDK的用法，但是发现有些问题，详细看了文档才知道，实际上框架做了很多工作来减少开发成本。当然每个框架有自己的哲学，主要原因可能还是权限这部分太碎片化了。

最后说一些建议吧，可能不完全对，可以再讨论：
1. 文档其实比较全，但像我上面说的，很多人其实都不看文档。所以可以考虑下优化现在的文档，可能要有个使用必读，有些特殊权限的使用姿势介绍。现在关于存储这部分权限的介绍是放在兼容性的描述里的，比较难抓住重点，看文档的时候容易忽略掉。
2. 关于兼容策略，不知道能不能做成可选的，或者可自定义的（目前看可能不现实，只是从设计之初来说是不是一个可以考虑的点）。其他权限框架主要是封装了申请流程，兼容性是要开发者自己的实现的；而本框架虽然实现了兼容性，但是这些兼容性是SDK作者实现的，对于开发者其实还是要了解某些细节才能真正用起来。

最后还是感谢一下老伙计，无论如何一个框架能一直维护就非常良心了，冲这点秒杀其他任何框架。

**Comment by getActivity** [comment]
小伙子，我来解答你上面的几个问题：

1. 框架有理解成本：因为框架设计理念是为了方便开发者调用，所以框架内部做了很多封装，其中有很多不需要开发者关注和处理的，但是有一些必须开发者关注的，例如框架对新权限在旧设备上面的兼容，这个就需要开发者了解和熟悉，但是我始终认为，这个适配不应该开放给外层来做，因为每个人无法对权限有一个很全面的认知，他完全不了解这个新权限对应的旧权限是什么，然后直接申请这个新权限，结果就是导致新权限在新设备上面没有问题，但是在旧设备申请失败了，最后的结果就是大多开发者会甩锅给框架作者，我用你这个框架申请权限结果就是有问题，还不如我直接用原生的 API 申请，浪费我的时间等抱怨的话，我会强制要求开发者在申请新权限的同时，要在清单文件中注册旧权限，这样框架才能在旧设备帮你做兼容处理。

2. 很多人不看文档的问题：这个问题非常正常的，大部分情况下人性是懒惰的，没有人会喜欢看文档，但是一直来问我这种重复问题，会给我造成巨大的困扰，可能今天张三问一次，明天李四问一次，后天王五问一次，同一个问题每天换不同的人来问，在这种模式下，开源作者是承受不了的，所以我做了一些限制，要求每一个提 issue 的人必须要看过文档，如果没有看过就来提，我会直接关闭不处理。

3. 给有的文档标记必读：我觉得这样是不太可行的，因为每一个人的需求不一样，可能你今天用我的框架遇到了问题，就会来看我的文档，如果没有的话，就不会来看我的文档了，至于必不必读我觉得没有什么必要，因为文档只针对特定的问题才能发挥作用，就算你写了必读，也不一定会有人照做，还不如等出现了问题，让这个人仔细看一遍，如果这个人想偷懒，也可以通过网页搜索关键字的方式来检索文档中有没有自己想要的。

4. 兼容策略：能不能做成可选的，其实你可以换一种思维，直接屏蔽框架的检测机制，然后判断当前的 Android 版本，根据不同的 Android 版本去申请不同的权限，这样也是可以的，但是这个需要你熟悉这个权限和做大量的测试，这个过程非常消耗时间，否则就很可能因为个人的认知存在问题，并且没有做够测试，就会导致很容易出现 Bug。

**Comment by Nobler** [comment]
> 小伙子，我来解答你上面的几个问题：
> 
> 1. 框架有理解成本：因为框架设计理念是为了方便开发者调用，所以框架内部做了很多封装，其中有很多不需要开发者关注和处理的，但是有一些必须开发者关注的，例如框架对新权限在旧设备上面的兼容，这个就需要开发者了解和熟悉，但是我始终认为，这个适配不应该开放给外层来做，因为每个人无法对权限有一个很全面的认知，他完全不了解这个新权限对应的旧权限是什么，然后直接申请这个新权限，结果就是导致新权限在新设备上面没有问题，但是在旧设备申请失败了，最后的结果就是大多开发者会甩锅给框架作者，我用你这个框架申请权限结果就是有问题，还不如我直接用原生的 API 申请，浪费我的时间等抱怨的话，我会强制要求开发者在申请新权限的同时，要在清单文件中注册旧权限，这样框架才能在旧设备帮你做兼容处理。
> 2. 很多人不看文档的问题：这个问题非常正常的，大部分情况下人性是懒惰的，没有人会喜欢看文档，但是一直来问我这种重复问题，会给我造成巨大的困扰，可能今天张三问一次，明天李四问一次，后天王五问一次，同一个问题每天换不同的人来问，在这种模式下，开源作者是承受不了的，所以我做了一些限制，要求每一个提 issue 的人必须要看过文档，如果没有看过就来提，我会直接关闭不处理。
> 3. 给有的文档标记必读：我觉得这样是不太可行的，因为每一个人的需求不一样，可能你今天用我的框架遇到了问题，就会来看我的文档，如果没有的话，就不会来看我的文档了，至于必不必读我觉得没有什么必要，因为文档只针对特定的问题才能发挥作用，就算你写了必读，也不一定会有人照做，还不如等出现了问题，让这个人仔细看一遍，如果这个人想偷懒，也可以通过网页搜索关键字的方式来检索文档中有没有自己想要的。
> 4. 可选的兼容策略：能不能做成可选的，其实你可以换一种思维，直接屏蔽框架的检测机制，然后判断当前的 Android 版本，根据不同的 Android 版本去申请不同的权限，这样做也是可以的，但是这个需要你熟悉这个权限和做大量的测试，这个过程非常消耗时间，否则就很可能因为个人的认知存在问题，并且没有做够测试，就会导致很容易出现 Bug。

1. 两种方式成本都是有的，我的想法是可以尽量按照官方的策略，比如这次的存储权限，其实和官方策略有些不一致。这样对于了解官方策略的人来说，成本可能小一点。当然对完全不懂的人来说没啥区别了。
2. 文档确实大多数时候是个字典，遇到问题了才回去看。检查这个做法也很好。我上面的建议主要是可以针对不同类型的权限的特殊处理要列的明确一些，现在存储权限的一些描述是比较分散的，如果可以整理一下，有个类目叫存储权限须知之类的可能更好。
3. 我的角度还是优化，没办法解决问题，只是试着减少问题。
4. 我的理解其实是可以提供兼容模式的开关，默认是开启兼容模式的。可能开发者想有自己的兼容策略，或者在某些时候SDK的兼容出现了问题，开发者也可以自己去做兼容。

**Comment by Nobler** [comment]
> 不过还有一个问题是，如果这样做的话，可能会导致另外一个问题，那么在 Android 11、Android 12 上面会申请 `WRITE_EXTERNAL_STORAGE` 会系统直接拒绝，因为这个权限虽然在清单文件中注册了，但是 `maxSdkVersion` 只到了 Android 10，在 Android 10 以上的设备申请是不受认可的，约等于在 Android 10 上面就是在清单文件中没有注册过这个权限的效果，而 Android 13 的话，我这边做了特殊处理，直接返回 true 表示有权限，所以没有什么影响，如果要解决刚刚说的那个问题，应该要把这个规则修改一下，在 targetSdk 大于等于 Android 11 的时候，同时在 Android 11、Android 12、Android 13 的设备上同时返回 true 表示有权限，这样应该就没有问题了。

关于这个问题，老伙计可以有时间了优化下。目前的解决方式只能是把check关闭，但是开着其实是更好的，但开着就没法写maxSdkVersion，如果应用商店有要求可能就影响上架了。

**Comment by getActivity** [comment]
> 关于这个问题，老伙计可以有时间了优化下。目前的解决方式只能是把check关闭，但是开着其实是更好的，但开着就没法写maxSdkVersion，如果应用商店有要求可能就影响上架了。

@Nobler 小伙子，目前有应用市场那么要求吗？

**Comment by Nobler** [comment]
目前还没遇到，android 13还在适配，还没上架。我是考虑到毕竟这个是官方文档上提到的做法，能保持逻辑一直是最好的。

Android轮子哥 ***@***.***> 于 2023年5月13日周六 21:31写道：
