### ISSUE TITLE
在Rokid station设备上请求权限会从竖屏转换为横屏状态

### ISSUE THREAD

**Issue by xiasir2333** [getActivity/XXPermissions#173]
#### 问题描述

* 请描述一下你的疑惑【必填】：XXX（注意：如果是框架 bug 请不要在这里提，否则一概不受理）
*在Rokid stationAR眼镜设备上请求权限会从竖屏转换为横屏状态，即使我设置了android:screenOrientation="sensorPortrait"也会这样，使用示例代码也会这样，我感觉这或许是设备的问题，想来确认一下，这个设备是默认横屏的，安卓TV系统，11版本，横竖屏切换不会导致异常，只是看起来UI会有些别扭

#### 请回答

* issue 是否有人曾提过类似的问题？【必答】（一旦出现重复提问我将不会再次解答）无

* 框架文档是否有提及到此问题？【必答】：是/否（请先看完框架的文档后再来提建议）无

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 没有严格按照 issue 模板填写问题

请重新提一个 issue 并纠正以上问题
