### ISSUE TITLE
在Rokid Station设备上请求权限会从竖屏转换为横屏状态

### ISSUE THREAD

**Issue by xiasir2333** [getActivity/XXPermissions#174]
#### 问题描述

* 请描述一下你的疑惑【必填】：
在Rokid stationAR眼镜设备上请求权限会从竖屏转换为横屏状态，即使我设置了android:screenOrientation="sensorPortrait"也会这样，使用示例代码也会这样，我感觉这或许是设备的问题，想来确认一下，这个设备是默认横屏的，安卓TV系统，11版本，横竖屏切换不会导致异常，只是看起来UI会有些别扭

#### 请回答

* issue 是否有人曾提过类似的问题？【必答】否

* 框架文档是否有提及到此问题？【必答】：否

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 这个问题属于 Bug，应该提 Bug 单，但是你提了疑惑单

请重新提一个 issue 并纠正以上问题

**Comment by xiasir2333** [comment]
我前面写的很明显已经说了认为这个不是BUG而是系统特性，你不指出我提交的分区不对，只说没按格式填写，我就以为是那些字没删干净，你这样子不是在浪费时间吗

**Comment by getActivity** [comment]
* 那你之前为什么不直接说明白呢？我看你之前还会截图指出有问题的地方，这样根本不知道哪有问题，

> 因为有的人会按照 issue 模板填写，但是实际上是乱填，为了杜绝此类问题，一般情况下我都不会把问题点说得太细，如果我按照之前的方式解答问题，会导致有人喜欢一有问题就疯狂提 issue，根本不顾及作者的感受，不过我现在的做法是一刀切，但是实际上做得还不够好，我应该指出问题大概的点，比如文档上面有写，我会提醒提问的人去看文档，但是我绝不会把文档丢到他面前，因为这样会给别人养成惰性。

* 那不就是你想回就回不想回就不回，

> 如果我想不回，直接就不会回复这个 issue 了，而不是提醒你要按照 issue 模板填写了。

* BUG跟特性是怎么区分的你有说过吗？

> Bug 的标准我现在没有列出到文档中，这是我做得不够好的地方，后续我会补充一下，但是我可以先说出来一个标准，运行代码遇到一切异常都可以算 Bug，比如崩溃闪退、应用程序无响应、UI 错乱、数据显示有问题，原本要执行逻辑没有执行，原本不需要执行的逻辑却执行了等等这些问题都能算 Bug，简单概括就是代码运行层面遇到的一些异常，然后只要是 Bug，无论是系统的还是应用的，都是需要提 Bug 单，而不是提疑问单或者建议单，疑问单开放出来主要是为了解答一些非 Bug 级别问题的，比如：为什么不转成 AndroidX？框架里面的那句代码这样写会不会有什么问题？遇到一个奇葩的需求框架满足不了该怎么办？文档那样写是不是有问题？等等这种问题就可以提疑问单。

* 我前面写的很明显已经说了认为这个不是BUG而是系统特性，你不指出我提交的分区不对，只说没按格式填写，我就以为是那些字没删干净，你这样子不是在浪费时间吗

> 《请求权限会从竖屏转换为横屏状态》像这种问题，如果不是你主动旋转屏幕，这不就是 Bug 了？你难道觉得这个还是正常的？别管是框架 Bug 或者系统 Bug，总之它就属于 Bug，应当按照 Bug issue 模板填写，而不是按照疑问 issue 模板填写，千万不要为了图省事而填写疑问单，否则你的问题只会越难解决，当然我也会优化自身的一些问题，下次如果提问的单子有问题，我尽量不将描述写得太模糊。

**Comment by getActivity** [comment]
https://github.com/getActivity/IssueTemplateGuide
