### ISSUE TITLE
国内厂商部份系统获取应用列表要新加一个危险权限：com.android.permission.GET_INSTALLED_APPS

### ISSUE THREAD

**Issue by qq549631030** [getActivity/XXPermissions#175]
#### 问题描述

* 框架版本【必填】：16.2

* 问题描述【必填】：申请com.android.permission.GET_INSTALLED_APPS权限时候会报错：The com.android.permission.GET_INSTALLED_APPS  is not a dangerous permission or special permission, please do not apply dynamically

* 复现步骤【必填】：申请com.android.permission.GET_INSTALLED_APPS权限

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：华为P50E

* 出现问题的安卓版本【必填】：Android 12（HarmonyOS 3.0.0.162）

* 问题信息的来源渠道【必填】：自己遇到的

#### 请回答

* 是部分机型还是所有机型都会出现【必答】：华为 HarmonyOS 3.0.0

* 框架最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：有个临时解决办法就是设置unchecked()

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 Demo 来复现该问题【必答】：是

* 使用原生的权限 API 是否会出现该问题【必答】：否

#### 其他

* 提供报错堆栈  
java.lang.IllegalArgumentException: The com.android.permission.GET_INSTALLED_APPS is not a dangerous permission or special permission, please do not apply dynamically
com.hjq.permissions.PermissionChecker.checkPermissionArgument(PermissionChecker.java:106)
com.hjq.permissions.XXPermissions.request(XXPermissions.java:159)
cn.hx.base.utils.PermUtil$ensurePermNormal$3$1.invokeSuspend(PermUtil.kt:182)
cn.hx.base.utils.PermUtil$ensurePermNormal$3$1.invoke(Unknown Source:8)
cn.hx.base.utils.PermUtil$ensurePermNormal$3$1.invoke(Unknown Source:4)

* 提供截图或视频

* 提供解决方案
com.hjq.permissions.Permission中把com.android.permission.GET_INSTALLED_APPS这一国产权限加上  
[移动终端应用软件列表权限实施指南](http://www.taf.org.cn/StdDetail.aspx?uid=3A7D6656-43B8-4C46-8871-E379A3EA1D48&stdType=TAF)

**Comment by getActivity** [comment]
小伙子，我这边兼容了这个权限，你可以下载上面的 aar 包试试看。

**Comment by qq549631030** [comment]
验证过了，ok了

**Comment by huaxuanHan** [comment]
有个问题想问很久了，大佬平时叫谁都是小伙子？大佬多大年纪了

**Comment by getActivity** [comment]
> 有个问题想问很久了，大佬平时叫谁都是小伙子？大佬多大年纪了

小伙子只是一个称呼，没有包含太多的含义

**Comment by getActivity** [comment]
[XXPermissions-16.6.aar.zip](https://github.com/getActivity/XXPermissions/files/10237420/XXPermissions-16.6.aar.zip)

**Comment by getActivity** [comment]
@qq549631030 小伙子，之前发给你的包发现一个 Bug：如果是在 Android 原生系统上面，你如果同时申请了 `GET_INSTALLED_APPS` 和**其他某个危险权限**，当用户授予了某个危险权限之后，会出现 `GET_INSTALLED_APPS` 授权失败的情况，但是后面用户再去申请就没有问题了，这是因为之前的包没有 `onRequestPermissionsResult` 方法中对 `GET_INSTALLED_APPS` 权限进行重新检查是否授权，因为 Android 原生系统下默认是没有这个权限的，所以在 Android 原生系统上面会授权失败，当然你如果没有拿 `GET_INSTALLED_APPS` 和**其他某个危险权限**去同时申请，其实也不需要更新这个 aar 包。

**Comment by qq549631030** [comment]
感谢，我没有和别的权限一起请求，请求这个之前会选判断系统支不支持这个权限
```
/**
 * 是否支持com.android.permission.GET_INSTALLED_APPS权限
 */
fun supportGetInstalledAppsPermission(context: Context): Boolean {
    val permissionInfo = try {
        context.packageManager.getPermissionInfo(GET_INSTALLED_APPS, 0)
    } catch (e: Exception) {
        null
    }
    return permissionInfo != null
}
```
另外发现一个问题，PermissionChecker.checkManifestPermissions方法里闹钟权限的判断有问题
```
                if (PermissionUtils.equalsPermission(permission, Permission.SCHEDULE_EXACT_ALARM)) {
                    // https://developer.android.google.cn/reference/android/Manifest.permission?hl=zh_cn#USE_EXACT_ALARM
                    if (AndroidVersion.getTargetSdkVersionCode(context) >= AndroidVersion.ANDROID_13) {
                        checkManifestPermission(permissionInfoList, Permission.SCHEDULE_EXACT_ALARM, AndroidVersion.ANDROID_12_L);
                    } else {
                        checkManifestPermission(permissionInfoList, Permission.SCHEDULE_EXACT_ALARM);
                    }
                    continue;
                }
```
判断的不应该是SCHEDULE_EXACT_ALARM，应该是Android 13新加的USE_EXACT_ALARM

**Comment by getActivity** [comment]
@qq549631030 小伙子，纠正你的两个错误：
1. 你不需要写 `com.android.permission.GET_INSTALLED_APPS`，因为 `Permission` 类中已经定义过了，直接引用 `Permission.GET_INSTALLED_APPS` 即可。
2. 你也不需要写判断是否支持申请这个权限，因为框架内部已经帮你做了这个判断了，如果手机系统不支持申请这个权限，会直接回调授权成功。

**Comment by AyakaAgo** [comment]
@getActivity 所以`com.android.permission.GET_INSTALLED_APPS`**其实不需要在`manifest`里声明**而只是 TAF 的要求？即使不写也可以查询到权限。

**Comment by getActivity** [comment]
> [@getActivity](https://github.com/getActivity) 所以`com.android.permission.GET_INSTALLED_APPS`其实**不需要在`manifest`里声明**而只是 TAF 的要求？即使不写也可以查询到权限，那我可以去掉了🙈

要在清单文件中加一下的，因为获取应用列表这个权限，虽然不是 Android 官方出品的权限，但是大部分厂商还是沿用的 Android 那套原生的危险权限机制来实现的 `com.android.permission.GET_INSTALLED_APPS` 这个权限，Android 原生的危险权限机制要求动态申请权限之前，需要在清单文件中进行静态注册。
