### ISSUE TITLE
鸿蒙3.0.0出现蓝牙权限SCAN拒绝但是无法打开的情况，疑似被系统冻结却没有任何地方可以打开，卸载重装可以重新申请权限。

### ISSUE THREAD

**Issue by zhouzhuo810** [getActivity/XXPermissions#177]
#### 问题描述

* 框架版本【必填】：请输入你使用的框架版本
16.0

* 问题描述【必填】：请输入你对这个问题的描述
鸿蒙3.0.0出现蓝牙权限SCAN拒绝但是无法打开的情况，疑似被系统冻结却没有任何地方可以打开，卸载重装可以重新申请权限。

* 复现步骤【必填】：请输入问题的复现步骤（注意：目前不受理没有复现步骤的 Bug 单）
据反馈，说是鸿蒙系统升级前蓝牙正常，升级到3.0.0之后不正常，且一直走的onDenied方法。

```
    <uses-permission android:name="android.permission.BLUETOOTH" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
    <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
    <uses-permission
        android:name="android.permission.BLUETOOTH_SCAN"
        android:usesPermissionFlags="neverForLocation" />
```

```
        if (OSUtils.isAndroid12()) {
            XXPermissions.with(this)
                .permission(Permission.BLUETOOTH_SCAN,
                    Permission.BLUETOOTH_CONNECT)
                .request(new OnPermissionCallback() {
                    @Override
                    public void onGranted(List<String> permissions, boolean all) {
                        if (all) {
                            startSearch();
                        }
                    }
                    
                    @Override
                    public void onDenied(List<String> permissions, boolean never) {
                        GFToastUtil.showNormalToast(getString(R.string.refuse_ble_scan_permission_hint));
                    }
                });
        }
```

* 是否必现【必填】：是，不过卸载重装后怎么复现还不知道，有可能是冻结了权限，但是设置里没有任何开关。

* 出现问题的手机信息【必填】：华为 Meta 40 

* 出现问题的安卓版本【必填】：Android 12（鸿蒙3.0.0）

* 问题信息的来源渠道【必填】：用户反馈

#### 请回答

* 是部分机型还是所有机型都会出现【必答】：和机型无关，和系统有关。

* 框架最新的版本是否存在这个问题【必答】：不清楚，但是我看框架最近几个版本没改过这一块。

* 是否已经查阅框架文档但还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 Demo 来复现该问题【必答】：否

* 使用原生的权限 API 是否会出现该问题【必答】：没试，还不知道怎么尝试。

#### 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）

* 提供截图或视频（根据需要提供，此项不强制）

![image](https://user-images.githubusercontent.com/15272555/210495124-38a206d9-6047-42b6-a625-acba573c8086.png)

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by zhouzhuo810** [comment]
好像是因为有个【附近设备】的权限被关闭了，我看小米没有这个权限，鸿蒙搞特殊化，加了个这个权限，我才发现，不好意思，打扰了。

**Comment by fixedyangsir** [comment]
> 好像是因为有个【附近设备】的权限被关闭了，我看小米没有这个权限，鸿蒙搞特殊化，加了个这个权限，我才发现，不好意思，打扰了。

哥们怎么解决的
