### ISSUE TITLE
Android10上，READ_PHONE_STATE没有弹出允许弹窗

### ISSUE THREAD

**Issue by ChenXiaoYao407** [getActivity/XXPermissions#178]
#### 问题描述

* 问题描述【必填】：Android10上，READ_PHONE_STATE没有弹出允许弹窗

#### 请回答

* issue 是否有人曾提过类似的问题？【没有

* 框架文档是否有提及到此问题？【必答】：否

**Comment by getActivity** [comment]
```
public final class Permission {

    ......

    /**
     * 读取电话状态
     *
     * 需要注意的是：这个权限在某些手机上面是没办法获取到的，因为某些系统禁止应用获得该权限
     *             所以你要是申请了这个权限之后没有弹授权框，而是直接回调授权失败方法
     *             请不要惊慌，这个不是 Bug、不是 Bug、不是 Bug，而是正常现象
     *
     * 后续情况汇报：有人反馈在 iQOO 手机上面获取不到该权限，在清单文件加入下面这个权限就可以了（这里只是做记录，并不代表这种方式就一定有效果）
     *             <uses-permission android:name="android.permission.READ_PRIVILEGED_PHONE_STATE" />
     */
    public static final String READ_PHONE_STATE = "android.permission.READ_PHONE_STATE";

    ......
}
```

**Comment by getActivity** [comment]
小伙子，你的这个问题代码注释上面回答得很清楚了

**Comment by ChenXiaoYao407** [comment]
看到了，但是<uses-permission android:name="android.permission.READ_PRIVILEGED_PHONE_STATE" />这个权限，在清单文件了写了之后，清单文件报错，我查看Manifest这个源码里没有这个权限，谢谢老哥

**Comment by ChenXiaoYao407** [comment]
还有一个问题，我没有找到蓝牙相关的权限
![image](https://user-images.githubusercontent.com/28752258/212674425-c43513d7-74fb-4d92-9273-ad1322ce35c8.png)

**Comment by getActivity** [comment]
> 看到了，但是这个权限，在清单文件了写了之后，清单文件报错，我查看Manifest这个源码里没有这个权限，谢谢老哥

<img width="763" alt="image" src="https://user-images.githubusercontent.com/28616817/212676579-74f52d9a-d353-4727-afc2-55f0d2ea3984.png">

它不是没有这个权限，而是会提示你这是一个系统应用权限才能授予的权限，但是你完全可以忽略这个警告。

**Comment by getActivity** [comment]
> 还有一个问题，我没有找到蓝牙相关的权限 ![image](https://user-images.githubusercontent.com/28752258/212674425-c43513d7-74fb-4d92-9273-ad1322ce35c8.png)

蓝牙权限是 Android 13 新出的权限，而 Android 13 是 2022 年 8 月发布的，但是你用的框架版本是 2018 年发布的，你猜一猜能不能从里面找到蓝牙权限？

**Comment by ChenXiaoYao407** [comment]
> > 看到了，但是这个权限，在清单文件写了之后，清单文件报错，我查看Manifest这个源码里没有这个权限，谢谢老哥
> 
> <img alt="图像" width="763" src="https://user-images.githubusercontent.com/28616817/212676579-74f52d9a-d353-4727-afc2-55f0d2ea3984.png">
> 
> 它不是没有这个权限，而是会提示你这是一个系统应用权限才能授予权限，但你完全可以忽略这个警告。

好的，感谢老哥

**Comment by getActivity** [comment]
超过一个星期没有响应，自动关闭此 issue。
