### ISSUE TITLE
小米手机短信权限弹框是否要读取一次短信才会弹出?

### ISSUE THREAD

**Issue by hanxiaomeme** [getActivity/XXPermissions#179]
#### 问题描述

* 问题描述【必填】：小米手机短信权限弹框是否要读取一次短信才会弹出?

#### 请回答

* issue 是否有人曾提过类似的问题？无

* 框架文档是否有提及到此问题？无

**Comment by getActivity** [comment]
小伙子，你如果出现了这个问题，请直接提一个 bug issue 给我，而不是反问我是不是这样的，你自己试一下不就知道了。
