### ISSUE TITLE
系统里面授权了，怎么获取这个状态呢

### ISSUE THREAD

**Issue by nevergoneok** [getActivity/XXPermissions#18]
去系统设置页面授权了，怎么在app里面判断是否在系统设置中授权了呢？运行了下demo，如果我是在系统设置页面授权，框架还是会提示要我去设置页面，有没有解决方案呢？

**Comment by getActivity** [comment]
我这边测试正常哦，在设置界面授予了权限之后，再次申请权限会提示已授予的

**Comment by getActivity** [comment]
如果这个问题还是存在，建议你加群联系我解决这个问题
