### ISSUE TITLE
通过checkJetifierAll命令发现 XXPermissions还未支持AndroidX，能否升级到AndroidX？

### ISSUE THREAD

**Issue by tanranran** [getActivity/XXPermissions#180]
task checkJetifierAll(group: "verification") { }
 
subprojects { project ->
    project.tasks.whenTaskAdded { task ->
        if (task.name == "checkJetifier") {
            checkJetifierAll.dependsOn(task)
        }
    }
}

通过运行./gradlew checkJetifierAll就可以打印出所有module的Jetifier使用情况

 Task :app:checkJetifier
The following libraries used by project ':app' depend on legacy support libraries. To disable Jetifier, you will need to use AndroidX-supported versions of these libraries.
        com.github.getActivity:XXPermissions:16.2 (Project ':app', configuration 'developDebugRuntimeClasspath' -> com.github.getActivity:XXPermissions:16.2 -> com.android.support:support-fragment:24.2.0)

通过上述步骤发现XXPermissions还再依赖com.android.support:support-fragment，导致没有完全适配Jetifier

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 没有严格按照 issue 模板填写问题

请重新提一个 issue 并纠正以上问题

**Comment by JarvanMo** [comment]
https://github.com/getActivity/XXPermissions/pull/215
