### ISSUE TITLE
小米12 S pro Android 13系统位置服务权限一直不弹出询问窗口

### ISSUE THREAD

**Issue by PPLLock** [getActivity/XXPermissions#182]
问题描述
问题描述【必填】：您好，小米12 S pro Android 13系统位置服务权限一直不弹出询问窗口导致蓝牙搜索不到设备?
请回答
issue 是否有人曾提过类似的问题？无
框架文档是否有提及到此问题？无

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 这个问题属于 bug，不能提疑问 issue 单，请提 bug issue 单

请重新提一个 issue 并纠正以上问题
