### ISSUE TITLE
XXPermission在安卓6.0+，安卓11以下无法拉起读写权限的动态授权

### ISSUE THREAD

**Issue by 9292922** [getActivity/XXPermissions#183]
#### 问题描述

* 框架版本【必填】：16.2

* 问题描述【必填】：请输入你对这个问题的描述

* 复现步骤【必填】：
调用READ_EXTERNAL_STORAGE、WRITE_EXTERNAL_STORAGE的授权，无法拉起授权
使用旧版本13.2不会有这个问题

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：谷歌Android模拟器

* 出现问题的安卓版本【必填】：API 26

* 问题信息的来源渠道【必填】：用户反馈，并且自己也遇到

#### 请回答

* 是部分机型还是所有机型都会出现【必答】：全部

* 框架最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档但还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 Demo 来复现该问题【必答】：否

* 使用原生的权限 API 是否会出现该问题【必答】：否

**Comment by getActivity** [comment]
小伙子，既然最新版本没有问题，你直接升级框架不就 OK 了？

**Comment by 9292922** [comment]
是最新版本有问题，旧版本13.2没问题



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月22日(周三) 中午12:35
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [getActivity/XXPermissions] XXPermission在安卓6.0+，安卓11以下无法拉起读写权限的动态授权 (Issue #183)




 
小伙子，既然最新版本没有问题，你直接升级框架不就 OK 了？

**Comment by getActivity** [comment]
那你为什么在《框架最新的版本是否存在这个问题》写否？

**Comment by 9292922** [comment]
> 那你为什么在《框架最新的版本是否存在这个问题》写否？

一时大意写错啦，抱歉，引起误会，那您这边测试最新版本是否可以在Android6.0～Android10中动态授权文件读写权限呢？

**Comment by getActivity** [comment]
@9292922 小伙子，issue 上面也有说明，乱填 issue 会被强制关闭，这次我对你也不例外，你需要重新发起一个 issue，我再给你处理，一定要严格遵守流程，这个 issue 我就关闭了。
