### ISSUE TITLE
XXPermissions.isGranted()在锤子手机android 7.1.1 上无效

### ISSUE THREAD

**Issue by liufeng382641424** [getActivity/XXPermissions#184]
#### 问题描述

* 框架版本【必填】：16.6

* 问题描述【必填】：XXPermissions.isGranted()在锤子手机android 7.1.1 上无效，无论是否有权限都返回为true

* 复现步骤【必填】：每次授权必现

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：锤子手机 smartisan OD105 (295ddbca)

* 出现问题的安卓版本【必填】：Android 7.1.1 API 25

* 问题信息的来源渠道【必填】：自己遇到的

#### 请回答

* 是部分机型还是所有机型都会出现【必答】：部分 锤子手机才会出现

* 框架最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档但还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 Demo 来复现该问题【必答】：Demo未发现是否有isGranted()该api的按钮

* 使用原生的权限 API 是否会出现该问题【必答】：未使用原生的来处理

#### 其他
无

**Comment by getActivity** [comment]
小伙子，请回答以下两个问题：

* 是否可以通过 Demo 来复现该问题【必答】：Demo未发现是否有isGranted()该api的按钮：请下载 Demo，然后调用此方法进行复现，然后来回答此问题。

* 使用原生的权限 API 是否会出现该问题【必答】：未使用原生的来处理：请使用原生的权限 API 进行请求，然后来回答此问题。

**Comment by liufeng382641424** [comment]
是否可以通过 Demo 来复现该问题【必答】：下载了demo和也看了源码中调用，未发现使用XXPermissions.isGranted()该api的地方。。。

使用原生的权限 API 是否会出现该问题【必答】：用原生方法测试也一样，也是检测该权限为true（实际权限未开启）

如果系统方法这边也不行，是否这个问题就无法修复呢？

**Comment by getActivity** [comment]
@liufeng382641424 是的，这个厂商自己搞了一套权限机制，这个我没有办法做适配。
