### ISSUE TITLE
最新版XXPermission在安卓6以上、安卓11以下无法正常申请文件读写权限

### ISSUE THREAD

**Issue by 9292922** [getActivity/XXPermissions#185]
#### 问题描述

* 框架版本【必填】：16.6

* 问题描述【必填】：最新版XXPermission16.6在安卓6以上、安卓11以下无法正常申请文件读写权限，但老版本13.2却正常

* 复现步骤【必填】：使用最新版本的XXPermission框架在Android6~Android10系统上申请文件读写权限，无响应

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：谷歌模拟器

* 出现问题的安卓版本【必填】：API26

* 问题信息的来源渠道【必填】：我自己遇到，用户也遇到

#### 请回答

* 是部分机型还是所有机型都会出现【必答】：部分

* 框架最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档但还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 Demo 来复现该问题【必答】：否

* 使用原生的权限 API 是否会出现该问题【必答】：否

#### 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）

* 提供截图或视频（根据需要提供，此项不强制）

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by getActivity** [comment]
小伙子，请回答以下问题

1. 请提供不能进行权限请求的权限名称
2. 请提供你们项目的 `targetSdkVersion` 版本
3. 项目是否禁用了 XXPermissions 权限检测机制
4. 请 debug 框架源码，看看 PermissionFragment 是否正常调用了 requestPermissions

**Comment by 9292922** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        1.WRITE_EXTERNAL_STORAGE、READ_EXTERNAL_STORAGE
    
        2.target 333.无4.抱歉，这个不太懂
    
    
    

    

    

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年02月26日 09:51
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [getActivity/XXPermissions] 最新版XXPermission在安卓6以上、安卓11以下无法正常申请文件读写权限 (Issue #185)
        
      
    
  
  

小伙子，请回答以下问题



请提供不能进行权限请求的权限名称

请提供你们项目的 targetSdkVersion 版本

项目是否禁用了 XXPermissions 权限检测机制

请 debug 框架源码，看看 PermissionFragment 是否正常调用了 requestPermissions

**Comment by getActivity** [comment]
小伙子，你的 `targetSdk = 33` 是不能申请 `WRITE_EXTERNAL_STORAGE` 和 `READ_EXTERNAL_STORAGE`，框架会直接给你抛一个 `When targetSdkVersion >= 33 should use android.permission.READ_MEDIA_IMAGES, android.permission.READ_MEDIA_VIDEO, android.permission.READ_MEDIA_AUDIO instead of android.permission.READ_EXTERNAL_STORAGE, android.permission.WRITE_EXTERNAL_STORAGE` 异常，这种情况你应该申请 `READ_MEDIA_IMAGES`、`READ_MEDIA_VIDEO`、`READ_MEDIA_AUDIO` 权限，而不是申请 `WRITE_EXTERNAL_STORAGE` 和 `READ_EXTERNAL_STORAGE` 权限

**Comment by getActivity** [comment]
小伙子，框架给你抛异常，你连看都不看的么？

**Comment by 9292922** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    但是这个是在Android11以下的时候申请的不应该是WRITE_EXTERNAL_STORAGE和 READ_EXTERNAL_STORAGE吗？在安卓11以下的系统申请那些权限有啥用？
    
        
            
        
    
    
    
    

    

    

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年02月26日 10:27
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [getActivity/XXPermissions] 最新版XXPermission在安卓6以上、安卓11以下无法正常申请文件读写权限 (Issue #185)
        
      
    
  
  

小伙子，你的 targetSdk = 33 是不能申请 WRITE_EXTERNAL_STORAGE 和 READ_EXTERNAL_STORAGE，框架会直接给你抛一个 When targetSdkVersion >= 33 should use android.permission.READ_MEDIA_IMAGES, android.permission.READ_MEDIA_VIDEO, android.permission.READ_MEDIA_AUDIO instead of android.permission.READ_EXTERNAL_STORAGE, android.permission.WRITE_EXTERNAL_STORAGE 异常，这种情况你应该申请 READ_MEDIA_IMAGES、READ_MEDIA_VIDEO、READ_MEDIA_AUDIO 权限，而不是申请 WRITE_EXTERNAL_STORAGE 和 READ_EXTERNAL_STORAGE 权限

**Comment by 9292922** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    我试试！谢谢解答
    
        
            
        
    
    
    
    

    

    

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年02月26日 10:28
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [getActivity/XXPermissions] 最新版XXPermission在安卓6以上、安卓11以下无法正常申请文件读写权限 (Issue #185)
        
      
    
  
  

小伙子，框架给你抛异常，你连看都不看的么？

**Comment by getActivity** [comment]
小伙子，没有问题的话 issue 我先关闭了，后续有问题可以直接在这个 issue 下面评论，还有另外一点需要注意的是，你如果后面有更新到 16.8 及以上版本的时候，申请 `READ_MEDIA_IMAGES`、`READ_MEDIA_VIDEO`、`READ_MEDIA_AUDIO`，在 Android 12 及以下版本框架会变成 `READ_EXTERNAL_STORAGE` 来代替申请，而不是用 `READ_EXTERNAL_STORAGE` 和 `WRITE_EXTERNAL_STORAGE` 这两个权限来代替申请了，如果你需要写存储的权限，还需要加上 `WRITE_EXTERNAL_STORAGE` 来申请。
