### ISSUE TITLE
iqoo(OriginOS 3)请求多个权限时会出现无法正常弹出权限询问弹窗

### ISSUE THREAD

**Issue by duguqqjian12** [getActivity/XXPermissions#186]
#### 问题描述

* 框架版本【必填】：XXPermissions:16.6

* 问题描述【必填】：同时申请2个或以上的权限时，如果权限A(比如相机)可选择为“每次使用时询问”，且权限B选择为"允许"或者"始终允许"的话，则不会弹出A权限询问弹窗并显示"获取授权失败"(目前这种情况仅出现在某些搭配中，但只要搭配对应得上，那么在demo中必定触发)。

* 复现步骤【必填】：
目前发现如下权限搭配均会无法拉起前者权限询问弹窗：
●相机(CAMERA)
①相机(每次询问)+麦克风（RECORD_AUDIO。允许） = 不弹出相机权限询问弹窗
②相机(每次询问)+身体传感器(BODY_SENSORS。允许)  =  不弹出相机权限询问弹窗
③相机(每次询问)+精确、粗略位置（ACCESS_FINE_LOCATION和ACCESS_COARSE_LOCATION。允许，权限详情页选精确出BUG，选粗略能正常触发弹窗）=  不弹出相机权限询问弹窗

●麦克风(RECORD_AUDIO)
①麦克风(每次询问)+身体传感器(BODY_SENSORS。允许) = 不弹出相麦克风限询问弹窗
②麦克风(每次询问)+精确、粗略位置(ACCESS_FINE_LOCATION和ACCESS_COARSE_LOCATION。允许，权限详情页选精确时出BUG，选粗略时能正常触发弹窗)=  不弹出相麦克风限询问弹窗

●活动认可(ACTIVITY_RECOGNITION)
①活动认可(每次询问)+身体传感器=bug（情况同麦克风①）
②活动认可(每次询问)+精确、粗略位置 = bug （情况同麦克风②）

●日历(READ_CALENDAR和WRITE_CALENDAR)
①日历(每次询问)+身体传感器=bug （情况同麦克风①）
②日历(每次询问)+精确、粗略位置 = bug （情况同麦克风②）

●身体传感器(BODY_SENSORS)
①身体传感器(每次询问)+精确、粗略位置 = bug （情况同麦克风②)

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：IQOO8 PRO

* 出现问题的安卓版本【必填】：Android13(OriginOS 3)

* 问题信息的来源渠道【必填】：自己遇到

#### 请回答

* 是部分机型还是所有机型都会出现【必答】：目前发现是IQOO8 PRO出现问题。另一测试机为红米K40S MIUI13.0.7 ，该机子测试正常

* 框架最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档但还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 Demo 来复现该问题【必答】：是

* 使用原生的权限 API 是否会出现该问题【必答】：
是，直接使用requestPermissions时，当情况为相机(每次询问)+麦克风（允许）的条件下。如果是requestPermissions(new String[]{Manifest.permission.CAMERA, android.permission.RECORD_AUDIO}, 200);这样2个权限塞在同一个数组写会触发同样的BUG,无法弹出请求相机权限的询问。但是如果分开2次写就没问题

**Comment by duguqqjian12** [comment]
> 小伙子，如果我没有理解错的话，你这个问题是属于厂商某个版本的 bug 吧？

目前发现好像是这样，主要我这边的小伙伴的vivo系机子都升OriginOS 3了，没法测试老版本OriginOS，所以也不太清楚OriginOS旧版Android12版本是否存在这个问题。目前也没别的问题，有劳轮子哥把issue关了吧

**Comment by getActivity** [comment]
小伙子，我手头有一台 iQOO 9 Pro（Android 12、OriginOS 2 ）手机，测试过了，没有出现你说的这个问题，应该是厂商新版本改出来的 Bug，你可以反馈给 vivo 厂商那边去修复。

**Comment by duguqqjian12** [comment]
> 小伙子，我手头有一台 iQOO 9 Pro（Android 12、OriginOS 2 ）手机，测试过了，没有出现你说的这个问题，应该是厂商新版本改出来的 Bug，你可以反馈给 vivo 厂商那边去修复。

好的，谢谢轮子哥帮忙测试

**Comment by duguqqjian12** [comment]
自己备注一下：3月1号给蓝厂反馈，3号晚收到系统更新推送，issue中的系统权限BUG已修复

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/222877911-85d03ae1-3759-4752-a920-9af8255a9693.jpg)
