### ISSUE TITLE
Android 11 框架自动添加的READ_EXTERNAL_STORAGE其实是无效的，而当用户请求MANAGE_EXTERNAL_STORAGE又不允许

### ISSUE THREAD

**Issue by censhengde** [getActivity/XXPermissions#188]
#### 问题描述 ：Android 11 框架自动添加的READ_EXTERNAL_STORAGE其实是无效的，而当用户请求MANAGE_EXTERNAL_STORAGE又不允许

* 框架版本【必填】：16.8

* 问题描述【必填】：Android 11 框架自动添加的READ_EXTERNAL_STORAGE其实是无效的，而当用户请求MANAGE_EXTERNAL_STORAGE又不允许;Android 13 READ_MEDIA_AUDIO、READ_MEDIA_IMAGES、READ_MEDIA_VIDEO代替不了MANAGE_EXTERNAL_STORAGE。

* 复现步骤【必填】：随便试都行。

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：oppo reno 7 pro 5G

* 出现问题的安卓版本【必填】：Android 11

* 问题信息的来源渠道【必填】：自己遇到的

#### 请回答

* 是部分机型还是所有机型都会出现【必答】：全部

* 框架最新的版本是否存在这个问题【必答】：是
* 是否已经查阅框架文档但还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：是

* 是否可以通过 Demo 来复现该问题【必答】：是/否（排查一下是不是自己的项目代码写得有问题导致的）

* 使用原生的权限 API 是否会出现该问题【必答】：是/否（排查一下是不是框架的代码存在问题导致的）

#### 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）

* 提供截图或视频（根据需要提供，此项不强制）

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 没有严格按照 issue 模板填写问题

请重新提一个 issue 并纠正以上问题
