### ISSUE TITLE
华为手机申请勿扰权限失败

### ISSUE THREAD

**Issue by qq549631030** [getActivity/XXPermissions#190]
#### 问题描述

* 框架版本【必填】：16.8

* 问题描述【必填】：华为手机申请勿扰权限失败

* 复现步骤【必填】：直接用16.8的Demo apk点申请勿扰权限

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：华为P50E，Mate 30 5G

* 出现问题的安卓版本【必填】：Android12、HarmonyOS 3.0.0

* 问题信息的来源渠道【必填】：想申请勿扰权限时发现

#### 请回答

* 是部分机型还是所有机型都会出现【必答】：目前权在两台华为HarmonyOS 3.0.0手机上发现，其它手机OK。

* 框架最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档但还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 Demo 来复现该问题【必答】：是

* 使用原生的权限 API 是否会出现该问题【必答】：否    用”android.settings.NOTIFICATION_POLICY_ACCESS_SETTINGS“这个action是可以的。框架有判断Android 10以上走"android.settings.NOTIFICATION_POLICY_ACCESS_DETAIL_SETTINGS"，这个是隐藏API。华为手机一调这个action，不会弹出权限申请框，直接返回失败。

#### 其他

* 提供报错堆栈 无

* 提供截图或视频 无

* 提供解决方案  是否能够做到这种一调就返回失败的情况fallback回”android.settings.NOTIFICATION_POLICY_ACCESS_SETTINGS“这个action呢？

**Comment by getActivity** [comment]
[XXPermissions-16.9.aar.zip](https://github.com/getActivity/XXPermissions/files/10895276/XXPermissions-16.9.aar.zip)

**Comment by getActivity** [comment]
小伙子，这个问题修复了，你用上面这个包再试试看有没有问题

**Comment by getActivity** [comment]
小伙子，这个包你先用着，有问题及时反馈，等后面发布远程依赖了你再换回来

**Comment by qq549631030** [comment]
好的

**Comment by hyl87** [comment]
我这也有个问题啊
 When targetSdkVersion >= 33 should use android.permission.READ_MEDIA_IMAGES, android.permission.READ_MEDIA_VIDEO, android.permission.READ_MEDIA_AUDIO instead of android.permission.READ_EXTERNAL_STORAGE

系统版本时Android9，这只判断了targetSdkVersion？不判断当前系统版本的啊？

**Comment by getActivity** [comment]
@hyl87 小伙子，这个问题你自己用低版本的手机试一下不就知道了？

**Comment by getActivity** [comment]
@qq549631030 小伙子，远程依赖已经更新，后续留意更新下即可。

**Comment by qq549631030** [comment]
@getActivity 发现荣耀的系统也有这个问题：
