### ISSUE TITLE
Android9和Android10的设备申请存储权限后不能写文件，文件重命名失败

### ISSUE THREAD

**Issue by AndyRenJie** [getActivity/XXPermissions#193]
#### 问题描述

* 框架版本【必填】：16.8

* 问题描述【必填】：OPPO（Android 9）和华为Pad（Android 10）的设备申请存储权限后，只能读不能写，File的canWrite()方法返回false，文件重命名失败

* 复现步骤【必填】：申请存储权限后，校验文件是否可写，重命名一个文件失败

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：OPPO（Android 9）和华为Pad（Android 10）

* 出现问题的安卓版本【必填】：请填写出现问题的 Android 9 和 Android 10

* 问题信息的来源渠道【必填】：重命名文件时发现

#### 请回答

* 是部分机型还是所有机型都会出现【必答】：部分（只有Android 11以下的设备出现）

* 框架最新的版本是否存在这个问题【必答】：16.8会出现，16.6是好的

* 是否已经查阅框架文档但还未能解决的【必答】：否

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 Demo 来复现该问题【必答】：否，Demo没有重命名文件的功能

* 使用原生的权限 API 是否会出现该问题【必答】：否，原生权限我们申请了写文件权限

#### 其他

* 提供截图或视频

这个是16.6的截图
![image](https://user-images.githubusercontent.com/34081177/226235613-dc3cb908-39ee-434b-8c29-b2c38507a4b7.png)

这个是16.8的截图
![image](https://user-images.githubusercontent.com/34081177/226235770-95adbf75-af2c-40b1-8ea6-6c927af55373.png)

**Comment by huaxuanHan** [comment]
Android11请求了存储权限还是补能读取照片

**Comment by getActivity** [comment]
https://github.com/getActivity/XXPermissions/issues/187

**Comment by getActivity** [comment]
小伙子，`READ_MEDIA_IMAGES`、`READ_MEDIA_VIDEO`、`READ_MEDIA_AUDIO` 对应的低版本的权限就是 `READ_EXTERNAL_STORAGE`，而不是 `READ_EXTERNAL_STORAGE` 和 `WRITE_EXTERNAL_STORAGE`，所以你在申请 `READ_MEDIA_IMAGES`、`READ_MEDIA_VIDEO`
、`READ_MEDIA_AUDIO` 的时候，需要考虑到带上 `WRITE_EXTERNAL_STORAGE` 一起申请。

**Comment by AndyRenJie** [comment]
好的，看到那个问题了，那就是现在需要再带上WRITE_EXTERNAL_STORAGE权限一起申请了，因为之前16.6的版本都是带着的，这次更新了之后测试发现在低版本的设备就出现问题了，这个在后期版本还会优化吗

**Comment by huaxuanHan** [comment]
Android11设备申请了MANAGE_EXTERNAL_STORAGE权限，在应用的权限里面也获取到允许管理所有文件的权限了，但是访问不了相册，我如果不获取MANAGE_EXTERNAL_STORAGE这个权限，自己去应用→权限里面选择允许管理所有文件的权限就能访问到相册，请问一下这是怎么回事呢

**Comment by getActivity** [comment]
> Android11设备申请了MANAGE_EXTERNAL_STORAGE权限，在应用的权限里面也获取到允许管理所有文件的权限了，但是访问不了相册，我如果不获取MANAGE_EXTERNAL_STORAGE这个权限，自己去应用→权限里面选择允许管理所有文件的权限就能访问到相册，请问一下这是怎么回事呢

小伙子，这个是另外的问题，劳烦请另提一个 bug issue

**Comment by Wenlong-Guo** [comment]
如果不是BUG是建议呢 怎么提交?

**Comment by getActivity** [comment]
> 如果不是BUG是建议呢 怎么提交?

建议也有专门的 issue 模板
