### ISSUE TITLE
对在横竖屏切换后fragment回调丢失问题的建议

### ISSUE THREAD

**Issue by Wenlong-Guo** [getActivity/XXPermissions#194]
建议收集
issue 是否有人曾提过类似的问题？
否

框架文档是否有提及到此问题？
有

你觉得框架有什么不足之处？

在横竖屏切换后fragment回调丢失问题中
我认为 可以用 ViewModelLazy 让activity和fragment共享一个viewmodel 
用viewmodel保存回调
亲测有效 可以保证fragment的回调不被回收
但是源码中用的不是fragmentActivity 
改造成本有点高哈

**Comment by getActivity** [comment]
小伙子，用 ViewModel 确实可以保存外层的回调对象，但是你有没有想过一个问题？回调对象一般都是 Activity 或者 Fragment 中直接 new 出来的匿名内部类对象，我们都知道内部类会持有外部类对象，而外部类对象是谁呢？显然易见就是 Activity 对象或者 Fragment 对象了，但是在屏幕旋转过程中，Activity 和 Fragment 对象本质上已经销毁了，会导致以下问题：

1. 在外部类对象销毁的情况下，内部类对象还存活着，并且还持有着之前的外部类对象，这样会导致外部类对象无法被 GC 正常回收，很可能会出现内存泄漏的情况

2. 在回调方法一般会去调用外部类的方法或者对象，但是外部类对象已经销毁了，假设在权限失败的回调方法中，弹出一个对话框，这个对话框的上下文传入的是已经销毁的 Activity 对象，这时很可能会触发程序 Crash

**Comment by Wenlong-Guo** [comment]
测试了一下 不会发生第二条 会发生第一条

但是不知道为什么 viewmodel持有的是旧的activity的东西 
但是还能使用旧的上下文完成弹AlertDialog以及后续操作(实在费解)

仔细考虑了一下这种情况确实很难恢复重建前的回调内容
锁定屏幕方向目前确实是最优解了
谢谢作者的解答
