### ISSUE TITLE
Permission.ACCESS_BACKGROUND_LOCATION 权限

### ISSUE THREAD

**Issue by libeimarch** [getActivity/XXPermissions#195]
问题描述

* 问题描述【必填】： 如何同步获取Permission.ACCESS_BACKGROUND_LOCATION 权限
* 直接请求会报一个错误 java.lang.IllegalArgumentException: Because it includes background location permissions, do not apply for permissions unrelated to location

#### 请回答

* issue 是否有人曾提过类似的问题？【必答】否

* 框架文档是否有提及到此问题？【必答】：否

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 没有严格按照 issue 模板填写问题（乱填 issue 选项）

请重新提一个 issue 并纠正以上问题
