### ISSUE TITLE
[Bug]：在鸿蒙手机获取存储权限的问题

### ISSUE THREAD

**Issue by sxb0602** [getActivity/XXPermissions#197]
### 框架版本【必填】

16.6

### 问题描述【必填】

在鸿蒙手机获取存储权限WRITE_EXTERNAL_STORAGE和READ_EXTERNAL_STORAGE，获取到的是文件和媒体，它还有一个选项“所有文件”，而用原生请求权限可以获取到所有文件这个选项。

### 复现步骤【必填】

鸿蒙手机，请求存储权限，请求到的是文件和媒体

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

32

### 出现问题的手机信息【必填】

鸿蒙系统 

### 出现问题的安卓版本【必填】

鸿蒙系统，最新版本吧，没注意

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

部分，手上只有一部华为手机

### 框架最新的版本是否存在这个问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

否

### issue 是否有人曾提过类似的问题【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

是

### 使用原生的权限 API 是否会出现该问题【必答】

否

**Comment by getActivity** [comment]
小伙子， 你用的是鸿蒙 2.0 还是 3.0 的？

**Comment by hike2008** [comment]
鸿蒙3.0 好像 蓝牙相关权限没法获取到

**Comment by getActivity** [comment]
@hike2008 小伙子，你这个是另外的问题，请另外提一个 issue 给到我

**Comment by hike2008** [comment]
> @hike2008 小伙子，你这个是另外的问题，请另外提一个 issue 给到我

经试验，在鸿蒙3.0把蓝牙相关权限的判断直接去掉，就行了，

如果不是故意这么设计，必然是系统层面的Bug，默认直接给授权了……

**Comment by getActivity** [comment]
超过一个星期没有响应，自动关闭此 issue。
