### ISSUE TITLE
[建议]：shortcut权限，国产手机貌似都做成动态权限了

### ISSUE THREAD

**Issue by CookieZJ** [getActivity/XXPermissions#198]
### 你觉得框架有什么不足之处？【必答】

目前该框架没有shortcut这个动态权限

### issue 是否有人曾提过类似的建议？【必答】

是

### 框架文档是否有提及到此问题？【必答】

是

**Comment by getActivity** [comment]
<img width="1518" alt="image" src="https://user-images.githubusercontent.com/28616817/231055801-53ce22f4-7cdf-4292-a03c-b9abd90f47d2.png">

小伙子，你确定？我用小米 12 Android 13 测试出来这个还是普通权限。

**Comment by getActivity** [comment]
超过一个星期没有响应，自动关闭此 issue。
