### ISSUE TITLE
[建议]：建议支持华为鸿蒙系统中的后台弹窗权限

### ISSUE THREAD

**Issue by aimeryxie** [getActivity/XXPermissions#199]
### 你觉得框架有什么不足之处？【必答】

华为鸿蒙系统中的后台弹窗权限怎么申请？这个权限在华为鸿蒙上如果允许的话就能在后台弹toast。

### issue 是否有人曾提过类似的建议？【必答】

否

### 框架文档是否有提及到此问题？【必答】

否

### 你觉得该怎么去完善会比较好？【非必答】

查了下都是鸿蒙系统中原生的开发方式，还没查到android上的实现，一些银行app比如建行 的确安装上这个权限就是打开的。我们自己的app安装上就是默认关闭的。

**Comment by getActivity** [comment]
超过一个星期没有响应，自动关闭此 issue。
