### ISSUE TITLE
[Bug]：三星、索尼等海外手机申请位置权限拒绝后，是否勾选了不再询问选项，永远返回true  callback.onDenied(deniedPermissions, doNotAskAgain);

### ISSUE THREAD

**Issue by ningwenqiang** [getActivity/XXPermissions#200]
### 框架版本【必填】

16.8-18.0都有问题，向下版本未知

### 问题描述【必填】

三星、索尼等海外手机申请权限拒绝后，是否勾选了不再询问选项，永远返回true  callback.onDenied(deniedPermissions, doNotAskAgain);  doNotAskAgain不管是否选择永久拒绝都是返回true

### 复现步骤【必填】

正常使用定位权限，申请定位，系统弹框选择拒绝

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

33

### 出现问题的手机信息【必填】

13652405186

### 出现问题的安卓版本【必填】

android 33

### 是部分机型还是所有机型都会出现【必答】

海外厂商手机，三星、索尼

### 框架最新的版本是否存在这个问题【必答】

是

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 是否有人曾提过类似的问题【必答】

否

### 是否可以通过 Demo 来复现该问题【必答】

是

### 使用原生的权限 API 是否会出现该问题【必答】

是

### 提供截图或视频

![1681280506498](https://user-images.githubusercontent.com/17328374/231368770-9a1df9c9-441d-48f0-9f0a-a2f3b580d246.png)

### 提供解决方案

是否可以优化，查看系统层api确实是返回true，具体可跟踪系统源码，也可查看下面链接
https://stackoverflow.com/questions/56412401/working-of-shouldshowrequestpermissionrationale-method

**Comment by getActivity** [comment]
https://github.com/getActivity/XXPermissions/issues/154

**Comment by getActivity** [comment]
小伙子，这个问题无解

**Comment by ningwenqiang** [comment]
无解
