### ISSUE TITLE
[疑惑]：依赖下载的问题

### ISSUE THREAD

**Issue by protectedMan** [getActivity/XXPermissions#201]
### 问题描述【必填】

```
Could not resolve all artifacts for configuration ':lezhu:lezhuDevelopmentDebugRuntimeClasspath'.
> Could not find com.github.getActivity:XXPermissions:15.0.
  Searched in the following locations:
https://www.jitpack.io/com/github/getActivity/XXPermissions/15.0/XXPermissions-15.0.pom

```
jetpack上依赖15.0版本的pom访问直接not found
试了下13.6、 16.0等版本的都可以正常下载

### issue 是否有人曾提过类似的问题？【必答】

未选择

### 框架文档是否有提及到此问题？【必答】

否

**Comment by getActivity** [comment]
小伙子， 我试了一下，确实存在这个问题，但是我无法在 jitpack 重新构建它，目前提供两个解决方案：

1. 升级到框架最新版本
2. 下载 [15.0](https://github.com/getActivity/XXPermissions/releases/tag/15.0) 的 aar 包进行离线依赖

**Comment by protectedMan** [comment]
是的,我正在用2方案

**Comment by anaer** [comment]
13.6貌似也下载不了了, 直接更新到最新了

**Comment by getActivity** [comment]
<img width="921" alt="image" src="https://github.com/user-attachments/assets/b96c620a-7c1e-439e-8c16-c3c4b7fe18c7">

**Comment by getActivity** [comment]
@anaer 我并没有在 jitpack 中删除它，这个问题应该是 jitpack 的问题，我这边已经重新构建了，你等会重新试一下

**Comment by anaer** [comment]
ok，试了下 已经可以下载了
