### ISSUE TITLE
[建议]：

### ISSUE THREAD

**Issue by clailan** [getActivity/XXPermissions#203]
### 你觉得框架有什么不足之处？【必答】

是否可以提供设置多语言方法，而不是仅根据系统改变

### issue 是否有人曾提过类似的建议？【必答】

否

### 框架文档是否有提及到此问题？【必答】

否

### 你觉得该怎么去完善会比较好？【非必答】

是否可以提供设置多语言方法，而不是仅根据系统改变

**Comment by getActivity** [comment]
小伙子，权限申请页面跟随系统语种是非常正确的事情，因为那个权限申请页面本身不属于框架的东西，另外关于这块谷歌没有提供任何接口开放对外修改，你如果真想实现这一需求，只能去给 Google 提建议了。

**Comment by clailan** [comment]
明白了，谢谢
