### ISSUE TITLE
[疑惑]：

### ISSUE THREAD

**Issue by ChloeDimen** [getActivity/XXPermissions#204]
### 问题描述【必填】

我在荣耀v30手机，鸿蒙系统3.0的系统，在APP开启就直接申请Permission.MANAGE_EXTERNAL_STORAGE权限，会直接跳转到“”所有文件访问"的设置界面。 

### issue 是否有人曾提过类似的问题？【必答】

否

### 框架文档是否有提及到此问题？【必答】

否

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 这个问题属于 bug，不能提疑问 issue 单，请提 bug issue 单

请重新提一个 issue 并纠正以上问题
