### ISSUE TITLE
[Bug]：鸿蒙3.0手机获取存储权限的问题

### ISSUE THREAD

**Issue by Jonny798** [getActivity/XXPermissions#205]
### 框架版本【必填】

18.0

### 问题描述【必填】

当获取WRITE_EXTERNAL_STORAGE与READ_EXTERNAL_STORAGE两条权限且框架判断权限已获取的情况下，无法读取外部存储目录下的文件列表

### 复现步骤【必填】

请求存储权限=>请求到的是文件和媒体

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

32

### 出现问题的手机信息【必填】

Nova6(5G)

### 出现问题的安卓版本【必填】

鸿蒙3.0

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

鸿蒙3.0都是

### 框架最新的版本是否存在这个问题【必答】

是

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 是否有人曾提过类似的问题【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

是

### 使用原生的权限 API 是否会出现该问题【必答】

否

**Comment by getActivity** [comment]
<img width="412" alt="image" src="https://user-images.githubusercontent.com/28616817/233245826-4ddb8c69-c540-4e5a-800f-aacd25bf9fd2.png">

小伙子，你说原生权限 API 不能复现该问题，意思就是原生的权限 API 申请 `WRITE_EXTERNAL_STORAGE` 和 `READ_EXTERNAL_STORAGE` 是可以正常读取到外部存储下的文件列表对吧？如果的是话，请你提供一个这样的 Demo 给到我。

**Comment by getActivity** [comment]
超过两个星期没有响应，自动关闭此 issue。
