### ISSUE TITLE
[Bug]：华为设备鸿蒙系统3.0（Android12），获取蓝牙权限时候，闪退

### ISSUE THREAD

**Issue by Jsonjia** [getActivity/XXPermissions#207]
### 框架版本【必填】

18.0

### 问题描述【必填】

华为设备鸿蒙系统3.0（Android12），获取蓝牙权限时候，闪退，提示：java.lang.IllegalArgumentException: The android.permission.BLUETOOTH is not a dangerous permission or special permission, please do not request dynamically

### 复现步骤【必填】

 private fun permissonList(): MutableList<String> {
        val mPermissionList: MutableList<String> = ArrayList()
        if (Build.VERSION.SDK_INT >= 31) {
            mPermissionList.add(Manifest.permission.BLUETOOTH_SCAN)
            mPermissionList.add(Manifest.permission.BLUETOOTH_ADVERTISE)
            mPermissionList.add(Manifest.permission.BLUETOOTH_CONNECT)
            mPermissionList.add(Manifest.permission.ACCESS_FINE_LOCATION)
            mPermissionList.add(Manifest.permission.BLUETOOTH)
        } else {
            mPermissionList.add(Manifest.permission.ACCESS_FINE_LOCATION)
            mPermissionList.add(Manifest.permission.ACCESS_COARSE_LOCATION)
            mPermissionList.add(Manifest.permission.BLUETOOTH)
        }
        return mPermissionList
    }

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

29

### 出现问题的手机信息【必填】

华为鸿蒙系统3.0   

### 出现问题的安卓版本【必填】

Android12

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

华为鸿蒙3.0必现

### 框架最新的版本是否存在这个问题【必答】

是

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 是否有人曾提过类似的问题【必答】

否

### 是否可以通过 Demo 来复现该问题【必答】

是

### 使用原生的权限 API 是否会出现该问题【必答】

是

**Comment by getActivity** [comment]
小伙子，报错的意思不是说得很明白了吗？难道还需要我翻译给你看？

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/233563459-7542b34a-4eff-40f1-bf6b-ada8725c2b55.jpg)

**Comment by Jsonjia** [comment]
Build.VERSION.SDK_INT >= 31 没有Manifest.permission.BLUETOOTH 这个权限么？
看了您的代码你是通过反射获取所有（目前是52条）的权限，然后当我传入的权限（Manifest.permission.BLUETOOTH）与你52条权限不匹配时候，你才抛这个异常。请问是sdk>=31，是没有Manifest.permission.BLUETOOTH权限么？

**Comment by getActivity** [comment]
<img width="938" alt="image" src="https://user-images.githubusercontent.com/28616817/234744516-07df29c6-d405-4a57-9fb7-1e6657ba2b3a.png">

**Comment by getActivity** [comment]
https://developer.android.google.cn/reference/android/Manifest.permission#BLUETOOTH

**Comment by getActivity** [comment]
小伙子，你先看一下官方文档介绍，再回来反问我这个问题。
