### ISSUE TITLE
[Bug]：android 13 无法跳转通知设置页面

### ISSUE THREAD

**Issue by Nobler** [getActivity/XXPermissions#208]
### 框架版本【必填】

18.0

### 问题描述【必填】

XXPermissions.startPermissionActivity(activity, Permission.POST_NOTIFICATIONS) 无法跳转到通知设置页面，只能跳转到应用设置页面

### 复现步骤【必填】

在android 13请求Permission.POST_NOTIFICATIONS权限被拒绝后，主动调用XXPermissions.startPermissionActivity(activity, Permission.POST_NOTIFICATIONS)跳转设置页面，只能跳转到应用设置，不能跳转到通知设置。android 13以下没有问题。

PermissionDelegateImplV33可能要拦截一下POST_NOTIFICATIONS权限，不然最后走到PermissionDelegateImplV19，这两个跳转都会失效：
https://github.com/getActivity/XXPermissions/blob/4c929a7859be44886e300845ddc8e501a647d8e8/library/src/main/java/com/hjq/permissions/PermissionDelegateImplV19.java#L77-L87

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

33

### 出现问题的手机信息【必填】

三星 s22

### 出现问题的安卓版本【必填】

android 13

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

android 13

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

否

**Comment by getActivity** [comment]
[XXPermissions-18.2.aar.zip](https://github.com/getActivity/XXPermissions/files/11469772/XXPermissions-18.2.aar.zip)

**Comment by getActivity** [comment]
小伙子，问题修复了，你用这个包再试试看。

**Comment by Nobler** [comment]
@getActivity 试过可以了

**Comment by Nobler** [comment]
发布周期是怎样的，新版本大概什么时候可用呢

**Comment by getActivity** [comment]
@Nobler 小伙子，这个问题不严重也不紧急，所以没有那么快发布，最快也是半个月后发布，具体时间还要根据实际情况而定，如果后续还有人反馈问题，但是问题很小，可能还会再延一段时间再发布，所以你先依赖这个本地的 aar，后续过程有出现其他的问题，请和我保持联系，这个 issue 我会保留到框架发布新版本后再关闭。

**Comment by Nobler** [comment]
OK。不过我不会本地依赖，接收不了这种方式，跳转逻辑我单独来写吧。

**Comment by getActivity** [comment]
@Nobler 小伙子，问题已经修复了，你可以更新一下远程依赖。
