### ISSUE TITLE
[疑惑]：部分机型检测检测返回结果不准

### ISSUE THREAD

**Issue by GuardYang** [getActivity/XXPermissions#209]
### 问题描述【必填】

部分机型用户拒绝定位权限，去设置开启了定位权限，检测权限还是拒绝，请问有方案解决吗
小米9、华为手机（畅享10plus）

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by getActivity** [comment]
@GuardYang 小伙子，你用原生的权限 API 去请求会有这种情况吗？

**Comment by GuardYang** [comment]
相信大佬即使系统有bug，也有方案修复，或者有其他解决方案

**Comment by getActivity** [comment]
@GuardYang 小伙子，我没有你想那么厉害，解铃还须系铃人，厂商搞出来的问题还是得他们自己解决。

**Comment by getActivity** [comment]
如果是我写的代码有问题，我会处理，如果是厂商的代码写得有问题，我想处理也处理不了，具体原因如下第一个我手头没有这样的设备，第二个我没有任何适配资料，第三个手机厂商的源码不开源，我无法看到内部实现。
