### ISSUE TITLE
提 issue 需知

### ISSUE THREAD

**Issue by getActivity** [getActivity/XXPermissions#21]
Github沟通效率实在是很低下，大家伙有问题或者Bug直接到Q群78797078私信给我反馈就OK，我会尽快答复你的问题

**Comment by CDCK** [comment]
android9.0设备 request方法会报错

**Comment by getActivity** [comment]
@CDCK  报什么错

**Comment by CDCK** [comment]
无法申请 Manifest.permission.READ_CONTACTS 权限
`
Caused by: com.hjq.permissions.ManifestRegisterException: android.permission.READ_CONTACTS: Permissions are not registered in the manifest file
        at com.hjq.permissions.PermissionUtils.checkPermissions(PermissionUtils.java:235)
        at com.hjq.permissions.XXPermissions.request(XXPermissions.java:88)
        at com.pa.paperless.activity.MainActivity.useXXP(MainActivity.java:1326)
        at com.pa.paperless.activity.MainActivity.initPermissions(MainActivity.java:1286)
        at com.pa.paperless.activity.MainActivity.onCreate(MainActivity.java:1099)
        at android.app.Activity.performCreate(Activity.java:7327)
        at android.app.Activity.performCreate(Activity.java:7318)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
`
使用系统写法的话就OK，只出现在9.0设备上

**Comment by getActivity** [comment]
Permissions are not registered in the manifest file at ：权限未在清单文件中注册

**Comment by CDCK** [comment]
。。。 原来我注释掉了

**Comment by CDCK** [comment]
使用系统的写法的即使清单文件中没注册也不会报错。。。

**Comment by getActivity** [comment]
危险权限必须在清单文件中注册，这个是谷歌规定的，你要是不注册也可以，在6.0系统以下运行看看

**Comment by vigiles** [comment]
如果能和hipermissions似的加个提示窗就更完美了

**Comment by vigiles** [comment]
78797078这个没找到群，只有一个qq号，不确定是不是作者的，没加。
我在这里做了个简单封装https://github.com/vigiles/XXPermissions/blob/patch-1/library/src/main/java/com/vigiles/tool/XXPermissionTool.java ， https://github.com/vigiles/XXPermissions/blob/patch-1/README.md

**Comment by shada2008** [comment]
activity启动模式是singleTask，弹出权限弹窗退到后台再到前台，就提示权限已获取，实际未获取

**Comment by shada2008** [comment]
> activity启动模式是singleTask，弹出权限弹窗退到后台再到前台，就提示权限已获取，实际未获取

临时解决方法：在onNewIntent 方法里重新获取权限

**Comment by PeterWu520** [comment]
Android 10 api 29，申请
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
崩溃
提示权限未在清单文件中注册，但是已经在Manfest中添加了这两个权限

**Comment by getActivity** [comment]
经过测试没有发现这个问题，小伙子你检查一下 apk 包中的清单文件是否有包含这两个权限

**Comment by PeterWu520** [comment]
> 经过测试没有发现这个问题，小伙子你检查一下 apk 包中的清单文件是否有包含这两个权限

清单文件已经包含这两个权限，之前compileSdkVersion和targetSdkVersion用的是28，申请这两个权限没问题，升到29后，用的版本是最新版8.6，清单文件也添加了
<application
    android:requestLegacyExternalStorage="true">
申请就崩溃了，提示清单文件没有注册这两个权限
然后用系统的申请方法就没问题
手机是一加5，Android 10

**Comment by wanghao9660** [comment]
建议加一个强制授权的方法，如果不给授权的话，app退出。

**Comment by getActivity** [comment]
@wanghao9660 https://github.com/getActivity/XXPermissions/issues/39

**Comment by tengdag** [comment]
8.8版本gradle同步报错:
ERROR: Failed to resolve: xxpermissions
rebuild报错:
Could not find xxpermissions.jar (com.hjq:xxpermissions:8.8).

**Comment by getActivity** [comment]
把 jcenter 放到阿里云远程仓库的前面试一下

**Comment by cjecky** [comment]
获取定位权限，没有反应，Manifest.permission.ACCESS_FINE_LOCATION，小米8SE ，系统是10.0

**Comment by getActivity** [comment]
用 Demo 会出现这个问题吗？
换个手机测试会出现这个问题吗？

**Comment by LeSwp** [comment]
extends  Activity 的页面调不起来申请权限

**Comment by getActivity** [comment]
@LeSwp 当前 Activity 必须是 FragmentActivity 的子类才可以

**Comment by getActivity** [comment]
还有一点需要注意，有问题请另起一个 issue，否则极有可能被忽略

**Comment by ayuhani** [comment]
加群没人理，只好在这里问了。现在请求权限时报方法找不到，实在查不到原因，不知道有没有人遇到过
java.lang.NoSuchMethodError: No static method with(Landroid/content/Context;)Lcom/hjq/permissions/XXPermissions; in class Lcom/hjq/permissions/XXPermissions; or its super classes (declaration of 'com.hjq.permissions.XXPermissions' appears in /data/app/~~pmKIo-uRA3Tg4QnkyYzOpQ==/cn.com.cbhb.mbank.per-5sHSnjjVrSqQ6ntZJv9E5g==/base.apk!classes2.dex)

**Comment by getActivity** [comment]
@ayuhani 小伙子，你看看是不是集成了 [https://github.com/getActivity/Logcat](https://github.com/getActivity/Logcat) 这个库，如果是的话，升级一下这个库的版本即可。

**Comment by getActivity** [comment]
@ayuhani 小伙子，又或者你检查看看是不是没在 Gradle 配置加上对 Java JDK 8 的支持

```groovy
android {
    // 支持 JDK 1.8
    compileOptions {
        targetCompatibility JavaVersion.VERSION_1_8
        sourceCompatibility JavaVersion.VERSION_1_8
    }
}
```

**Comment by ppg408331701** [comment]
* 框架版本：11.5

* 问题描述：在百度移动统计发现几十例报错统计

* 复现步骤：本地目前还无法复现


* 手机信息：华为小米OV均有出现
```
java.lang.AbstractMethodError: abstract method "void com.hjq.permissions.OnPermissionCallback.onDenied(java.util.List, boolean)"
	at com.hjq.permissions.IPermissionInterceptor$-CC.$default$deniedPermissions(IPermissionInterceptor.java:34)
	at com.hjq.permissions.XXPermissions$1.deniedPermissions(Unknown Source:0)
	at com.hjq.permissions.PermissionFragment.onRequestPermissionsResult(PermissionFragment.java:387)
	at android.app.Activity.dispatchRequestPermissionsResultToFragment(Activity.java:8577)
	at android.app.Activity.dispatchActivityResult(Activity.java:8421)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5464)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5512)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:213)
	at android.app.ActivityThread.main(ActivityThread.java:8178)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
```

**Comment by getActivity** [comment]
@ppg408331701 小伙子，你看看是不是集成了 https://github.com/getActivity/Logcat 这个库，如果是的话，升级一下这个库的版本即可。

**Comment by ppg408331701** [comment]
没有继承，我的日志打印库用的是Blankj/AndroidUtilCode的。我现在也一头雾水，先升级到11.6再观察一下吧，AbstractMethodError这个错误网上说是引用版本不一致导致的，但是我这边版本都是一样的。就奇怪了

**Comment by getActivity** [comment]
* 小伙子，你可以到项目依赖库列表排查一下是否依赖了不同版本的 XXPermissions 框架

![](https://user-images.githubusercontent.com/28616817/125106306-13a25a00-e112-11eb-85ab-86782630b67f.png)

**Comment by ppg408331701** [comment]
检查过了，只引用了XXPermission  不知道是不是和compileOnly有关。我在base_lib用api引用了XXPermission  ，又在和base_lib平行的第三方库（在线视频、在线聊天）的两个库里面使用compileOnly引用XXPermission。
![image](https://user-images.githubusercontent.com/16531268/125225613-2c716200-e302-11eb-801e-8ba945008a13.png)
如图所示
目前我更新了11.6，先发布一个新版观察一下，。到时有结果再回
![image](https://user-images.githubusercontent.com/16531268/125225738-588ce300-e302-11eb-895a-a57b3ff15667.png)

另外，我之前一直使用的是10.8没出这个问题，更新到11.5之后才出现的。

**Comment by amosxb** [comment]
问下，我在按系统返回键退到home页面后，再重新进来，就报The Activity has been finishing, Please manually determine the status of the Activity 这个错误，不明白是啥原因导致的。

**Comment by getActivity** [comment]
@amosxb 小伙子，根据你提供的描述，我并不能复现该问题。

**Comment by getActivity** [comment]
@amosxb 你可以通过 QQ 群或者加我为好友的方式跟我反馈这个问题，我收到问题之后会进行处理。

**Comment by yunianshu** [comment]
用作者大大项目编译的apk【release版本】在小米10，小米11真机测试，点击  申请新版存储权限 直接崩溃了

**Comment by getActivity** [comment]
@yunianshu  小伙子，麻烦提供一下报错信息及堆栈信息

**Comment by yunianshu** [comment]
@getActivity 我是云真机测试的，没有真正的小米手机，下面是我截取到的一部分信息
11-23 23:42:34.397  3831  3848 I MediaProvider: Invalidating LocalCallingIdentity cache for package com.hjq.permissions.demo. Reason: op android:read_external_storage
11-23 23:42:34.398 25573 15666 D Wth2:ToolUtils: getCallingPackageName failed: Package com.miui.weather2 does not belong to 10082
11-23 23:42:34.398 25573 15666 D Wth2:ToolUtils: getCallingPackageName callingPackageName: com.miui.weather2
11-23 23:42:34.398 25573 15666 D Wth2:ToolUtils: packageName: com.miui.weather2 hasAccessProvider: true
11-23 23:42:34.399  2582  2582 D AppMiniWindowManager: topActivity updated in onTaskStackChanged
11-23 23:42:34.401 25573 15666 D Wth2:ToolUtils: getCallingPackageName failed: Package com.miui.weather2 does not belong to 10082
11-23 23:42:34.401 25573 15666 D Wth2:ToolUtils: getCallingPackageName callingPackageName: com.miui.weather2
11-23 23:42:34.401 25573 15666 D Wth2:ProviderAnalyzeUtil: weather do not need analyze!
11-23 23:42:34.401 25573 15666 D Wth2:WeatherProvider: WeatherProvider query match is:7
11-23 23:42:34.401  1615  1774 I PackageDexOptimizer: Running dexopt (dexoptNeeded=1) on: /data/app/~~bXcclnojcDY3Kk6GcvuqXQ==/com.hjq.permissions.demo-l-e678pcRzNJJOQwuGdAQA==/base.apk pkg=com.hjq.permissions.demo isa=arm64 dexoptFlags=boot_complete,profile_guided,public,enable_hidden_api_checks targetFilter=speed-profile oatDir=/data/app/~~bXcclnojcDY3Kk6GcvuqXQ==/com.hjq.permissions.demo-l-e678pcRzNJJOQwuGdAQA==/oat classLoaderContext=PCL[]{}
11-23 23:42:34.401  1325 12559 V installd: DexInv: --- BEGIN '/data/app/~~bXcclnojcDY3Kk6GcvuqXQ==/com.hjq.permissions.demo-l-e678pcRzNJJOQwuGdAQA==/base.apk' ---
11-23 23:42:34.402  3831  3848 I MediaProvider: Invalidating LocalCallingIdentity cache for package com.hjq.permissions.demo. Reason: op android:read_external_storage
11-23 23:42:34.402 25573 15666 D Wth2:ToolUtils: getCallingPackageName failed: Package com.miui.weather2 does not belong to 10082
11-23 23:42:34.402 25573 15666 D Wth2:ToolUtils: getCallingPackageName callingPackageName: com.miui.weather2
11-23 23:42:34.403  3831  3848 I MediaProvider: Invalidating LocalCallingIdentity cache for package com.hjq.permissions.demo. Reason: op android:read_external_storage

**Comment by getActivity** [comment]
@yunianshu 小伙子，从你提供的堆栈信息，我没有得到任何有用的信息。

**Comment by yunianshu** [comment]
@getActivity 感谢作者的回复，我上午测试了一下，发现用原生的请求方式也会出错，所以应该不是框架的问题，还有我用红米k40真机测试了，这个是android 11版本，也没有问题，但是要上架还是有问题，可能是小米渠道有做限制

**Comment by weilei131** [comment]
我使用的系统是：vivo V1928A，Android9，项目的targetSDK是29，使用XXpermission版本13.2 和 12.8
出现以下问题：
在申请使用permission(Manifest.permission.READ_PHONE_STATE)权限是，调用request()方法出现如下异常：
The AndroidManifest.xml file <uses-permission android:name="android.permission.READ_PHONE_STATE" android:maxSdkVersion="29" /> does not meet the requirements, please delete the android:maxSdkVersion="29" attribute
![image](https://user-images.githubusercontent.com/28497579/143971698-65a13a9c-f09e-41f0-98b1-52d05762ca5e.png)

**Comment by getActivity** [comment]
@weilei131 小伙子，框架的报错信息写得还不够清楚么？让你把 `android:maxSdkVersion="29"` 的属性删掉。

**Comment by zengyunpeng** [comment]
我在Android7.1.2的开发板上遇到这个问题
![175eacf6288bcfd6d6c3667dc796501](https://user-images.githubusercontent.com/15943384/145542674-be052740-36a3-40c3-8589-558607f4e3e2.png)

**Comment by zengyunpeng** [comment]
权限是已经加了的,偶现

**Comment by getActivity** [comment]
@zengyunpeng 你用的框架版本号是多少？还有最新版本有没有这个问题？

**Comment by zengyunpeng** [comment]
> @zengyunpeng 你用的框架版本号是多少？还有最新版本有没有这个问题？

不是最新版本,12.6版本,晚点我试一下,偶现的不好找规律,现在在赶项目

**Comment by zengyunpeng** [comment]
![b5355637c11c7e9b6471a49748ee95e](https://user-images.githubusercontent.com/15943384/145550021-0eb35d37-9c84-4b6e-9b36-9382bbdc0c86.png) 像是从清单文件读权限时候出的问题

**Comment by getActivity** [comment]
@zengyunpeng 最新版本应该是没有这个问题的，因为最新版本修改了获取清单文件的方式，并且还会对清单文件进行核对，如果获取的清单文件包名和当前包名不是同一个，那么不会触发检查的。

**Comment by w296365959** [comment]
oppoR11 7.1.1系统  联系人权限默认关闭  可权限判断为打开，无法保存通讯录 CheckPermission: Permission Denial: can't read contacts， 只有手动设置过后，权限判断才生效；有啥解决办法么

**Comment by iielse** [comment]
询问: @getActivity 大佬 最新版本 好像没有 XXPermissions.with(androidx.fragment.app.Fragment fragment)？

**Comment by getActivity** [comment]
@iielse 
<img width="885" alt="image" src="https://user-images.githubusercontent.com/28616817/156167508-966c7858-78e1-49ae-8b1f-8b13ab53c021.png">

**Comment by anhuifix** [comment]
博主你好，你们库，这个版本使用不了，  implementation 'com.github.getActivity:XXPermissions:13.5' 引入之后一直提示加载中，麻烦看看怎么回事呢

**Comment by getActivity** [comment]
@anhuifix 你的项目有加入 `jitpack` 仓库的配置了吗？

<img width="849" alt="image" src="https://user-images.githubusercontent.com/28616817/159397968-66b73efc-c239-4784-bbb3-5ebaa30d0149.png">
