### ISSUE TITLE
[疑惑]：jitpack.io依赖问题

### ISSUE THREAD

**Issue by wp529** [getActivity/XXPermissions#211]
### 问题描述【必填】

jitpack.io上所有版本的依赖都不存在了
![image](https://github.com/getActivity/XXPermissions/assets/18145495/d7410c86-b41b-425f-8dfc-e8e09f2ce8da)

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by isliuqihang** [comment]
我也遇到这个问题了，老哥是如何解决的？

**Comment by getActivity** [comment]
@isliuqihang 小伙子，现在是什么版本下载有问题呢？我可以帮你看一下。

**Comment by getActivity** [comment]
[XXPermissions-18.5.pom](https://jitpack.io/com/github/getActivity/XXPermissions/18.5/XXPermissions-18.5.pom)
