### ISSUE TITLE
支持 jetpack compose

### ISSUE THREAD

**Issue by mcxinyu** [getActivity/XXPermissions#212]
### 你觉得框架有什么不足之处？【必答】

我看了框架的 readme，似乎还不支持 compose 哈，使用中是可以通过 remember 来支持 compose 的，但是就比较麻烦了，希望大佬能支持 compose。

### issue 是否有人曾提过类似的建议？【必答】

否

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

**Comment by mcxinyu** [comment]
虽然 compose 有 [accompanist/permissions](https://google.github.io/accompanist/permissions/)，但是没有`新权限自动兼容旧设备`这么贴心。

**Comment by getActivity** [comment]
小伙子，我理解你所说的支持 Compose 就是用 Kotlin 重写一遍框架对吧？

**Comment by getActivity** [comment]
<img width="890" alt="image" src="https://github.com/getActivity/XXPermissions/assets/28616817/f58937b2-574b-4368-aa52-48e8bf52c9c6">

小伙子，我理解你是想要一个 State 值来记录权限授予的状态，然后对 View 和 Module 进行双向绑定对吧？

**Comment by mcxinyu** [comment]
对的哈，我用咋们这个框架，还要在外面维护一个state。

**Comment by getActivity** [comment]
小伙子，我咨询了一个对 Compose 熟悉的朋友，和聊了一下里面的细节，另外聊了一下 Compose 的现状和未来，就我目前了解的来看，Compose 还没有成为主流的趋势，所以经过深思熟虑，暂时不考虑针对 Compose 进行额外的适配。

**Comment by getActivity** [comment]
小伙子，目前你可以先封装一个 state 来使用，目前这个看来不算太麻烦，可以先这样做。
