### ISSUE TITLE
[Bug]：Callback never called in release builds

### ISSUE THREAD

**Issue by mary-ng5519** [getActivity/XXPermissions#213]
### 框架版本【必填】

Android 11

### 问题描述【必填】

we love you work, please help investigate the issue, OnPermissionCallback is never called after user grants permissions or deny permissions
```
XXPermissions.with(this)
    // Request single permission
    .permission(Permission.RECORD_AUDIO)
    // Request multiple permission
    .permission(Permission.Group.CALENDAR)
    // Set permission request interceptor (local settings)
    //.interceptor(new PermissionInterceptor())
    // Setting does not trigger error detection mechanism (local setting)
    //.unchecked()
    .request(object : OnPermissionCallback {

        override fun onGranted(permissions: MutableList<String>, allGranted: Boolean) {
            if (!allGranted) {
                toast("Some permissions were obtained successfully, but some permissions were not granted normally")
                return
            }
            toast("Acquired recording and calendar permissions successfully")
        }

        override fun onDenied(permissions: MutableList<String>, doNotAskAgain: Boolean) {
            if (doNotAskAgain) {
                toast("Authorization denied permanently, please grant recording and calendar permissions manually")
                // If it is permanently denied, jump to the application permission system settings page
                XXPermissions.startPermissionActivity(context, permissions)
            } else {
                toast("Failed to get recording and calendar permissions")
            }
        }
    })
```

### 复现步骤【必填】

Create a hello world to test OnPermissionCallback to make sure the callbacks are called properly

### 是否必现【必填】

未选择

### 项目 targetSdkVersion【必填】

33

### 出现问题的手机信息【必填】

All Android 11+ devices

### 出现问题的安卓版本【必填】

Samsung Android 11, A series

### 问题信息的来源渠道【必填】

Bugly 看到的

### 是部分机型还是所有机型都会出现【必答】

Android 11+ 

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

是

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

是

**Comment by getActivity** [comment]
https://github.com/getActivity/XXPermissions/assets/28616817/65fff6ea-7447-4cf6-88fa-41e876f9b412

**Comment by getActivity** [comment]
<img width="611" alt="image" src="https://github.com/getActivity/XXPermissions/assets/28616817/8d4f7dba-9d71-4974-9899-a936d315f1f8">

**Comment by getActivity** [comment]
Hello, according to the reproduction steps you provided, I cannot reproduce the problem, please provide more information to help me solve the problem.
