### ISSUE TITLE
[建议]：这其实是个Bug.

### ISSUE THREAD

**Issue by hanhan500** [getActivity/XXPermissions#214]
### 你觉得框架有什么不足之处？【必答】

The AndroidManifest.xml file <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" android:maxSdkVersion="29" /> does not meet the requirements, please delete the android:maxSdkVersion="29" attribute

删除以后华为手机扫描，扫不出其他应用创建的文件。

### issue 是否有人曾提过类似的建议？【必答】

未选择

### 框架文档是否提及了该问题【必答】

未选择

### 是否已经查阅框架文档但还未能解决的【必答】

未选择

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 这个问题属于 bug，不能提建议 issue 单，请提 bug issue 单

请重新提一个 issue 并纠正以上问题
