### ISSUE TITLE
[建议]：请问能否支持无障碍权限的申请

### ISSUE THREAD

**Issue by SkyD666** [getActivity/XXPermissions#216]
### 你觉得框架有什么不足之处？【必答】

貌似无法申请无障碍权限

### issue 是否有人曾提过类似的建议？【必答】

否

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### 你觉得该怎么去完善会比较好？【非必答】

添加无障碍权限的申请 和 检查

**Comment by getActivity** [comment]
[Android-无障碍服务（AccessibilityService）](https://blog.csdn.net/Jason_Lee155/article/details/115966816)

**Comment by getActivity** [comment]
小伙子，我看了几篇文章，目前给的结论是无法开发此功能，原因是，判断有没有无障碍权限，需要知道外层使用的无障碍 Service 的类名，目前框架无法得知外层所使用的无障碍服务的类名是什么。

**Comment by SkyD666** [comment]
请问能否通过传入service类名的方式来判断，或者提供一个跟其他权限申请方式不一样的无障碍权限申请方法？

**Comment by getActivity** [comment]
@SkyD666 目前暂时不考虑这样做，因为改造的成本非常高，但是我会好好思考这个建议。

**Comment by SkyD666** [comment]
> @SkyD666 目前暂时不考虑这样做，因为改造的成本非常高，但是我会好好思考这个建议。

感谢
