### ISSUE TITLE
[疑惑]：不能直接定位到具体app某个权限开关吗？

### ISSUE THREAD

**Issue by superen7527** [getActivity/XXPermissions#219]
### 问题描述【必填】

悬浮窗权限：我记得以前使用安卓旧版，对应悬浮窗权限，会自动跳转到权限具体位置。后来应该是某个安卓版本高了，都是跳转到像现在demo里面安装apk权限那种全部应用列表界面去选择"允许上层权限"，找起来比较麻烦，而且没有回调？(刚刚测试有点匆忙，忘了是哪个没有回调了)，这个有没有办法具体到对应app的开关界面？我测试过 应用权限里面的悬浮窗权限和上层权限是同一个。所以如果实在不行，现在demo处理方式也不错，是我心里最佳解决方案了，可以直接下滑找到悬浮窗权限打开，(不过好像没有回调？)

安装未知apk权限：这个应该是可以具体的到apk开关，不过用的是全部应用列表，我还是第一次见到应用安装权限也有这种界面。所以我想如果可以优化这个，也许能找到悬浮窗权限的相关解决办法？

另外 本人不是搞安卓开发的，我只是从一个软件的开源列表转过来，感觉有点意思就试了一下demo，习惯性对优化的地方提个issue，如果问题太浅显很抱歉。可以关闭issue不理会我。

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by getActivity** [comment]
小伙子，这个问题我已经在文档上面写了，你回去再仔细翻一下文档看看。

**Comment by superen7527** [comment]
我之前只在文档上找到[这个](https://github.com/getActivity/XXPermissions/blob/master/HelpDoc-zh.md#%E6%96%B0%E7%89%88%E6%A1%86%E6%9E%B6%E4%B8%BA%E4%BB%80%E4%B9%88%E7%A7%BB%E9%99%A4%E4%BA%86%E5%9B%BD%E4%BA%A7%E6%89%8B%E6%9C%BA%E6%9D%83%E9%99%90%E8%AE%BE%E7%BD%AE%E9%A1%B5%E5%8A%9F%E8%83%BD) ，有点不太明白，意思是本来是可以支持，但是为了兼容性所以才移除是这个意思吗？还是我找错文档了。。
我只是比较奇怪，好像授权安装未知应用的权限是有具体到对应设置页的跳转api的，如果是为了兼容不能写一个判断吗？单纯就是一个疑问，没别的意思。

不过我这个issue应该没什么意义，我先关了保持issue区域整洁。要是有空再解答吧，要是实在无语就算了，我确实是门外汉，见谅。
