### ISSUE TITLE
[疑惑]：MIUI12/13 权限空白通行证

### ISSUE THREAD

**Issue by kbq670554802** [getActivity/XXPermissions#220]
### 问题描述【必填】

MIUI12/13 权限多了一个空白通行证选项，使用XXPermissions.isGranted()，判断权限是允许的。但实际运行代码提示权限未申请，所以无法操作。请问这个怎么处理解决

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

否

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

否

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 没有严格按照 issue 模板填写问题（乱填 issue 的问题）

请重新提一个 issue 并纠正以上问题
