### ISSUE TITLE
[疑惑]：混淆规则呢？

### ISSUE THREAD

**Issue by yijian2033** [getActivity/XXPermissions#221]
### 问题描述【必填】

混淆规则有吗？

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by getActivity** [comment]
不需要混淆规则，直接混淆即可。
