### ISSUE TITLE
[建议]：最近在上架应用宝的时候提示说要同步权限说明

### ISSUE THREAD

**Issue by bjy520** [getActivity/XXPermissions#222]
### 你觉得框架有什么不足之处？【必答】

![image](https://github.com/getActivity/XXPermissions/assets/18107295/51b7ffd7-b649-4eef-9405-0c2367fcd1ea)
https://wikinew.open.qq.com/index.html#/iwiki/4007776075  应用包对应网址  

### issue 是否有人曾提过类似的建议？【必答】

否

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### 你觉得该怎么去完善会比较好？【非必答】

增加个方法集合 能同步多个说明

**Comment by getActivity** [comment]
小伙子，关于你说的权限说明弹窗，这个框架内部已经提供了一个拦截器的类，你可以通过拦截器器的类来显示权限说明，另外一个问题是，能够增加个方法集合，能同步多个说明，这个目前做不到，这是因为你一次性申请多种权限，那么只有用户全部授权完后框架才能收到回调，所以暂时无法做到一种权限对应一个说明，但并不是没有办法做到这种效果，你可以考虑分拆多次权限申请。但是目前就我的了解来看，就算申请多种权限，弹一个权限说明框，应该是没有问题，政策上面是合规的，你可以把多个权限说明合并成一个然后进行展示。

**Comment by getActivity** [comment]
超过一个星期没有响应，自动关闭此 issue。
