### ISSUE TITLE
[Bug]：

### ISSUE THREAD

**Issue by kerwinkeep** [getActivity/XXPermissions#223]
### 框架版本【必填】

18.2

### 问题描述【必填】

`mBinding.ecMyLocation.setOnClickListener {
            XXPermissions.with(this)
                .permission(LocationHelper.PRECISE_LOCATION_PERMISSION)
                .request(object : OnPermissionCallback {
                    override fun onGranted(permissions: MutableList<String>, allGranted: Boolean) {
                       
                    }

                    override fun onDenied(
                        permissions: MutableList<String>,
                        doNotAskAgain: Boolean
                    ) {
                        super.onDenied(permissions, doNotAskAgain)
                        if (XXPermissions.isPermanentDenied(activity, LocationHelper.PRECISE_LOCATION_PERMISSION)) {
                            Log.d("kerwin", "onDenied:都被永久拒绝 ")
                        }
                        if (XXPermissions.isPermanentDenied(activity, LocationHelper.PRECISE_LOCATION_PERMISSION[0])) {
                            Log.d("kerwin", "onDenied:粗略位置被永久拒绝 ")
                        }
                        if (XXPermissions.isPermanentDenied(activity, LocationHelper.PRECISE_LOCATION_PERMISSION[1])) {
                            Log.d("kerwin", "onDenied:详细位置被永久拒绝 ")
                        }
                        if (doNotAskAgain && permissions.contains(LocationHelper.PRECISE_LOCATION_PERMISSION[0])) {
                             Log.d("kerwin", "onDenied:粗略位置被永久拒绝 ")
                        }
                    }
                })
        }`

### 复现步骤【必填】

GooglePixel 3 XL；
Android12；
点击按钮，弹出系统权限申请弹窗，不允许也不拒绝，直接点击返回键，上面代码会返回全部权限都被永久拒绝

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

31

### 出现问题的手机信息【必填】

GooglePixel 3 XL

### 出现问题的安卓版本【必填】

Android12

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

手头只有GooglePixel 3 XL也只测试了GooglePixel 3 XL

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

未选择

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

未选择

### 是否可以通过 Demo 来复现该问题【必答】

是

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 没有严格按照 issue 模板填写问题

请重新提一个 issue 并纠正以上问题
