### ISSUE TITLE
[疑惑]：为什么项目中的demo不能打release包？

### ISSUE THREAD

**Issue by Vicent9920** [getActivity/XXPermissions#224]
### 问题描述【必填】

打包时报错：
```
Javadoc generation failed. Generated Javadoc options file (useful for troubleshooting): 'G:\workcode\XXPermissions\build\library\tmp\javadoc\javadoc.options'
```

### 框架文档是否提及了该问题【必答】

未选择

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by getActivity** [comment]
<img width="1680" alt="image" src="https://github.com/getActivity/XXPermissions/assets/28616817/4a8451da-56bd-4c5d-8925-48961f94a019">

**Comment by getActivity** [comment]
小伙子，我经过测试，是没有问题的。

**Comment by getActivity** [comment]
超过一个星期没有响应，自动关闭此 issue。
