### ISSUE TITLE
[Bug]：系统权限申请弹窗弹出后如果点击空白区域，弹窗消失，此时OnPermissionCallback中的onDenied方法中的doNotAskAgain会返回true

### ISSUE THREAD

**Issue by zzzsssbo** [getActivity/XXPermissions#225]
### 框架版本【必填】

18.2

### 问题描述【必填】

系统权限申请弹窗弹出后如果点击空白区域，弹窗消失，此时OnPermissionCallback中的onDenied方法中的doNotAskAgain会返回true，实际上用户并没有点击拒绝。

### 复现步骤【必填】

系统权限弹窗弹出后点击空白区域，然后OnPermissionCallback中的onDenied方法中打印日志，doNotAskAgain为true。

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

29

### 出现问题的手机信息【必填】

小米11pro

### 出现问题的安卓版本【必填】

32

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

目前仅测试了小米11pro，暂无其他测试机型

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

是

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

是

**Comment by getActivity** [comment]
https://github.com/getActivity/XXPermissions/issues/151

**Comment by getActivity** [comment]
https://github.com/getActivity/XXPermissions/issues/154

**Comment by getActivity** [comment]
小伙子，你确定别人没有提过这个问题？
