### ISSUE TITLE
[Bug]：startPermissionActivity时，选择拒绝，返回时，不触发onDenied，还导致重建了activity

### ISSUE THREAD

**Issue by lerit** [getActivity/XXPermissions#227]
### 框架版本【必填】

18.2

### 问题描述【必填】

如果选择的位置权限不满足要求（比如要求后台位置，只选择了仅在使用时允许），且选择了不再提示时，我会通过XXPermissions.startPermissionActivity引导用户到手动设置。

如果这时用户继续选择了拒绝并返回，我期望的是触发onDenied，但是并没有触发任何事件，反而导致之前的activity被重建（触发了activity的onCreate）。

demo中我也发现有此问题，见复现步骤。

### 复现步骤【必填】

xxPermissions的demo：

- 将主界面稍微滚动向下一些（以确定之后是否被重建）
- 选择申请定位权限按钮
- 仅在使用时访（不再询问）
- 会提示手动授权后台定位，点击前往授权
- 将位置信息权限，选择为‘’拒绝‘’
- 按返回键或者左上角返回按钮，直到demo
- 发现主界面恢复了原始状态（滚动位置没保持）

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

31

### 出现问题的手机信息【必填】

sumsang galaxy note 9(sm-n9600)

### 出现问题的安卓版本【必填】

10

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

我只又找了另外一台杂牌子，也有这个问题。

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

是

**Comment by getActivity** [comment]
小伙子，你不用框架也会出现这个问题，这个是系统杀你的，先打开你的 App，然后在设置找到自己应用的权限设置页，先给定位权限设置授予，然后再点拒绝，你再回去应用上面看看是不是重启了？

**Comment by lerit** [comment]
果然如此，微信都有这问题，谢啦。
