### ISSUE TITLE
[疑惑]：请问这个项目目前还在继续维护嘛?

### ISSUE THREAD

**Issue by suzhenghui-sky** [getActivity/XXPermissions#228]
### 问题描述【必填】

请问这个项目还在继续维护嘛?

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

否

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

否

**Comment by getActivity** [comment]
小伙子，你是从哪个方面看出来这个项目不维护了？

**Comment by suzhenghui-sky** [comment]
> 小伙子，你是从哪个方面看出来这个项目不维护了？

主要是担心，你回复也就是证明项目还在维护。
