### ISSUE TITLE
[建议]：权限设置页面跳转兜底的Intent不返回null

### ISSUE THREAD

**Issue by qq549631030** [getActivity/XXPermissions#232]
### 你觉得框架有什么不足之处？【必答】

PermissionIntentManager.getApplicationDetailsIntent()最后返回的Intent是可空的，但是在StartActivityManager.startActivity()和StartActivityManager.startActivityForResult()参数intent是非空的，这样就会报空指针错误了。

PermissionIntentManager.getApplicationDetailsIntent()返回null，这种情况在真机上应该不会出现。但是在用robolectric做单元测试的时候，因为PermissionUtil.areActivityIntent()一直返回false，所以就导致返回null了。

### issue 是否有人曾提过类似的建议？【必答】

否

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

否

### 你觉得该怎么去完善会比较好？【非必答】

希望PermissionIntentManager.getApplicationDetailsIntent()返回非空的，或者把PermissionUtil.areActivityIntent()公开出来，做单元测试的时候好mock

**Comment by getActivity** [comment]
[XXPermissions-18.3.aar.zip](https://github.com/getActivity/XXPermissions/files/12354595/XXPermissions-18.3.aar.zip)

**Comment by getActivity** [comment]
小伙子，建议已经采纳，你可以下载上面的 aar 包试试看。
