### ISSUE TITLE
[Bug]：荣耀手机申请勿扰权限失败

### ISSUE THREAD

**Issue by qq549631030** [getActivity/XXPermissions#233]
### 框架版本【必填】

18.2

### 问题描述【必填】

荣耀手机申请勿扰权限失败，和之前[华为手机申请勿扰权限失败](https://github.com/getActivity/XXPermissions/issues/190)一样

### 复现步骤【必填】

直接用18.2的Demo apk点申请勿扰权限

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

33

### 出现问题的手机信息【必填】

荣耀Magic 4

### 出现问题的安卓版本【必填】

Android 13

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

荣耀手机

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

是

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

是

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

是

**Comment by getActivity** [comment]
[XXPermissions-18.3.aar.zip](https://github.com/getActivity/XXPermissions/files/12354596/XXPermissions-18.3.aar.zip)

**Comment by getActivity** [comment]
小伙子，问题已经修复，你可以下载上面的 aar 包进行测试。

**Comment by qq549631030** [comment]
ok了
