### ISSUE TITLE
[Bug]: Keep asking Permission.READ_PHONE_STATE permission after user granted it

### ISSUE THREAD

**Issue by mary-ng5519** [getActivity/XXPermissions#234]
### Framework Version [Required]

com.github.getActivity:XXPermissions:18.2

### Issue Description [Required]

Keep asking Permission.READ_PHONE_STATE permission after user granted it

### Steps to Reproduce [Required]
```
XXPermissions.with(this)
            .permission(Permission.Group.STORAGE)
            .permission(Permission.Group.CONTACTS)
            .permission(Permission.Group.BLUETOOTH)
            .permission(Permission.PACKAGE_USAGE_STATS)
            .permission(Manifest.permission.BLUETOOTH_ADMIN)
            .permission(Permission.BLUETOOTH_SCAN)
            .permission(Permission.BLUETOOTH_CONNECT)
            .permission(Permission.BLUETOOTH_ADVERTISE)
            .permission(Permission.SCHEDULE_EXACT_ALARM)
            .permission(Permission.READ_PHONE_STATE)
            .permission(Permission.WRITE_SETTINGS)
            .permission(Manifest.permission.LOCATION_HARDWARE)
            .permission(Permission.ACCESS_BACKGROUND_LOCATION)
            .permission(Permission.ACCESS_COARSE_LOCATION)
            .permission(Permission.ACCESS_FINE_LOCATION)
            .interceptor(PermissionInterceptor())
            // Setting does not trigger error detectiFon mechanism (local setting)
            .unchecked()
            .request(object : OnPermissionCallback {

                override fun onGranted(permissions: MutableList<String>, allGranted: Boolean) {
                    if (!allGranted) {
Logger.d(message = "@@@ Some permissions were obtained successfully, but some permissions were not granted normally")
//always true even users granted all permissions
                    }
                }

                override fun onDenied(permissions: MutableList<String>, doNotAskAgain: Boolean) {
                    Logger.d("@@@ ${permissions.toString()}")
                }
            })
```
### Is the Issue Reproducible? [Required]

Yes

### Project targetSdkVersion [Required]

31

### Device Information [Required]

Samsung - android 11 devices

### Android Version [Required]

11

### Issue Source Channel [Required]

Identified in Bugly

### Is it specific to certain device models? [Required]

all Samsung Android 11 related devices

### Does the latest version of the framework have this issue? [Required]

Yes

### Is the issue mentioned in the framework documentation? [Required]

No

### Did you consult the framework documentation but couldn't find a solution? [Required]

Yes

### Has a similar issue been reported in the issue list? [Required]

No

### Have you searched the issue list but couldn't find a solution? [Required]

Yes

### Can the issue be reproduced with a demo project? [Required]

No

**Comment by getActivity** [comment]
Hello, from your description, I still don't know what you want to express?

**Comment by getActivity** [comment]
Hello, if you don't respond to this issue, then I will close it in the near future

**Comment by getActivity** [comment]
No response for more than two weeks. Close this issue.
