### ISSUE TITLE
[Bug]：targetVersion 未作为面向新版本权限的兼容性判断，造成差异

### ISSUE THREAD

**Issue by gentrio** [getActivity/XXPermissions#235]
### 框架版本【必填】

18.3

### 问题描述【必填】

当XXPermission作为二方库的三方库依赖时，二方库面向最新版本的targetVersion，但使用方的targetVersion是未知的，可能低于二方库的targetVersion；此时对于最新版本targetVersion的权限请求并不会收到回调。
目前所有版本适配判断大部分只判断了 Build.Version，导致面向 targetVersion 的权限在低 targetVersion 的情况下没有很好的处理。

### 复现步骤【必填】

比如二方库targetVersion面向 Android 13，请求POST_NOTIFICATIONS；
接入方targerVersion 面向 Android 12；
此时Android 13手机请求POST_NOTIFICATIONS 并不会收到回调，且PermissionChecker.optimizeDeprecatedPermission 仅判断了Build.Version 也不会对权限进行低版本适配成 NOTIFICATION_SERVICE

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

33

### 出现问题的手机信息【必填】

小米、Pixel

### 出现问题的安卓版本【必填】

13

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

所有机型

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

是

**Comment by getActivity** [comment]
小伙子，我没理解你说的二方库是什么意思？

**Comment by gentrio** [comment]
就当是module好了，当module targetsdkversion高于application targetsdkversion时，并且跑在高版本的系统上（module 的target），比如申请POST_NOTIFICATIONS 权限会收不到回调

**Comment by yuzhiqiang1993** [comment]
你的二方库不要指定targetsdkversion不就完了

**Comment by gentrio** [comment]
> 你的二方库不要指定targetsdkversion不就完了

二方库的 targetVersion 是为了适配任意 targetSdkVersion 的 application；目前的问题是是Application使用了低 targetVersion 但运行在高版本系统上时，如果申请了高版本的权限，XXPermission 并不会收到回调，因为系统也不会给回调。

XXPermission 本来对于低版本系统的高版本权限是通过 PermissionChecker.optimizeDeprecatedPermission 来做了权限转换，但比如对 POST_NOTIFICATIONS 的处理却只做了运行时系统版本判断，没有做应用的目标版本做判断，就会造成完全没有回调的情况。

目前看下来，框架虽然做了高低版本的权限适配，但是判断的条件并不充分，所以仅使用最新的权限没办法适配所有 Build.Version 和 targetSdkVersion的 情况。

**Comment by getActivity** [comment]
小伙子，POST_NOTIFICATIONS 属于 Android 13 的权限，一旦申请了这个权限，框架会强制要求项目的 targetSdkVersion 要大于等于 33，具体的方式是抛异常出来，你是不是通过 unchecked 方法来屏蔽了这个策略？

**Comment by getActivity** [comment]
超过两个星期没有响应，自动关闭此 issue。
