### ISSUE TITLE
[Bug]：android.content.pm.action.REQUEST_PERMISSIONS 出现空指针

### ISSUE THREAD

**Issue by lixiang0418** [getActivity/XXPermissions#236]
### 框架版本【必填】

16.6

### 问题描述【必填】

Bugly上报异常
1 java.lang.RuntimeException:Failure delivering result ResultInfo{who=@android:requestPermissions:android:fragment:1, request=110, result=0, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.faloo.BookReader4Android/com.faloo.view.activity.SplashActivity}: java.lang.NullPointerException: Attempt to get length of null array
1	java.lang.RuntimeException:Failure delivering result ResultInfo{who=@android:requestPermissions:android:fragment:1, request=110, result=0, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.faloo.BookReader4Android/com.faloo.view.activity.SplashActivity}: java.lang.NullPointerException: Attempt to get length of null array
2	android.app.ActivityThread.deliverResults(ActivityThread.java:4426)
3	......
4	Caused by:
5	java.lang.NullPointerException:Attempt to get length of null array
6	com.hjq.permissions.PermissionFragment.onRequestPermissionsResult(Proguard:360)
7	android.app.Activity.dispatchRequestPermissionsResultToFragment(Activity.java:7630)
8	android.app.Activity.dispatchActivityResult(Activity.java:7474)
9	android.app.ActivityThread.deliverResults(ActivityThread.java:4419)
10	android.app.ActivityThread.handleSendResult(ActivityThread.java:4468)
11	android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
12	android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
13	android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
14	android.app.ActivityThread$H.handleMessage(ActivityThread.java:1813)
15	android.os.Handler.dispatchMessage(Handler.java:106)
16	android.os.Looper.loop(Looper.java:193)
17	android.app.ActivityThread.main(ActivityThread.java:6820)
18	java.lang.reflect.Method.invoke(Native Method)
19	com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
20	com.android.internal.os.ZygoteInit.main(ZygoteInit.java:861)

### 复现步骤【必填】

使用云真机，没有找到 联想 Z5 Pro设备，
使用 联想Z6 型号，Android 9 进行测试未复现
使用 拯救者Y90 型号，Android 12进行测试未复现
使用 联想 ZUK edge 型号，Android 7进行测试未复现

一加 6，vivo Z3，索尼 XZ2，ROG 游戏手机2 均是Android 9，进行测试，未复现

### 是否必现【必填】

未选择

### 项目 targetSdkVersion【必填】

26

### 出现问题的手机信息【必填】

联想 Z5 Pro

### 出现问题的安卓版本【必填】

Android 9,level 28

### 问题信息的来源渠道【必填】

Bugly 看到的

### 是部分机型还是所有机型都会出现【必答】

部分

### 框架最新的版本是否存在这个问题【必答】

否

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

否

### 提供解决方案

16.6和18.3 PermissionFragment 的 onRequestPermissionsResult方法，只判断了permissions.length == 0，是不是可以增加 ==null 的判断呢
源代码：
```
        if (permissions.length == 0 || grantResults.length == 0) {
            return;
        }
```
期望代码：
```
        if (permissions == null || permissions.length == 0 || grantResults.length == 0) {
            return;
        }
```

**Comment by lixiang0418** [comment]
翻和轮子哥的聊天记录发现，以前反馈过vivo的出现过类似的权限问题，也是这个权限，不过异常是  ActivityNotFoundException 
![Uploading![bugly](https://github.com/getActivity/XXPermissions/assets/18587062/4fe4b369-ee86-4092-8cc4-b63f03e36bd0)image.png…]()

**Comment by getActivity** [comment]
小伙子，正常情况下是肯定不会出现空的情况，因为在 Android 源码中已经标注 `permissions` 参数是非空的，还有一种特殊情况是厂商修改了这块的实现，返回了空数组导致的，不过小伙子你既然提了这个问题，就证明这个问题是存在的，我在下个版本加上这个防空判断。

<img width="1037" alt="image" src="https://github.com/getActivity/XXPermissions/assets/28616817/af764312-28fd-404e-9198-66492de06019">

**Comment by androidDvlper** [comment]
这个修复，不够严谨，会导致另外的问题：REQUEST_CODE_ARRAY.remove((Integer) requestCode); 没有被移除，在monkey环境中，REQUEST_CODE_ARRAY中存放了255个随机数后，导致while (REQUEST_CODE_ARRAY.contains(requestCode)) 死循环。死循环问题我遇到了。

onRequestPermissionsResult 回调后的第一件事，就要REQUEST_CODE_ARRAY.remove((Integer) requestCode);。

**Comment by getActivity** [comment]
<img width="1680" alt="image" src="https://github.com/getActivity/XXPermissions/assets/28616817/f82cdf59-e2c9-4897-be01-54a5c1633ee5">

**Comment by getActivity** [comment]
[XXPermissions-18.66.aar.zip](https://github.com/user-attachments/files/16132245/XXPermissions-18.66.aar.zip)

**Comment by getActivity** [comment]
@androidDvlper 小伙子，针对你说的这个问题，我对这块的代码逻辑进行了优化，你用上面的 aar 包测试看看问题还会不会出现？
