### ISSUE TITLE
[Bug]：targetSdkVersion 30 时 申请存储权限Permission.MANAGE_EXTERNAL_STORAGE 成功之后写入WRITE_EXTERNAL_STORAGE权限并没有成功

### ISSUE THREAD

**Issue by protectedMan** [getActivity/XXPermissions#237]
### 框架版本【必填】

18.3

### 问题描述【必填】

targetSdkVersion 30 时 申请存储权限Permission.MANAGE_EXTERNAL_STORAGE 成功之后写入WRITE_EXTERNAL_STORAGE权限并没有打开 写入失败 改为申请Permission.Group.STORAGE 权限 文件外部写入不可使用  只有两个权限在不同地方都申请写入正常   将demo targetSdkVersion 变为30申请所有文件权限提示成功 但XXPermissions.isGranted(MainActivity.this,Permission.WRITE_EXTERNAL_STORAGE) 为false

### 复现步骤【必填】

targetSdkVersion 30  申请Permission.MANAGE_EXTERNAL_STORAGE 成功后 使用Aria下载 提示启动失败，缺少权限：Manifest.permission.WRITE_EXTERNAL_STORAGE  鸿蒙3.0正常

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

30

### 出现问题的手机信息【必填】

OPPO k7x

### 出现问题的安卓版本【必填】

12

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

vivo Y31s androidb版本11也出现

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

是

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

是

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

是

**Comment by getActivity** [comment]
<img width="1060" alt="image" src="https://github.com/getActivity/XXPermissions/assets/28616817/4cb71237-ba9f-40ca-b938-174aecd9a060">

**Comment by getActivity** [comment]
小伙子，`WRITE_EXTERNAL_STORAGE` 和 `MANAGE_EXTERNAL_STORAGE` 是两种不同的权限，你的项目 targetSdk 大于等于 30，如果想要读写外部存储，则需要申请 `MANAGE_EXTERNAL_STORAGE` 权限，申请到就即可，不需要再去申请 `MANAGE_EXTERNAL_STORAGE`。

**Comment by getActivity** [comment]
至于你说的 [Aria](https://github.com/AriaLyy/Aria) 框架下载失败的问题，这个问题属于框架的问题，它没有做好对 `MANAGE_EXTERNAL_STORAGE` 权限判断，你可以联系 Aria 作者加上，又或者自己克隆源码加上。

**Comment by getActivity** [comment]
超过两个星期没有响应，自动关闭此 issue。

**Comment by akhzz905** [comment]
Aria很久没更新了，如果确认能写入文件，用ignoreCheckPermissions方法忽略检查权限就可以了
