### ISSUE TITLE
[建议]：跳转应用详情页和应用权限设置页希望分两个方法

### ISSUE THREAD

**Issue by jiqianwen** [getActivity/XXPermissions#238]
### 你觉得框架有什么不足之处？【必答】

现在startPermissionActivity如果权限传空只会跳转到应用详情页，希望可以分两个方法既可以跳转到应用详情，也可以跳转到权限设置（跳转到权限设置权限参数可以为空）

### issue 是否有人曾提过类似的建议？【必答】

否

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

**Comment by getActivity** [comment]
小伙子，你用的框架版本是多少？

**Comment by jiqianwen** [comment]
> 小伙子，你用的框架版本是多少？

18.3

**Comment by jiqianwen** [comment]
> <img alt="image" width="1113" src="https://user-images.githubusercontent.com/28616817/266313055-ae30581c-7ccf-47d7-8d27-018ceac862bb.png">
> 小伙子，框架本身就有两个方法的，如果不传权限，就是应用详情页，如果传了权限，就跳转到具体的权限设置页，这样有什么问题吗？还是说我没有理解对你的意思？

我的意思是不传权限也可以跳转到权限设置页，项目需求只是为了跳转权限设置页，并不是需要申请XX权限

**Comment by jiqianwen** [comment]
比如跳转应用详情  startAppDetailsActivity()

**Comment by jiqianwen** [comment]
目前框架的做法是，如果权限传入为空，最后会跳转到兜底的应用详情页，期望是即使权限传入空也是跳转到权限设置页，而不是走兜底的逻辑，应用详情页可以单独分一个方法出来

**Comment by getActivity** [comment]
小伙子，现在大部分的权限设置页已经无法直接跳转了，只能跳转应用详情页，所以不要白费力气了

**Comment by getActivity** [comment]
超过三个星期没有响应，自动关闭此 issue。
