### ISSUE TITLE
[建议]：MIUI 13/14 上的新权限

### ISSUE THREAD

**Issue by AyakaAgo** [getActivity/XXPermissions#239]
### 你觉得框架有什么不足之处？【必答】

MIUI 13/14 新增的**剪贴板**、**动态壁纸**、**加速度传感器**权限**需要动态授权**，但**没有授权对话框**，需要 `AppOpsManager` 和前往应用信息授权

### issue 是否有人曾提过类似的建议？【必答】

否

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### 你觉得该怎么去完善会比较好？【非必答】

AppOpsManager 部分常量

| 权限 | OP STRING |
| ----- | ----- |
| 读取剪贴板 | android:read_clipboard |
| 写入剪贴板 | android:write_clipboard |
| 加速度传感器 | MIUI:10044 |
| 动态壁纸 | MIUI:10045 |

_MIUI 14.0.3_

**Comment by getActivity** [comment]
小伙子，这几个权限都是 miui 的权限，并不是 Android 的权限，你为什么会想要框架支持这几个权限？具体的用途是什么？
