### ISSUE TITLE
[Bug]：vivo部分机型应用列表权限一直返回为false

### ISSUE THREAD

**Issue by womarklee** [getActivity/XXPermissions#240]
### 框架版本【必填】

18.2

### 问题描述【必填】

XXPermissions.isGranted(context, Permission.GET_INSTALLED_APPS)
XXPermissions.with(context).permission(Permission.GET_INSTALLED_APPS).request()
vivo部分机型一直返回为false，调用动态申请直接走onDenied逻辑。

在对应设备上手动调用 PermissionUtils.checkSelfPermission(context, Permission.GET_INSTALLED_APPS)  一直返回为false
猜测是vivo新款设备有修改，导致 isSupportGetInstalledAppsPermission(context) 返回为 true

### 复现步骤【必填】

无

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

28

### 出现问题的手机信息【必填】

vivo V2278A     vivo V2270A

### 出现问题的安卓版本【必填】

Android13

### 问题信息的来源渠道【必填】

用户反馈

### 是部分机型还是所有机型都会出现【必答】

vivo部分机型

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

是

**Comment by getActivity** [comment]
小伙子，我从你的问题中已经看到了，你已经知道这个问题是厂商的问题，为什么最终是反馈给我呢？我既不能督促厂商按照工信部的要求做，也不能直接修改手机厂商的系统源码。

**Comment by getActivity** [comment]
这些问题需要你去反馈给 vivo，vivo 如果不改的话，建议直接反馈给工信部门，至于为什么不是我来反馈，因为我一个人反馈无法引起重视，但是千千万万个开发者反馈，这件事情的性质就不一样了，有些事情只有客诉量上来了，才能引发重视，才会有人处理。

**Comment by womarklee** [comment]
明白

**Comment by woomartin** [comment]
> 最后解决了吗？ [@woomartin](https://github.com/woomartin)

当时处理方案是判断是vivo时，一律默认有这个权限。

**Comment by getActivity** [comment]
> > 最后解决了吗？ [@woomartin](https://github.com/woomartin)
> 
> 当时处理方案是判断是vivo时，一律默认有这个权限。

默认有这个权限处理？你确定这样做能读取到应用列表吗？
