### ISSUE TITLE
[Bug]：申请定位权限成功，但是拿不到位置信息

### ISSUE THREAD

**Issue by SunryOne** [getActivity/XXPermissions#241]
### 框架版本【必填】

18.2

### 问题描述【必填】

在部分手机中，未开启手机本身位置信息服务的情况下，申请定位权限，权限申请成功，但是依然拿不到定位相关信息。希望能够增加相关判断，并可跳转位置信息开启页面，

### 复现步骤【必填】

手机-设置-位置服务关闭，申请位置信息权限，赋予权限，依然不能获取位置信息。

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

32

### 出现问题的手机信息【必填】

Redmi K50 Pro

### 出现问题的安卓版本【必填】

13

### 是部分机型还是所有机型都会出现【必答】

全部

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

否

### 是否可以通过 Demo 来复现该问题【必答】

是

**Comment by getActivity** [comment]
小伙子，目前框架的定位是和权限相关的功能，你说的位置开关不属于权限的范围，位置权限和位置开关本质是两种东西，位置权限是对某个应用程序的限制，而位置开关是针对所有应用程序的限制，作为权限请求框架来讲，不会去位置开关的判断和申请，另外蓝牙权限和蓝牙开关、wifi 权限和 wifi 开关也同理。

**Comment by getActivity** [comment]
超过两个星期没有响应，自动关闭此 issue。
