### ISSUE TITLE
[疑惑]：为什么不用 Android 版本判断，而是用 targetSdk 版本判断

### ISSUE THREAD

**Issue by jhui20130703** [getActivity/XXPermissions#242]
### 问题描述【必填】

![image](https://github.com/getActivity/XXPermissions/assets/20755330/c4a5047c-10ca-4efc-aeaa-6afec2897044)

使用XXPermissions 18.3版本，我看框架里面判断的是targetSdk 版本大于等于ANDROID_13去检查新的图片、音频、视频权限，此处是否应该是根据当前手机的Android 版本来判断呢？

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by getActivity** [comment]
小伙子，你是否熟悉 targetSdkVersion 的含义？

**Comment by Crisy1084** [comment]
如果应用target升级到33了，但是又需要兼容低版本的时候（低版本android的存量还有不少），这里就没办法绕过去了。

**Comment by getActivity** [comment]
@Crisy1084 @JohnWa97 小伙子，targetSdk 是项目在清单文件中注册的，是固定不变的值，当你升级了 targetSdk 为 33 的时候，那么代表你不能用旧的权限进行权限申请，而是应该用新的权限来进行权限申请，否则在高版本的设备会有问题，像截图中的 `READ_EXTERNAL_STORAGE` 权限，你将不能在 Android 13 上面申请该权限，而是应该申请 `READ_MEDIA_IMAGES`、`READ_MEDIA_VIDEO`、`READ_MEDIA_AUDIO` 任一权限，如果你仍然选择申请 `READ_EXTERNAL_STORAGE` 权限，权限申请会被系统无情拒绝，并且还是不会弹窗询问用户的那种。

另外对于新权限在旧系统上面的兼容，框架已经做好了处理，你只需要申请新权限即可，框架会自动判断，如果是在旧系统上面运行，则框架会自动添加旧权限进行权限申请，不需要你在外层做任何处理。

另外你如果不想升级 targetSdk 版本，请不要使用新权限来申请权限，直接用旧权限来申请权限即可。

**Comment by Carlos2927** [comment]
@getActivity 轮子哥 有个问题啊 这三个android 13的新权限你在更低版本系统时请求权限列表为什么不删除掉呢
![image](https://github.com/getActivity/XXPermissions/assets/12493233/eca22821-b1c4-40e4-ad08-386369753564)

**Comment by getActivity** [comment]
@Carlos2927 框架如果删掉，后续系统通过权限回调给我的时候也没有这个权限，框架回调外层的时候也是没有这个权限，这样就会导致成一个很奇怪的现象，你就申请了 A 权限，但是权限回调给的权限集合中只有 B 权限，没有 A 权限。

**Comment by kanshenmekan** [comment]
有一个问题啊轮子哥，对于公共文件夹，比如图片文档下载之类，Android12以上是可以不需要权限就可以操作的。但是对于Android12以下的还是要去申请READ_EXTERNAL_STORAGE来处理，Android12以上不需要申请READ_MEDIA_IMAGES、READ_MEDIA_VIDEO、READ_MEDIA_AUDIO之类的。这种情况要怎么处理

**Comment by kanshenmekan** [comment]
> > 有一个问题啊轮子哥，对于公共文件夹，比如图片文档下载之类，Android12以上是可以不需要权限就可以操作的。但是对于Android12以下的还是要去申请READ_EXTERNAL_STORAGE来处理，Android12以上不需要申请READ_MEDIA_IMAGES、READ_MEDIA_VIDEO、READ_MEDIA_AUDIO之类的。这种情况要怎么处理
> 
> 请求权限之前先判断一下 Android 版本，如果大于 Android 12 就不去申请权限，另外关闭一下框架的错误检查机制。
> 
> <img alt="Image" width="863" src="https://private-user-images.githubusercontent.com/28616817/459363207-7ef4a53e-50ba-448d-91fa-9f2f8d33c5f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTA5MzYyNjIsIm5iZiI6MTc1MDkzNTk2MiwicGF0aCI6Ii8yODYxNjgxNy80NTkzNjMyMDctN2VmNGE1M2UtNTBiYS00NDhkLTkxZmEtOWYyZjhkMzNjNWYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNjI2VDExMDYwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3YWU2M2U1OWM5ZDQxZTg0MjlhYzVjMGE5YjMwN2Q3YzRkOTEzZmRmNTk0ZjlmNjlmZDkwMWViODNkNWQ0MDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.AbTXZMRzPN6995Tyz97J6Jqi6-_HGv1YUf7xRafQNZU">

我现在就是这样处理的，但是我感觉储存权限这块还是没处理好，不过是google的搞得历史包袱问题

**Comment by getActivity** [comment]
@kanshenmekan 既然在 Android 12 及以上操作公共文件夹不需要权限，你试一下在 Android 12 以下是不是也不需要权限？
