### ISSUE TITLE
[疑惑]：关于MANAGE_EXTERNAL_STORAGE权限的疑问

### ISSUE THREAD

**Issue by qiushui95** [getActivity/XXPermissions#245]
### 问题描述【必填】

我下载目前的代码运行
将        android:requestLegacyExternalStorage="true"  删除
新增文档的ScopedStorage配置
然后获取MANAGE_EXTERNAL_STORAGE权限，必崩溃
必须要android:requestLegacyExternalStorage="true" 属性才能正常运行，不知道是不是bug

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 乱填 issue 问题

请重新提一个 issue 并纠正以上问题

**Comment by qiushui95** [comment]
> 小伙子，该 issue 被打回，打回的原因如下：
> 
> * 乱填 issue 问题
> 
> 请重新提一个 issue 并纠正以上问题

是因为类型不对？
