### ISSUE TITLE
[疑惑]：找不到androidx.fragment.app.Fragment的类文件

### ISSUE THREAD

**Issue by ffdsss** [getActivity/XXPermissions#247]
### 问题描述【必填】

报错：错误: 无法访问Fragment
        XXPermissions.with(MyApp.getInstance().getCurrentActivity())，， 在另一个项目中同样的写法没问题

![image](https://github.com/getActivity/XXPermissions/assets/48895716/c92565ab-ef13-4f17-b523-25ab3707372a)

MyApp代码：
![image](https://github.com/getActivity/XXPermissions/assets/48895716/4ba4c8cf-9ae4-4c36-b668-dca8593a70fa)

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

否

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by ffdsss** [comment]
没事了  少依赖

**Comment by licoba** [comment]
> 没事了 少依赖

少了啥依赖啊

**Comment by pangli** [comment]
在项目的gradle.properties文件中加入android.enableJetifier=true将三方库的依赖迁移到AndroidX

**Comment by getActivity** [comment]
框架已迁移到 AndroidX，详情请见 [Release v28.0](https://github.com/getActivity/XXPermissions/releases/tag/28.0)
