### ISSUE TITLE
[疑惑]：小米设备有一个通知类短信类别权限问题

### ISSUE THREAD

**Issue by zs18340282344** [getActivity/XXPermissions#249]
### 问题描述【必填】

我在使用READ_SMS这个权限时候获取到的信息不全，通知类短信类别的信息获取不到有没有单独的权限

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by getActivity** [comment]
小伙子，我拒绝回答此问题，因为这个问题本质上跟权限请求框架没有任何关联，你就算用系统原生的 API 申请权限也肯定会遇到这个问题，我不会参与这类问题的排查，如果你能确认这个是框架的问题，并且提供证明，我可以协助定位和解决，但是从目前的情况来看，找不到有关框架的问题线索。

**Comment by pangli** [comment]
我在Redmi 6A上也遇到了同样的问题，使用`XXPermissions.isGranted(this, permissions)`检查READ_SMS权限是否申请一直返回false
