### ISSUE TITLE
混淆导致的问题 打包出错 

### ISSUE THREAD

**Issue by lichaohuilala** [getActivity/XXPermissions#25]
具体错误  ---->我找了好久 
混淆我也加了 。。    

Warning: com.hjq.permissions.PermissionUtils: can't find referenced method 'boolean canRequestPackageInstalls()' in library class android.content.pm.PackageManager

**Comment by lichaohuilala** [comment]
compile 'com.hjq:xxpermissions:5.5'
-keep class com.hjq.permissions.** {*;}

**Comment by getActivity** [comment]
从你提供的这些信息，我无法得出问题出在哪儿。我自己混淆是没有问题的。

**Comment by nealkafuly** [comment]
mmp，问题很明显呀，很好解决， class android.content.pm.PackageManager把系统的混淆放开
或者增肌 -keep android.content.**{*;}

**Comment by nealkafuly** [comment]
你规则写的太死了

**Comment by lichaohuilala** [comment]
我解决了  ，我之前的
compileSdkVersion =25   targetSdkVersion=“25”
改成    
 compileSdkVersion = 26   targetSdkVersion = "26"

**Comment by lichaohuilala** [comment]
总之感谢大佬 ！谢谢回复
