### ISSUE TITLE
怎么申请权限前加一个弹窗权限使用说明[Suggestion]:

### ISSUE THREAD

**Issue by githubzoujiayun** [getActivity/XXPermissions#252]
### What are the shortcomings you have noticed in the framework? [Required]

比如申请权限弹窗上加入说明：将申请访问您的麦克风权限，用于练习录制音频使用

### Has a similar suggestion been made in the issue list? [Required]

Not Selected

### Is the suggestion mentioned in the framework documentation? [Required]

Not Selected

### Did you consult the framework documentation but couldn't find a solution? [Required]

Not Selected

### How do you suggest improving it? [Optional]

比如申请权限弹窗上加入说明：将申请访问您的麦克风权限，用于练习录制音频使用

**Comment by getActivity** [comment]
小伙子，目前此 issue 打回，原因如下：

* 没有严格按照 issue 模板填写

请重新提交 issue，并且严格按照 issue 模板填写
