### ISSUE TITLE
[疑惑]：为什么在Gradle 7.0以下引入不了呢？7.0以上就可以

### ISSUE THREAD

**Issue by SuperKung** [getActivity/XXPermissions#253]
### 问题描述【必填】

studio版本是Giraffe | 2022.3.1 Patch 4，在jitpack.io前面加上www也不行。我把轮子哥的技术中台项目下载下来，原封不动点击运行，里面轮子哥自己的依赖库也是下载不下来，这是怎么回事捏？

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by getActivity** [comment]
小伙子，你换个网络环境或者手机热点试一下是否有此问题，我自己测试是没有问题的。

**Comment by payne1107** [comment]
我也遇到这个问题了，你咋解决的

**Comment by SuperKung** [comment]
> 我也遇到这个问题了，你咋解决的

好像是把jdk1.8改成了自带的11就好了。

**Comment by payne1107** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
