### ISSUE TITLE
[Question]: 发现一个bug: 

### ISSUE THREAD

**Issue by Amity927** [getActivity/XXPermissions#254]
### Question Description [Required]

先申请音频权限在申请视频+图片权限(设置页显示以获取， 但是判断还是未申请呢)

### Is the issue mentioned in the framework documentation? [Required]

Not Selected

### Did you consult the framework documentation but couldn't find a solution? [Required]

Not Selected

### Has a similar issue been reported in the issue list? [Required]

Not Selected

### Have you searched the issue list but couldn't find a solution? [Required]

Not Selected

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 没有严格按照 issue 模板填写问题

* 这个问题属于 bug，不能提疑问 issue 单，请提 bug issue 单

请重新提一个 issue 并纠正以上问题
