### ISSUE TITLE
【疑惑】关于定位权限请求的问题

### ISSUE THREAD

**Issue by LuckyCodeer** [getActivity/XXPermissions#255]
### 问题描述【必填】

定位权限：Permission.ACCESS_COARSE_LOCATION    Permission.ACCESS_FINE_LOCATION
看谷歌官网建议两个权限同时请求
问题：如果我单独只请求  Permission.ACCESS_FINE_LOCATION ，会有问题吗（目前自测没有崩溃），我们的框架会自动加上Permission.ACCESS_COARSE_LOCATION吗？

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by getActivity** [comment]
官方文档：[大致位置  |  Android 开发者  |  Android Developers](https://developer.android.google.cn/about/versions/12/approximate-location?hl=zh-cn)

**Comment by getActivity** [comment]
<img width="1129" alt="image" src="https://github.com/getActivity/XXPermissions/assets/28616817/596528cb-c4b4-4a5c-92f1-6d62041b6016">

**Comment by getActivity** [comment]
* 如果我单独只请求 Permission.ACCESS_FINE_LOCATION ，会有问题吗（目前自测没有崩溃）

> 目前没有发现问题，如果后续有出现问题，请及时反馈给我

* 我们的框架会自动加上Permission.ACCESS_COARSE_LOCATION吗？

> 不会，下次如果有这种问题，建议你直接搜源码，比我问来得快

<img width="1375" alt="image" src="https://github.com/getActivity/XXPermissions/assets/28616817/8c1f753e-8fda-48c7-81be-7e9eec5743e6">
