### ISSUE TITLE
[Bug]: 请求读写权限, 在android13上读写权限合并, 弹窗只弹一次, 被识别为部分拒绝了其中一个权限

### ISSUE THREAD

**Issue by manitozhang** [getActivity/XXPermissions#258]
### Framework Version [Required]

18.5

### Issue Description [Required]

```java
XXPermissions.with(fragment)
            .permission(Permission.Group.STORAGE)
            .request(new OnPermissionCallback() {

                @Override
                public void onGranted(@NonNull List<String> permissions, boolean allGranted) {
                }

                @Override
                public void onDenied(@NonNull List<String> permissions, boolean doNotAskAgain) {
                }
            });
```

传入一个权限组, 因为在小米手机上读写合并, 只弹出了一次弹窗, 就会走判断请求的和同意的权限列表长度不同, 被认为是其中一个拒绝了, 是否可以适配

### Steps to Reproduce [Required]

必现

### Is the Issue Reproducible? [Required]

Yes

### Project targetSdkVersion [Required]

30

### Device Information [Required]

Redmi Note 13 5G

### Android Version [Required]

13

### Issue Source Channel [Required]

自己遇到的

### Is it specific to certain device models? [Required]

是

### Does the latest version of the framework have this issue? [Required]

Yes

### Is the issue mentioned in the framework documentation? [Required]

No

### Did you consult the framework documentation but couldn't find a solution? [Required]

Yes

### Has a similar issue been reported in the issue list? [Required]

No

### Have you searched the issue list but couldn't find a solution? [Required]

Yes

### Can the issue be reproduced with a demo project? [Required]

Yes

**Comment by getActivity** [comment]
https://github.com/getActivity/XXPermissions/assets/28616817/1a973314-2305-422d-b72b-56c968bfdbb2

**Comment by getActivity** [comment]
![](https://github.com/getActivity/XXPermissions/assets/28616817/2a7cad43-e1f4-4e21-bf0d-ae89061b212c)

**Comment by getActivity** [comment]
@manitozhang 小伙子，根据你提供的复现步骤，我找到了对应型号的手机进行测试，另外用 vivo android 13 进行测试，均无法复现到该问题，请你确认给的复现步骤是否准确无误？如果是的话，请使用其他的 android 13 小米手机测试是否也会出现该问题？

**Comment by manitozhang** [comment]
![微信截图_20231228103518](https://github.com/getActivity/XXPermissions/assets/35214125/dd89162b-28db-4642-a6e5-67415e0e41bf)
昨天这里一直是判断allPermission为2, grantedPermissions为1, 应该是昨天搞错了, 不好意思, 今天没有再复现
