### ISSUE TITLE
[建议]：权限说明拦截器现在项目里面确实有,但还是不合规

### ISSUE THREAD

**Issue by clbDream** [getActivity/XXPermissions#260]
### 你觉得框架有什么不足之处？【必答】

也有人提过相关问题,但是并没有回复到主要问题点上,在华为应用市场,要求说明中需要包含使用目的，包括但不限于申请权限的名称、服务的具体功能、用途,类似这样,但是框架中的说明是一个固定格式的固定说明,在实际项目中,同一个权限的使用目的什么的可能在不同地方都是不同的,是否可以在这里拓展一个方法可以自定已下面的说明文案吗?或者提供一个相关解决思路
![251383181-51b7ffd7-b649-4eef-9405-0c2367fcd1ea](https://github.com/getActivity/XXPermissions/assets/28987014/9b8e1e3e-0e02-4ea3-8f34-e4feec4b44e6)

### issue 是否有人曾提过类似的建议？【必答】

是

### 框架文档是否提及了该问题【必答】

是

### 是否已经查阅框架文档但还未能解决的【必答】

是

### 你觉得该怎么去完善会比较好？【非必答】

是否可以在拦截器这里拓展一个方法可以自定义下面的说明文案,这样的话在每个地方都可以按照项目自己的实际用途进行说明,不设置的话就按照默认的说明进行展示

**Comment by clbDream** [comment]
虽然有这个弹窗说明,但是实际上在应用市场那边,这个并没有告知使用目的和用途,所以还是不合规的,经测试,在华为上面是无法通过的,其他应用市场审核不严,暂时还是准予通过,以后肯定也会加强审核
![image](https://github.com/getActivity/XXPermissions/assets/28987014/2e8163f1-0d99-48f2-80a9-be73214c1b47)

**Comment by clbDream** [comment]
如果设置自定义说明的话,应该就可以满足市场的要求了,就像下面这样
![JPRRYZIL346C}W6MU1CJ }I](https://github.com/getActivity/XXPermissions/assets/28987014/bc0e6fbb-e2ef-4d8c-aca0-2d598fa4dfb9)

**Comment by clbDream** [comment]
我这边这样处理了一下,暂时能满足应用市场的需求
![{ 55K` _~$W95()ZWUB@1}2](https://github.com/getActivity/XXPermissions/assets/28987014/e81f4d16-a92e-43c6-836d-89852aa61257)
![)B9`$0{$MVHX CX0M1DQ1IT](https://github.com/getActivity/XXPermissions/assets/28987014/7e9247ec-2333-4f40-a874-60a3627455d7)
![image](https://github.com/getActivity/XXPermissions/assets/28987014/84c0c234-e8e2-4d39-9b08-057a059f1cc8)

**Comment by getActivity** [comment]
小伙子，我理解权限说明的文案是要根据具体的业务场景而定的，框架目前给的只是一种示例，当然不能直接照抄照搬，当然你给的建议很好，我也会持续优化 Demo 中的案例。

**Comment by EspoirX** [comment]
提供一个方便的api操作比较好，另外提示框在底下，有些手机不细看都发现不了

**Comment by getActivity** [comment]
> 提供一个方便的api操作比较好，另外提示框在底下，有些手机不细看都发现不了

@EspoirX 小伙子，框架的权限说明提示框不是显示在屏幕上方？

![](https://github.com/getActivity/XXPermissions/assets/28616817/97a5cabc-1624-4158-9bca-42bd57c1e650)

**Comment by getActivity** [comment]
@clbDream 小伙子，针对你提的建议，我对权限说明文案进行了优化，你可以看一下具体的效果，有什么其他建议也可以提

![](https://github.com/getActivity/XXPermissions/assets/28616817/6673bb6f-c6a2-49f0-aaaf-970dd61b7782)

**Comment by lishide** [comment]
轮子哥，@EspoirX 这位说的“底下”是页面层次吧，被系统的权限弹窗蒙层挡上了。

**Comment by lishide** [comment]
> @clbDream 小伙子，针对你提的建议，我对权限说明文案进行了优化，你可以看一下具体的效果，有什么其他建议也可以提
> 
> ![](https://private-user-images.githubusercontent.com/28616817/296418231-6673bb6f-c6a2-49f0-aaaf-970dd61b7782.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNzIzMzUsIm5iZiI6MTcwNTM3MjAzNSwicGF0aCI6Ii8yODYxNjgxNy8yOTY0MTgyMzEtNjY3M2JiNmYtYzZhMi00OWYwLWFhYWYtOTcwZGQ2MWI3NzgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDAyMjcxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmODEwNjYxNjgxZjI2OTFkMDJlOWJjNzE0MWNmYWVmOWQxMGE3MzRjNzI4MWUxZGRiNzUzNzhiZmUxYWE3Y2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JgNf1P2NaQeeLM0JHppI-GCZOYcDpYSQHHeAvLZuyoQ)

这个什么时候上线

**Comment by getActivity** [comment]
> 轮子哥，@EspoirX 这位说的“底下”是页面层次吧，被系统的权限弹窗蒙层挡上了。

小伙子，那你想一下，如果权限说明弹窗展示在系统权限弹窗之上，先不论能不能实现，用户点击同意或者拒绝的时候，是点不了，又或者点了之后权限说明弹窗自动消失，这种效果就特别奇怪。

**Comment by getActivity** [comment]
> > @clbDream 小伙子，针对你提的建议，我对权限说明文案进行了优化，你可以看一下具体的效果，有什么其他建议也可以提
> > ![](https://private-user-images.githubusercontent.com/28616817/296418231-6673bb6f-c6a2-49f0-aaaf-970dd61b7782.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNzIzMzUsIm5iZiI6MTcwNTM3MjAzNSwicGF0aCI6Ii8yODYxNjgxNy8yOTY0MTgyMzEtNjY3M2JiNmYtYzZhMi00OWYwLWFhYWYtOTcwZGQ2MWI3NzgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDAyMjcxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmODEwNjYxNjgxZjI2OTFkMDJlOWJjNzE0MWNmYWVmOWQxMGE3MzRjNzI4MWUxZGRiNzUzNzhiZmUxYWE3Y2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JgNf1P2NaQeeLM0JHppI-GCZOYcDpYSQHHeAvLZuyoQ)
> 
> 这个什么时候上线

* 小伙子，没有那么快上线，你如果着急用可以先下载这块的代码。

[相关代码.zip](https://github.com/getActivity/XXPermissions/files/13944822/default.zip)

**Comment by lishide** [comment]
> > 轮子哥，@EspoirX 这位说的“底下”是页面层次吧，被系统的权限弹窗蒙层挡上了。
> 
> 小伙子，那你想一下，如果权限说明弹窗展示在系统权限弹窗之上，先不论能不能实现，用户点击同意或者拒绝的时候，是点不了，又或者点了之后权限说明弹窗自动消失，这种效果就特别奇怪。

嗯，是的（仅解释上面那个哥们的表述）

**Comment by lishide** [comment]
> > > @clbDream 小伙子，针对你提的建议，我对权限说明文案进行了优化，你可以看一下具体的效果，有什么其他建议也可以提
> > > ![](https://private-user-images.githubusercontent.com/28616817/296418231-6673bb6f-c6a2-49f0-aaaf-970dd61b7782.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNzIzMzUsIm5iZiI6MTcwNTM3MjAzNSwicGF0aCI6Ii8yODYxNjgxNy8yOTY0MTgyMzEtNjY3M2JiNmYtYzZhMi00OWYwLWFhYWYtOTcwZGQ2MWI3NzgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDAyMjcxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmODEwNjYxNjgxZjI2OTFkMDJlOWJjNzE0MWNmYWVmOWQxMGE3MzRjNzI4MWUxZGRiNzUzNzhiZmUxYWE3Y2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JgNf1P2NaQeeLM0JHppI-GCZOYcDpYSQHHeAvLZuyoQ)
> > 
> > 
> > 这个什么时候上线
> 
> * 小伙子，没有那么快上线，你如果着急用可以先下载这块的代码。
> 
> [相关代码.zip](https://github.com/getActivity/XXPermissions/files/13944822/default.zip)

感谢，不过还缺几个文件，期待轮子哥下次的更新，再跟进同步上去。

**Comment by getActivity** [comment]
@lishide 小伙子，代码已经更新上去了。
