### ISSUE TITLE
[建议]：国际化加台湾繁体，香港繁体等

### ISSUE THREAD

**Issue by xuexirong** [getActivity/XXPermissions#261]
### 你觉得框架有什么不足之处？【必答】

目前没有

### issue 是否有人曾提过类似的建议？【必答】

否

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

**Comment by getActivity** [comment]
小伙子，这两种繁体有什么区别呢？

**Comment by xuexirong** [comment]
@getActivity https://zhuanlan.zhihu.com/p/77914413  有些字不一样

**Comment by getActivity** [comment]
@xuexirong 小伙子，你这个问题是语种翻译的问题，和权限请求框架有啥联系？
