### ISSUE TITLE
[Bug]：华为审核需要同步进行弹框提示

### ISSUE THREAD

**Issue by xuexirong** [getActivity/XXPermissions#262]
### 框架版本【必填】

18.5

### 问题描述【必填】

![截屏2024-01-08 14 01 49](https://github.com/getActivity/XXPermissions/assets/13816024/93e32f41-83fb-45c3-95e8-56b1608d5c75)
目前你这个插件好像无法满足需求，IPermissionInterceptor需要再加个回调，用来判断是否弹出了系统的权限选择框。
launchPermissionRequest只能判断是否进行了请求权限，无法获悉是否真的弹出了系统选择框

### 复现步骤【必填】

无

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

30

### 出现问题的手机信息【必填】

小米12spro

### 出现问题的安卓版本【必填】

android14

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

所有

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

是

**Comment by getActivity** [comment]
@xuexirong 小伙子，你这个问题是被华为审核打回了呢？还是说看到华为的文档那么说心存疑惑来问而已？

**Comment by xuexirong** [comment]
@getActivity 被华为打回了，我也知道问题在哪，怎么解决，只是希望这个工具可以加上上面我说的方法，方便国内开发者使用。比如用户选择了禁止权限且不再提示，那下次再调用你这个工具时，系统不会弹权限选择框，需求上不会弹出权限说明。但是在你这里我应该把这个是否弹出自定义的权限说明写在哪呢？

**Comment by xuexirong** [comment]
@getActivity PictureSelector这个框架里面就加了这个功能，可以参考一下，就是拦截器里加一个，弹出权限描述的方法

**Comment by getActivity** [comment]
小伙子，你的意思是 Demo 中权限说明弹窗使用了延迟弹出，导致你过不了华为应用商店的审核对吗？

**Comment by xuexirong** [comment]
@getActivity 我之前没看到你这个demo，你这个应该也没问题，能不能把这个封装成一个单独的回调，就是延迟300毫秒检测是否需要弹框这个，我们用的时候只在里面加自己的权限说明弹框

**Comment by xuexirong** [comment]
@getActivity 准确的说我提的issue是个优化需求，不是个bug

**Comment by getActivity** [comment]
@xuexirong 小伙子，这个实现已经写在了 PermissionInterceptor 类中，你要的话可以直接抄代码过去。

**Comment by getActivity** [comment]
@xuexirong 小伙子，关于你提这个建议已经采纳，框架内部提供了一个权限说明的接口，并且会判断某项权限是否需要发起申请，是的才会回调该接口的方法，如果不是则不会回调该接口的方法，你可以通过实现这个接口来显示权限说明弹窗，目前已经在 [23.0](https://github.com/getActivity/XXPermissions/releases/tag/23.0) 版本上面实现，你可以留意一下，欢迎下载 Demo Apk 体验具体的效果。
