### ISSUE TITLE
google 上架使用MANAGE_EXTERNAL_STORAGE问题？

### ISSUE THREAD

**Issue by penglei60** [getActivity/XXPermissions#264]
### 问题描述【必填】

使用XXPermissions:18.5，使用android.permission.MANAGE_EXTERNAL_STORAGE权限后，获取手机内存文件，使用没有问题。在上架google时，由于这个权限拒审，有没有可解决代替的方案？

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by getActivity** [comment]
无，只能适配分区存储特性。

**Comment by penglei60** [comment]
好的，谢谢了。




PengLei
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "getActivity/XXPermissions"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月15日(星期一) 下午2:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [getActivity/XXPermissions] google 上架使用MANAGE_EXTERNAL_STORAGE问题？ (Issue #264)





 
无，只能适配分区存储特性。
