### ISSUE TITLE
[疑惑]：Android9存储到外部提示Permission denied

### ISSUE THREAD

**Issue by ly469097645** [getActivity/XXPermissions#267]
### 问题描述【必填】

大佬你好，我遇到了如下的问题，我的targetSdk版本为33，在申请权限时我用的是Manifest.permission.READ_MEDIA_IMAGES这个权限，在打开APP的时候申请的时候我执行了拒绝的操作，而后在下载图片的时候我执行了同意的操作，此时我在onGranted中开始了保存图片到 ---Environment.getExternalStorageDirectory().absolutePath + File.separator 文件夹中，会一直提示我Permission denied，但是不管如何申请权限都是通过的
当我重启APP之后，再进行保存的操作则能正常保存
所以是因为什么导致的，我拒绝之后再同意权限会一直报错Permission denied，必须重启之后才能正常保存
烦请大佬指导下
![image](https://github.com/getActivity/XXPermissions/assets/12133597/4dc2e177-7b60-4fd9-8bdd-0ec400b5edba)
![image](https://github.com/getActivity/XXPermissions/assets/12133597/ef4b77db-8902-48ba-87e8-60e08ec92477)
![image](https://github.com/getActivity/XXPermissions/assets/12133597/78474c07-3573-4051-8153-418c15808da0)
![image](https://github.com/getActivity/XXPermissions/assets/12133597/708f5263-5800-4120-bcaf-c66320f6a2b2)

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 这个问题属于 bug，不能提疑问 issue 单，请提 bug issue 单

请重新提一个 issue 并纠正以上问题
