### ISSUE TITLE
[Bug]：Android10以下的机型申请了Manifest.permission.READ_MEDIA_IMAGES后无法保存到外部存储

### ISSUE THREAD

**Issue by ly469097645** [getActivity/XXPermissions#268]
### 框架版本【必填】

com.github.getActivity:XXPermissions:18.6

### 问题描述【必填】

targetSdk版本为33，在Android10以下申请Manifest.permission.READ_MEDIA_IMAGES这个权限，第一次拒绝权限，第二次通过权限后执行保存图片到外部存储路径，此时申请权限是通过的，但是保存的时候提示Permission denied
在demo中的表现是，权限通过但是永远提示Permission Denied
在我项目中的表现是，权限通过但是提示Permission Denied，重启后可以正常保存

### 复现步骤【必填】

1、申请Manifest.permission.READ_MEDIA_IMAGES权限，拒绝
2、申请Manifest.permission.READ_MEDIA_IMAGES权限通过，在Grant中执行保存图片到/storage/emulated/0/Test/test.jpg中，提示Permission Denied
3、重启APP后，无需重新申请权限，保存成功（Demo中重启后也还是无法保存）

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

33

### 出现问题的手机信息【必填】

sansung SM-A505X

### 出现问题的安卓版本【必填】

Android9

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

android10以下的机型都会出现

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

是

**Comment by pp83223828** [comment]
所以是怎么解决的呢，希望给出思路

**Comment by getActivity** [comment]
@pp83223828 小伙子，`READ_MEDIA_IMAGES` 权限是用于读取图片媒体文件的，你申请后写入文件到外部存储卡，肯定是有问题的，你需要申请写入到外部存储卡相关的权限才行。

**Comment by JackyKeke** [comment]
Manifest.permission.READ_MEDIA_IMAGES,
Manifest.permission.READ_MEDIA_VIDEO,
Manifest.permission.READ_MEDIA_AUDIO,
不是真正等于
Manifest.permission.WRITE_EXTERNAL_STORAGE,
Manifest.permission.READ_EXTERNAL_STORAGE
的啊？

怪不得我大于等于33编译在api11 api12的手机运行时，用系统api检查旧的储存权限和信新的储存权限都是denied
一直想不明白

**Comment by impeterwayne** [comment]
is anyone solve this? this really annoying
