### ISSUE TITLE
[建议]：希望大佬适配下OPPO新出的“应用权限受阻跳转优化适配”

### ISSUE THREAD

**Issue by qq549631030** [getActivity/XXPermissions#270]
### 你觉得框架有什么不足之处？【必答】

OPPO新出了一个[应用权限受阻跳转优化适配](https://open.oppomobile.com/new/developmentDoc/info?id=12983)，感觉非常的人性化，希望大佬有空适配下。

### issue 是否有人曾提过类似的建议？【必答】

否

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

**Comment by getActivity** [comment]
[XXPermissions-18.6.aar.zip](https://github.com/getActivity/XXPermissions/files/14137241/XXPermissions-18.6.aar.zip)

**Comment by getActivity** [comment]
@qq549631030 小伙子，功能加上了，你可以测试一下，另外不保证这个功能会在后面的版本会存在，具体会根据实际情况而定。

**Comment by getActivity** [comment]
<img width="641" alt="image" src="https://github.com/getActivity/XXPermissions/assets/28616817/577444b6-14e1-47ee-9fc1-a04bd36ad91e">

<img width="642" alt="image" src="https://github.com/getActivity/XXPermissions/assets/28616817/70272d13-92a3-4339-9b77-c52ed1a5dad0">

这个功能我在 OPPO 云测上面跑过，做得还是有 Bug，官方说的跳转页面后滚动高亮，实际测试我只看到了滚动，但是没有看到高亮，另外我认为这个功能做得还是不够好，如果真的想人性化，建议直接跳转到对应权限设置页面，而不是还是停留在权限列表，还需要用户手动去点对应的权限条目才能进入对应的权限开关设置。
