### ISSUE TITLE
[疑惑]：权限拒绝并不再提示的问题

### ISSUE THREAD

**Issue by LinHuiG** [getActivity/XXPermissions#271]
### 问题描述【必填】

存储权限无法开启，会报错：“被永久拒绝授权，请手动授予相关权限！” 但是手动授权的时候在权限下的应用列表里找不到它
手机型号：iqoo12

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

是

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 这个问题属于 bug，不能提疑问 issue 单，请提 bug issue 单

请重新提一个 issue 并纠正以上问题
