### ISSUE TITLE
[疑惑]：对于一个兼容问题，不知道算bug还是算正常，所以提出一点疑问

### ISSUE THREAD

**Issue by mobilewhj** [getActivity/XXPermissions#275]
### 问题描述【必填】

今天做系统相机录像功能demo的时候，做了如下操作：

> 
>         if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
>             XXPermissions.with(this)
>                 .permission(Permission.READ_MEDIA_VIDEO)
>                 .request { _, allGranted ->
>                     if (allGranted){
>                         // 创建录制视频的Intent
>                         val intent = Intent(MediaStore.ACTION_VIDEO_CAPTURE)
>                         // 指定视频最大录制时长，单位为秒
>                         intent.putExtra(MediaStore.EXTRA_DURATION_LIMIT, 5)
>                         mVideoCameraLauncher.launch(intent)
>                     }
>                 }
>         }else{
>             XXPermissions.with(this)
>                 .unchecked()
>                 .permission(Permission.WRITE_EXTERNAL_STORAGE)
>                 .permission(Permission.READ_EXTERNAL_STORAGE)
>                 .request { _, allGranted ->
>                     if (allGranted){
>                         // 创建录制视频的Intent
>                         val intent = Intent(MediaStore.ACTION_VIDEO_CAPTURE)
>                         // 指定视频最大录制时长，单位为秒
>                         intent.putExtra(MediaStore.EXTRA_DURATION_LIMIT, 5)
>                         mVideoCameraLauncher.launch(intent)
>                     }
>                 }
>         }
> 

我只能使用uncheked()绕过框架限制才能不会崩溃。我尝试了几种写法：

>         if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
>             XXPermissions.with(this)
>                 .permission(Permission.READ_MEDIA_VIDEO)
>                 .request { _, allGranted ->
>                     if (allGranted){
>                         // 创建录制视频的Intent
>                         val intent = Intent(MediaStore.ACTION_VIDEO_CAPTURE)
>                         // 指定视频最大录制时长，单位为秒
>                         intent.putExtra(MediaStore.EXTRA_DURATION_LIMIT, 5)
>                         mVideoCameraLauncher.launch(intent)
>                     }
>                 }
>         }else{
>             XXPermissions.with(this)
>                 .permission(Permission.MANAGE_EXTERNAL_STORAGE)
>                 .request { _, allGranted ->
>                     if (allGranted){
>                         // 创建录制视频的Intent
>                         val intent = Intent(MediaStore.ACTION_VIDEO_CAPTURE)
>                         // 指定视频最大录制时长，单位为秒
>                         intent.putExtra(MediaStore.EXTRA_DURATION_LIMIT, 5)
>                         mVideoCameraLauncher.launch(intent)
>                     }
>                 }
>         }

这种会提示我 java.lang.IllegalStateException: Please register the android:requestLegacyExternalStorage="true" attribute in the AndroidManifest.xml file, otherwise it will cause incompatibility with the old version。
 

> XXPermissions.with(this)
>                 .permission(Permission.WRITE_EXTERNAL_STORAGE)
>                 .permission(Permission.READ_EXTERNAL_STORAGE)
>                 .request { _, allGranted ->
>                     if (allGranted){
>                         // 创建录制视频的Intent
>                         val intent = Intent(MediaStore.ACTION_VIDEO_CAPTURE)
>                         // 指定视频最大录制时长，单位为秒
>                         intent.putExtra(MediaStore.EXTRA_DURATION_LIMIT, 5)
>                         mVideoCameraLauncher.launch(intent)
>                     }
>                 }

这种会提示我 java.lang.IllegalArgumentException: When targetSdkVersion >= 33 should use android.permission.READ_MEDIA_IMAGES, android.permission.READ_MEDIA_VIDEO, android.permission.READ_MEDIA_AUDIO instead of android.permission.READ_EXTERNAL_STORAGE。
如果不做版本判断， 

> 
> XXPermissions.with(this)
>                 .permission(Permission.READ_MEDIA_VIDEO)
>                 .request { _, allGranted ->
>                     if (allGranted){
>                         // 创建录制视频的Intent
>                         val intent = Intent(MediaStore.ACTION_VIDEO_CAPTURE)
>                         // 指定视频最大录制时长，单位为秒
>                         intent.putExtra(MediaStore.EXTRA_DURATION_LIMIT, 5)
>                         mVideoCameraLauncher.launch(intent)
>                     }
>                 } 
> 

只这么处理的话，会出现 java.io.FileNotFoundException: /storage/emulated/0/Movies/MyMovies/19866.mp4 (No such file or directory)没有权限的错误。我不知道怎么写是正确的，所以想咨询一下，对于读写的兼容应该如何处理呢。
下面是我xml中权限部分的声明：
    <queries>
        <package android:name="com.tencent.mm" />

        <intent>
            <action android:name="com.getui.sdk.action" />
        </intent>
        <intent>
            <action android:name="android.intent.action.PICK" />

            <data android:mimeType="*/*" />
        </intent>
        <intent>
            <action android:name="android.media.action.IMAGE_CAPTURE" />
        </intent>
        <intent>
            <action android:name="android.media.action.VIDEO_CAPTURE" />
        </intent>
    </queries>
    
    
    <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission
        android:name="android.permission.ACCESS_FINE_LOCATION"
        android:maxSdkVersion="32" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.ACTIVITY_RECOGNITION" />
    <uses-permission android:name="android.permission.BODY_SENSORS" />
    <uses-permission android:name="android.permission.BODY_SENSORS_BACKGROUND" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.POST_NOTIFICATIONS" />
    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
    <uses-permission android:name="android.permission.READ_MEDIA_AUDIO" />
    <uses-permission android:name="android.permission.READ_MEDIA_IMAGES" />
    <uses-permission android:name="android.permission.READ_MEDIA_VIDEO" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES" />
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:ignore="ScopedStorage" />

    <uses-feature
        android:name="android.hardware.camera"
        android:required="true" />

我的版本：
compileSdk = 33， minSdk = 24， targetSdk = 33
androidstudio版本：
Android Studio Hedgehog | 2023.1.1 Patch 2
手机型号：
vivo Y93 V1818T android版本为8.1.0

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by getActivity** [comment]
[XXPermissions-18.63.aar.zip](https://github.com/getActivity/XXPermissions/files/14903310/XXPermissions-18.63.aar.zip)

**Comment by getActivity** [comment]
<img width="1920" alt="image" src="https://github.com/getActivity/XXPermissions/assets/28616817/8c103458-d4af-4409-a521-f50cec00878b">

**Comment by getActivity** [comment]
@mobilewhj 小伙子，远程依赖已经更新，你可以换成远程依赖再试一下。

**Comment by mobilewhj** [comment]
顺便问一下RECORD_AUDIO这个权限要做类似的WRITE_EXTERNAL_STORAGE操作吗？当前加上是报错的。

**Comment by getActivity** [comment]
@mobilewhj  申请`RECORD_AUDIO` 权限为什么要带上 `WRITE_EXTERNAL_STORAGE` 权限？这两者没有关系吧？

**Comment by getActivity** [comment]
你说的类似是什么意思？麦克风本身只有读取权限，没有提供写入权限。

<img width="713" alt="image" src="https://github.com/getActivity/XXPermissions/assets/28616817/6df305a9-053d-46e9-a14a-1e4cb9f31695">

**Comment by mobilewhj** [comment]
我想的是录制音频文件写入磁盘，对于低版本手机需要好WRITE_EXTERNAL_STORAGE，可能我想的多了。
