### ISSUE TITLE
[Bug]：安卓TV 11 上 申请MANAGE_EXTERNAL_STORAGE权限无反应

### ISSUE THREAD

**Issue by 360060316** [getActivity/XXPermissions#276]
### 框架版本【必填】

18.62

### 问题描述【必填】

安卓TV 11 上 申请MANAGE_EXTERNAL_STORAGE权限无反应

### 复现步骤【必填】

安卓TV 11 上 申请MANAGE_EXTERNAL_STORAGE权限无反应

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

34

### 出现问题的手机信息【必填】

安卓TV

### 出现问题的安卓版本【必填】

Android 11

### 问题信息的来源渠道【必填】

用户反馈

### 是部分机型还是所有机型都会出现【必答】

Android 11

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

是

**Comment by getActivity** [comment]
<img width="1342" alt="image" src="https://github.com/getActivity/XXPermissions/assets/28616817/872ba638-4177-4b97-87c1-70e03dcded5d">

**Comment by getActivity** [comment]
https://github.com/getActivity/XXPermissions/assets/28616817/ad280cfc-1678-4b33-b0c4-8f2af0a7a3d0

**Comment by getActivity** [comment]
小伙子，我用 Android 11 的 TV 模拟器试过了，没有问题，你可以看一下上面的视频。

**Comment by getActivity** [comment]
小伙子，我看到你有 Android TV 的设备，你可以拿自己的 TV 设备 debug 一下 Github Demo 工程代码，然后告诉我是哪句代码有问题，我来做处理。

**Comment by getActivity** [comment]
<img width="1342" alt="image" src="https://github.com/getActivity/XXPermissions/assets/28616817/19562fdd-c251-41cb-ab25-d1232f66f5e8">

**Comment by getActivity** [comment]
<img width="1354" alt="image" src="https://github.com/getActivity/XXPermissions/assets/28616817/622816ed-2e40-42e3-99e7-6b85b13e034c">
