### ISSUE TITLE
[Question]: 阿里云这种权限申请是怎么做到的

### ISSUE THREAD

**Issue by Sidnio** [getActivity/XXPermissions#277]
### Question Description [Required]

![Screenshot_2024-04-08-20-55-09-435_com lbe security miui](https://github.com/getActivity/XXPermissions/assets/33193340/11dac7e0-8e3d-4535-a293-30e11af5ea6a)

### Is the issue mentioned in the framework documentation? [Required]

No

### Did you consult the framework documentation but couldn't find a solution? [Required]

Yes

### Has a similar issue been reported in the issue list? [Required]

No

### Have you searched the issue list but couldn't find a solution? [Required]

Yes

**Comment by getActivity** [comment]
小伙子，这个是你的个人使用问题，并非框架的问题，建议你自行解决，可以考虑用 jadx 对阿里云 app 进行反编译。
