### ISSUE TITLE
权限检查问题，全部都允许了，还是走nopermission

### ISSUE THREAD

**Issue by unengchen** [getActivity/XXPermissions#28]
是否永久拒绝了某个权限===true
LauncherActivity: android.permission.FOREGROUND_SERVICE
LauncherActivity: android.permission.CAPTURE_VIDEO_OUTPUT
是否有全部权限===false

在nopermission中打印出来，是这两个权限缺少了。

**Comment by getActivity** [comment]
这两个权限不属于危险权限

**Comment by unengchen** [comment]
不属于危险权限，自动检测的时候，显示这两个权限未授权。我也觉得很奇怪，更奇怪的是我看了清单文件，我根本没有添加android.permission.CAPTURE_VIDEO_OUTPUT，但是却有这个打印出来，我用的是夜神模拟器，是否是夜神的问题

**Comment by getActivity** [comment]
试一下真机有没有问题
