### ISSUE TITLE
[疑惑]：获取短信权限没有弹窗

### ISSUE THREAD

**Issue by ka1244151821** [getActivity/XXPermissions#282]
### 问题描述【必填】

获取短信权限没有弹窗   使用的是红米手机

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

否

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by pangli** [comment]
解决了吗？怎么处理的？ @ka1244151821
