### ISSUE TITLE
[Bug]: 去掉已授权的缓存

### ISSUE THREAD

**Issue by liupeng176** [getActivity/XXPermissions#283]
### Framework Version [Required]

14.0

### Issue Description [Required]

一加11,安卓14，Color Os 14.0正式版本  型号  phb110
在app授权READ_MEDIA_VIDEO和READ_MEDIA_IMAGES时候，用户全部允许,这个时候是正常的,然后用户在系统权限中，把照片和视频权限改为每次都询问,此时由于XXPermissions.java第206行中判断已经授权过,所以直接回调了成功,导致得到错误的权限结果,这里建议去掉缓存,每次都请求最新的。
 `  if (PermissionApi.isGrantedPermissions(context, permissions)) {
            // 证明这些权限已经全部授予过，直接回调成功
            if (callback != null) {
                interceptor.grantedPermissionRequest(activity, permissions, permissions, true, callback);
                interceptor.finishPermissionRequest(activity, permissions, true, callback);
            }
            return;
        }`

### Steps to Reproduce [Required]

同上

### Is the Issue Reproducible? [Required]

Yes

### Project targetSdkVersion [Required]

33

### Device Information [Required]

phb110

### Android Version [Required]

14

### Is it specific to certain device models? [Required]

phb110

### Does the latest version of the framework have this issue? [Required]

Not Selected

### Is the issue mentioned in the framework documentation? [Required]

No

### Did you consult the framework documentation but couldn't find a solution? [Required]

No

### Has a similar issue been reported in the issue list? [Required]

No

### Have you searched the issue list but couldn't find a solution? [Required]

No

### Can the issue be reproduced with a demo project? [Required]

No

**Comment by liupeng176** [comment]
修复方案，去掉这段代码.直接不检测 每次都申请就可

**Comment by getActivity** [comment]
小伙子，目前此 issue 打回，原因如下：

* 没有严格按照 issue 模板填写

请重新提交 issue，并且严格按照 issue 模板填写

**Comment by TOPWN** [comment]
> ### Framework Version [Required]
> 14.0
> 
> ### Issue Description [Required]
> 一加11,安卓14，Color Os 14.0正式版本 型号 phb110 在app授权READ_MEDIA_VIDEO和READ_MEDIA_IMAGES时候，用户全部允许,这个时候是正常的,然后用户在系统权限中，把照片和视频权限改为每次都询问,此时由于XXPermissions.java第206行中判断已经授权过,所以直接回调了成功,导致得到错误的权限结果,这里建议去掉缓存,每次都请求最新的。 ` if (PermissionApi.isGrantedPermissions(context, permissions)) { // 证明这些权限已经全部授予过，直接回调成功 if (callback != null) { interceptor.grantedPermissionRequest(activity, permissions, permissions, true, callback); interceptor.finishPermissionRequest(activity, permissions, true, callback); } return; }`
> 
> ### Steps to Reproduce [Required]
> 同上
> 
> ### Is the Issue Reproducible? [Required]
> Yes
> 
> ### Project targetSdkVersion [Required]
> 33
> 
> ### Device Information [Required]
> phb110
> 
> ### Android Version [Required]
> 14
> 
> ### Issue Source Channel [Required]
> _No response_
> 
> ### Is it specific to certain device models? [Required]
> phb110
> 
> ### Does the latest version of the framework have this issue? [Required]
> Not Selected
> 
> ### Is the issue mentioned in the framework documentation? [Required]
> No
> 
> ### Did you consult the framework documentation but couldn't find a solution? [Required]
> No
> 
> ### Has a similar issue been reported in the issue list? [Required]
> No
> 
> ### Have you searched the issue list but couldn't find a solution? [Required]
> No
> 
> ### Can the issue be reproduced with a demo project? [Required]
> No
> 
> ### Provide Error Stack Trace
> _No response_
> 
> ### Provide Screenshots or Videos
> _No response_
> 
> ### Provide a Solution
> _No response_

Android14（三星S24）遇到同样的问题，在app授权READ_MEDIA_VIDEO和READ_MEDIA_IMAGES时候，用户全部允许,这个时候是正常的,然后用户在系统权限中，把照片和视频权限改为每次都询问, 直接回调了成功
