### ISSUE TITLE
[疑惑]：已经适配了分区分出但是总是报错呢

### ISSUE THREAD

**Issue by liguangze** [getActivity/XXPermissions#286]
### 问题描述【必填】

The storage permission application is abnormal. If you have adapted the scope storage, please register the <meta-data android:name="ScopedStorage" android:value="true" /> attribute in the AndroidManifest.xml file. If there is no adaptation scope storage, please use android.permission.MANAGE_EXTERNAL_STORAGE to apply for permission 

报这个错，但是我已经AndroidManifest.xml里面设置了android:name="ScopedStorage" android:value="true" 

申请权限的是时候
       XXPermissions.with(context)
                    // 不适配 Android 11 可以这样写
                    .permission(Permission.Group.STORAGE)
                    .request(new OnPermissionCallback() {

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by getActivity** [comment]
<img width="1494" alt="image" src="https://github.com/getActivity/XXPermissions/assets/28616817/66c8f508-01f0-49b4-8bd7-a6081af396b1">

**Comment by getActivity** [comment]
@liguangze 你 debug 一下这块代码，看看是哪个判断条件触发到了？

**Comment by liguangze** [comment]
感谢开源，好像是设备的问题，写入的代码一直没有生效，把设备系统升级了一下，现在没有问题，感谢
