### ISSUE TITLE
[Bug]：

### ISSUE THREAD

**Issue by linqipeng** [getActivity/XXPermissions#287]
### 框架版本【必填】

18.63

### 问题描述【必填】

权限申请点击系统弹窗外面的区域，系统弹窗被关闭后会显示去系统设置里面授权的弹窗，

期望：关闭后就正常关闭，用户需要的时候再次申请就好了，去系统设置授权的这个弹窗只有在勾选不再询问后再显示

### 复现步骤【必填】

红米手机  必现

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

31

### 出现问题的手机信息【必填】

 红米

### 出现问题的安卓版本【必填】

33

### 是部分机型还是所有机型都会出现【必答】

 未知

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

否

### 是否可以通过 Demo 来复现该问题【必答】

是

**Comment by getActivity** [comment]
小伙子，目前此 issue 打回，原因如下：

* 没有严格按照 issue 模板填写

请重新提交 issue，并且严格按照 issue 模板填写

**Comment by getActivity** [comment]
<img width="396" alt="image" src="https://github.com/getActivity/XXPermissions/assets/28616817/26a47a58-0203-41c9-b99e-011134df7b91">

你确定这个问题没有人提过？
