### ISSUE TITLE
[疑惑]：您好，我在权限清单已经填写了MANAGE_EXTERNAL_STORAGE权限，为什么申请的时候还是会报错提示没有在清单文件声明权限呢？

### ISSUE THREAD

**Issue by Lsy1992** [getActivity/XXPermissions#291]
### 问题描述【必填】

```
 java.lang.IllegalStateException: Please register permissions in the 
AndroidManifest.xml file <uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE" />
at com.hjq.permissions.PermissionChecker.checkManifestPermission(PermissionChecker.java:653)
at com.hjq.permissions.PermissionChecker.checkManifestPermission(PermissionChecker.java:627)
at com.hjq.permissions.PermissionChecker.checkManifestPermissions(PermissionChecker.java:542)
at com.hjq.permissions.XXPermissions.request(XXPermissions.java:200)
```

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by getActivity** [comment]
这个异常是框架给你抛的，具体是什么问题，异常信息已经写得很明白了，就是没有在清单文件中注册这个权限，如果你认为自己有注册，你可以将代码工程打包成一个 apk，然后将 apk 文件拖到 Studio 反编译看一下清单文件是否有注册这个权限。

**Comment by Lsy1992** [comment]
确实清单文件有这个权限，框架还是崩了

**Comment by getActivity** [comment]
@Lsy1992 你是怎么看到有的？直接看工程里面的清单文件还是反编译看的清单文件？

**Comment by Lsy1992** [comment]
.unchecked() 开启这个就正常了，也能申请权限了。。。

**Comment by getActivity** [comment]
@Lsy1992 小伙子，你的回答确定是我问的问题？

**Comment by getActivity** [comment]
长时间没有响应，自动关闭此 issue。

**Comment by yangyueyue** [comment]
我也遇到了这个问题。已经在清单里面注册了 <uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE" /> 但是报错还是提示

**Comment by getActivity** [comment]
> 我也遇到了这个问题。已经在清单里面注册了 <uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE" /> 但是报错还是提示

反编译 apk 看一下清单文件看看权限有没有注册

**Comment by yangyueyue** [comment]
感谢开源者。.apk里确实没有。被三方sdk移除了
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"
        tools:node="replace"/>
加上这句就正常了
