### ISSUE TITLE
[建议]：特殊权限和危险权限同时申请时，框架先申请特殊权限，后申请危险权限。希望能支持修改，或者按照添加顺序申请。

### ISSUE THREAD

**Issue by womarklee** [getActivity/XXPermissions#292]
### 你觉得框架有什么不足之处？【必答】

比如同时申请通知权限和查看应用使用情况权限，期望是先申请通知权限，再申请应用使用情况权限。

### issue 是否有人曾提过类似的建议？【必答】

否

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

**Comment by getActivity** [comment]
小伙子，你这个建议改造成本有点大，并且会增加性能开销，如果要这么做的话，代码改造工作量是其次的，每申请一个权限就要添加一个透明的 Fragment 进来，这个是不能解决的问题，考虑这个需求不是很常见，建议你选择分开多次调用权限框架来实现这一需求。

**Comment by getActivity** [comment]
<img width="963" alt="image" src="https://github.com/getActivity/XXPermissions/assets/28616817/cd19384e-b79c-41a1-932b-07ca3c036264">

至于你说的另外一个问题，不同特殊权限申请顺序的问题，先申请通知权限，再申请应用使用情况权限，我测试过了，会先显示应用使用情况权限设置界面，再显示通知权限设置界面，造成这个问题的原因是，框架确实是按照顺序跳转到对应权限的设置界面，但是由于新的 Activity 会覆盖旧的 Activity，所以你看到的顺序是反着来的，解决这个问题也很简单，你把权限的添加顺序反着来，当然这个是一个临时方案，在下一个版本中，我会优化此问题。

**Comment by getActivity** [comment]
[XXPermissions-18.65.aar.zip](https://github.com/getActivity/XXPermissions/files/15478191/XXPermissions-18.65.aar.zip)

我目前已经做了修改，但是未发布到远程依赖，或者你可以下载上面的 aar 包做为替换进行测试

**Comment by womarklee** [comment]
仍然是先申请 应用情况使用权限，新aar也试过，写的顺序也调整过。

![image](https://github.com/getActivity/XXPermissions/assets/27982416/5b1fba36-c8c0-40a0-b4c8-3b5bafd77298)

**Comment by getActivity** [comment]
小伙子，你说的是两个问题，第一个问题是危险权限和特殊权限申请顺序的问题，第二个问题是不同特殊权限申请顺序的问题，我分别回答了，你回去看清楚。

**Comment by getActivity** [comment]
@woomartin 小伙子，关于你说的按照外层传入的权限顺序来申请权限这个建议，目前已经在 [23.0](https://github.com/getActivity/XXPermissions/releases/tag/23.0) 版本上面实现，你可以留意一下，欢迎下载 Demo Apk 体验具体的效果。
