### ISSUE TITLE
[疑惑]：

### ISSUE THREAD

**Issue by liguangze** [getActivity/XXPermissions#293]
### 问题描述【必填】

版本16.3，之前都用着没问题，今天突然遇到这个，获取权限的时候报错
The AndroidManifest.xml file <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" android:maxSdkVersion="32" /> does not meet the requirements, please delete the android:maxSdkVersion="32" attribute

我检查了下代码，并没有这个maxSdkVersion="32"

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by liguangze** [comment]
java.lang.IllegalArgumentException: The AndroidManifest.xml file <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" android:maxSdkVersion="32" /> does not meet the requirements, please delete the android:maxSdkVersion="32" attribute


这个是全部的错误信息，但是我在AndroidManifest.xml并没有设置android:maxSdkVersion="32"，我全局搜索都没有这个

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 这个问题属于 bug，不能提疑问 issue 单，请提 bug issue 单

请重新提一个 issue 并纠正以上问题
