### ISSUE TITLE
[Bug]：提示我删除maxSdkVersion="32"，但是全局都没有搜索到这个

### ISSUE THREAD

**Issue by liguangze** [getActivity/XXPermissions#294]
### 框架版本【必填】

16.6

### 问题描述【必填】

The AndroidManifest.xml file <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" android:maxSdkVersion="32" /> does not meet the requirements, please delete the android:maxSdkVersion="32" attribute

这个是全部的错误信息，但是我在AndroidManifest.xml并没有设置android:maxSdkVersion="32"，我全局搜索都没有这个maxSdkVersion

### 复现步骤【必填】

下载获取文件的时候，获取存储权限
 if (!XXPermissions.isGranted(ClassDetailVideoActivity.this, Permission.Group.STORAGE)) {
                            XXPermissions.with(ClassDetailVideoActivity.this)
                                    // 不适配 Android 11 可以这样写
                                    //.permission(Permission.Group.STORAGE)
                         
                                    .permission(Permission.Group.STORAGE)

这个代码就回去报上面的错误

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

30

### 出现问题的手机信息【必填】

华为

### 出现问题的安卓版本【必填】

8.0

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

华为手机必现

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

是

### 是否已经查阅框架文档但还未能解决的【必答】

否

### issue 列表中是否有人曾提过类似的问题【必答】

是

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

否

### 提供报错堆栈

```text
The AndroidManifest.xml file <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" android:maxSdkVersion="32" /> does not meet the requirements, please delete the android:maxSdkVersion="32" attribute
```

### 提供截图或视频

无

### 提供解决方案

无

**Comment by liguangze** [comment]
在清单文件中静态注册权限的时候，不要带上 maxSdkVersion 属性，这样就不会触发框架的检测异常

在权限申请的时候，调用 .unchecked() 方法，表示不会进行任何权限检查，这样就不会触发框架的检测异常

解决办法是这两个，可我清单文件中静态注册权限的时候，根本没有带上 maxSdkVersion 属性。为什么提示我这个呢，
而且之前一直在用，都没有问题，就今天开始报错了

**Comment by getActivity** [comment]
你反编译 apk 看一下 `AndroidManifest.xml` 是否有加 `maxSdkVersion` 属性？

**Comment by liguangze** [comment]
![111](https://github.com/getActivity/XXPermissions/assets/10549682/9b31acc3-15d7-4386-8d30-d4d61a8c2238)
反编译之后的结果，并没有maxSdkVersion这个属性呢

**Comment by getActivity** [comment]
<img width="359" alt="image" src="https://github.com/getActivity/XXPermissions/assets/28616817/6afa0807-533a-448d-8cf6-3e0878a6264e">

**Comment by getActivity** [comment]
你测试过了最新版本也有这个问题？

**Comment by liguangze** [comment]
是了一下，新版本也是不行，但是我打成正式包没有问题，我运行正式包就会有这个问题，混淆的原因？

**Comment by getActivity** [comment]
> 是了一下，新版本也是不行，但是我打成正式包没有问题，我运行正式包就会有这个问题，混淆的原因？

这是因为检测机制只在 Debug 包下生效，Release 包下不会生效。

**Comment by getActivity** [comment]
@liguangze 你把项目的框架升级到最新版本，然后打一个 apk 上传到这里，并告知 App 上面的复现步骤，我这边来复现一下问题。

**Comment by liguangze** [comment]
感谢开源，不纠结这个问题了，添加这个方法 .unchecked() 方法可以解决
