### ISSUE TITLE
[Bug]：Android14权限适配有问题

### ISSUE THREAD

**Issue by TOPWN** [getActivity/XXPermissions#296]
### 框架版本【必填】

Android14

### 问题描述【必填】

三星S24, 安卓14
在app授权READ_MEDIA_VIDEO和READ_MEDIA_IMAGES时候，用户全部允许,这个时候是正常的,然后用户在系统权限中，把照片和视频权限改为每次都询问,会直接回调成功,导致得到错误的权限结果

### 复现步骤【必填】

同上

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

34

### 出现问题的手机信息【必填】

三星S24

### 出现问题的安卓版本【必填】

Android14

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

全部

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

是

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

是

**Comment by JackyKeke** [comment]
放视频看看？

**Comment by getActivity** [comment]
<img width="263" alt="image" src="https://github.com/getActivity/XXPermissions/assets/28616817/d3d7b02c-0f98-4c0f-a86d-beeff8e4361b">

<img width="263" alt="image" src="https://github.com/getActivity/XXPermissions/assets/28616817/6755d875-3f61-4a3c-b24c-a0c7d5c4b146">

**Comment by getActivity** [comment]
![screenshot1717776239196](https://github.com/getActivity/XXPermissions/assets/28616817/521d735f-f85d-4418-a07f-486721007c4b)

**Comment by JackyKeke** [comment]
感谢你的来信，我会及时处理。祝工作顺利，万事如意

**Comment by getActivity** [comment]
小伙子，根据你提供的复现步骤，我无法复现该问题，具体复现步骤我已经上传 gif 图在上面，你需要提供更多的信息辅助我复现该问题。

**Comment by cq5420000** [comment]
这个是有问题，Android14先申请图片权限成功后再申请视频权限会发现读取视频有问题，反之先申请视频再申请图片权限，读取图片有问题，感觉是READ_MEDIA_VISUAL_USER_SELECTED这个权限没有每次都申请

**Comment by getActivity** [comment]
@cq5420000 小伙子，你这个是另外的一个问题，不要在这里留言，请另起一个新的 bug issue，并且严格按照 issue 模板填写，我看到会处理的。

**Comment by getActivity** [comment]
长期没有响应，自动关闭此 issue。
