### ISSUE TITLE
[Bug]：java.lang.IllegalStateException: The activity has been finishing, please manually determine the status of the activity

### ISSUE THREAD

**Issue by billdizl** [getActivity/XXPermissions#299]
### 框架版本【必填】

18.63

### 问题描述【必填】

![](https://github.com/getActivity/XXPermissions/assets/30317994/a7f50450-7222-4290-bed6-5577e5cf7f12)

### 复现步骤【必填】

快速打开 关闭该页面

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

33

### 出现问题的手机信息【必填】

vivo

### 出现问题的安卓版本【必填】

9

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

部分

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

是

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

否

**Comment by billdizl** [comment]
![image](https://github.com/getActivity/XXPermissions/assets/30317994/27eedb23-4f51-4f31-9e9e-3106f2f1d9cf)

**Comment by getActivity** [comment]
<img width="754" alt="image" src="https://github.com/getActivity/XXPermissions/assets/28616817/7d5fae2f-d10e-4e4f-a13e-beb548d62326">

<img width="376" alt="image" src="https://github.com/getActivity/XXPermissions/assets/28616817/3b786c29-6dcb-46db-aea8-f5ad3d9b87f7">

<img width="861" alt="image" src="https://github.com/getActivity/XXPermissions/assets/28616817/e239b26f-ed0b-477b-b607-f52b08838b33">

小伙子，框架这个提示给得还不够明显么？还是框架的文档哪里写得不清楚？
