### ISSUE TITLE
[Question]: New Androidx Activity Result API

### ISSUE THREAD

**Issue by kriz84** [getActivity/XXPermissions#301]
### Question Description [Required]

Hello,
 i have one question, is it possible to update the Library to use the new API?
I tried changing the XXPermission to update the request function with the new API but it doesnt request any permissions, for any reason just the POST.NOTIFICATIONS permissions, but i have more thn 8 permissions to request.

This is the code how i updated the request function, but i converted it to kotlin;
Well, i do only hope that the permissioncontroller under Android 14 will be found when its on the foreground, thats why i tried to update the code cause for any reason the permissioncontroller wont be found even the permission request code is on the foreground. I need to traverse the permissioncontroller cause i need to install every day over 20 phones and i want to grant automatically the permissions and its disturbing always to grant manualy the permissions. I dont even know if this resolves the problem anyway.
And by the Way, why not updating to androidx.app.fragment? Is there a reason?

greets

 /**
     * Request permissions
     */
    fun request(callback: OnPermissionCallbacky?) {
        val activity = mContext as? AppCompatActivity ?: return
        log("Starting permission request")

        val permissions = ArrayList(mPermissions)
        log("Permissions to request: $permissions")

        val permissionLauncher = activity.registerForActivityResult(
            ActivityResultContracts.RequestMultiplePermissions()
        ) { result ->
            log("Permission request result: $result")
            val grantedPermissions = result.filter { it.value }.keys.toList()
            log("All permissions granted")
            val deniedPermissions = result.filter { !it.value }.keys.toList()
            log("Some permissions denied: $deniedPermissions")

            if (deniedPermissions.isEmpty()) {
                // All permissions granted
                callback?.onGranted(grantedPermissions, true)
            } else {
                // Some permissions denied
                callback?.onDenied(deniedPermissions, false)
            }
        }

        if (mInterceptor == null) {
            mInterceptor = getInterceptor()
        }

        val context: Context = mContext

        val interceptor: IPermissionInterceptort? = mInterceptor

        val checkMode = isCheckMode(activity)

        // Check whether the current Activity status is normal, if not, do not request permissions
        val foundActivity = PermissionUtilsv.findActivity(activity) ?: return
        if (!PermissionCheckerp.checkActivityStatus(foundActivity, checkMode)) {
            return
        }

### Is the issue mentioned in the framework documentation? [Required]

Not Selected

### Did you consult the framework documentation but couldn't find a solution? [Required]

Not Selected

### Has a similar issue been reported in the issue list? [Required]

Not Selected

### Have you searched the issue list but couldn't find a solution? [Required]

Yes

**Comment by kriz84** [comment]
it seems why it dont requested for permissions is not this the reason, iam still a newbie and i do get help by Cloudus Sonnet 3.5 A.I, i need to test more if this new code works, i need to take my backup files some codes seems makes the problem that even the old request code works now, sorry

**Comment by getActivity** [comment]
This issue is currently back for the following reasons:

* Did not fill in the issue template strictly

Please resubmit the issue and fill in the issue template strictly

**Comment by kriz84** [comment]
Hello,
iam sorry that i cant give much info, but my main question is if its possible to update the framework API to ActivityResult API.
The main problem is, but it seems its not related to XXPermissions. I think iam on the wrong place now.
But about the new API i wanted to ask and the Permissions which is missing in Android 14 "READ_MEDIA_VISUAL", its a permission group for allowing granting full access to Photo and Video not like "READ_MEDIA_VISUAL_SELECTED" which have limited access. Well i added it myself in XXPerm.

My Main problem is that the permissioncontroller with the packagename "com.google.android.permissioncontroller" will not found even the permission request dialog is on the foreground after i request permissions directly after i grant accessibility service, its like the dialog is hidden or something else.
One time i was successful traversing the permissioncontroller under A14 but i have needed to take my backup files, now iam unable to traversing it.
Maybe you know something have i thought, and i have not updated the Phones which was working traversing.

Well, thats everything i wanted to say i think.
Really issues i dont have in XXPerm, but iam a person which always like to update what is everything possible.
I updated for example now android.app.Fragment to androidx.fragment.app.Fragment* and i have no problems.
Thanks anyway for the great Permission Library where its so what from easy to request for permissions.

greets
