### ISSUE TITLE
[Bug]：targetSdk<31 的 app 在高版本 Android 上的蓝牙权限问题

### ISSUE THREAD

**Issue by JackCui001** [getActivity/XXPermissions#302]
### 框架版本【必填】

18.63

### 问题描述【必填】

realme GT5 Pro（OPPO系），Android 14，申请 BLUETOOTH_CONNECT 权限报错。与 Issue #123 相似。
targetSdk < 30，清单中申请 BLUETOOTH，BLUETOOTH_ADMIN，BLUETOOTH_CONNECT 权限
调用 bluetoothAdapter.enable() 时，抛出
> java.lang.SecurityException: Need android.permission.BLUETOOTH_CONNECT permission for ......

但用 XXPermission 动态申请 BLUETOOTH_CONNECT 权限时，抛出
> java.lang.IllegalStateException: Request android.permission.BLUETOOTH_CONNECT permission, The targetSdkVersion SDK must be 31 or more, if you do not want to upgrade targetSdkVersion, please apply with the old permission.

使用 unchecked() 忽略权限检查后，成功弹窗申请权限，一切正常。

### 复现步骤【必填】

targetSdk<31 的 app 在高版本 Android 上申请 BLUETOOTH_CONNECT 权限。

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

28

### 出现问题的手机信息【必填】

realme GT5 Pro

### 出现问题的安卓版本【必填】

14

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

全部

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

是

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

是

### 提供截图或视频

![微信图片_20240705094812](https://github.com/getActivity/XXPermissions/assets/6670163/461e4394-6280-4e48-b50c-3e70609efddd)
![微信图片_20240705094743](https://github.com/getActivity/XXPermissions/assets/6670163/cc16bfd2-fe6d-44ae-8b21-20a95e6b7d94)

### 提供解决方案

临时方案：使用 unchecked() 禁用权限检查。

**Comment by getActivity** [comment]
[XXPermissions-18.65.aar.zip](https://github.com/user-attachments/files/16112360/XXPermissions-18.65.aar.zip)

**Comment by getActivity** [comment]
小伙子，针对你说的这个问题，我对框架的代码逻辑进行优化，你试试看上面的 aar 包是否还有这个问题？如果有的话，请及时跟我反馈，如果没有的话也劳烦通知我一声，我稍后会发布远程依赖出来。

**Comment by JackCui001** [comment]
好的，代码在公司电脑上，要周一早上过去才能测试，我会尽快将结果告知你。

**Comment by JackCui001** [comment]
经过测试，18.65版本修复了上述问题，但是貌似又引入了新问题：
当在清单文件中声明
> <uses-permission android:name="android.permission.BLUETOOTH_SCAN"/>
提示需要替换为
> <uses-permission android:name="android.permission.BLUETOOTH_SCAN" android:usesPermissionFlags="neverForLocation"/>
或
> <uses-permission android:name="android.permission.BLUETOOTH_SCAN" />
> <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
但实际上，必须要使用
> <uses-permission android:name="android.permission.BLUETOOTH_SCAN" android:usesPermissionFlags="neverForLocation"/>
> <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
才能避免框架检查报错。

**Comment by getActivity** [comment]
<img width="1500" alt="image" src="https://github.com/getActivity/XXPermissions/assets/28616817/d90bb323-3a93-4a1f-8e64-65464cd654fc">

**Comment by getActivity** [comment]
<img width="879" alt="image" src="https://github.com/getActivity/XXPermissions/assets/28616817/7c7590ed-c3b7-46ab-b7b7-5950a35804bf">

**Comment by getActivity** [comment]
<img width="1374" alt="image" src="https://github.com/getActivity/XXPermissions/assets/28616817/7763e253-38d5-4ef5-a47c-102d297a0f92">

**Comment by getActivity** [comment]
1. 加 `android:usesPermissionFlags="neverForLocation"` 是为了蓝牙权限申请之后能正常使用蓝牙功能，如果你没有加这个属性，在动态申请权限的时候，还需要加上定位权限一起申请，否则如果只单独申请蓝牙权限，申请成功后有些蓝牙功能是没有办法用的。

2. 在清单文件上面添加 `<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>` 则是为了向下兼容，这是因为 `BLUETOOTH_SCAN` 权限在 Android 12 及以上的系统才出现的，如果是在 Android 12 以下的系统上面直接申请，会被旧系统直接拒绝，框架会智能判断，如果是在 Android 12 以下的系统申请 `BLUETOOTH_SCAN`，则自动使用 `ACCESS_FINE_LOCATION` 代替 `BLUETOOTH_SCAN` 来动态申请权限。

**Comment by getActivity** [comment]
@JackCui001 小伙子，远程依赖已经更新了，你可以更新再试一下。

**Comment by JackCui001** [comment]
已解决，多谢
