### ISSUE TITLE
[Bug]：盒子或者AndroidTV的app无法获取焦点

### ISSUE THREAD

**Issue by fly803** [getActivity/XXPermissions#303]
### 框架版本【必填】

18.63

### 问题描述【必填】

盒子或者AndroidTV的app无法获取焦点，遥控器无法对权限的确定取消进行选择。

### 复现步骤【必填】

启动的时候，运行

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

33

### 出现问题的手机信息【必填】

RK3588

### 出现问题的安卓版本【必填】

Android12

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

所有

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

是

### 提供截图或视频

![1720162453794](https://github.com/getActivity/XXPermissions/assets/16131168/6dfab0bb-734d-44bb-9295-6f0b1f1e2a27)

**Comment by getActivity** [comment]
@fly803 你试一下用系统的 API 申请权限是否有这样的问题？

**Comment by fly803** [comment]
系统API也有这样的问题。














在 2024-07-06 00:28:43，"Android轮子哥" ***@***.***> 写道：

@fly803 你试一下用系统的 API 申请权限是否有这样的问题？

**Comment by getActivity** [comment]
@fly803 那这就不是框架的问题了，建议你尝试找厂商解决。
