### ISSUE TITLE
[疑惑]：拦截授权，弹出弹窗，说明文字是从哪里来的

### ISSUE THREAD

**Issue by FanXH123** [getActivity/XXPermissions#304]
### 问题描述【必填】

请教下，现在请求权限之前，必须要弹窗该权限是拿来做什么的说明，我在PermissionsAspect 类中找到了拦截的方法，也可以弹窗了，但是说明文字要怎么传过来，还是说是去判断拦截到的权限列表去直接生成说明字符串吗，下图是我在PermissionsAspect的requestPermissions改写的
![QQ截图20240708103748](https://github.com/getActivity/XXPermissions/assets/16459353/1f675901-b3ad-4b9c-b498-96a64963d4e7)

### 框架文档是否提及了该问题【必答】

是

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

是

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 没有严格按照 issue 模板填写问题：看似回答了问题，但是实际是乱回答

请重新提一个 issue 并纠正以上问题
