### ISSUE TITLE
[Bug]：Android14 获取视频储存权限有问题

### ISSUE THREAD

**Issue by Equalzys** [getActivity/XXPermissions#306]
### 框架版本【必填】

18.65

### 问题描述【必填】

1、android14手机
2、第一次打开App获取视频储存权限时，选择授权部分视频选项（即：READ_MEDIA_VISUAL_USER_SELECTED）
3、第二次打开App发现ActivityCompat.checkSelfPermission(Manifest.permission.READ_MEDIA_VIDEO) 返回PERMISSION_GRANTED；
4、此时代码再次调用框架去请求视频储存权限，此时不会弹权限弹窗；

ps:希望如果READ_MEDIA_VISUAL_USER_SELECTED为 PERMISSION_GRANTED，此时再次调用框架去请求视频储存权限，会弹权限弹窗,让用户可以授权全部视频的机会;

### 复现步骤【必填】

同上

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

34

### 出现问题的手机信息【必填】

一加9pro 

### 出现问题的安卓版本【必填】

android 14

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

没其他测试机，不确定

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

否

### issue 列表中是否有人曾提过类似的问题【必答】

是

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

否

**Comment by getActivity** [comment]
https://github.com/getActivity/XXPermissions/issues/244

**Comment by getActivity** [comment]
<img width="411" alt="image" src="https://github.com/getActivity/XXPermissions/assets/28616817/63d44852-fa43-4b93-8b2f-5155e07faf27">

小伙子，这个问题我不是解答过了？怎么又重复问？

**Comment by Equalzys** [comment]
> <img alt="image" width="411" src="https://private-user-images.githubusercontent.com/28616817/346885039-63d44852-fa43-4b93-8b2f-5155e07faf27.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MTczNTgsIm5iZiI6MTcyMDUxNzA1OCwicGF0aCI6Ii8yODYxNjgxNy8zNDY4ODUwMzktNjNkNDQ4NTItZmE0My00YjkzLThiMmYtNTE1NWUwN2ZhZjI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDA5MjQxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExNjBiZTI4OTlkZjFiN2ZjN2ViYzJlNzY1Y2VjNGJjMDI5OTk1ZTJmMzkwMmUyYjc0YTNhNDhkOGEwNDAzYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p74EYES5bELH9ZL9cOH83EPsdOVstbuNjonSkrqWkWc">
> 小伙子，这个问题我不是解答过了？怎么又重复问？

没找到视频的，去那回复了，这个我关了
