### ISSUE TITLE
[Suggestion]: 可否开放PhoneRomUtils供调用？

### ISSUE THREAD

**Issue by klxiaoniu** [getActivity/XXPermissions#309]
### What are the shortcomings you have noticed in the framework? [Required]

PhoneRomUtils是本库中判断系统类型的一个工具类。我最近在做AppWidget请求添加到桌面的事情，不同厂商对其要求不一样，如小米要打开创建快捷方式权限、vivo不支持、OPPO直接可以添加等，这里就用到了机型判断，来给用户做不同的引导。对于这种比较复杂的需求，开发者可能需要自己判断机型来手动处理。我目前是复制了一份PhoneRomUtils来使用，后续可否考虑开放这个类供调用？

### Has a similar suggestion been made in the issue list? [Required]

No

### Is the suggestion mentioned in the framework documentation? [Required]

No

### Did you consult the framework documentation but couldn't find a solution? [Required]

Yes

### How do you suggest improving it? [Optional]

开放PhoneRomUtils供调用

**Comment by getActivity** [comment]
小伙子，这个建议不会被采纳，因为框架的内部代码不会提供给外部使用。

**Comment by klxiaoniu** [comment]
> 小伙子，这个建议不会被采纳，因为框架的内部代码不会提供给外部使用。

好嘞

**Comment by getActivity** [comment]
我已经将这个功能单独抽成了一个开源库：[DeviceCompat](https://github.com/getActivity/DeviceCompat)
