### ISSUE TITLE
IllegalStateException 

### ISSUE THREAD

**Issue by Tobin-github** [getActivity/XXPermissions#31]
在 PermissionFragment.prepareRequest (SourceFile:62) 
activity.getFragmentManager().beginTransaction().add(this, activity.getClass().getName()).commitAllowingStateLoss();

Fatal Exception: java.lang.IllegalStateException Activity has been destroyed

**Comment by getActivity** [comment]
库的版本是多少

**Comment by Tobin-github** [comment]
最新版的， 出现几率不大，google firebase bug 检测有出现这个情况

**Comment by getActivity** [comment]
我已经在最新版本上面修复了这个问题，你可以查看提交记录，如果你这边的库版本还是旧的话请更新版本之后再进行测试

**Comment by Tobin-github** [comment]
看了提交记录 commit 改成了 commitAllowingStateLoss 这个记录 ？ 但是还是会有个别用户报 IllegalStateException 异常 我用的就是这个版本 Commits on Jul 9, 2019

**Comment by getActivity** [comment]
// 如果用户离开太久，会导致 Activity 被回收掉，所以这里要判断当前 Fragment 是否有被添加到 Activity（可在开发者模式中开启不保留活动复现崩溃的 Bug）
        if (isAdded()) {
            // 请求其他危险权限
            requestPermission();
        }

**Comment by Tobin-github** [comment]
这个判断是有的，我使用的是最新版本， 在考虑是不是由于连续两次添加fragment导致的

**Comment by getActivity** [comment]
把报错的代码贴一下

**Comment by Tobin-github** [comment]
/**
     * 准备请求
     */
    public void prepareRequest(Activity activity, OnPermission call) {
        // 将当前的请求码和对象添加到集合中
        PERMISSION_ARRAY.put(getArguments().getInt(REQUEST_CODE), call);
//        activity.getFragmentManager().beginTransaction().add(this, activity.getClass().getName()).commit();

//        commit方法可能在Activity的onSaveInstanceState()之后调用，会导致“java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState”报错，
//        修改为commitAllowingStateLoss（）方法
            activity.getFragmentManager().beginTransaction().add(this, activity.getClass().getName()).commitAllowingStateLoss();

    }报错的就是这里， 而且isAdded（）判断并不靠谱

**Comment by getActivity** [comment]
再把报错的信息贴一下，哪个类哪行代码

**Comment by Tobin-github** [comment]
Fatal Exception: java.lang.IllegalStateException
Activity has been destroyed
android.app.FragmentManagerImpl.enqueueAction (FragmentManager.java:1460)
android.app.BackStackRecord.commitInternal (BackStackRecord.java:708)
android.app.BackStackRecord.commitAllowingStateLoss (BackStackRecord.java:676)
com.xxx.xxx.permissions.PermissionFragment.prepareRequest (SourceFile:62)
com.xxx.xxx.permissions.XXPermissions.request (SourceFile:117)

**Comment by getActivity** [comment]
有复现步骤么

**Comment by Tobin-github** [comment]
目前无法复现，我们发布googleplay的 目前只有几个用户报错

**Comment by Tobin-github** [comment]
这个问题已经解决，因为activity回收导致的
 看你到你的代码有 这样一行注释 
// 使用isFinishing方法Activity在熄屏状态下会导致崩溃
//        if (mActivity == null ||mActivity.isFinishing()) throw new IllegalArgumentException("Illegal Activity was passed in");
        if (mActivity == null) throw new IllegalArgumentException("The activity is empty");
我看了下Android 源码 单纯判断isFinishing是不行的，我参考下fragment源码对activity的判断修添加了如下判断，没有在出现问题了
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1){
            if (mActivity == null || mActivity.isDestroyed() || mActivity.isFinishing()) {
                throw new IllegalArgumentException("Illegal Activity was destroyed in");
            }
        }

**Comment by getActivity** [comment]
多谢提醒，已经记录
