### ISSUE TITLE
[疑惑]：设置权限请求拦截器（全局设置）后，有办法让某个请求不走拦截器中的方法吗

### ISSUE THREAD

**Issue by FanXH123** [getActivity/XXPermissions#310]
### 问题描述【必填】

请教下轮子哥，进入应用后我要申请发送通知权限，但是现在设置了全局的权限拦截器，申请权限的时候都有弹窗说明，在申请发送通知权限的时候也会出现这个弹窗说明，如果想要不弹窗说明的话是只能在拦截器代码里面做过滤吗，还是有什么api可以直接跳过拦截器。谢谢啦

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by getActivity** [comment]
<img width="380" alt="image" src="https://github.com/user-attachments/assets/38c01663-fb70-4089-9512-4d3435c17d15">

**Comment by getActivity** [comment]
@FanXH123 这个问题我不会直接告诉你答案，你回去把框架首页文档和疑问文档一字不差看一遍就知道了。

**Comment by FanXH123** [comment]
我知道框架有局部设置权限请求拦截器的方法，我现在就是这么做的，建了一个新的局部的拦截器拦截，但是还是想问下除了这个还有跳过全局拦截器的方法吗，在文档里面找了很多圈了没有找到。

**Comment by FanXH123** [comment]
不纠结这个问题了，局部新建一个拦截器拦截可以解决
