### ISSUE TITLE
[疑惑]：我最近拉取了一个老项目，项目里面用到的版本是12.8，但是我死活拉不下来这个版本。

### ISSUE THREAD

**Issue by ToFigting** [getActivity/XXPermissions#311]
### 问题描述【必填】

编译器提示https://jitpack.io/com/github/getActivity/XXPermissions/12.8/XXPermissions-12.8.pom 获取不到。我想问问是这个资源已经被删掉了吗？

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by getActivity** [comment]
小伙子，我到 jitpack 重新构建了一下，你再试试看行不行

**Comment by Summer-Android** [comment]
@ToFigting 大概率跟Gradle版本有关系，试试升级Gradle8.0
