### ISSUE TITLE
[Bug]：

### ISSUE THREAD

**Issue by cjqq354139968** [getActivity/XXPermissions#312]
### 框架版本【必填】

V20.0

### 问题描述【必填】

问题1 ， 使用  XXPermissions.isDoNotAskAgainPermissions(activity, Permission.WRITE_EXTERNAL_STORAGE))  api ，当没有权限的时候 会永远返回 true 。问题是 我并没有 请求权限 。在 三星S8 ，小米8 SE ， 上均复现。

问题2 ， OnPermissionCallback.onDenied 没有被回调。 onGranted 回调正常 。

问题3 ，关闭检查模式应该可以避免我说的问题。没有测试。

targetSdkVersion = 34, 手机版本 28 （安卓9），请求 存储权限报错 。 应该修改成

PermissionChecker.java 150行 ，

if (AndroidVersion.getTargetSdkVersionCode(context) >= AndroidVersion.ANDROID_13 && Build.VERSION.SDK_INT >= 33 && PermissionUtils.containsPermission(requestPermissions, Permission.READ_EXTERNAL_STORAGE)) {
            // 当 targetSdkVersion >= 33 应该使用 READ_MEDIA_IMAGES、READ_MEDIA_VIDEO、READ_MEDIA_AUDIO 来代替 READ_EXTERNAL_STORAGE
            // 因为经过测试，如果当 targetSdkVersion >= 33 申请 READ_EXTERNAL_STORAGE 或者 WRITE_EXTERNAL_STORAGE 会被系统直接拒绝，不会弹出任何授权框
            throw new IllegalArgumentException("When targetSdkVersion And SystemVersion >= 33 should use " + Permission.READ_MEDIA_IMAGES + ", " + Permission.READ_MEDIA_VIDEO + ", " + Permission.READ_MEDIA_AUDIO + ", rather than " + Permission.READ_EXTERNAL_STORAGE);
        }

### 复现步骤【必填】

问题1 ，2 target = 34（不知道是不是target的原因，我在target=34上复现），使用 安卓 9 ,10 设备 ， 调用 XXPermissions.isDoNotAskAgainPermissions(activity, Permission.WRITE_EXTERNAL_STORAGE)) 

问题2  target = 34 , 使用 低于 安卓 33（包括安卓12 以及更低的机型）

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

34

### 出现问题的手机信息【必填】

三星S8 ，小米8 SE 

### 出现问题的安卓版本【必填】

9

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

安卓9，其它未测试。

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

否

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

否

### 是否可以通过 Demo 来复现该问题【必答】

否

**Comment by getActivity** [comment]
<img width="1200" alt="image" src="https://github.com/user-attachments/assets/550598bf-3d34-4223-96f3-37df8faa3799">

**Comment by getActivity** [comment]
小伙子，你调用 API 都不看一下代码注释的？

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 没有严格按照 issue 模板填写问题：看似回答了问题，但是实际是乱回答

请重新提一个 issue 并纠正以上问题
