### ISSUE TITLE
[疑惑]：已经申请了Manifest.permission.BLUETOOTH_CONNECT权限，同时申请Manifest.permission.BLUETOOTH_CONNECT与Manifest.permission.BLUETOOTH_SCAN时无法申请。

### ISSUE THREAD

**Issue by Carlos2927** [getActivity/XXPermissions#313]
### 问题描述【必填】

在用户已经申请了Manifest.permission.BLUETOOTH_CONNECT权限的场景下，如果用框架同时申请Manifest.permission.BLUETOOTH_CONNECT与Manifest.permission.BLUETOOTH_SCAN权限，不会出现Manifest.permission.BLUETOOTH_SCAN的申请弹窗，只会在OnPermissionCallback.onDenied中回调，这个回调方法第一个参数permissions中只有Manifest.permission.BLUETOOTH_SCAN权限，第二个参数doNotAskAgain为true。此时如果只单独申请Manifest.permission.BLUETOOTH_SCAN权限是可以正常弹出系统权限申请弹窗的，使用ActivityCompat.requestPermissions()测试也是一样的情况。请问这种场景下如何处理，难道只能分开单独申请吗？

框架版本：20.0  测试手机：Samsung Galaxy S22 Ultra   Android 14  targetSdkVersion 34

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 这个问题属于 bug，不能提疑问 issue 单，请提 bug issue 单

请重新提一个 issue 并纠正以上问题
