### ISSUE TITLE
[Bug]：已经申请了Manifest.permission.BLUETOOTH_CONNECT权限，同时申请Manifest.permission.BLUETOOTH_CONNECT与Manifest.permission.BLUETOOTH_SCAN时无法申请。

### ISSUE THREAD

**Issue by Carlos2927** [getActivity/XXPermissions#314]
### 框架版本【必填】

20.0

### 问题描述【必填】

在用户已经申请了Manifest.permission.BLUETOOTH_CONNECT权限的场景下，如果用框架同时申请Manifest.permission.BLUETOOTH_CONNECT与Manifest.permission.BLUETOOTH_SCAN权限，不会出现Manifest.permission.BLUETOOTH_SCAN的申请弹窗，只会在OnPermissionCallback.onDenied中回调，这个回调方法第一个参数permissions中只有Manifest.permission.BLUETOOTH_SCAN权限，第二个参数doNotAskAgain为true。此时如果只单独申请Manifest.permission.BLUETOOTH_SCAN权限是可以正常弹出系统权限申请弹窗的，使用ActivityCompat.requestPermissions()测试也是一样的情况。请问这种场景下如何处理，难道只能分开单独申请吗？

在其他品牌手机上（Redmi K50 Pro Android 14 、Google Pixel 3A Android 12）测试没有出现该问题，因为这两个权限申请其中一个权限时另外一个也同时申请了，而三星手机（Samsung Galaxy S22 Ultra Android 14）经过实测，这两个权限是可以单独申请的，第一次同时申请时会合并成一个授权弹窗。

### 复现步骤【必填】

先申请Manifest.permission.BLUETOOTH_CONNECT权限，授权成功再同时申请Manifest.permission.BLUETOOTH_CONNECT与Manifest.permission.BLUETOOTH_SCAN权限

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

34

### 出现问题的手机信息【必填】

Samsung Galaxy S22 Ultra

### 出现问题的安卓版本【必填】

Android 14

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

三星手机必现

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

是

### 提供截图或视频

demo可以复现
![image](https://github.com/user-attachments/assets/53694852-b1fd-404d-a703-c7944264dcc6)
![image](https://github.com/user-attachments/assets/1a1ef7fe-c8a9-4f97-94c4-85b63a474b6a)

**Comment by getActivity** [comment]
<img width="337" alt="image" src="https://github.com/user-attachments/assets/a65a56ba-4e34-45ab-b7c9-70748c4eadbe">

除三星之外的手机是否也会出现？

**Comment by Carlos2927** [comment]
> <img alt="image" width="337" src="https://private-user-images.githubusercontent.com/28616817/354568771-a65a56ba-4e34-45ab-b7c9-70748c4eadbe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MDI5NzYsIm5iZiI6MTcyMjYwMjY3NiwicGF0aCI6Ii8yODYxNjgxNy8zNTQ1Njg3NzEtYTY1YTU2YmEtNGUzNC00NWFiLWI3YzktNzA3NDhjNGVhZGJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDEyNDQzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0MWNhYjU0ODVmZDhlYWViOTU2MDY3MmI5ZTcyMzczMTg1Yjc1NzEzZTFjZDdmODI2MjZjYjE0OTcyNmJkNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QBL8iD0gCc5Z303grW6BkplNPIj0rI_7Q6ZuJfClkxs">
> 除三星之外的手机是否也会出现？
目前只在三星手机上出现，我Android 12以上测试手机不多，其他手机没有发现这种情况

**Comment by getActivity** [comment]
@Carlos2927 那这个就是三星的问题了，你反馈一下给三星官方
