### ISSUE TITLE
[Bug]：华为手机在设置界面 手动关闭附近设备权限后，框架判断还是已授权状态

### ISSUE THREAD

**Issue by liuhuan8986** [getActivity/XXPermissions#315]
### 框架版本【必填】

com.github.getActivity:XXPermissions:20.0

### 问题描述【必填】

【华为P40 pro】使用框架请求BLUETOOTH_SCAN权限，会正常弹出授权提示，正常授权。然后去设置界面关闭掉附近设备权限，再次使用框架执行请求权限，会跑到onGranted回调里，没有弹出授权提示，但此时，是没有权限的。

    private void request(){
        XXPermissions.with(this)
                .permission(Permission.BLUETOOTH_SCAN)
                .request(new com.hjq.permissions.OnPermissionCallback() {
                    @Override
                    public void onGranted(List<String> permissions, boolean all) {
                        showAlertDialog("授权成功");
                    }

                    @Override
                    public void onDenied(List<String> permissions, boolean never) {
                        showAlertDialog("授权失败");
                    }
                });
    }

如果不用框架，用Android自带的 requestPermissions方法，请求权限正常授权之后，去设置界面关闭掉附近设备权限，再次使用requestPermissions请求权限，会正常弹出授权提示

### 复现步骤【必填】

【华为P40 pro】使用框架请求BLUETOOTH_SCAN权限，会正常弹出授权提示，正常授权。然后去设置界面关闭掉附近设备权限，再次使用框架执行请求权限，会跑到onGranted回调里，但此时，是没有权限的。

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

30

### 出现问题的手机信息【必填】

华为P40 pro

### 出现问题的安卓版本【必填】

android12

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

目前只测试了华为P40 pro 必现，没有那么多机器测试

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

是

### 提供截图或视频

demo和操作视频都放上来了

https://github.com/user-attachments/assets/84e645ff-f9b5-4891-b4e4-244ec71b2166

[MyApplication2.zip](https://github.com/user-attachments/files/16607262/MyApplication2.zip)

**Comment by getActivity** [comment]
<img width="333" alt="image" src="https://github.com/user-attachments/assets/d45c7ac9-8b00-4b4f-9e08-a9cfe5acc672">

你在这个时候点击按钮判断是否授权的结果是什么样的？

**Comment by getActivity** [comment]
<img width="389" alt="image" src="https://github.com/user-attachments/assets/75000dc6-eeff-4b7f-9a36-c829100b2130">

还有你这个问题回答得不规范，既然 issue 模板提了这个问题，就是让提问者把问题确认清楚再提，而不是来一句我手头只有这一台手机然后直接丢给框架作者来确认，我可以肯定地回答你，框架作者是不会帮你确认这个问题是否在特定机型出现的，最终只能是你来确认，无论你用何种办法。

**Comment by getActivity** [comment]
长期没有响应，自动关闭此 issue。
