### ISSUE TITLE
[疑惑]：targetSdkVersion设置为34，在Android10可以申请WRITE_EXTERNAL_STORAGE读写文件，强制校验是部分手机兼容问题？

### ISSUE THREAD

**Issue by woomartin** [getActivity/XXPermissions#317]
### 问题描述【必填】

targetSDK设置为34，也设置了android:requestLegacyExternalStorage="true"，无其他设置
使用了unchecked方法，不然校验不通过。
手机三星S9+, Android10
![image](https://github.com/user-attachments/assets/8a6d4970-5ee9-4e55-b7ea-b221e21f6bc8)

### 框架文档是否提及了该问题【必答】

是

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

是

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by getActivity** [comment]
小伙子，目前此 issue 打回，原因如下：

* 没有严格按照 issue 模板填写

* 没有严格按照 issue 模板填写问题：看似回答了问题，但是实际是乱回答

请重新提一个 issue 并纠正以上问题
