### ISSUE TITLE
[Question]:Class not found android.support.v4.app.Fragment

### ISSUE THREAD

**Issue by SudsMekathotti** [getActivity/XXPermissions#320]
### Question Description [Required]

Code fragment below.    Please help with any pointers               

 XXPermissions.startPermissionActivity(MMXActivity.this, permissions);
                                             ^
  class file for android.support.v4.app.Fragment not found

### Is the issue mentioned in the framework documentation? [Required]

No

### Did you consult the framework documentation but couldn't find a solution? [Required]

Yes

### Has a similar issue been reported in the issue list? [Required]

No

### Have you searched the issue list but couldn't find a solution? [Required]

Yes

**Comment by getActivity** [comment]
Did you add a support dependency?

**Comment by SudsMekathotti** [comment]
Thank you for the pointer. You're right. Was missing dependency 
      compileOnly 'com.android.support:support-fragment:24.2.0'
which I later found in the library/build.gradle.
