### ISSUE TITLE
[Bug]:Android 14 对部分照片和视频进行访问授权异常问题

### ISSUE THREAD

**Issue by LaiYin9** [getActivity/XXPermissions#323]
### Framework Version [Required]

20.0

### Issue Description [Required]

申请多个权限
 XXPermissions.with(this)
.permission(Manifest.permission.CAMERA)
.permission(Manifest.permission.READ_MEDIA_VISUAL_USER_SELECTED)
.permission(Manifest.permission.READ_MEDIA_IMAGES).interceptor(new PermissionInterceptor()).request(new OnPermissionCallback() {

                @Override
                public void onGranted(@NonNull List<String> permissions, boolean allGranted) {
                    if (!allGranted) {
                        return;
                    }
                    toast(String.format(getString(R.string.demo_obtain_permission_success_hint), PermissionNameConvert.getPermissionNames(MainActivity.this, permissions)));
                }

                @Override
                public void onDenied(@NonNull List<String> permissions, boolean doNotAskAgain) {
                    OnPermissionCallback.super.onDenied(permissions, doNotAskAgain);
                    Log.e("onDenied", permissions.toString() + "----" + doNotAskAgain);
                }
            });
 

### Steps to Reproduce [Required]

在Android 14 小米手机上，申请多个权限。当我相机权限申请通过后。申请照片和视频权限时，提示
1、选择照片和视频 
2、全部允许
3、不选择其他数据
点击选择照片和视频，允许某个照片后，onGranted返回申请成功。
第二次点击按钮申请权限，还是会弹出系统弹窗。申请权限，点击拒绝  onGranted 返回申请成功。
理论上讲，当我点击拒绝时，权限申请应返回失败

### Is the Issue Reproducible? [Required]

Not Selected

### Project targetSdkVersion [Required]

34

### Device Information [Required]

小米 Xiaomi MIX Flip

### Android Version [Required]

Android 14

### Issue Source Channel [Required]

Encountered by myself

### Is it specific to certain device models? [Required]

Android 14

### Does the latest version of the framework have this issue? [Required]

Yes

### Is the issue mentioned in the framework documentation? [Required]

No

### Did you consult the framework documentation but couldn't find a solution? [Required]

Yes

### Has a similar issue been reported in the issue list? [Required]

No

### Have you searched the issue list but couldn't find a solution? [Required]

Yes

### Can the issue be reproduced with a demo project? [Required]

Yes

### Provide Screenshots or Videos

https://github.com/user-attachments/assets/fe9c4fee-fed9-44f7-8075-e09b4496297d

https://github.com/user-attachments/assets/f0a443fc-412b-4a2f-a50a-b9ccd4b1edf0

**Comment by getActivity** [comment]
这是因为你之前已经授权了部分照片访问，所以拒绝这一次的权限并不会影响上次已经授权部分访问的照片。

**Comment by LaiYin9** [comment]
当用户给了部分权限后，再次申请权限，这时用户点击了拒绝后，由于在权限回调中检测到已经有了部分权限后所以会返回已经有权限了，可用户点击的是拒绝，这种情况有好的解决办法吗？

**Comment by getActivity** [comment]
你用原生的 API 申请权限也是这样

**Comment by getActivity** [comment]
长期没有响应，自动关闭此 issue。
