### ISSUE TITLE
[建议]：能否提供桌面快捷方式权限?

### ISSUE THREAD

**Issue by stevenwsg** [getActivity/XXPermissions#324]
### 你觉得框架有什么不足之处？【必答】

目前感觉没有比较好的方案，来检查桌面快捷方式权限，谷歌官方没有把创建桌面快捷方式设置为运行时权限。 国内一些rom厂商， 将这个权限设置成了 运行时权限。 各个厂商的检查方法各不相同，参考 https://juejin.cn/post/6974011562231087141。 这个作者提供了Android 7~11 的方案。目前已经发展到了Android 14了， 不知道有没有比较好的方案来检测？

### issue 是否有人曾提过类似的建议？【必答】

否

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### 你觉得该怎么去完善会比较好？【非必答】

处理主流版本，主流厂商ROM的 创建桌面快捷方式的权限， 能检查有没有权限， 没有权限的话，能跳转到开启权限页面

**Comment by getActivity** [comment]
框架不会支持创建快捷方式权限，和开机自启的权限一样，有如下的问题：

1. 不同厂家的权限判断和跳转权限页方式不一样，没有统一的规范来约束

2. 厂家的不同系统版本处理还不太一样，这意味着会有大量的兼容问题需要处理

这是一件吃力不讨好的事情，无论框架怎么做，都是不可能做好，所以我干脆选择不做。

**Comment by stevenwsg** [comment]
> 框架不会支持创建快捷方式权限，和开机自启的权限一样，有如下的问题：
> 
> 1. 不同厂家的权限判断和跳转权限页方式不一样，没有统一的规范来约束
> 2. 厂家的不同系统版本处理还不太一样，这意味着会有大量的兼容问题需要处理
> 
> 这是一件吃力不讨好的事情，无论框架怎么做，都是不可能做好，所以我干脆选择不做。

嗯嗯 好的，谢谢回复哈。明白了
