### ISSUE TITLE
[建议]：with方法可否支持AndroidX下的Fragment？

### ISSUE THREAD

**Issue by AppCompatActivity** [getActivity/XXPermissions#325]
### 你觉得框架有什么不足之处？【必答】

我看当前似乎只支持android包下的Fragment和V4包下的Fragment。

### issue 是否有人曾提过类似的建议？【必答】

否

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

**Comment by getActivity** [comment]
<img width="363" alt="image" src="https://github.com/user-attachments/assets/93a9234f-54c4-4ec7-8972-d77bc13388b3">

**Comment by getActivity** [comment]
你确定这个问题没有人提过？

**Comment by getActivity** [comment]
框架已迁移到 AndroidX，详情请见 [Release v28.0](https://github.com/getActivity/XXPermissions/releases/tag/28.0)
