### ISSUE TITLE
[Question]: 模拟器器申请日历读写权限不会弹申请框

### ISSUE THREAD

**Issue by willBars** [getActivity/XXPermissions#328]
### Question Description [Required]

框架版本 ： XXPermissions:20.0

问题描述 ： 在雷电或者mumu模拟器环境中，申请日历的读写权限时，不会弹出日历权限申请框，框架直接返回的结果是权限已经申请ok，但是往日历中添加uri，确是添加失败

复现步骤 ： 申请步骤，日历权限读，然后日历权限写
                  XXPermissions.with(this)
            .permission(Permission.READ_CALENDAR)
            .permission(Permission.WRITE_CALENDAR)
            .request(object : OnPermissionCallback {
                @RequiresApi(Build.VERSION_CODES.N)
                override fun onGranted(
                    permissions: MutableList<String>,
                    all: Boolean
                ) {

### Is the issue mentioned in the framework documentation? [Required]

Yes

### Did you consult the framework documentation but couldn't find a solution? [Required]

Yes

### Has a similar issue been reported in the issue list? [Required]

Yes

### Have you searched the issue list but couldn't find a solution? [Required]

Yes

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 该问题属于 Bug，但是提了疑问的 issue，请按照 bug issue 模板填写问题

* 没有严格按照 issue 模板填写问题：看似回答了问题，但是实际是乱回答，没有认真去核实问题就乱回答

请重新提一个 issue 并纠正以上问题
