### ISSUE TITLE
[Bug]：错误: 无法访问Fragment XXPermissions.with(getActivity())  找不到android.support.v4.app.Fragment的类文件

### ISSUE THREAD

**Issue by Jasperben** [getActivity/XXPermissions#330]
### 框架版本【必填】

20.0

### 问题描述【必填】

![image](https://github.com/user-attachments/assets/fe754da7-1509-44b7-ab15-8dea51258f3f)

### 复现步骤【必填】

w

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

34

### 出现问题的手机信息【必填】

vivo

### 出现问题的安卓版本【必填】

14

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

全部

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

是

**Comment by Summer-Android** [comment]
@Jasperben https://github.com/getActivity/XXPermissions?tab=readme-ov-file#androidx-%E5%85%BC%E5%AE%B9

**Comment by Jasperben** [comment]
@Summer-Android 感谢提醒

**Comment by Jasperben** [comment]
大意了

**Comment by getActivity** [comment]
框架已迁移到 AndroidX，详情请见 [Release v28.0](https://github.com/getActivity/XXPermissions/releases/tag/28.0)
