### ISSUE TITLE
[疑惑]：请问XXPermission目前是否支持Android15的权限适配

### ISSUE THREAD

**Issue by OnClickListener2048** [getActivity/XXPermissions#331]
### 问题描述【必填】

请问XXPermission目前是否支持Android15的权限适配

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by getActivity** [comment]
Android 15 有什么新的权限需要适配？

**Comment by OnClickListener2048** [comment]
目前在小米android15上之前的权限请求弹窗无法唤起了
