### ISSUE TITLE
[Bug]：XXPermissions.with(this) 

### ISSUE THREAD

**Issue by androidTH** [getActivity/XXPermissions#332]
### 框架版本【必填】

XXPermissions.with(this)

### 问题描述【必填】

    class file for android.support.v4.app.Fragment not found

### 复现步骤【必填】

  class file for android.support.v4.app.Fragment not found

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

34

### 出现问题的手机信息【必填】

不区分

### 出现问题的安卓版本【必填】

34

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

所有

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

是

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

是

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

是

### 提供解决方案

请看下这个问题

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 没有严格按照 issue 模板填写问题：看似回答了问题，但是实际是乱回答，没有认真去核实问题就乱回答

请重新提一个 issue 并纠正以上问题
