### ISSUE TITLE
红米5plus  Android8.0.1拒绝权限后，在设置中打开后；还是检测到是拒绝的

### ISSUE THREAD

**Issue by kanfRUI** [getActivity/XXPermissions#34]
红米5plus  Android8.0.1拒绝权限后，在设置中打开后，还是检测到是拒绝的或者是允许后再在设置中关闭权限，还是检测不到

**Comment by getActivity** [comment]
你换成原生的 API 试试看会不会出现这种情况

**Comment by getActivity** [comment]
经过沟通，原生的 API 也会导致这个问题，是厂商篡改了谷歌的 API，框架本身的代码逻辑是没有任何问题的。
