### ISSUE TITLE
清单文件，没有填写任何权限；这时用框架请求权限会有空指针异常

### ISSUE THREAD

**Issue by JustDoItOrSayBB** [getActivity/XXPermissions#35]
![image](https://user-images.githubusercontent.com/31194070/86077082-ea41fd80-babd-11ea-9100-a050cd755990.png)

**Comment by getActivity** [comment]
经过排查，这个只是一个小问题，因为一般的 App 的清单列表为空的可能性几乎为零，并且申请的动态权限需要先在清单文件中注册，这个问题无伤大雅，我会在下个版本会纠正这个问题，多谢提醒
