### ISSUE TITLE
小米手机权限拒绝后，库中判断的小米权限设置界面开启无效

### ISSUE THREAD

**Issue by meetpasser** [getActivity/XXPermissions#38]
红米Note4 , MIUI 10.9.3.21开发版
安卓6.0

红米K30i MIUI中12.0.3稳定版
安卓10

权限拒绝后并且点击不再提示，跳转到的权限界面。

库中跳转的小米系统权限设置界面， 点击允许后权限获取无效。
com.miui.permcenter.permissions.PermissionsEditorActivity

系统默认的权限设置界面，点击允许后正常。
com.android.settings.applications.InstalledAppDetailsTop

下载的示例，两台手机测试都属于上面情况。

**Comment by getActivity** [comment]
你是使用 Demo 进行测试的吗？

**Comment by getActivity** [comment]
我用小米 9 miui 12.0.3 稳定版进行测试，并不能复现出来你所描述的那种情况，在具体的权限设置界面授予之后返回 Demo 是可以获取到权限的。

**Comment by getActivity** [comment]
这种情况你只能通过 Q群 78797078 和我私信取得联系，Github issue 已经提到过了，我等你回复要等半天，说不定半天之后我已经把这个事情给遗忘了。

**Comment by meetpasser** [comment]
在开发者选项 中，将MIUI优化 打开后，权限申请正常。

**Comment by getActivity** [comment]
@ghost 这个问题已经在最新版本处理，在跳转到小米特有的权限设置页之前，会先判断 miui 优化选项有无开启，有开启的话才会跳转，否则会直接跳转到应用详情页。
