### ISSUE TITLE
关于拒绝权限后一直请求获取的优化问题

### ISSUE THREAD

**Issue by FangXiaoyang** [getActivity/XXPermissions#39]
前两天收到了小米和华为的邮件，两封邮件同时提醒了在权限上的问题，明确指出禁止频繁获取用户权限，以及用户禁止权限后正常使用问题，所以有个对于上架的应用，  所以constantRequest()方法应该谨慎使用。

**Comment by FangXiaoyang** [comment]
![111](https://user-images.githubusercontent.com/16100095/90757815-aeceed00-e310-11ea-916b-e6e113c6530d.png)
![222](https://user-images.githubusercontent.com/16100095/90757827-b2627400-e310-11ea-8e95-33218cf537d0.png)

**Comment by getActivity** [comment]
收到，多谢小伙子的建议

**Comment by getActivity** [comment]
相关 API 已经被标记过时，下个版本会更新
