### ISSUE TITLE
先拒绝再打开权限，判断不准

### ISSUE THREAD

**Issue by caiyoufei** [getActivity/XXPermissions#4]
只设置了地理位置权限，先拒绝，再打开权限，然后一直判断都是失败
手机是红米5
![1](https://user-images.githubusercontent.com/11989916/44137507-42f418b4-a0a3-11e8-9842-a64aba1bb584.gif)

**Comment by 880634** [comment]
你好，我这边经过测试不会出现这种情况，你重启一下手机或者换部手机再试试看

**Comment by caiyoufei** [comment]
@880634 重启手机依然是这样的

**Comment by 880634** [comment]
换部手机还会吗

**Comment by 880634** [comment]
又或者建议你更新一下系统，很可能是系统的问题

**Comment by caiyoufei** [comment]
给你展示一个完整版本的：
![1](https://user-images.githubusercontent.com/11989916/44137951-cf80a030-a0a4-11e8-968f-e8d272206fb7.gif)

**Comment by 880634** [comment]
我这边测试还是没有问题，动态截图如下：

![](https://user-images.githubusercontent.com/24937241/44139886-03d56a2c-a0ab-11e8-8c31-54fef78bafd8.gif)

**Comment by 880634** [comment]
我的机型是红米Note5，代码没有任何问题，只能建议你更新系统啦

**Comment by caiyoufei** [comment]
好吧，可能是部分手机的兼容性问题，试了另外一个华为手机，也没问题

**Comment by caiyoufei** [comment]
但是我的手机是最新版MIUI了，没法升级了
