### ISSUE TITLE
Permission.ACCESS_BACKGROUND_LOCATION问题

### ISSUE THREAD

**Issue by WangYP90** [getActivity/XXPermissions#41]
大佬,我在MIUI 12.20.9.3 版本上,申请Permission.Group.LOCATION权限组,  第一次申请 只会提示    Permission.ACCESS_FINE_LOCATION,Permission.ACCESS_COARSE_LOCATION 权限的弹窗, Permission.ACCESS_BACKGROUND_LOCATION权限弹窗直接不弹弹窗,默认拒绝,

我的解决办法 延迟1.5s 再去请求权限组,Permission.Group.LOCATION弹出 后台定位权限,  但是不管点击, 在运行时允许、运行时允许且不提示，都会回调被拒绝，只有始终允许才能正常。

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/92243981-e59e2900-eef4-11ea-9f83-a25c525f991b.jpg)

**Comment by getActivity** [comment]
小伙子，我根据你说的，申请 Permission.Group.LOCATION 权限组，然后点击本次运行允许是没有任何问题的，回调是成功的。

**Comment by getActivity** [comment]
我的手机是小米9 MIUI 12.0.3 稳定版

**Comment by WangYP90** [comment]
大佬,我使用的MIUI 12.20.9.3预览版,  我估计是系统写的有问题.
![4b31b33c3a22726b7949ecc539a96ce](https://user-images.githubusercontent.com/21963753/92357303-33e04180-f11a-11ea-8d93-7fdd7c7d2651.jpg)

**Comment by getActivity** [comment]
你换个手机试一下

**Comment by WangYP90** [comment]
这个是开发版 系统加的功能,  您看他加了一个"仅在使用时允许且不再询问",等正式版了再说, 估计是系统哪里写的有问题.

**Comment by WangYP90** [comment]
由于该问题出在MiUI开发版,本身开发版系统就是最终版本,所以关闭该issue.
