### ISSUE TITLE
清单文件里面有需要请求的权限，在代码里面不请求权限报错，不知道算不算问题

### ISSUE THREAD

**Issue by huaxuanHan** [getActivity/XXPermissions#42]
![image](https://user-images.githubusercontent.com/60837230/93730280-86c9f680-fbfa-11ea-9a31-71e6e8bae652.png)
java.lang.IllegalArgumentException: The requested permission cannot be empty

**Comment by huaxuanHan** [comment]
以前6.2版本代码里面不请求任何权限的话就默认请求清单里面的权限了，升级8.5后没注意，报了java.lang.IllegalArgumentException: The requested permission cannot be empty的错误

**Comment by getActivity** [comment]
https://github.com/getActivity/XXPermissions/releases/tag/8.6

**Comment by getActivity** [comment]
框架更新内容上面已经注明了移除
