### ISSUE TITLE
轮子哥，Android11+文件管理授权干嘛用ACTION_MANAGE_ALL_FILES_ACCESS_PERMISSION而不用ACTION_MANAGE_APP_ALL_FILES_ACCESS_PERMISSION呢？

### ISSUE THREAD

**Issue by liyujiang-gzu** [getActivity/XXPermissions#43]
ACTION_MANAGE_ALL_FILES_ACCESS_PERMISSION是所用APP列表。
ACTION_MANAGE_APP_ALL_FILES_ACCESS_PERMISSION是指定APP。

**Comment by getActivity** [comment]
经过核实，这块的确写错了，现在已经在代码中纠正，下个版本会更新，感谢小伙子的提醒！

**Comment by getActivity** [comment]
[xxpermissions.aar.zip](https://github.com/getActivity/XXPermissions/files/5358575/xxpermissions.aar.zip)

**Comment by getActivity** [comment]
小伙子如果你着急用的话，你可以先用这个包，我后面会找个时间更新到远程仓库上面。
