### ISSUE TITLE
java.lang.IllegalStateException

### ISSUE THREAD

**Issue by oudengding** [getActivity/XXPermissions#44]
java.lang.IllegalStateException：
 The event has been finish

这个异常出现的很频繁，我这里是每次执行点击事件后调用请求方法抛出的，这正常吗？

**Comment by getActivity** [comment]
已经协助处理，下个版本会纠正这一问题

**Comment by coderxiaotu** [comment]
> java.lang.IllegalStateException：
> The event has been finish
> 
> 这个异常出现的很频繁，我这里是每次执行点击事件后调用请求方法抛出的，这正常吗？
你好，请问更新版本后问题解决了吗？

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/111147141-21f9c280-85c5-11eb-8a60-1f8a05a2912c.png)

**Comment by getActivity** [comment]
@coderxiaotu 小伙子，之前的版本有加上，不过后面去掉了，现在又加上了，框架的意思让你在外层做好 Activity 状态的判断，销毁的时候就不要走权限申请的逻辑了
