### ISSUE TITLE
如何获取跳转到应用权限设置页返回后的requestCode？

### ISSUE THREAD

**Issue by lixiang0418** [getActivity/XXPermissions#47]
XXPermissions的startPermissionActivity这个方法，使用到了 int requestCode = PermissionUtils.getRandomRequestCode();
请教下，我如何能获取这个requestCode ，来处理逻辑。
  我需要在onActivityResult里面获取requestCode，验证授权结果，请指教。
  我的邮箱137237056@qq.com

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/97384190-2cfbd100-190a-11eb-8fb4-0da624355705.png)

**Comment by lixiang0418** [comment]
谢谢轮子哥


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "getActivity/XXPermissions"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月28日(星期三) 上午10:42
收件人:&nbsp;"getActivity/XXPermissions"<XXPermissions@noreply.github.com&gt;;
抄送:&nbsp;"137237056"<137237056@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [getActivity/XXPermissions] 如何获取跳转到应用权限设置页返回后的requestCode？ (#47)
