### ISSUE TITLE
华为Mate7 申请WRITE_SETTINGS权限直接崩溃

### ISSUE THREAD

**Issue by yinxu2015** [getActivity/XXPermissions#48]
手机型号：HUAWEI MT7-UL00
版本号：MT7-UL00C17B577
系统版本号：EMUI系统4.0.1
Android版本：6.0
处理器：Hisilicon Kirin 925

**Comment by yinxu2015** [comment]
经查是签名问题，签名后可以运行。
只是在这个手机上，一直会跳转到系统设置页面，但系统设置页面属于灰显不能设置，然后就频繁往复了。

**Comment by getActivity** [comment]
你用原生的 API 调一下看看有没有这个问题

**Comment by getActivity** [comment]
长时间没有响应，关闭 issue
