### ISSUE TITLE
授权时屏幕旋转会出现多个权限弹窗

### ISSUE THREAD

**Issue by haianhsing** [getActivity/XXPermissions#49]
屏幕旋转时，fragment会出现销毁重建的情况，然后会出现多个权限弹窗

**Comment by getActivity** [comment]
通过原生 API context.requestPermissions 调起授权对话框，但是这个对话框是系统弹出来的，而不是应用弹出来的，我们并不能控制让它显示或者隐藏。

**Comment by getActivity** [comment]
要解决这个问题也很简单，你需要在清单文件中加入 
```xml
android:configChanges="orientation|screenSize|keyboardHidden"
```
这样就能让 Activity 在进行屏幕旋转的时候不进行重启

**Comment by getActivity** [comment]
又或者在清单文件中锁定 Activity 的方向

**Comment by getActivity** [comment]
小伙子，框架最新版本已经处理了这个问题，解决方式是申请权限时将 Activity 的方向固定，申请完成之后将 Activity 的方向还原回去，具体细节框架主页有介绍，小伙子你要是感兴趣可以去看看。
