### ISSUE TITLE
问题比较多哈，经常出现重复请求，已授权也会跳到noPermission方法

### ISSUE THREAD

**Issue by leveychen** [getActivity/XXPermissions#5]
基本上快被测试小姐姐打死了。。

**Comment by 880634** [comment]
库的版本是最新的吗

**Comment by leveychen** [comment]
是啊， 3.6 的版本，  努比亚和vivo，oppo 出现了已授权也直接跳 noPermission

**Comment by 880634** [comment]
你请求了什么权限？XXPermissions.permission(？？？)

**Comment by 880634** [comment]
老哥，这个问题在我测试的手机里面没有啊，麻烦描述清楚

**Comment by leveychen** [comment]
不是必现的，NEX和 Find X 上面偶尔会出现，而且在手动授权之后，app直接重启了，但是权限没有打开。。重启手机也没有用。
经测试，不仅是 XXPermissions 这个库有这个问题，AndPermissions ，和几个主流的库都一样的问题，我估计是手机rom本身的问题。

**Comment by 880634** [comment]
对于这种问题老哥也是无能为力
