### ISSUE TITLE
关于miui优化状态api

### ISSUE THREAD

**Issue by stytooldex** [getActivity/XXPermissions#51]
逆向应该能找的到！

**Comment by getActivity** [comment]
假设小米的问题解决了，华为的问题呢？

**Comment by getActivity** [comment]
这些问题很多时候无从下手，很难全部兼容到位。

**Comment by getActivity** [comment]
小伙子，我最近研究了一下，是可以判断到 miui 优化开关的，具体代码如下：

```java
/**
 * 判断 miui 优化有没有开启（默认开启，关闭步骤为：开发者选项-> 启动 MIUI 优化 -> 点击关闭）
 */
@SuppressLint("PrivateApi")
static boolean isMiuiOptimization() {
  try {
     Class<?> clazz = Class.forName("android.os.SystemProperties");
     Method getMethod = clazz.getMethod("get", String.class, String.class);
     String ctsValue = String.valueOf(getMethod.invoke(clazz, "ro.miui.cts", ""));
     Method getBooleanMethod = clazz.getMethod("getBoolean", String.class, boolean.class);
     return Boolean.parseBoolean(String.valueOf(getBooleanMethod.invoke(clazz, "persist.sys.miui_optimization", !"1".equals(ctsValue))));
  } catch (ClassNotFoundException e) {
     e.printStackTrace();
  } catch (InvocationTargetException e) {
     e.printStackTrace();
  } catch (NoSuchMethodException e) {
     e.printStackTrace();
  } catch (IllegalAccessException e) {
     e.printStackTrace();
  }
  return true;
}
```

**Comment by stytooldex** [comment]
> 小伙子，我最近研究了一下，是可以判断到 miui 优化开关的，具体代码如下：
> 
> ```java
> /**
>  * 判断 miui 优化有没有开启（默认开启，关闭步骤为：开发者选项-> 启动 MIUI 优化 -> 点击关闭）
>  */
> @SuppressLint("PrivateApi")
> static boolean isMiuiOptimization() {
>   try {
>      Class<?> clazz = Class.forName("android.os.SystemProperties");
>      Method getMethod = clazz.getMethod("get", String.class, String.class);
>      String ctsValue = String.valueOf(getMethod.invoke(clazz, "ro.miui.cts", ""));
>      Method getBooleanMethod = clazz.getMethod("getBoolean", String.class, boolean.class);
>      return Boolean.parseBoolean(String.valueOf(getBooleanMethod.invoke(clazz, "persist.sys.miui_optimization", !"1".equals(ctsValue))));
>   } catch (ClassNotFoundException e) {
>      e.printStackTrace();
>   } catch (InvocationTargetException e) {
>      e.printStackTrace();
>   } catch (NoSuchMethodException e) {
>      e.printStackTrace();
>   } catch (IllegalAccessException e) {
>      e.printStackTrace();
>   }
>   return true;
> }
> ```

两年半了，都还在，666
