### ISSUE TITLE
INSTALL_SHORTCUT

### ISSUE THREAD

**Issue by wangyuan0217** [getActivity/XXPermissions#52]
怎么没有这个选项

**Comment by getActivity** [comment]
这个权限不是危险权限或者特殊权限

**Comment by liuzian** [comment]
对呀，群主加上个这权限吧。INSTALL_SHORTCUT

**Comment by getActivity** [comment]
@liuzian 这个权限是厂商定义的权限，目前大部分厂商（除了小米）没有对外开放这个权限的申请方式和判断状态方法，所以不打算兼容这个权限。
