### ISSUE TITLE
建议恢复跳转权限设置页和获取AndroidManifest的所有权限两个实用功能

### ISSUE THREAD

**Issue by huaxuanHan** [getActivity/XXPermissions#54]
我是比较喜欢追新的，愿意尝试新功能，但是我试了从9.6往下的每一个版本，直到6.2，每一个版本我都做了测试，最终我决定使用8.2，并且应该在之后很长一段时间都停留在8.2了，我觉得跳转权限设置页和获取AndroidManifest的所有权限这两个功能挺实用的，而且我没有遇到什么问题，可能是我测试的设备比较少的原因，对于我们这种小公司，尽量通过工具减少开发量尽快完工是必须的，可能一个小app，从说到做完只有一天时间甚至更短。麻烦大佬看到后直接关闭此issues就好

**Comment by getActivity** [comment]
小伙子，首先非常感谢你的反馈，但是移除每一个功能我都会认真斟酌，例如国产手机设置页，最初加入这个功能的时候并没有发现太多问题，但是在最后面跟我反馈的人越来越多，并且我花了很多时间和精力去解决这些问题，但是最终得到的结果是无法解决，原因我也有在框架首页有描述。

**Comment by getActivity** [comment]
另外一个是获取清单权限并申请的功能，这个虽然非常方便，但是存在一些隐患，因为 apk 中的清单文件最终是由多个 module 的清单文件合并而成，会变得不可控，这样会使我们无法预估申请的权限，并且还会掺杂一些不需要的权限，所以经过慎重考虑移除该功能。
