### ISSUE TITLE
闪退了

### ISSUE THREAD

**Issue by kangdawei** [getActivity/XXPermissions#60]
Caused by: java.lang.IllegalArgumentException: Because it includes background location permissions, do not apply for permissions unrelated to location

` XXPermissions.with(this)
                .permission(Permission.ACCESS_COARSE_LOCATION)
                .permission(Permission.ACCESS_FINE_LOCATION)
                .permission(Permission.ACCESS_BACKGROUND_LOCATION)
                .permission(Permission.READ_EXTERNAL_STORAGE)
                .permission(Permission.WRITE_EXTERNAL_STORAGE)
                .permission(Permission.READ_PHONE_STATE)
                .request(new OnPermissionCallback() {
                    @Override
                    public void onGranted(List<String> permissions, boolean all) {
                        if (all) {
                            //初始化定位
                           
                        }
                    }
                });`

**Comment by getActivity** [comment]
小伙子，这个报错是框架给你抛的，意思是你不要把后台定位权限和其他非定位权限一起申请。

**Comment by getActivity** [comment]
小伙子，还有其他问题么，没有的话我就关闭 issue 了
