### ISSUE TITLE
Android11存储权限过时问题

### ISSUE THREAD

**Issue by ozyl** [getActivity/XXPermissions#61]
虽然申请MANAGE_EXTERNAL_STORAGE可以节省适配时间，从官方和用户角度应该尽量避免使用MANAGE_EXTERNAL_STORAGE权限。

在lib中READ_EXTERNAL_STORAGE权限被标记了@Deprecated，在android11中这个权限会被提示为是否访问媒体、相册，没有过时，应该取消掉注解。

PermissionUtils.checkStoragePermission中高版本被限制了只能使用MANAGE_EXTERNAL_STORAGE，并且需要添加requestLegacyExternalStorage配置。不应该抛异常，应该给警告提示。

相关文档地址（MANAGE_EXTERNAL_STORAGE）：https://developer.android.com/training/data-storage/manage-all-files?hl=zh-cn
相关文档地址（Android11）：https://developer.android.com/about/versions/11/privacy/storage?hl=zh-cn
> Google Play通知 
本部分向在Google Play上发布应用的开发人员提供通知。
为了限制对共享存储的广泛访问，Google Play商店已更新其策略， 以评估针对Android 11（API级别30）或更高版本的应用，并通过MANAGE_EXTERNAL_STORAGE许可请求所有文件的访问。
MANAGE_EXTERNAL_STORAGE仅当您的应用无法有效利用更隐私友好的API（例如Storage Access Framework或Media Store API）时，才应请求许可。此外，应用程序对权限的使用必须在允许的使用范围内，并且必须直接与应用程序的核心功能绑定。如果您的应用程序包含与以下示例类似的用例，则很可能允许其请求 MANAGE_EXTERNAL_STORAGE许可：
档案管理员
备份还原
防病毒应用
文件管理应用程式
出于与COVID-19相关的考虑，面向Android 11（API级别30）或更高版本且需要MANAGE_EXTERNAL_STORAGE 许可的应用程序必须在2021年初之前才能上传到Google Play。其中包括新应用程序以及对现有应用程序的更新。要了解更多信息，请 从策略帮助中心阅读更新后的策略。

**Comment by getActivity** [comment]
收到，多谢小伙子的提醒，这个问题我其实已经处理了，现在还处于测试和改进中，我会尽快发布新的版本。

**Comment by getActivity** [comment]
小伙子，框架已经更新，更新一下版本即可。
