### ISSUE TITLE
第一次授权存储权限闪退 ，已经授权成功

### ISSUE THREAD

**Issue by lovehua** [getActivity/XXPermissions#62]
permission grant or revoke changed gids

log中看不到报错信息

**Comment by getActivity** [comment]
小伙子，要贴报错信息，不然我怎么帮你排查呢？

**Comment by lovehua** [comment]
> 小伙子，要贴报错信息，不然我怎么帮你排查呢？

**Comment by lovehua** [comment]
Logcat中没有打印出报错日志？？不知道怎么处理了 ，只有存储权限不行，其他权限没有这个问题

**Comment by getActivity** [comment]
小伙子，你用原生 API 试一下有没有问题
