### ISSUE TITLE
关于安卓11中MANAGE_EXTERNAL_STORAGE无效的问题

### ISSUE THREAD

**Issue by lzxshare** [getActivity/XXPermissions#63]
本人按照作者大大的框架说明适配了安卓11文件存储框架，并且申请了MANAGE_EXTERNAL_STORAGE权限，并且调用Environment.isExternalStorageManage（)方法返回true，但是仍然无法在外部存储目录中用原生File API直接读写文件，总是提示Failed to open a write stream to /storage/emulated/0/Veb/VebEncryption/Pictures/2021-03-06 17:31:19.jpg
    java.io.FileNotFoundException: /storage/emulated/0/Veb/VebEncryption/Pictures/2021-03-06 17:31:19.jpg: open failed: EPERM (Operation not permitted)
        at libcore.io.IoBridge.open(IoBridge.java:492)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:236)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
我想问下这个权限适配作者有试过在外部存储目录中直接读写文件吗

**Comment by getActivity** [comment]
小伙子，我再试了一下，是没有问题的，你看看是不是没有在清单文件中注册 `android:requestLegacyExternalStorage="true"` 这个属性？

**Comment by lzxshare** [comment]
请问能加个联系方式吗？我是在清单文件中注册 android:requestLegacyExternalStorage="true"了这个属性。我这边的场景是：我用CameraX拍照输出的照片，放在应用的内部存储目录下file/Camera/2021-03-06.jpg,然后我再把这个照片复制到外部存储的根目录下的文件夹里，但是总是报权限拒绝错误，用的是小米11系统

**Comment by getActivity** [comment]
可以的，小伙子，你加一下 Q群 78797078，通过之后然后私信给我就 OK。

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/110285399-2c90e680-801e-11eb-9183-02edc235f92b.png)

**Comment by Xiaoben336** [comment]
遇到了同样的问题，不知道你们是怎么解决的
