### ISSUE TITLE
MANAGE_EXTERNAL_STORAGE & Android 11

### ISSUE THREAD

**Issue by Mouadabdelghafouraitali** [getActivity/XXPermissions#64]
Is it necessary to use MANAGE_EXTERNAL_STORAGE permission in order to save files (image or video), because this permission is sensitive as Google said :  https://support.google.com/googleplay/android-developer/answer/9956427?hl=en

**Comment by getActivity** [comment]
请见：https://github.com/getActivity/XXPermissions/issues/61

**Comment by getActivity** [comment]
小伙子，还有其他问题不，没有的话我就关闭 issue 了
