### ISSUE TITLE
能不能把PermissionUtils#isPermissionPermanentDenied的Activity改为Context呢？

### ISSUE THREAD

**Issue by guozhiqiang123** [getActivity/XXPermissions#65]
如题。

**Comment by getActivity** [comment]
小伙子，我看是不行的，PermissionUtils#isPermissionPermanentDenied 里面使用了 Activity 的 API

**Comment by getActivity** [comment]
小伙子，你是遇到了什么问题了呢？

**Comment by AdminQQZ** [comment]
是的，小伙子，你有问题要说。

**Comment by guozhiqiang123** [comment]
想升级到最新版，但是原来的isHasPermission（Context,String）现在换成Activity了 很多地方传参都要改

**Comment by AdminQQZ** [comment]
这样好啊，上班摸鱼，慢慢调

**Comment by guozhiqiang123** [comment]
这一周都要加班 摸不到🐟了！

**Comment by AdminQQZ** [comment]
你可以方法重载的方式，写一个一模一样的，参数变化一下即可，需要强转

**Comment by guozhiqiang123** [comment]
那还是算了 万一哪天库升级了我又得改，先这样吧  我去改参数还稳妥些
