### ISSUE TITLE
崩溃问题

### ISSUE THREAD

**Issue by qq570026938** [getActivity/XXPermissions#66]
复现：在子module中做隐私协议相关的弹窗，点击弹窗中的隐私协议跳转子module中的activity，然后返回，在点击同意协议，弹出子module中的权限说明，这时点击同意，回调到主app中调用权限请求此时会崩溃提示Please register the android:requestLegacyExternalStorage="true" attribute in the manifest file ，在app清单文件中已经申请了，而且在弹协议的时候不点击查看协议的话，直接同意不会崩溃

**Comment by qq570026938** [comment]
> 复现：在子module中做隐私协议相关的弹窗，点击弹窗中的隐私协议跳转子module中的activity，然后返回，在点击同意协议，弹出子module中的权限说明，这时点击同意，回调到主app中调用权限请求此时会崩溃提示Please register the android:requestLegacyExternalStorage="true" attribute in the manifest file ，在app清单文件中已经申请了，而且在弹协议的时候不点击查看协议的话，直接同意不会崩溃

强调说明：隐私协议和权限说明的弹窗还有查看隐私协议跳转的页面都在子module中做的，在同意权限的时候回调到主app中请求权限

**Comment by qq570026938** [comment]
刚提出这个问题，就看到10.6版本已解决，厉害了

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/112613707-5a1dc280-8e5b-11eb-86d8-824e721bbec8.png)
