### ISSUE TITLE
单个权限请求出现死循环

### ISSUE THREAD

**Issue by logney** [getActivity/XXPermissions#7]
测试手机小米6，在用户点击不再询问之后，在PermissionFragment中如下代码进入死循环，不再询问应该是一个永久性的拒绝权限，应该跳转到设置界面，大佬快修复下！
           //获取拒绝权限
            List<String> failPermissions = PermissionUtils.getFailPermissions(permissions, grantResults);

            if (getArguments().getBoolean(REQUEST_CONSTANT) && 
            PermissionUtils.checkPermissionPermanentDenied(getActivity(), failPermissions)) {
                //继续请求权限直到用户授权或者永久拒绝
                requestPermission();
                return;
            }

**Comment by getActivity** [comment]
你好，这个问题可能是部分手机的问题，麻烦你加一下Q群78797078

**Comment by getActivity** [comment]
这个问题已经修复好，更新一下库的版本即可
