### ISSUE TITLE
美图手机不会弹出检测权限弹窗？

### ISSUE THREAD

**Issue by shiner0** [getActivity/XXPermissions#72]
美图手机检测权限显示获取权限成功，并且我在手机权限管理里面 看到权限还是处于询问得状态

**Comment by getActivity** [comment]
小伙子，你用原生 API 试试看有没有这个问题

**Comment by MrDon94** [comment]
安卓6.0的平板也是遇到这样的问题，不会弹出检测权限弹窗直接显示获取权限成功

**Comment by getActivity** [comment]
@MrDon94 小伙子，你用原生 API 试过了没？原生 API 有没有这个问题？

**Comment by getActivity** [comment]
@shiner0 小伙子，你要及时回复呢，不然我就默认你的问题是已经解决了

**Comment by yuqianglianshou** [comment]
> 美图手机检测权限显示获取权限成功，并且我在手机权限管理里面 看到权限还是处于询问得状态

小伙子，朋友我也想知道问题解决了没有嗨

**Comment by shiner0** [comment]
使用原生的也不行
| |
shiner
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年4月26日 ***@***.***> 写道：

@shiner0 小伙子，你要及时回复呢，不然我就默认你的问题是已经解决了

**Comment by getActivity** [comment]
@shiner0 小伙子，如果厂商不按谷歌提供的规范来做，那这个我就帮不了你了。

**Comment by yijiebuyi** [comment]
我在魅族note手机上，android7.0同样显示权限授权成功（不会弹出检测权限弹窗直接显示获取权限成功）。我用AndPermission就会弹出申请，原因是AndroidPermission在实现权限检测时，使用双层检查

**Comment by getActivity** [comment]
@yijiebuyi 小伙子，我看了一下 AndPermission 的源码，它确实是做了双重判断，第一种是权限的 API 来检查，第二种是用相机的 API 来检查，但是这种写法不规范，我们应该由谷歌官方提供的 API 来做权限，如果某些厂商要搞特殊的话，我是不会做兼容的，因为兼容成本非常高，并且这样会让这些厂商变本加厉，如果厂商们都想搞自己的一套规则，我建议他们直接做一个系统，而不是基于 Android 做定制化。

**Comment by shiner0** [comment]
> @yijiebuyi 小伙子，我看了一下 AndPermission 的源码，它确实是做了双重判断，第一种是权限的 API 来检查，第二种是用相机的 API 来检查，但是这种写法不规范，我们应该由谷歌官方提供的 API 来做权限，如果某些厂商要搞特殊的话，我是不会做兼容的，因为兼容成本非常高，并且这样会让这些厂商变本加厉，如果厂商们都想搞自己的一套规则，我建议他们直接做一个系统，而不是基于 Android 做定制化，既然选择了 Android，那么就应该按照谷歌提供的接口规范来做权限管理，否则没有人能陪他们那样玩。

我使用andPermission 来检测 也是没有任何效果的

**Comment by getActivity** [comment]
@shiner0 最好的兼容方式就是不兼容，既然原生 API 都有这种问题，只要运行在这个手机上面大部分应用都会有该问题，同时我也说明了为什么不支持厂商那种自立山头的方式。

**Comment by getActivity** [comment]
小伙子，你如果没有其他问题的话，我就关闭 issue 了。

**Comment by yijiebuyi** [comment]
> @yijiebuyi 小伙子，我看了一下 AndPermission 的源码，它确实是做了双重判断，第一种是权限的 API 来检查，第二种是用相机的 API 来检查，但是这种写法不规范，我们应该由谷歌官方提供的 API 来做权限，如果某些厂商要搞特殊的话，我是不会做兼容的，因为兼容成本非常高，并且这样会让这些厂商变本加厉，如果厂商们都想搞自己的一套规则，我建议他们直接做一个系统，而不是基于 Android 做定制化，既然选择了 Android，那么就应该按照谷歌提供的接口规范来做权限管理，否则没有人能陪他们那样玩。

国内做Android App的就是要适配各大Rom厂商，MD各种作死的修改Framwork。

**Comment by getActivity** [comment]
@yijiebuyi 我不建议做兼容，否则等于给厂商开了一道口子，要是谷歌没有权限管理，他们可以那么搞，但是谷歌统一了这块规范，他们就不那么做了，因为他们那么做了，只有死路一条，因为基本没有人能知道怎么适配，所以你也不要担心。

**Comment by AdminQQZ** [comment]
打死也不做兼容！垃圾国产
