### ISSUE TITLE
请教下最新版是什么原因删除定位权限组呢

### ISSUE THREAD

**Issue by w296365959** [getActivity/XXPermissions#74]
请教下最新版是什么原因删除了定位权限组呢

**Comment by getActivity** [comment]
原因是我如果开放 Permission.Group.LOCATION 数组常量，那么会有一部分人在不需要后台定位权限的情况也会申请该权限，这个是我经过一些反馈得知的，所以我删掉这个数组的初衷仅仅只是为了，大家在申请定位权限的时候尽量不要申请到后台定位权限，因为需要用到后台定位权限的 App 基本很少，除了地图 App，我实在想不到还有什么 App 需要这个权限，另外在 Android 11 上面申请后台定位权限的方式会更加繁琐，需要拆分为两步才能申请成功。

**Comment by getActivity** [comment]
* 还有小伙子，框架只是删除了 Permission.Group.LOCATION 数组常量，并不意味着整个定位权限组无法申请，只不过你需要一个个加入到权限申请列表里面

```java
public final class Permission {

    /** 获取精确位置 */
    public static final String ACCESS_FINE_LOCATION = "android.permission.ACCESS_FINE_LOCATION";
    /** 获取粗略位置 */
    public static final String ACCESS_COARSE_LOCATION = "android.permission.ACCESS_COARSE_LOCATION";
    /** 在后台获取位置（需要 Android 10.0 及以上） */
    public static final String ACCESS_BACKGROUND_LOCATION = "android.permission.ACCESS_BACKGROUND_LOCATION";

}
```

**Comment by getActivity** [comment]
小伙子，你还有其他问题不，如果没有的话我就关闭 issue 了
