### ISSUE TITLE
Android 11 集成该框架之后gps无法定位

### ISSUE THREAD

**Issue by zxh965321** [getActivity/XXPermissions#77]
小米10 手机上运行定位demo集成xxpermissions之后并不能使用gps 完成定位  Location location = locationManager.getLastKnownLocation(provider); // 通过GPS获取位置这个设置的是gps的provide获取的location为null

**Comment by getActivity** [comment]
小伙子，那你现在进一下应用详情页面，看看权限是不是已经授予了？

**Comment by zxh965321** [comment]
只是无法gps定位


在2021年04月29日 ***@***.***> 写道：

小伙子，那你现在进一下应用详情页面，看看权限是不是已经授予了？

**Comment by getActivity** [comment]
@zxh965321 小伙子，你还没有告诉我的问题答案。

**Comment by zxh965321** [comment]
Manifest.permission.ACCESS_BACKGROUND_LOCATION该权限获取不了，Manifest.permission.ACCESS_FINE_LOCATION
ACCESS_COARSE_LOCATION都获取到了，不用该框架这俩都可以获取到，但是后台那个获取不到，定位gps定位无法获取经纬度

**Comment by getActivity** [comment]
小伙子，你先回答我几个问题
1、你的手机 Android 版本是多少
2、你使用定位功能的时候应用是处于前台进程还是后台进程
3、获取定位功能无法经纬度，这个时候权限是授予状态？应用详情页显示权限是已经授予了吗？

**Comment by getActivity** [comment]
超过三天没有响应，关闭此 issue。
