### ISSUE TITLE
ACCESS_BACKGROUND_LOCATION 重复申请问题

### ISSUE THREAD

**Issue by BibuYing** [getActivity/XXPermissions#78]
大佬你好，我这边用的测试是红米8（MIUI12，android10），在申请后台定位权限的时候，选了始终允许，彻底关掉app再次打开之后，还是会重新申请该权限。

**Comment by getActivity** [comment]
小伙子，请提供回答以下问题：
1、你使用的框架版本是多少？
2、点击始终允许之后权限页显示什么？
3、使用原生 API 请求权限是否存在此问题？
4、换台 Android 10 的手机测试是否有同样的问题？

**Comment by BibuYing** [comment]
我用的是最新版的，也下载了demo，会有一样的问题。在demo里面，点击始终允许后，会显示所有权限都通过了，也可以正常使用，就是下次打开之后就不会了，我换别的框架就不会有这个问题

**Comment by yangkf1985** [comment]
@BibuYing @getActivity 我也从出现了类似的问题：
我使用的是小米的K30Pro， android11
1.框架版本11.0；
2.点击始终允许以后，点击返回键有到了授权页面；
3.使用原生的api和10.8不存在这个问题；
4.android11以下不存在这个问题。

**Comment by getActivity** [comment]
@yangkf1985 @BibuYing 小伙子，这个问题有点难整，需要你通过 QQ 联系一下我，具体方式你可以通过先加 QQ 群，等加群通过后直接私信我解决这个问题即可。

**Comment by getActivity** [comment]
@yangkf1985 @BibuYing 小伙子们，如果长时间不回复的话我就强制关闭 issue 了

**Comment by getActivity** [comment]
超过三天没有响应，强制关闭此 issue。
