### ISSUE TITLE
缺少权限

### ISSUE THREAD

**Issue by MattFirefly** [getActivity/XXPermissions#81]
## 问题描述

* 框架版本：XXX
10.8
* 问题描述：XXX
缺少权限 缺少挺多的 比如麦克风 隐私权限等等 你要没写进去给个方式调用呀 别直接拦截了
* 复现步骤：XXX

* 是否必现：填是/否
是
* 手机信息：例如某米 9 / Android 10
全部
## 请回答

* 是部分机型还是所有机型都会出现：部分/全部
全部
* 框架最新的版本是否存在这个问题：是/否
是
* 是否已经查阅框架文档还未能解决的：是/否
否
* issue 是否有人曾提过类似的问题：是/否
否
* 是否可以通过 Demo 来复现该问题：是/否
是
## 其他

* 提供报错堆栈（如果有报错的话必填）

* 提供截图或视频（根据需要提供，不强制）

* 提供解决方案（如果已经解决了的话）

**Comment by getActivity** [comment]
* 小伙子，麦克风权限不是这个权限？

![](https://user-images.githubusercontent.com/28616817/119293285-b0a15480-bc84-11eb-9227-fbef075f00f2.png)

**Comment by getActivity** [comment]
小伙子，你说的隐私权限是什么？我搞权限请求框架那么久，头一回听说有这么一个权限。

**Comment by MattFirefly** [comment]
是这个权限哦android.permission-group.MICROPHONE 
隐私权限是个很特殊的权限哦 Settings.ACTION_USAGE_ACCESS_SETTINGS

**Comment by getActivity** [comment]
小伙子，这个 android.permission-group.MICROPHONE 不是危险权限吧？不信的话你用原生 API 申请看看？

**Comment by getActivity** [comment]
另外小伙子，`android.permission.PACKAGE_USAGE_STATS` 这个权限我做了很详细的了解，但是很遗憾地告诉你，框架大概率不会去做兼容，主要原因如下：

1. 框架的设计是只兼容 Android 6.0 及之后的权限，而 `android.permission.PACKAGE_USAGE_STATS` 是 Android 5.0 就有了，如果要去兼容这个权限，那么对于框架的改动是非常之大的，兼容成本非常高。

2. `android.permission.PACKAGE_USAGE_STATS` 这个权限使用的人群非常少，框架不太可能会为了兼容一个很少使用权限而去做大改，付出和收获远不成正比，因为那样做往往得不偿失。

所以小伙子，我这边建议你直接使用原生 API 去申请这个权限。

**Comment by getActivity** [comment]
小伙子，你这边还有其他的问题不，没有的话我就关闭 issue 了。

**Comment by getActivity** [comment]
小伙子，框架已经支持 `PACKAGE_USAGE_STATS` 权限申请，更新一下到最新版本即可。
