### ISSUE TITLE
安卓11  存储权限适配

### ISSUE THREAD

**Issue by shuaimango** [getActivity/XXPermissions#82]
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE" />
以上权限全部在清单文件注册，但框架还是会抛出没在清单文件中注册的异常。用安卓11小米机断点发现getManifestPermissions返回的权限列表里只有MANAGE_EXTERNAL_STORAGE，没有WRITE_EXTERNAL_STORAGE和READ_EXTERNAL_STORAGE，很奇怪。
特意下了官方demo却是正常的，不得其解

**Comment by getActivity** [comment]
* 小伙子，你这样添加这两个权限再试试
```xml
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" tools:node="replace" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:node="replace" />
```

**Comment by shuaimango** [comment]
感谢大佬可以了。不过还是不明白demo没加tools:node="replace"为什么也可以。
另外，Manifest.permission.MODIFY_AUDIO_SETTINGS等权限框架里没有，为啥框架不直接用Manifest.permission里的权限，而是自定义呢

**Comment by getActivity** [comment]
* 小伙子，这个问题别人给我反馈过，我直接把聊天截图给你看吧，你看完就知道原因了

![](https://user-images.githubusercontent.com/28616817/120591050-143e3580-c46e-11eb-82e6-860b61edf5ca.png)

**Comment by getActivity** [comment]
* 另外关于 Manifest.permission.MODIFY_AUDIO_SETTINGS 这个权限框架里面没有，我可以很明确地说，这个权限不是危险权限，不信你可以看[官网对这个权限的介绍](https://developer.android.google.cn/reference/android/Manifest.permission?hl=zh_cn#MODIFY_AUDIO_SETTINGS)

![](https://user-images.githubusercontent.com/28616817/120591495-d261bf00-c46e-11eb-9610-383391f41b67.png)

**Comment by getActivity** [comment]
* 最后一个问题，框架为什么不直接用 Manifest.permission 里面的字段，而是另起山头呢？原因其实有若干个，我这里简单列举两个：

1. Manifest.permission 包含权限种类太多，其中就包括了危险权限和特殊权限之外的权限，这样很容易给人造成混淆，不懂的人会直接申请这些权限，但实际这些权限是不需要动态申请的，只需要在清单文件中静态注册即可。

2. Manifest.permission 包含了不同 Android 版本的权限常量，那么你直接引用的话也是没有问题的，但是很多时候 Gradle 会出现一个黄色的警告，告诉你引用了高版本的常量字段，但实际不需要做任何兼容。

**Comment by getActivity** [comment]
小伙子，你这边还有其他问题不？没有的话我就关闭 issue 了
