### ISSUE TITLE
大佬，如何自定义弹框呢。

### ISSUE THREAD

**Issue by o199666** [getActivity/XXPermissions#83]
## 建议收集

*  我不知道如何自定义弹框，有无思路

* 权限弹框，不使用系统的，用自己的怎么实现呀

**Comment by getActivity** [comment]
小伙子，系统的授权弹窗你是改不了的，没有任何办法。

**Comment by getActivity** [comment]
小伙子，你这边还有其他问题不？没有的话我就关闭 issue 了

**Comment by o199666** [comment]
没有了 大佬， 我解决了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月4日(星期五) 中午11:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [getActivity/XXPermissions] 大佬，如何自定义弹框呢。 (#83)





 
小伙子，你这边还有其他问题不？没有的话我就关闭 issue 了

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/120911659-92dbe280-c6bb-11eb-8cf9-74f31e0dd995.png)

**Comment by getActivity** [comment]
行的小伙子，后续有啥问题随时欢迎你反馈给我。
