### ISSUE TITLE
请问是否只能支持FragmentActivity来请求权限呢？

### ISSUE THREAD

**Issue by hnty545** [getActivity/XXPermissions#84]
您好，我使用11.2的源码，调起权限请求的是一个Activity，我发现不能正常调用，于是追踪源码发现request中是这样的
```
// 检查当前 Activity 状态是否是正常的，如果不是则不请求权限
FragmentActivity fragmentActivity = PermissionUtils.findFragmentActivity(mContext);
if (!PermissionChecker.checkActivityStatus(fragmentActivity, debugMode)) {
    return;
}
```
findFragmentActivity是这样的
```
static FragmentActivity findFragmentActivity(Context context) {
        do {
            if (context instanceof FragmentActivity) {
                return (FragmentActivity) context;
            } else if (context instanceof ContextWrapper){
                context = ((ContextWrapper) context).getBaseContext();
            } else {
                return null;
            }
        } while (context != null);
        return null;
    }
```
而我传入的是Activity会命中context instanceof ContextWrapper条件，但是return就是null了
checkActivityStatus中检查activity == null不通过就会报这个错The Activity must be a subclass of FragmentActivity, Please directly inherit AppCompatActivity
——————————————
请问是否只能支持FragmentActivity来请求权限呢？

**Comment by hnty545** [comment]
我想是只支持FragmentActivity的子类，我看到项目帮助里讲到了。

**Comment by getActivity** [comment]
小伙子，框架最新版已经优化了这个地方了，将原先需要传入 FragmentActivity 限制改成了 Activity，你更新一下版本即可。

**Comment by hnty545** [comment]
@getActivity 好的感谢，还有个问题是，有的方法要编译版本api30才有，比如MANAGE_EXTERNAL_STORAGE权限的判断，我编译版本目前是api28，在api30的真机上获取READ_EXTERNAL_STORAGE、WRITE_EXTERNAL_STORAGE就可以对存储操作了呢？

**Comment by getActivity** [comment]
如果在 targetSdkVersion >= 30 的情况下，你需要申请 MANAGE_EXTERNAL_STORAGE 才能读写外部存储，如果是 targetSdkVersion < 30 的情况下，你只需要申请 READ_EXTERNAL_STORAGE、WRITE_EXTERNAL_STORAGE 权限就能读写外部存储。

**Comment by hnty545** [comment]
@getActivity 明白了，感谢！

**Comment by hnty545** [comment]
@getActivity 建议把IPermissionInterceptor改为abstract class，因为default特性要求minapi24，有时候没必要设置那么高

**Comment by getActivity** [comment]
* 小伙子，那个特性是 JDK 8 的新特性，你只需要在 Gradle 中加入此配置项即可，你没有加入的话就需要 minSdkVersion >= 24 才能用了

![](https://user-images.githubusercontent.com/28616817/121211914-76080080-c8af-11eb-926f-8c7ca60475f1.png)
