### ISSUE TITLE
Android11  申请REQUEST_INSTALL_PACKAGES权限，跳转到页面点击允许后，再点返回没有成功的回调，不允许点返回有拒绝的回调

### ISSUE THREAD

**Issue by zp0511** [getActivity/XXPermissions#85]
## 问题描述

* 框架版本：11.5

* 问题描述：Android11  申请REQUEST_INSTALL_PACKAGES权限，跳转到页面点击允许后，再点返回没有成功的回调，不允许点返回有拒绝的回调

* 复现步骤：XXX

* 是否必现：是

* 手机信息：oppo / Android 11

## 请回答

* 是部分机型还是所有机型都会出现：部分/全部（例如：某为，某 Android 版本会出现）

* 框架最新的版本是否存在这个问题：是/否（如果用的是旧版本的话，建议升级看问题是否还存在）

* 是否已经查阅框架文档还未能解决的：是/否（文档会提供最常见的问题解答，可以看看是否有自己想要的）

* issue 是否有人曾提过类似的问题：是/否（看看曾经有人提过类似的问题，先参考一下别人是怎么解决的）

* 是否可以通过 Demo 来复现该问题：是/否（排查一下是不是自己的项目代码写得有问题导致的）

* 使用原生 API 是否会出现该问题：是/否（排查一下是不是框架的代码写法存在问题导致的）

## 其他

* 提供报错堆栈（如果有报错的话必填）

* 提供截图或视频（根据需要提供，此项不强制）

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by getActivity** [comment]
* 小伙子，这个不是 Bug，而是 Android 11 的新特性，详细你可以看一下这篇文章：[Android 11特性调整：安装外部来源应用需要重启APP](https://cloud.tencent.com/developer/news/637591)

**Comment by getActivity** [comment]
小伙子，你这边还有其他问题不？没有的话我就关闭 issue 了。
