### ISSUE TITLE
在 Activity 的 onResume 方法中请求权限，会导致 onResume() 被反复触发，进而导致不断的执行请求

### ISSUE THREAD

**Issue by jefshi** [getActivity/XXPermissions#86]
## 问题描述

* 框架版本：implementation 'com.github.getActivity:XXPermissions:11.5'

* 问题描述：如下述示意代码，在 Activity 的 onResume 方法中请求权限，会导致 onResume() 被反复触发，进而导致不断的执行请求

public class DemoActivity extends AppCompatActivity {

    @Override
    protected void onResume() {
        super.onResume();
        Log.e("onResume", "onResume");
        XXPermissions.with(getContext())
                .permission(Manifest.permission.MANAGE_EXTERNAL_STORAGE)
                .request(new OnPermissionCallback() {
                    @Override
                    public void onGranted(List<String> permissions, boolean all) {
                        Log.e("onGranted", "onGranted");
                    }

                    @Override
                    public void onDenied(List<String> permissions, boolean never) {
                        Log.e("onDenied", "onDenied");
                    }
                });
    }
}

* 复现步骤：XXX

* 是否必现：是

* 手机信息：华为荣耀 8

## 请回答

* 是部分机型还是所有机型都会出现：部分/全部（例如：某为，某 Android 版本会出现）

* 框架最新的版本是否存在这个问题：是/否（如果用的是旧版本的话，建议升级看问题是否还存在）

* 是否已经查阅框架文档还未能解决的：是/否（文档会提供最常见的问题解答，可以看看是否有自己想要的）

* issue 是否有人曾提过类似的问题：是/否（看看曾经有人提过类似的问题，先参考一下别人是怎么解决的）

* 是否可以通过 Demo 来复现该问题：是/否（排查一下是不是自己的项目代码写得有问题导致的）

* 使用原生 API 是否会出现该问题：是/否（排查一下是不是框架的代码写法存在问题导致的）

## 其他

* 提供报错堆栈（如果有报错的话必填）

* 提供截图或视频（根据需要提供，此项不强制）

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by getActivity** [comment]
小伙子，MANAGE_EXTERNAL_STORAGE 是一个跳页面的操作，从那个页面返回回来是会回调 Activity.onResume 方法，是开发的基本常识，Activity 从不可见到可见会调用 onResume 方法，这个有什么问题吗？

**Comment by getActivity** [comment]
你这种权限申请的操作放到 onResume 方法里面本身就是一种错误，应该要放到 onCreate 方法，框架本身是没有任何问题的。

**Comment by jefshi** [comment]
产品需求要求，如果应用未授权 MANAGE_EXTERNAL_STORAGE 权限，则一直弹窗提示用户去授权，简单说未授权不能用也不能退出应用。这种需求就无法通用 onCreate 去做了，因为跳设置页面用户是可以不授权的，目前我能想到到的就是在 onResume 里检测并申请

**Comment by jefshi** [comment]
哦，抱歉，问题描述的时候，应该写上 Android 版本，Android 11 以上估计没这个问题，因为是跳页面。但 Android 11 以下，是弹系统对话框，拒绝并不提醒后，系统对话框就不会弹出，这种情况下，onResume 会一直调，导致权限一直去申请

**Comment by getActivity** [comment]
在 onCreate 申请也可以做到这种效果，你可以搞一个专门申请权限的方法，如果回调失败就直接递归调用，直到用户授权了。

**Comment by jefshi** [comment]
额，我再应用中授权了，然后我不退出应用，切任务到设置页面，把存储权限给关了，这种情况下 onCreate 是不行的

**Comment by getActivity** [comment]
我说的是大体思路，你这个问题是细节方面的处理，你可以自己想办法处理。

**Comment by jefshi** [comment]
不是，我的意思是，我认为在 Android 11 以下，拒绝权限弹框后，在不触发授权对话框的情况下，或者调用者不主动触发引发 onResume 的情况下（就像上面的只是日志啥也没干），不应该触发申请页面的 onResume 生命周期。如果触发的话，可以认为是个缺陷

**Comment by jefshi** [comment]
不是，我的意思是，我认为在 Android 11 以下，拒绝权限弹框后，在不触发授权对话框的情况下，或者调用者不主动触发引发 onResume 的情况下（就像上面的只是日志啥也没干），不应该触发申请页面的 onResume 生命周期。如果触发的话，可以认为是个缺陷

**Comment by getActivity** [comment]
小伙子，onResume 是系统调用的，触不触发不是框架说了算，不信你用原生 API 试一下，也是会调用 onResume 方法的。

**Comment by getActivity** [comment]
小伙子，这个问题真的框架不是引发的，系统本身设计就是这样的，你看看这边还有其他问题不？没有的话我就关闭 issue 了。

**Comment by jefshi** [comment]
没有了。另外原生的请求权限 API 并不会引发这种问题，否则我就不会提这个问题了。我猜测应该是 PermissionFragment 造成的，粗略瞄了一下暂时没看到 Activity 的东西，我下周看看框架源码吧

**Comment by jefshi** [comment]
建议暂时不关闭吧，下周有问题继续在这和你讨论

**Comment by getActivity** [comment]
@jefshi 小伙子，你用原生 API 请求的是 MANAGE_EXTERNAL_STORAGE 权限还是 READ_EXTERNAL_STORAGE 和 WRITE_EXTERNAL_STORAGE 权限？

**Comment by getActivity** [comment]
@jefshi 小伙子，issue 是要关的，你如果后面还有问题可以再提 issue，这里不会做任何限制，你只需要提新 issue 的时候将旧的 issue 的地址贴上即可。

**Comment by getActivity** [comment]
小伙子，你要是嫌麻烦的话，也可以直接在这个 issue 下留言，这样我也是可以看到的。
