### ISSUE TITLE
关于安卓11 的MANAGE_EXTERNAL_STORAGE权限问题

### ISSUE THREAD

**Issue by a1b22003001** [getActivity/XXPermissions#87]
## 建议收集

* 关于在android 11 版本 中申请 MANAGE_EXTERNAL_STORAGE权限，在魅族17Pro 和realme Q3的机子上(手上只有这2台android 11版本的机子)，再跳转的Actvitiy中给与授权后，在手机设置中的应用权限上看读写权限还是处于拒绝的状态，但是在我自己写的应用和XXPermissions.apk 上都是显示已授权，但是实际的读写文件还是不行，进过测试后发现，在这2款机子上还是需要用READ_EXTERNAL_STORAGE和WRITE_EXTERNAL_STORAGE 去申请权限，在手机设置中的读写权限才会是允许状态。

* 你觉得该怎么去完善会比较好？ 我觉的应该需要添加不同手机厂商的关于是用MANAGE_EXTERNAL_STORAGE 或者是READ_EXTERNAL_STORAGE和WRITE_EXTERNAL_STORAGE的一样判断，或者是有什么方法可以去判断在当前的机子是使用MANAGE_EXTERNAL_STORAGE申请权限还是使用READ_EXTERNAL_STORAGE和WRITE_EXTERNAL_STORAGE 去申请权限。

**Comment by a1b22003001** [comment]
发现只要将debug模式改成false，在安卓11上将MANAGE_EXTERNAL_STORAGE 改为READ_EXTERNAL_STORAGE和WRITE_EXTERNAL_STORAGE 申请读取权限也一样可以获取，设置里面的权限也变成了允许，在虚拟机上也成功获取到权限，算是解决了。

**Comment by getActivity** [comment]
小伙子，`MANAGE_EXTERNAL_STORAGE` 是 Android 11 出来的新权限，是所有文件的管理权限，优先级高于 `READ_EXTERNAL_STORAGE` 和 `WRITE_EXTERNAL_STORAGE` 权限，并且我已经测试过，申请了 `MANAGE_EXTERNAL_STORAGE` 权限就不需要再申请 `READ_EXTERNAL_STORAGE` 和 `WRITE_EXTERNAL_STORAGE` 权限。

**Comment by getActivity** [comment]
你申请了 `MANAGE_EXTERNAL_STORAGE` 权限，但是在设置页面看到没有授予权限是正常的，因为设置页面看到的存储权限状态根据是 `READ_EXTERNAL_STORAGE` 和 `WRITE_EXTERNAL_STORAGE` 这两个权限的状态而定的， `MANAGE_EXTERNAL_STORAGE` 是特殊权限，而 `READ_EXTERNAL_STORAGE` 和 `WRITE_EXTERNAL_STORAGE` 是危险权限，这是两种不相同的权限，你要区分清楚。

**Comment by getActivity** [comment]
至于你说的在魅族17Pro 和 realme Q3 的手机上面读写失败，麻烦你试一下 [EasyHttp](https://github.com/getActivity/EasyHttp) 这个框架的 Demo 是否有此问题，Demo 里面有 `下载文件` 的选项，你可以做一下测试。

**Comment by a1b22003001** [comment]
我试了EasyHttp, 下载文件到Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS)，就算没给权限也可以写到。看来我还是乖乖按照分区存储来改一下吧。这个issue可以关了

**Comment by getActivity** [comment]
也行，有问题欢迎小伙子再反馈给我

**Comment by a1b22003001** [comment]
好的，感谢感谢

**Comment by 390057892** [comment]
> 小伙子，`MANAGE_EXTERNAL_STORAGE` 是 Android 11 出来的新权限，是所有文件的管理权限，优先级高于 `READ_EXTERNAL_STORAGE` 和 `WRITE_EXTERNAL_STORAGE` 权限，并且我已经测试过，申请了 `MANAGE_EXTERNAL_STORAGE` 权限就不需要再申请 `READ_EXTERNAL_STORAGE` 和 `WRITE_EXTERNAL_STORAGE` 权限。

求教一下，在安卓11以后，授权了MANAGE_EXTERNAL_STORAGE之后，不需要申请READ_EXTERNAL_STORAGE与WRITE_EXTERNAL_STORAGE也可以进行文件读写嘛。

**Comment by 1477466721** [comment]
@getActivity 大佬，能指导一下为什么申请了MANAGE_EXTERNAL_STORAGE 权限，还是无法访问Android/data里面的文件吗？
