### ISSUE TITLE
如何判断是否获取了权限

### ISSUE THREAD

**Issue by ytxyyt** [getActivity/XXPermissions#88]
我只想判断是否获取了权限不想，申请权限怎么办？

**Comment by getActivity** [comment]
小伙子，你的意思是怎么判断权限是否授予了是吧？

**Comment by getActivity** [comment]
你可以用这个 `XXPermissions.isGranted` API 来做判断

**Comment by getActivity** [comment]
小伙子，你这边看看还有其他问题不？没有的话我就关闭 issue 了。
