### ISSUE TITLE
通知栏权限8.0以上适配

### ISSUE THREAD

**Issue by HarrisonShen** [getActivity/XXPermissions#89]
我看代码里面只适配了通知栏权限android7 没适配8.0以上的吗？

**Comment by getActivity** [comment]
小伙子，Android 7.0 及以上通知栏权限判断用的是 `context.getSystemService(NotificationManager.class).areNotificationsEnabled()` 这个 API，Android 8.0 在这块好像没有做修改，你是不是搞错了？

**Comment by HarrisonShen** [comment]
嗯 可能我搞错了
