### ISSUE TITLE
华为p20使用你自己的demo apk进行测试，有bug

### ISSUE THREAD

**Issue by qw30716** [getActivity/XXPermissions#9]
华为p20手机两个权限组，如果勾选其中一个权限组“禁止后不再询问”，点击第二个权限组的“始终允许”会弹出“被永久拒绝权限，请手动赋予”

**Comment by 880634** [comment]
Demo只是一个测试用例，实际代码没有问题，用户统一处理完后会进行回调，通过回调的某个参数告诉开发人员，用户拒绝了某个权限并且选择了不再询问，这个时候就无法弹出权限窗口了，必须要用户前往设置页面开启权限
