### ISSUE TITLE
将PermissionUtil工具类开放出来

### ISSUE THREAD

**Issue by Jun1orChan** [getActivity/XXPermissions#90]
## 建议收集

* 你觉得框架有什么不足之处？（必答项，你可以描述框架有什么令你不满意的地方）
   挺好的
* 你觉得该怎么去完善会比较好？（非必答项，你可以提供一下自己的想法或者做法供作者参考）
   如题，场景：在一个基础库中，申请权限，如果没有在Manifest中声明权限，则框架会导致Crash，这是面向开发的，没有什么问题，但是作为一些基础库的提供者来说，调用方如果忘记申请权限，直接Crash有点无脑，所以需要前置判断权限是否已经声明过了，然后打印出Log，进行提醒，比较友好。最后感谢作者开源。

**Comment by getActivity** [comment]
@Jun1orChan 小伙子，我为什么在框架设计层面直接抛异常，而不是直接打日志？不是每个人都跟你一样，框架出现问题了就会去看日志（根本原因在于 Android 的日志很乱），而是第一时间找到框架作者反馈解决，假设框架只打日志不抛异常，那么会给我带来巨大的排查成本。

**Comment by getActivity** [comment]
@Jun1orChan 至于小伙子，你说的开放 PermissionUtils 类，这种做法违反了迪米特原则，另外我觉得这个属于极少数人的需求，所以我建议你 fork 源码来改。

**Comment by Jun1orChan** [comment]
不好意思，可能我没描述清楚，我是赞同你的Crash做法的。后面的描述，只是想表达，我想使用PerimissionUtil.getManifestPermissions()方法。问题不大，感谢大佬回复。

**Comment by getActivity** [comment]
可以的，后续还有啥问题欢迎再提 issue 给我
