### ISSUE TITLE
Activity Results API 适配

### ISSUE THREAD

**Issue by SGPublic** [getActivity/XXPermissions#91]
onActivityResult(Int, Int, Intent?) 被弃用，官方推荐使用 Activity Results API，会考虑进行适配吗？谢谢。

**Comment by getActivity** [comment]
@SGPublic 小伙子，谷歌不会动这块代码的，顶多新增一种获取权限回调的方式，至于标记过时只是谷歌想提醒你用他新出的 API 而已，所以你的想法是多余的。
