### ISSUE TITLE
开放 `PermissionSettingPage#getSmartPermissionIntent()` 方法

### ISSUE THREAD

**Issue by qihuan92** [getActivity/XXPermissions#92]
## 建议收集

* 你觉得框架有什么不足之处？（必答项，你可以描述框架有什么令你不满意的地方）
首先感谢大佬的权限库，用起来很方便，请问是否可以开放 `PermissionSettingPage#getSmartPermissionIntent()` 方法，以便自定义打开设置返回的 ActivityResultContract，这样就可以使用 Android Result API。
* 你觉得该怎么去完善会比较好？（非必答项，你可以提供一下自己的想法或者做法供作者参考）
开放 `PermissionSettingPage#getSmartPermissionIntent()` 方法
```java
public class XXPermissionsSettingContract extends ActivityResultContract<List<String>, Map<String, Boolean>> {

    private Context context;
    private final List<String> permissions = new ArrayList<>();

    @NonNull
    @Override
    public Intent createIntent(@NonNull Context context, List<String> input) {
        this.context = context;
        this.permissions.addAll(input);
        return PermissionSettingPage.getSmartPermissionIntent(context, input);
    }

    @Override
    public Map<String, Boolean> parseResult(int resultCode, @Nullable Intent intent) {
        Map<String, Boolean> result = new HashMap<>();
        if (resultCode == Activity.RESULT_OK) {
            for (String permission : permissions) {
                result.put(permission, XXPermissions.isGranted(context, permission));
            }
        }
        return result;
    }
}
```

**Comment by getActivity** [comment]
小伙子，先回答我一个问题，你为什么要用 Android Result API 来申请权限？

**Comment by qihuan92** [comment]
> 小伙子，先回答我一个问题，你为什么要用 Android Result API 来申请权限？

感谢大佬回复，目前做的是个新开的项目，已经没有使用 onActivityResult() 这种方式了，所以有扩展打开设置回调的想法，希望可以多提供一种方案，感谢😝

**Comment by getActivity** [comment]
小伙子，你这个理由说服不了我，框架的每一个改动都要为每一个使用的人负责，所以你的建议我无法采纳，如果你有这个需要，请自行 fork 源码下来修改。

**Comment by qihuan92** [comment]
> 小伙子，你这个理由说服不了我，框架的每一个改动都要为每一个使用的人负责，所以你的建议我无法采纳，如果你有这个需要，请自行 fork 源码下来修改。

好的，理解，再次感谢
