### ISSUE TITLE
不能申请项目里面之前规定权限之外的权限，比如蓝牙权限

### ISSUE THREAD

**Issue by Robin-jiangyufeng** [getActivity/XXPermissions#93]
## 问题描述

* 框架版本：XXX

* 问题描述：XXX

* 复现步骤：XXX

* 是否必现：填是/否

* 手机信息：例如某米 9 / Android 10

## 请回答

* 是部分机型还是所有机型都会出现：部分/全部（例如：某为，某 Android 版本会出现）

* 框架最新的版本是否存在这个问题：是/否（如果用的是旧版本的话，建议升级看问题是否还存在）

* 是否已经查阅框架文档还未能解决的：是/否（文档会提供最常见的问题解答，可以看看是否有自己想要的）

* issue 是否有人曾提过类似的问题：是/否（看看曾经有人提过类似的问题，先参考一下别人是怎么解决的）

* 是否可以通过 Demo 来复现该问题：是/否（排查一下是不是自己的项目代码写得有问题导致的）

* 使用原生 API 是否会出现该问题：是/否（排查一下是不是框架的代码写法存在问题导致的）

## 其他

* 提供报错堆栈（如果有报错的话必填）

* 提供截图或视频（根据需要提供，此项不强制）

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by getActivity** [comment]
小伙子，蓝牙权限不是危险权限或者特殊权限。

**Comment by getActivity** [comment]
https://developer.android.google.cn/reference/android/Manifest.permission?hl=zh_cn#BLUETOOTH

**Comment by getActivity** [comment]
这种问题属于低级问题，第一个你没有去了解蓝牙权限是属于什么权限，第二个框架已经明确告诉你这个权限不是危险权限或者特殊权限，麻烦提 issue 前先搞清楚情况再提。
