### ISSUE TITLE
可以在检测权限前做一个自定义弹窗提示吗？

### ISSUE THREAD

**Issue by LLQQHH** [getActivity/XXPermissions#94]
## 建议收集

* 你觉得框架有什么不足之处？（必答项，你可以描述框架有什么令你不满意的地方）
此框架兼容性很好，但是使用中遇到一些个人觉得可以优化的问题！
1.有需求是在检测权前弹窗，友好的告知用户为什么需要权限，我看到XXPermissions没有这个功能。andPermissions是有这个功能的！
2.对于非特殊的危险权限，没有被授权，而且被永久拒绝时候，发现只能跳到应用信息界面，无法跳到app对应的权限信息界面！
* 你觉得该怎么去完善会比较好？（非必答项，你可以提供一下自己的想法或者做法供作者参考）
对于第二点的建议，对大厂做兼容跳转，这里截图andPermissions的做法,尝试获取大厂的app权限信息界面，如果跳转失败，再去跳到默认的应用信息界面！
![image](https://user-images.githubusercontent.com/19651932/127987172-d2f029da-faef-4b3e-abc5-a9dfd6bd161e.png)

**Comment by getActivity** [comment]
* 问题一：框架没有判断权限是否授予的方法，其实框架是有开放的，方法如下：

![](https://user-images.githubusercontent.com/28616817/127992084-f64dfb88-6cb8-43bf-a334-ce24e9c4c202.png)

* 问题二：在申请权限之前弹提示框，这个框架也是支持的，你可以[点击此处查看文档](https://github.com/getActivity/XXPermissions/blob/master/HelpDoc.md)：

![](https://user-images.githubusercontent.com/28616817/127992656-50cfb5a8-dfd5-40cc-a276-fcae4ee282f8.png)

* 问题三：框架为什么不直接跳转到国厂手机设置页，这块框架之前的版本是支持的，只不过后面移除掉了，具体因为什么移除掉，文档也有给出答案，你可以[点击此处查看文档](https://github.com/getActivity/XXPermissions/blob/master/HelpDoc.md)：

![](https://user-images.githubusercontent.com/28616817/127993504-635f2af3-fabd-4922-a291-3cbcbffc2d85.png)

**Comment by LLQQHH** [comment]
只是看了demo没有这些功能，忘记看文档了！我看看文档先！

**Comment by getActivity** [comment]
OK 的，小伙子，你看看你这边还有其他问题不，没有的话我就关闭 issue 了。

**Comment by LLQQHH** [comment]
1.可否提供一个权限转文字的方法，类似于List<String> transformText(Context context, List<String> permissions)
2.demo里面的源码是不是写错了，如下图，对于没有useInterceptor，如果你没有全部授权，你调用了两次onDenied，最后一个应该是调用onGranted！对于权限回调，我想知道为什么回调不做单一职责，onGranted就是全部授权，onDenied就是失败，至于失败的情况，可以在参数中定义类似这么写onDenied(List<String> deniedPermissions,List<String> neverPermissions)？
![image](https://user-images.githubusercontent.com/19651932/128110050-081c92ce-4295-4731-bd1d-fe1dc9487f4d.png)

**Comment by getActivity** [comment]
问题一：框架只做纯 Java 代码相关，而权限转文字需要用到资源，一旦涉及到字符串又要考虑国际化，并且在权限请求中不是必要因素，所以不会考虑加入框架中，你如果需要的话自行加入到项目中。

问题二：首先这块确实是代码写错了，已经纠正了，多谢小伙子的提醒，下个版本会更新上去。

**Comment by LLQQHH** [comment]
那下个版本有没有打算把回调方式改下，成功就是成功，失败就是失败，即去调用onGranted，又去调用onDenied违反api单一职责原则！就好比网络请求，成功就调用onsucess，失败就调用onfail，然后到底是什么导致的fail，使用者自己去onfail回调的参数找！

**Comment by getActivity** [comment]
小伙子，单一职责是指类的职责单一，而不是指方法调用方式单一，权限申请有成功也有失败，你说的是申请一种权限的情况，如果是申请多种权限的情况，有的授予了，有的没授予，那么该怎么回调？

**Comment by getActivity** [comment]
还有框架在设计的时候，onGranted 方法有一个叫 all 参数，你可以通过此标记来判断权限是否全部授予，还是部分授予。

**Comment by getActivity** [comment]
小伙子，我认为这样的设计并没有不合理的地方，是按照正常人的逻辑来走的，全部授予就回调成功的方法，全部拒绝就回调失败的方法，部分授予部分拒绝这种就同时回调成功和失败的方法。

**Comment by LLQQHH** [comment]
正常逻辑，有部分授予部分拒绝也没人会去onGranted这个方法做什么操作，你去调用这个根本没意义！因为你多这个，还让别人还得再去判断boolean all这个参数，根本多此一举！部分拒绝通常只会去onDenied做操作！

**Comment by getActivity** [comment]
问题一：判断 all 参数多此一举，首先你要是申请单个权限可以不用判断，如果是多种权限就需要判断了，你说的没用并不代表真的没用，所以请不要轻易否定框架的设计，如果你想要否定也可以，但是要拿出十足的理由来说服我，而不是这一两句话来概括。

问题二：关于拦截器不要设置静态的，这个问题我思考了很久，觉得还是要设置成静态的，因为如果每次申请权限都要设置一遍，这样会造成一些麻烦，最好能全局统一设置，当然你的想法也是对的，所以我的做法是，在原有的基础上，支持设置某次权限请求的拦截器设置（即局部的拦截器），如果没有设置局部的拦截器，就使用全局的拦截器。

**Comment by getActivity** [comment]
小伙子，你看看这边还有其他问题不，没有的话我就关闭 issue 了。
