### ISSUE TITLE
请求WRITE_EXTERNAL_STORAGE权限的时候直接闪退

### ISSUE THREAD

**Issue by zhoufanGithub** [getActivity/XXPermissions#95]
## 问题描述

* 框架版本：com.github.getActivity:XXPermissions:11.6

* 问题描述：在 targetSdkVersion = 30的时候debug模式下请求WRITE_EXTERNAL_STORAGE权限的时候直接闪退

* 复现步骤：XXX

* 是否必现：是

* 手机信息：Redmi K30 5G

## 请回答

* 是部分机型还是所有机型都会出现：全部

* 框架最新的版本是否存在这个问题：是
* 
* 是否已经查阅框架文档还未能解决的：是

* issue 是否有人曾提过类似的问题：是/否（看看曾经有人提过类似的问题，先参考一下别人是怎么解决的）

* 是否可以通过 Demo 来复现该问题：是

* 使用原生 API 是否会出现该问题：是/否（排查一下是不是框架的代码写法存在问题导致的）

## 其他

 Process: com.stkj.wormhole, PID: 32550
    java.lang.IllegalArgumentException: Please adapt the scoped storage, or use the MANAGE_EXTERNAL_STORAGE permission
        at com.hjq.permissions.PermissionChecker.checkStoragePermission(PermissionChecker.java:150)
        at com.hjq.permissions.XXPermissions.request(XXPermissions.java:148)

**Comment by getActivity** [comment]
小伙子，这个异常是框架给你抛的，你可以根据报错提示来解决问题。
