### ISSUE TITLE
权限请求优化

### ISSUE THREAD

**Issue by iielse** [getActivity/XXPermissions#96]
## 建议收集

* 你觉得框架有什么不足之处？（必答项，你可以描述框架有什么令你不满意的地方）
java.lang.IllegalArgumentException: If you have applied for MANAGE_EXTERNAL_STORAGE permissions, do not apply for the READ_EXTERNAL_STORAGE and WRITE_EXTERNAL_STORAGE permissions
* 你觉得该怎么去完善会比较好？（非必答项，你可以提供一下自己的想法或者做法供作者参考）
* 这个问题能在sdk内部处理吗

**Comment by getActivity** [comment]
小伙子，这个其实框架内部已经处理了，当你申请了 MANAGE_EXTERNAL_STORAGE 权限，那么在高版本上面会使用这个权限进行申请，如果是 Android 10 及以下版本则会自动添加 READ_EXTERNAL_STORAGE 和 WRITE_EXTERNAL_STORAGE 权限进行申请，所以你不需要同时申请这三个权限，只需要加 MANAGE_EXTERNAL_STORAGE 就够了，框架会自动帮你做向下兼容。

**Comment by getActivity** [comment]
小伙子，你看看这边还有其他问题不，没有的话我就关闭 issue 了。

**Comment by iielse** [comment]
可惜我同时传递这3个报错了。 好的没别的问题，谢谢，可以关闭了
