### ISSUE TITLE
11.8版本不设置interceptor存在内存泄漏

### ISSUE THREAD

**Issue by w296365959** [getActivity/XXPermissions#97]
## 问题描述

* 框架版本：11.8

* 问题描述：11.8版本不设置interceptor存在内存泄漏
*         if (mInterceptor == null) {
            if (sInterceptor == null) {
                sInterceptor = new IPermissionInterceptor() {};
            }
            mInterceptor = sInterceptor;
        }

* 复现步骤：请求权限不设置interceptor

* 是否必现：是

* 手机信息：荣耀9 / Android 9

## 请回答

* 是部分机型还是所有机型都会出现： 全部（例如：某为，某 Android 版本会出现）

* 框架最新的版本是否存在这个问题：是 （如果用的是旧版本的话，建议升级看问题是否还存在）

* 是否已经查阅框架文档还未能解决的：是 （文档会提供最常见的问题解答，可以看看是否有自己想要的）

* issue 是否有人曾提过类似的问题： 否（看看曾经有人提过类似的问题，先参考一下别人是怎么解决的）

* 是否可以通过 Demo 来复现该问题：是 （排查一下是不是自己的项目代码写得有问题导致的）

* 使用原生 API 是否会出现该问题： 否（排查一下是不是框架的代码写法存在问题导致的）

## 其他

* 提供报错堆栈（如果有报错的话必填）

* 提供截图或视频（根据需要提供，此项不强制）

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by getActivity** [comment]
麻烦小伙子提供一下内存泄露的堆栈

**Comment by w296365959** [comment]
<img width="243" alt="无标题001" src="https://user-images.githubusercontent.com/25173856/130438810-a9366694-f15d-4e8a-80f2-2f6b370ac989.png">
<img width="359" alt="无标题022" src="https://user-images.githubusercontent.com/25173856/130438834-effae9a4-38e6-4b59-8b04-0b4cd23b8667.png">

**Comment by getActivity** [comment]
[XXPermissions-12.0.aar.zip](https://github.com/getActivity/XXPermissions/files/7031912/XXPermissions-12.0.aar.zip)

**Comment by getActivity** [comment]
@w296365959 小伙子，内存泄漏的问题修复了，你下载这个 aar 包测试看看，如果没有的话我再提交代码到 Github 上面。

**Comment by getActivity** [comment]
@w296365959 小伙子，试完还有发现问题么？

**Comment by w296365959** [comment]
抱歉上午有事，下午我试下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月24日(周二) 中午11:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [getActivity/XXPermissions] 11.8版本不设置interceptor存在内存泄漏 (#97)




 
@w296365959 小伙子，试完还有发现问题么？
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by getActivity** [comment]
ok 的，小伙子

**Comment by w296365959** [comment]
可以了 暂未发现其他问题

**Comment by getActivity** [comment]
小伙子，远程依赖已经更新了，你更新到最新版本即可。
