### ISSUE TITLE
Manifest已经注册.READ_PHONE_STATE 但是部分手机还是会报错

### ISSUE THREAD

**Issue by NeVaDaAAA** [getActivity/XXPermissions#98]
## 问题描述

* 框架版本：12.2

* 问题描述：Manifest已经注册android.permission.READ_PHONE_STATE 但是华为手机还是报错
com.hjq.permissions.ManifestRegisterException: android.permission.READ_PHONE_STATE: Permissions are not registered in the manifest file

* 复现步骤：进入MainActivity进行申请READ_PHONE_STATE权限

* 是否必现：填是

* 手机信息：华为荣耀play (HUAWEI COR-AL10)  Android 9

## 请回答

* 是部分机型还是所有机型都会出现：部分 
* 1. (目前我的小米11U Android 11 如果不加android.permission.READ_PRIVILEGED_PHONE_STATE 会崩溃 )
* 2. HUAWEI COR-AL10  Android 9 会崩溃
* 崩溃问题相同 

* 框架最新的版本是否存在这个问题：是

* 是否已经查阅框架文档还未能解决的：是

* issue 是否有人曾提过类似的问题：否

* 是否可以通过 Demo 来复现该问题：是

* 使用原生 API 是否会出现该问题：未知

## 其他

* 提供报错堆栈（如果有报错的话必填）
* java.lang.RuntimeException: Unable to start activity ComponentInfo{cn.petshub.pethelper/com.xarequest.main.MainActivity}: com.hjq.permissions.ManifestRegisterException: android.permission.READ_PHONE_STATE: Permissions are not registered in the manifest file
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3430)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
	at android.os.Handler.dispatchMessage(Handler.java:112)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

* 提供截图或视频（根据需要提供，此项不强制）
* 
![image](https://user-images.githubusercontent.com/20659340/132785936-48d628fa-c227-4867-8c0d-f0bc0ad5e5cb.png)
![image](https://user-images.githubusercontent.com/20659340/132785994-91301a78-8963-498e-b589-59f7706c3b6f.png)
![image](https://user-images.githubusercontent.com/20659340/132788596-64ba1c6e-b478-4100-af27-26d7481eba19.png)

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by NeVaDaAAA** [comment]
minSdkVersion    : 21, 
targetSdkVersion : 29

**Comment by getActivity** [comment]
* 小伙子，请在编译完成的 apk 包查看是否设置了 `android:maxSdkVersion` 这个属性，请注意不要直接在你的项目清单文件中查看，而是在编译完成的 apk 中去查看，就像下图这样的。

![](https://user-images.githubusercontent.com/28616817/132791211-e77ed643-faf0-440b-a436-5d2b0170cd4f.png)

**Comment by NeVaDaAAA** [comment]
![image](https://user-images.githubusercontent.com/20659340/132793128-db046337-7a07-4978-81be-dbbed17790af.png)
你好 我这边在编译过的apk的manifest中没有找到.READ_PHONE_STATE

**Comment by getActivity** [comment]
那就不是框架的判断有误了，而是你的 apk 没有把这个权限打进去，建议你这边检查一下项目看看是不是在哪里被移除掉了。

**Comment by getActivity** [comment]
* 小伙子，建议你检查一下是不是加入了 `tools:node="remove"` 属性导致的，就像下面这样的，如果你们项目这样写的话，会导致这个权限无法打进 apk 包中。

```xml
<uses-permission android:name="android.permission.READ_PHONE_STATE" tools:node="remove"/>
```

**Comment by NeVaDaAAA** [comment]
问题找到了
我们项目里面接入了阿里的一键登录SDK
在他的manifest中存在tools:node="remove"
![image](https://user-images.githubusercontent.com/20659340/132796048-87a3ceed-9aba-4968-85ac-702208632260.png)

我这边修改为
![image](https://user-images.githubusercontent.com/20659340/132796136-869bc04d-727c-436e-b1c2-daf9ce644833.png)
就OK了
问题已解决,十分感谢作者!!!
