### ISSUE TITLE
权限拒绝并不再提示的问题

### ISSUE THREAD

**Issue by zhangkun0018** [getActivity/XXPermissions#99]
## 问题描述

* 框架版本：12.3

* 问题描述：申请任意权限，拒绝且不在询问后，提示获取权限失败，请手动授予权限，按照提示框跳转到权限设置页面，无法修改权限。从系统设置去修改权限后，回到App，在次申请权限，还是提示获取权限失败，请手动授予。

* 是否必现：是

* 手机信息：红米  系统Android11

**Comment by getActivity** [comment]
小伙子，根据你提供的步骤，我在红米 K20 30（Android 11）没有复现到该问题。

**Comment by getActivity** [comment]
小伙子，你用原生的 API 试一下是否也会出现该问题？

**Comment by zhangkun0018** [comment]
https://user-images.githubusercontent.com/23331766/135372645-f1ee1ce1-1aa3-4e00-82db-0985302101f6.mp4

我录了个视频，你可以看看

**Comment by getActivity** [comment]
小伙子，你是不是在开发者选项中关闭了 **启用MIUI优化** 选项？你把这个开起来就没事了。

**Comment by zhangkun0018** [comment]
是关闭MIUI优化，谢谢啦

**Comment by getActivity** [comment]
小伙子，你看看这边还有其他问题不，没有的话我就关闭 issue 了。

**Comment by getActivity** [comment]
超过三天没有响应，关闭此 issue。
